import type { CompatibilitySurfaceRegistry } from './types.ts';

/**
 * The `pyric/app` compatibility registry — the client app-management surface:
 * the initialization path every user hits first. Rows are authored FROM the
 * `app-registry-*` observations captured from the installed `firebase/app`
 * package (packages/conformance/observations/app/) and machine-checked by the
 * replay suite packages/pyric/test/app/oracle-conformance.test.ts.
 *
 * `initializeServerApp` is an unsupported behavior row here; its availability
 * and rationale are authored once as disposition `app.server-app` in the
 * machine-readable surface contract.
 */
const CONFORMANCE_TEST = 'packages/pyric/test/app/oracle-conformance.test.ts';

export const appRegistry = {
  surface: 'app',
  label: 'App',
  compatPath: 'packages/pyric/docs/app/COMPAT.md',
  blocks: [
    {
      kind: 'markdown',
      markdown:
        "# `pyric/app` compatibility matrix\n\n## Status legend\n\n| Status | Meaning |\n|---|---|\n| ✓ | **Conforming** — the mirror matches prod, locked by a passing replay |\n| ⚠ | **Diverged (documented)** — intentional difference with a written reason |\n| ✗ | **Bug** — should match prod but doesn't; failing probe pins it |\n| — | **Not implemented yet** — deliberately or deferred |\n| ? | **Unverified** — claim from docs not yet observed prod-side |\n",
    },
    {
      kind: 'table',
      prefix: "## `initializeApp(config, name?)` — the app registry\n",
      rows: [
        {
          id: 'app#1',
          surface: 'app',
          aliases: [],
          featureKeys: ["initializeApp"],
          rowRef: '1',
          rowNumber: 1,
          section: '`initializeApp(config, name?)` — the app registry',
          api: 'initializeApp(config)',
          behavior:
            "Registers the default app under the name `'[DEFAULT]'`; `getApps()` has length 1 and `getApp()` (no arg) resolves the same instance",
          status: 'conforms',
          evidence:
            'oracle: `app-registry-initializeapp-default` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-initializeapp-default'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#2',
          surface: 'app',
          aliases: [],
          featureKeys: ["initializeApp"],
          rowRef: '2',
          rowNumber: 2,
          section: '`initializeApp(config, name?)` — the app registry',
          api: "initializeApp(config, 'secondary')",
          behavior:
            "Registers a named app alongside the default; `getApp('secondary')` resolves it and `getApps()` has length 2 (default + named)",
          status: 'conforms',
          evidence:
            'oracle: `app-registry-initializeapp-named` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-initializeapp-named'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#3',
          surface: 'app',
          aliases: [],
          featureKeys: ["initializeApp"],
          rowRef: '3',
          rowNumber: 3,
          section: '`initializeApp(config, name?)` — the app registry',
          api: 'initializeApp(config)',
          behavior:
            'A same-name re-initialization with a DIFFERENT config throws `FirebaseError` code `app/duplicate-app`, with the app name embedded in the message',
          status: 'conforms',
          evidence:
            'oracle: `app-registry-initializeapp-duplicate-name` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['error-code', 'specific-value'],
          riskScore: 4,
          riskReasons: ['asserts Firebase error code `app/duplicate-app`', 'asserts the exact error message'],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-initializeapp-duplicate-name'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#4',
          surface: 'app',
          aliases: [],
          featureKeys: ["initializeApp"],
          rowRef: '4',
          rowNumber: 4,
          section: '`initializeApp(config, name?)` — the app registry',
          api: 'initializeApp(config)',
          behavior:
            'A same-name re-initialization with EQUAL config is idempotent — no throw, returns the existing instance, and `getApps()` stays length 1',
          status: 'conforms',
          evidence:
            'oracle: `app-registry-initializeapp-duplicate-config` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-initializeapp-duplicate-config'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#5',
          surface: 'app',
          aliases: [],
          featureKeys: ["getApp"],
          rowRef: '5',
          rowNumber: 5,
          section: '`getApp` / `getApps` / `deleteApp` — registry accessors',
          api: 'getApp()',
          behavior: "`getApp()` with no name resolves the default app instance; its name is `'[DEFAULT]'`",
          status: 'conforms',
          evidence: 'oracle: `app-registry-getapp-default` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-getapp-default'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#6',
          surface: 'app',
          aliases: [],
          featureKeys: ["getApp"],
          rowRef: '6',
          rowNumber: 6,
          section: '`getApp` / `getApps` / `deleteApp` — registry accessors',
          api: "getApp('secondary')",
          behavior: "`getApp('secondary')` resolves the named app instance; its name is `'secondary'`",
          status: 'conforms',
          evidence: 'oracle: `app-registry-getapp-named` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-getapp-named'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#7',
          surface: 'app',
          aliases: [],
          featureKeys: ["getApp"],
          rowRef: '7',
          rowNumber: 7,
          section: '`getApp` / `getApps` / `deleteApp` — registry accessors',
          api: 'getApp(name)',
          behavior:
            '`getApp(name)` for a name that was never initialized throws `FirebaseError` code `app/no-app`, directing the caller to `initializeApp()`',
          status: 'conforms',
          evidence:
            'oracle: `app-registry-getapp-unknown-name` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['error-code', 'specific-value'],
          riskScore: 4,
          riskReasons: ['asserts Firebase error code `app/no-app`', 'asserts the exact error message'],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-getapp-unknown-name'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#8',
          surface: 'app',
          aliases: [],
          featureKeys: ["getApps"],
          rowRef: '8',
          rowNumber: 8,
          section: '`getApp` / `getApps` / `deleteApp` — registry accessors',
          api: 'getApps()',
          behavior: '`getApps()` returns an array containing every registered app by identity (the exact instances, not copies)',
          status: 'conforms',
          evidence: 'oracle: `app-registry-getapps-contents` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-getapps-contents'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#9',
          surface: 'app',
          aliases: [],
          featureKeys: ["deleteApp"],
          rowRef: '9',
          rowNumber: 9,
          section: '`getApp` / `getApps` / `deleteApp` — registry accessors',
          api: 'deleteApp(app)',
          behavior:
            '`deleteApp(app)` returns a Promise, deregisters the app (so `getApps()` shrinks), a later `getApp(name)` throws `app/no-app`, and the name can be re-initialized afterwards',
          status: 'conforms',
          evidence: 'oracle: `app-registry-deleteapp` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['error-code'],
          riskScore: 3,
          riskReasons: ['asserts Firebase error code `app/no-app` after deletion'],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-deleteapp'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#10',
          surface: 'app',
          aliases: [],
          featureKeys: ["deleteApp"],
          rowRef: '10',
          rowNumber: 10,
          section: '`getApp` / `getApps` / `deleteApp` — registry accessors',
          api: 'deleteApp(app)',
          behavior: '`deleteApp` on an already-deleted app throws `FirebaseError` code `app/app-deleted`',
          status: 'conforms',
          evidence: 'oracle: `app-registry-deleteapp-double` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['error-code', 'specific-value'],
          riskScore: 4,
          riskReasons: ['asserts Firebase error code `app/app-deleted`', 'asserts the exact error message'],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-deleteapp-double'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#11',
          surface: 'app',
          aliases: [],
          featureKeys: ["SDK_VERSION"],
          rowRef: '11',
          rowNumber: 11,
          section: '`FirebaseError` / `SDK_VERSION` / logger seam',
          api: 'SDK_VERSION',
          behavior:
            "`SDK_VERSION` is the Firebase client SDK semver string whose behavior pyric currently mirrors, pinned to the oracle version (`12.13.0`)",
          status: 'conforms',
          evidence: 'oracle: `app-registry-sdk-version` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['specific-value'],
          riskScore: 2,
          riskReasons: ['asserts the exact SDK version string'],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-sdk-version'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#12',
          surface: 'app',
          aliases: [],
          featureKeys: ["FirebaseError"],
          rowRef: '12',
          rowNumber: 12,
          section: '`FirebaseError` / `SDK_VERSION` / logger seam',
          api: 'FirebaseError',
          behavior:
            "`FirebaseError` is an app-owned Error subclass: `instanceof Error`, `constructor.name` is `'FirebaseError'`, and it preserves `.code` and `.message` without loading `firebase/app`",
          status: 'conforms',
          evidence:
            'oracle: `app-registry-firebaseerror-shape` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-firebaseerror-shape'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#13',
          surface: 'app',
          aliases: [],
          featureKeys: ["onLog","setLogLevel"],
          rowRef: '13',
          rowNumber: 13,
          section: '`FirebaseError` / `SDK_VERSION` / logger seam',
          api: 'onLog / setLogLevel',
          behavior:
            "`onLog(cb)` / `setLogLevel(level)` are a functioning app-owned diagnostic-logger seam: registering a handler returns undefined, raising the threshold takes effect, and a malformed `registerVersion` emits a `warn` entry (type `@firebase/app`) to the handler",
          status: 'conforms',
          evidence: 'oracle: `app-registry-onlog-setloglevel` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-onlog-setloglevel'],
          conformanceTests: [CONFORMANCE_TEST],
          notes:
            'The sandbox logger is process-local and independent from Firebase. Package resolution ensures production code receives the real Firebase logger, while the mirror reproduces the observed register, threshold, and emission contract without a production runtime dependency.',
        },
        {
          id: 'app#14',
          surface: 'app',
          aliases: [],
          featureKeys: ["registerVersion"],
          rowRef: '14',
          rowNumber: 14,
          section: '`FirebaseError` / `SDK_VERSION` / logger seam',
          api: 'registerVersion',
          behavior:
            '`registerVersion(library, version)` accepts a well-formed registration and returns undefined without throwing; malformed values emit the observed warning through the app-owned logger',
          status: 'conforms',
          evidence: 'oracle: `app-registry-registerversion` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-registerversion'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#15',
          surface: 'app',
          aliases: [],
          featureKeys: ["initializeServerApp"],
          rowRef: '15',
          rowNumber: 15,
          section: 'Deferred',
          api: 'initializeServerApp',
          behavior: 'Not implemented; disposition `app.server-app` owns the reviewed availability and rationale',
          status: 'unsupported',
          evidence: 'disposition:app.server-app',
          risk: [],
          riskScore: 0,
          riskReasons: [],
          automation: 'unsupported',
          oracleObservations: [],
          conformanceTests: [],
          exceptionReason: 'availability policy is authored in disposition `app.server-app`',
        },
        {
          id: 'app#16',
          surface: 'app',
          aliases: [],
          featureKeys: ["initializeApp"],
          rowRef: '16',
          rowNumber: 16,
          section: '`FirebaseApp` container shape',
          api: 'initializeApp(options, settings)',
          behavior:
            '`initializeApp` snapshots options, accepts a settings object, initializes `automaticDataCollectionEnabled`, and leaves that app property mutable',
          status: 'conforms',
          evidence:
            'oracle: `app-registry-initializeapp-settings-options` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural', 'specific-value'],
          riskScore: 2,
          riskReasons: ['asserts the default/mutable app setting values'],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-initializeapp-settings-options'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#17',
          surface: 'app',
          aliases: [],
          featureKeys: ["initializeApp"],
          rowRef: '17',
          rowNumber: 17,
          section: '`FirebaseApp` container shape',
          api: "initializeApp(equalOptions, 'secondary')",
          behavior:
            'Equal-config named apps are distinct app containers with equal option values and independent name-keyed registry identity',
          status: 'conforms',
          evidence:
            'oracle: `app-registry-initializeapp-named-equal-config` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-initializeapp-named-equal-config'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#18',
          surface: 'app',
          aliases: [],
          featureKeys: ["getStorage","getAuth","getFirestore","getDatabase"],
          rowRef: '18',
          rowNumber: 18,
          section: '`FirebaseApp` service containers',
          api: 'getAuth/getFirestore/getDatabase/getStorage(app)',
          behavior:
            'Equal-config named apps own distinct app-associated service handles while resolving the same configured RTDB and Storage backend locators',
          status: 'conforms',
          evidence:
            'oracle: `app-registry-multi-app-service-containers` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-multi-app-service-containers'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#19',
          surface: 'app',
          aliases: [],
          featureKeys: ["initializeApp"],
          rowRef: '19',
          rowNumber: 19,
          section: 'Documented single-backend limitation',
          api: "initializeApp(differentOptions, 'secondary')",
          behavior:
            'Production permits a differently configured named app; Pyric rejects it because one runtime currently owns exactly one sandbox backend',
          status: 'diverged-documented',
          evidence:
            'oracle: `app-registry-initializeapp-named-different-config` (firebase 12.13.0) + replay pins `app/multiple-configs-not-supported`; `packages/cli/test/e2e/app-multi-app.pw.ts` proves the same lock is enforced by the authoritative SharedWorker across same-origin tabs, not only by one page registry',
          risk: ['error-code', 'structural'],
          riskScore: 3,
          riskReasons: ['valid upstream multi-backend initialization is rejected'],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-initializeapp-named-different-config'],
          conformanceTests: [
            CONFORMANCE_TEST,
            'packages/cli/test/e2e/app-multi-app.pw.ts',
          ],
          exceptionReason:
            'The initial mirror supports one FirebaseOptions value and one sandbox backend per runtime; accepting and silently misrouting a second config would be less trustworthy than an explicit error.',
        },
        {
          id: 'app#20',
          surface: 'app',
          aliases: [],
          featureKeys: ["deleteApp","initializeApp"],
          rowRef: '20',
          rowNumber: 20,
          section: 'Documented single-backend limitation',
          api: 'deleteApp(app); initializeApp(differentOptions)',
          behavior:
            'Production permits a different configuration after deletion; Pyric retains the runtime backend lock and rejects the reinitialization',
          status: 'diverged-documented',
          evidence:
            'oracle: `app-registry-delete-reinitialize-different-config` (firebase 12.13.0) + replay pins `app/multiple-configs-not-supported`',
          risk: ['error-code', 'structural'],
          riskScore: 3,
          riskReasons: ['valid upstream post-delete reconfiguration is rejected'],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-delete-reinitialize-different-config'],
          conformanceTests: [CONFORMANCE_TEST],
          exceptionReason:
            'Deleting an SDK container must not relabel or erase the shared persisted sandbox backend; the config lock therefore lasts for the runtime lifetime.',
        },
        {
          id: 'app#21',
          surface: 'app',
          aliases: [],
          featureKeys: ["initializeApp"],
          rowRef: '21',
          rowNumber: 21,
          section: '`initializeApp` validation',
          api: 'initializeApp()',
          behavior:
            'Without Hosting-provided defaults, omitting options throws FirebaseError code `app/no-options` with the production message',
          status: 'conforms',
          evidence:
            'oracle: `app-registry-initializeapp-no-options` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['error-code', 'specific-value'],
          riskScore: 4,
          riskReasons: ['asserts Firebase error code `app/no-options`', 'asserts exact message text'],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-initializeapp-no-options'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#22',
          surface: 'app',
          aliases: [],
          featureKeys: ["getStorage","getAuth","getFirestore","getDatabase"],
          rowRef: '22',
          rowNumber: 22,
          section: '`FirebaseApp` service containers',
          api: 'getAuth/getFirestore/getDatabase/getStorage()',
          behavior:
            'With a registered default app, each no-argument service factory resolves a service associated with that exact default app',
          status: 'conforms',
          evidence:
            'oracle: `app-registry-default-service-factories` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-default-service-factories'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#23',
          surface: 'app',
          aliases: [],
          featureKeys: ["initializeApp"],
          rowRef: '23',
          rowNumber: 23,
          section: 'Shared backend invariant',
          api: "initializeApp(equalOptions, name)",
          behavior:
            'Equal-config app instances connect to one logical backend: data written through one app is readable through another, while their active Auth sessions remain independent',
          status: 'conforms',
          evidence:
            'oracle: `app-production-multi-app-topology` (firebase 12.13.0, real Chromium against production) + twin replay: `production-multi-app-oracle.test.ts`; served SharedWorker replay: `app-multi-app.pw.ts`',
          risk: ['stateful', 'structural'],
          riskScore: 3,
          riskReasons: ['asserts shared persistent state across app containers'],
          automation: 'oracle-backed',
          oracleObservations: ['app-production-multi-app-topology'],
          conformanceTests: [
            'packages/pyric/test/app/production-multi-app-oracle.test.ts',
            'packages/cli/test/e2e/app-multi-app.pw.ts',
          ],
        },
        {
          id: 'app#24',
          surface: 'app',
          aliases: [],
          featureKeys: ["deleteApp"],
          rowRef: '24',
          rowNumber: 24,
          section: '`FirebaseApp` deletion lifecycle',
          api: 'deleteApp(app); app.name / app.options / app.automaticDataCollectionEnabled',
          behavior:
            'After deletion resolves, every public FirebaseApp property accessor throws `FirebaseError` code `app/app-deleted`',
          status: 'conforms',
          evidence:
            'oracle: `app-registry-deleted-property-access` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['error-code', 'structural'],
          riskScore: 3,
          riskReasons: ['asserts Firebase error code `app/app-deleted` for each public app accessor'],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-deleted-property-access'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#25',
          surface: 'app',
          aliases: [],
          featureKeys: ["deleteApp","getAI","getAuth","getFirestore","getDatabase","getStorage"],
          rowRef: '25',
          rowNumber: 25,
          section: '`FirebaseApp` deletion lifecycle',
          api: 'deleteApp(app); getAuth/getFirestore/getDatabase/getStorage/getAI(app)',
          behavior:
            'After deletion, fresh Auth/Firestore/RTDB/Storage factories reject; cached factories return retained handles; retained Auth sign-out resolves but a new anonymous sign-in rejects `app/app-deleted`; Firestore reads report termination, RTDB refuses new refs, Storage refs remain constructible, and `getAI(deletedApp)` returns an app-associated handle',
          status: 'conforms',
          evidence:
            'oracles: `app-registry-deleted-service-factories` and real-Chromium `app-production-multi-app-topology` (firebase 12.13.0) + replays: `oracle-conformance.test.ts`, `deleted-service-lifecycle.test.ts`, and `production-multi-app-oracle.test.ts`',
          risk: ['error-code', 'structural'],
          riskScore: 3,
          riskReasons: ['asserts deleted-container and retained-handle behavior across five service families'],
          automation: 'oracle-backed',
          oracleObservations: [
            'app-registry-deleted-service-factories',
            'app-production-multi-app-topology',
          ],
          conformanceTests: [
            CONFORMANCE_TEST,
            'packages/pyric/test/app/deleted-service-lifecycle.test.ts',
            'packages/pyric/test/app/production-multi-app-oracle.test.ts',
          ],
        },
        {
          id: 'app#26',
          surface: 'app',
          aliases: [],
          featureKeys: ["deleteApp"],
          rowRef: '26',
          rowNumber: 26,
          section: '`FirebaseApp` deletion lifecycle',
          api: 'deleteApp(app)',
          behavior:
            'Deleting one app terminates its Firestore listener through the error callback with code `aborted`, silently stops its RTDB listener, and leaves equal-config sibling listeners and the shared backend usable',
          status: 'conforms',
          evidence:
            'oracle: `app-production-multi-app-topology` (firebase 12.13.0, real Chromium against production) + twin replay: `production-multi-app-oracle.test.ts`; focused family tests: `multi-app-listener-auth.test.ts` and served `app-multi-app.pw.ts`',
          risk: ['listener', 'stateful', 'structural'],
          riskScore: 5,
          riskReasons: ['asserts service-specific listener termination and sibling isolation'],
          automation: 'oracle-backed',
          oracleObservations: ['app-production-multi-app-topology'],
          conformanceTests: [
            'packages/pyric/test/app/production-multi-app-oracle.test.ts',
            'packages/pyric/test/app/multi-app-listener-auth.test.ts',
            'packages/cli/test/e2e/app-multi-app.pw.ts',
          ],
        },
        {
          id: 'app#27',
          surface: 'app',
          aliases: [],
          featureKeys: ["getAI","deleteApp"],
          rowRef: '27',
          rowNumber: 27,
          section: '`FirebaseApp` deletion lifecycle',
          api: 'getAI(app, customEngine); deleteApp(app); retainedModel operation',
          behavior:
            'Served worker mode rejects page-local custom AnswerEngine objects; a model retained from a deleted app rejects, while an equal-config sibling model remains usable through its own app-scoped worker port',
          status: 'unverified',
          evidence:
            '`packages/cli/test/e2e/app-deletion.pw.ts` observes AI code `unsupported` for a custom engine, then exercises retained and sibling models through canonical served imports after deleting one app; `packages/pyric/src/ai/sandbox-plane.ts` guards every model operation. A credentialed production AI lifecycle capture is still needed',
          risk: ['stateful', 'structural'],
          riskScore: 4,
          riskReasons: ['asserts deleted-container isolation, worker ownership, and sibling survival'],
          automation: 'unverified',
          oracleObservations: [],
          conformanceTests: [],
        },
      ],
    },
  ],
} as CompatibilitySurfaceRegistry;
