import type { CompatibilitySurfaceRegistry } from './types.ts';

/**
 * The `pyric/app` compatibility registry — the client app-management surface:
 * the initialization path every user hits first. Rows are authored FROM the
 * `app-registry-*` observations captured from the installed `firebase/app`
 * package (packages/conformance/observations/app/) and machine-checked by the
 * replay suite packages/pyric/test/app/oracle-conformance.test.ts.
 *
 * `initializeServerApp` is deferred (SSR server-app semantics with no decided
 * sandbox mirror) — recorded here as an `unsupported` row and in the census
 * deny-list (tier `deferred`), not silently dropped.
 */
const CONFORMANCE_TEST = 'packages/pyric/test/app/oracle-conformance.test.ts';

export const appRegistry = {
  surface: 'app',
  compatPath: 'packages/pyric/docs/app/COMPAT.md',
  blocks: [
    {
      kind: 'markdown',
      markdown:
        "# `pyric/app` compatibility matrix\n\nThe single readable contract for \"what the `pyric/app` initialization surface\nguarantees vs the production `firebase/app` client SDK.\" `pyric/app` is the\nentry point every user hits first: `initializeApp`, the name-keyed app registry\n(`getApp` / `getApps` / `deleteApp`), the `FirebaseError` class and `SDK_VERSION`\nconstant, and the diagnostic logger seam (`onLog` / `setLogLevel` /\n`registerVersion`).\n\nThe registry rows are authored from the `app-registry-*` oracle observations\n(pure in-process captures of the installed `firebase/app` package — no project,\nno network) and replayed verdict-for-verdict by\n`packages/pyric/test/app/oracle-conformance.test.ts`.\n\n## Status legend\n\n| Status | Meaning |\n|---|---|\n| ✓ | **Conforming** — the mirror matches prod, locked by a passing replay |\n| ⚠ | **Diverged (documented)** — intentional difference with a written reason |\n| ✗ | **Bug** — should match prod but doesn't; failing probe pins it |\n| — | **Unsupported** — not implemented (deliberately or deferred) |\n| ? | **Unverified** — claim from docs not yet observed prod-side |\n\n---\n",
    },
    {
      kind: 'table',
      prefix: "## `initializeApp(config, name?)` — the app registry\n",
      rows: [
        {
          id: 'app#1',
          surface: 'app',
          aliases: [],
          rowRef: '1',
          rowNumber: 1,
          section: '`initializeApp(config, name?)` — the app registry',
          api: 'initializeApp(config)',
          behavior:
            "Registers the default app under the name `'[DEFAULT]'`; `getApps()` has length 1 and `getApp()` (no arg) resolves the same instance",
          status: 'conforms',
          evidence:
            'oracle: `app-registry-initializeapp-default` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-initializeapp-default'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#2',
          surface: 'app',
          aliases: [],
          rowRef: '2',
          rowNumber: 2,
          section: '`initializeApp(config, name?)` — the app registry',
          api: "initializeApp(config, 'secondary')",
          behavior:
            "Registers a named app alongside the default; `getApp('secondary')` resolves it and `getApps()` has length 2 (default + named)",
          status: 'conforms',
          evidence:
            'oracle: `app-registry-initializeapp-named` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-initializeapp-named'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#3',
          surface: 'app',
          aliases: [],
          rowRef: '3',
          rowNumber: 3,
          section: '`initializeApp(config, name?)` — the app registry',
          api: 'initializeApp(config)',
          behavior:
            'A same-name re-initialization with a DIFFERENT config throws `FirebaseError` code `app/duplicate-app`, with the app name embedded in the message',
          status: 'conforms',
          evidence:
            'oracle: `app-registry-initializeapp-duplicate-name` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['error-code', 'specific-value'],
          riskScore: 4,
          riskReasons: ['asserts Firebase error code `app/duplicate-app`', 'asserts the exact error message'],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-initializeapp-duplicate-name'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#4',
          surface: 'app',
          aliases: [],
          rowRef: '4',
          rowNumber: 4,
          section: '`initializeApp(config, name?)` — the app registry',
          api: 'initializeApp(config)',
          behavior:
            'A same-name re-initialization with EQUAL config is idempotent — no throw, returns the existing instance, `getApps()` stays length 1 (reference identity is the deep-equal-options analog for a `{ sandbox }` config)',
          status: 'conforms',
          evidence:
            'oracle: `app-registry-initializeapp-duplicate-config` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-initializeapp-duplicate-config'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#5',
          surface: 'app',
          aliases: [],
          rowRef: '5',
          rowNumber: 5,
          section: '`getApp` / `getApps` / `deleteApp` — registry accessors',
          api: 'getApp()',
          behavior: "`getApp()` with no name resolves the default app instance; its name is `'[DEFAULT]'`",
          status: 'conforms',
          evidence: 'oracle: `app-registry-getapp-default` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-getapp-default'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#6',
          surface: 'app',
          aliases: [],
          rowRef: '6',
          rowNumber: 6,
          section: '`getApp` / `getApps` / `deleteApp` — registry accessors',
          api: "getApp('secondary')",
          behavior: "`getApp('secondary')` resolves the named app instance; its name is `'secondary'`",
          status: 'conforms',
          evidence: 'oracle: `app-registry-getapp-named` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-getapp-named'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#7',
          surface: 'app',
          aliases: [],
          rowRef: '7',
          rowNumber: 7,
          section: '`getApp` / `getApps` / `deleteApp` — registry accessors',
          api: 'getApp(name)',
          behavior:
            '`getApp(name)` for a name that was never initialized throws `FirebaseError` code `app/no-app`, directing the caller to `initializeApp()`',
          status: 'conforms',
          evidence:
            'oracle: `app-registry-getapp-unknown-name` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['error-code', 'specific-value'],
          riskScore: 4,
          riskReasons: ['asserts Firebase error code `app/no-app`', 'asserts the exact error message'],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-getapp-unknown-name'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#8',
          surface: 'app',
          aliases: [],
          rowRef: '8',
          rowNumber: 8,
          section: '`getApp` / `getApps` / `deleteApp` — registry accessors',
          api: 'getApps()',
          behavior: '`getApps()` returns an array containing every registered app by identity (the exact instances, not copies)',
          status: 'conforms',
          evidence: 'oracle: `app-registry-getapps-contents` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-getapps-contents'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#9',
          surface: 'app',
          aliases: [],
          rowRef: '9',
          rowNumber: 9,
          section: '`getApp` / `getApps` / `deleteApp` — registry accessors',
          api: 'deleteApp(app)',
          behavior:
            '`deleteApp(app)` returns a Promise, deregisters the app (so `getApps()` shrinks), a later `getApp(name)` throws `app/no-app`, and the name can be re-initialized afterwards',
          status: 'conforms',
          evidence: 'oracle: `app-registry-deleteapp` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['error-code'],
          riskScore: 3,
          riskReasons: ['asserts Firebase error code `app/no-app` after deletion'],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-deleteapp'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#10',
          surface: 'app',
          aliases: [],
          rowRef: '10',
          rowNumber: 10,
          section: '`getApp` / `getApps` / `deleteApp` — registry accessors',
          api: 'deleteApp(app)',
          behavior: '`deleteApp` on an already-deleted app throws `FirebaseError` code `app/app-deleted`',
          status: 'conforms',
          evidence: 'oracle: `app-registry-deleteapp-double` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['error-code', 'specific-value'],
          riskScore: 4,
          riskReasons: ['asserts Firebase error code `app/app-deleted`', 'asserts the exact error message'],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-deleteapp-double'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#11',
          surface: 'app',
          aliases: [],
          rowRef: '11',
          rowNumber: 11,
          section: '`FirebaseError` / `SDK_VERSION` / logger seam',
          api: 'SDK_VERSION',
          behavior:
            "`SDK_VERSION` is the Firebase client SDK semver string whose behavior pyric currently mirrors, pinned to the oracle version (`12.13.0`)",
          status: 'conforms',
          evidence: 'oracle: `app-registry-sdk-version` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['specific-value'],
          riskScore: 2,
          riskReasons: ['asserts the exact SDK version string'],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-sdk-version'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#12',
          surface: 'app',
          aliases: [],
          rowRef: '12',
          rowNumber: 12,
          section: '`FirebaseError` / `SDK_VERSION` / logger seam',
          api: 'FirebaseError',
          behavior:
            "`FirebaseError` is an app-owned Error subclass: `instanceof Error`, `constructor.name` is `'FirebaseError'`, and it preserves `.code` and `.message` without loading `firebase/app`",
          status: 'conforms',
          evidence:
            'oracle: `app-registry-firebaseerror-shape` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-firebaseerror-shape'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#13',
          surface: 'app',
          aliases: [],
          rowRef: '13',
          rowNumber: 13,
          section: '`FirebaseError` / `SDK_VERSION` / logger seam',
          api: 'onLog / setLogLevel',
          behavior:
            "`onLog(cb)` / `setLogLevel(level)` are a functioning app-owned diagnostic-logger seam: registering a handler returns undefined, raising the threshold takes effect, and a malformed `registerVersion` emits a `warn` entry (type `@firebase/app`) to the handler",
          status: 'conforms',
          evidence: 'oracle: `app-registry-onlog-setloglevel` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-onlog-setloglevel'],
          conformanceTests: [CONFORMANCE_TEST],
          notes:
            'The sandbox logger is process-local and independent from Firebase. Package resolution ensures production code receives the real Firebase logger, while the mirror reproduces the observed register, threshold, and emission contract without a production runtime dependency.',
        },
        {
          id: 'app#14',
          surface: 'app',
          aliases: [],
          rowRef: '14',
          rowNumber: 14,
          section: '`FirebaseError` / `SDK_VERSION` / logger seam',
          api: 'registerVersion',
          behavior:
            '`registerVersion(library, version)` accepts a well-formed registration and returns undefined without throwing; malformed values emit the observed warning through the app-owned logger',
          status: 'conforms',
          evidence: 'oracle: `app-registry-registerversion` (firebase 12.13.0) + replay: `oracle-conformance.test.ts`',
          risk: ['structural'],
          riskScore: 0,
          riskReasons: [],
          automation: 'oracle-backed',
          oracleObservations: ['app-registry-registerversion'],
          conformanceTests: [CONFORMANCE_TEST],
        },
        {
          id: 'app#15',
          surface: 'app',
          aliases: [],
          rowRef: '15',
          rowNumber: 15,
          section: 'Deferred',
          api: 'initializeServerApp',
          behavior:
            'Not implemented — server-app (SSR) initialization is deferred: a FirebaseServerApp carries per-request auth/heartbeat state with no decided sandbox mirror pattern yet',
          status: 'unsupported',
          evidence: 'deferred — see census deny-list (tier `deferred`) for the surface-coverage debt entry',
          risk: [],
          riskScore: 0,
          riskReasons: [],
          automation: 'unsupported',
          oracleObservations: [],
          conformanceTests: [],
          exceptionReason:
            'SSR server-app semantics; the sandbox mirror pattern is undecided (per-request auth/heartbeat state has no sandbox analog yet). Deferred, not dropped — tracked as census deny-list debt (tier `deferred`).',
        },
      ],
    },
  ],
} as CompatibilitySurfaceRegistry;
