import { defineRows } from './define-rows.ts';
import type { CompatibilityRow, CompatibilitySurfaceRegistry } from './types.ts';

const CONFORMANCE_SUITE = 'packages/swift-client/Tests/PyricFirestoreTests/ConformanceTests.swift';
const UNOBSERVED_REASON =
  'Behavior stated from FirebaseFirestore Swift specification; test has not passed yet.';

const buildRow = defineRows({
  surface: 'firestore-swift',
});

interface SwiftRowSeed {
  ref: number;
  section: string;
  api: string;
  behavior: string;
  featureKeys: string[];
  evidence?: string;
  flipped?: 'unit-backed';
}

function row(seed: SwiftRowSeed): CompatibilityRow {
  const { ref, flipped, evidence, ...rest } = seed;
  const defaultEvidence = flipped
    ? 'FirebaseFirestore Swift specification.'
    : 'FirebaseFirestore Swift specification; unverified locally.';
  const resolvedEvidence = evidence ?? defaultEvidence;
  const climb = flipped
    ? {
        status: 'conforms' as const,
        automation: 'unit-backed' as const,
        evidence: `${resolvedEvidence} Swift test: \`${CONFORMANCE_SUITE}\` assertion set \`firestore-swift#${ref}\`.`,
        conformanceTests: [CONFORMANCE_SUITE],
      }
    : {
        status: 'unverified' as const,
        automation: 'unverified' as const,
        risk: ['unobserved'],
        riskScore: 2,
        riskReasons: [UNOBSERVED_REASON],
        evidence: resolvedEvidence,
      };
  return buildRow({
    ...rest,
    rowRef: String(ref),
    ...climb,
  });
}

export const firestoreSwiftRows: CompatibilityRow[] = [
  // ── 1. Firestore: Instance & Lifecycle ────────────────────────────────────
  row({
    ref: 1,
    flipped: 'unit-backed',
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.firestore()',
    behavior: 'Returns the default Firestore instance configured with the default FirebaseApp.',
    featureKeys: ['firestore'],
  }),
  row({
    ref: 2,
    flipped: 'unit-backed',
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.firestore(app:)',
    behavior: 'Returns a Firestore instance associated with the specified FirebaseApp.',
    featureKeys: ['firestoreApp'],
  }),
  row({
    ref: 3,
    flipped: 'unit-backed',
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.firestore(app:database:)',
    behavior: 'Returns a named database instance for the specified FirebaseApp.',
    featureKeys: ['firestoreAppDatabase'],
  }),
  row({
    ref: 4,
    flipped: 'unit-backed',
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.firestore(database:)',
    behavior: 'Returns a named database instance for the default FirebaseApp.',
    featureKeys: ['firestoreDatabase'],
  }),
  row({
    ref: 5,
    flipped: 'unit-backed',
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.settings',
    behavior: 'Provides custom client configuration including host, sslEnabled, dispatchQueue, and cacheSettings.',
    featureKeys: ['settings'],
  }),
  row({
    ref: 6,
    flipped: 'unit-backed',
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.app',
    behavior: 'Returns the FirebaseApp associated with this Firestore instance.',
    featureKeys: ['app'],
  }),
  row({
    ref: 7,
    flipped: 'unit-backed',
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.document(_:)',
    behavior: 'Instantiates a DocumentReference pointing to the slash-delimited document path.',
    featureKeys: ['document'],
  }),
  row({
    ref: 8,
    flipped: 'unit-backed',
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.collection(_:)',
    behavior: 'Instantiates a CollectionReference pointing to the slash-delimited collection path.',
    featureKeys: ['collection'],
  }),
  row({
    ref: 9,
    flipped: 'unit-backed',
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.collectionGroup(_:)',
    behavior: 'Instantiates a Query spanning all collections with the matching collectionID.',
    featureKeys: ['collectionGroup'],
  }),
  row({
    ref: 10,
    flipped: 'unit-backed',
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.batch()',
    behavior: 'Instantiates a WriteBatch for atomic batched mutations.',
    featureKeys: ['batch'],
  }),
  row({
    ref: 11,
    flipped: 'unit-backed',
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.runTransaction(_:)',
    behavior: 'Executes an interactive transaction block with automatic conflict retry.',
    featureKeys: ['runTransaction'],
  }),
  row({
    ref: 12,
    flipped: 'unit-backed',
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.runTransaction(options:block:)',
    behavior: 'Executes an interactive transaction with custom TransactionOptions.',
    featureKeys: ['runTransactionWithOptions'],
  }),
  row({
    ref: 13,
    flipped: 'unit-backed',
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.runTransaction(_:) async',
    behavior: 'Executes an interactive transaction asynchronously via Swift concurrency.',
    featureKeys: ['runTransactionAsync'],
  }),
  row({
    ref: 14,
    flipped: 'unit-backed',
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.useEmulator(host:port:)',
    behavior: 'Configures client networking to route requests to a local emulator or Pyric bridge.',
    featureKeys: ['useEmulator'],
  }),
  row({
    ref: 15,
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.enableNetwork() / disableNetwork()',
    behavior: 'Toggles client network connectivity to simulate offline and online operation.',
    featureKeys: ['enableNetwork', 'disableNetwork'],
  }),
  row({
    ref: 16,
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.clearPersistence()',
    behavior: 'Clears offline client persistence cache when no active listeners exist.',
    featureKeys: ['clearPersistence'],
  }),
  row({
    ref: 17,
    flipped: 'unit-backed',
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.terminate()',
    behavior: 'Terminates the client instance and cancels active snapshot listeners.',
    featureKeys: ['terminate'],
  }),
  row({
    ref: 18,
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.waitForPendingWrites()',
    behavior: 'Awaits backend acknowledgment of all pending local writes.',
    featureKeys: ['waitForPendingWrites'],
  }),
  row({
    ref: 19,
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.addSnapshotsInSyncListener(_:)',
    behavior: 'Attaches a callback invoked when all active snapshot listeners synchronize.',
    featureKeys: ['addSnapshotsInSyncListener'],
  }),
  row({
    ref: 20,
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.loadBundle(_:)',
    behavior: 'Loads serialized Firestore bundle data into the local cache.',
    featureKeys: ['loadBundle'],
  }),
  row({
    ref: 21,
    section: '`Firestore` — instance & lifecycle',
    api: 'Firestore.getQuery(named:completion:)',
    behavior: 'Retrieves a named query from a previously loaded Firestore bundle.',
    featureKeys: ['getQuery'],
  }),

  // ── 2. DocumentReference: Document Operations ────────────────────────────
  row({
    ref: 22,
    flipped: 'unit-backed',
    section: '`DocumentReference` — document operations',
    api: 'DocumentReference.documentID',
    behavior: 'Returns the document identifier representing the last path component.',
    featureKeys: ['documentID'],
  }),
  row({
    ref: 23,
    flipped: 'unit-backed',
    section: '`DocumentReference` — document operations',
    api: 'DocumentReference.path',
    behavior: 'Returns the slash-delimited path relative to the database root.',
    featureKeys: ['path'],
  }),
  row({
    ref: 24,
    flipped: 'unit-backed',
    section: '`DocumentReference` — document operations',
    api: 'DocumentReference.parent',
    behavior: 'Returns the parent CollectionReference containing this document.',
    featureKeys: ['parent'],
  }),
  row({
    ref: 25,
    flipped: 'unit-backed',
    section: '`DocumentReference` — document operations',
    api: 'DocumentReference.collection(_:)',
    behavior: 'Instantiates a child CollectionReference nested under this document.',
    featureKeys: ['collection'],
  }),
  row({
    ref: 26,
    flipped: 'unit-backed',
    section: '`DocumentReference` — document operations',
    api: 'DocumentReference.getDocument(source:)',
    behavior: 'Reads document snapshot from server, cache, or default source.',
    featureKeys: ['getDocument'],
  }),
  row({
    ref: 27,
    flipped: 'unit-backed',
    section: '`DocumentReference` — document operations',
    api: 'DocumentReference.setData(_:)',
    behavior: 'Overwrites the target document completely with provided dictionary payload.',
    featureKeys: ['setData'],
  }),
  row({
    ref: 28,
    flipped: 'unit-backed',
    section: '`DocumentReference` — document operations',
    api: 'DocumentReference.setData(_:merge:)',
    behavior: 'Merges payload fields into existing document without overwriting unspecified fields.',
    featureKeys: ['setDataMerge'],
  }),
  row({
    ref: 29,
    flipped: 'unit-backed',
    section: '`DocumentReference` — document operations',
    api: 'DocumentReference.setData(_:mergeFields:)',
    behavior: 'Replaces only explicitly specified field paths in the target document.',
    featureKeys: ['setDataMergeFields'],
  }),
  row({
    ref: 30,
    flipped: 'unit-backed',
    section: '`DocumentReference` — document operations',
    api: 'DocumentReference.updateData(_:)',
    behavior: 'Updates specified fields in an existing document; fails if document does not exist.',
    featureKeys: ['updateData'],
  }),
  row({
    ref: 31,
    flipped: 'unit-backed',
    section: '`DocumentReference` — document operations',
    api: 'DocumentReference.delete()',
    behavior: 'Deletes document at reference path from Firestore database.',
    featureKeys: ['delete'],
  }),
  row({
    ref: 32,
    flipped: 'unit-backed',
    section: '`DocumentReference` — document operations',
    api: 'DocumentReference.addSnapshotListener(_:)',
    behavior: 'Attaches real-time closure listener receiving DocumentSnapshot updates.',
    featureKeys: ['addSnapshotListener'],
  }),
  row({
    ref: 33,
    flipped: 'unit-backed',
    section: '`DocumentReference` — document operations',
    api: 'DocumentReference.addSnapshotListener(includeMetadataChanges:listener:)',
    behavior: 'Listens to document snapshot updates including metadata-only transitions.',
    featureKeys: ['addSnapshotListenerMetadata'],
  }),
  row({
    ref: 34,
    flipped: 'unit-backed',
    section: '`DocumentReference` — document operations',
    api: 'DocumentReference.addSnapshotListener(options:listener:)',
    behavior: 'Listens to document updates configured with SnapshotListenOptions.',
    featureKeys: ['addSnapshotListenerOptions'],
  }),

  // ── 3. CollectionReference: Collection Operations ────────────────────────
  row({
    ref: 35,
    flipped: 'unit-backed',
    section: '`CollectionReference` — collection operations',
    api: 'CollectionReference.collectionID',
    behavior: 'Returns the collection identifier string.',
    featureKeys: ['collectionID'],
  }),
  row({
    ref: 36,
    flipped: 'unit-backed',
    section: '`CollectionReference` — collection operations',
    api: 'CollectionReference.path',
    behavior: 'Returns the full slash-separated collection path relative to database root.',
    featureKeys: ['path'],
  }),
  row({
    ref: 37,
    flipped: 'unit-backed',
    section: '`CollectionReference` — collection operations',
    api: 'CollectionReference.parent',
    behavior: 'Returns parent DocumentReference or nil if this is a root collection.',
    featureKeys: ['parent'],
  }),
  row({
    ref: 38,
    flipped: 'unit-backed',
    section: '`CollectionReference` — collection operations',
    api: 'CollectionReference.document()',
    behavior: 'Instantiates a child DocumentReference with an auto-generated unique ID.',
    featureKeys: ['documentAutoId'],
  }),
  row({
    ref: 39,
    flipped: 'unit-backed',
    section: '`CollectionReference` — collection operations',
    api: 'CollectionReference.document(_:)',
    behavior: 'Instantiates a child DocumentReference at relative document path.',
    featureKeys: ['documentPath'],
  }),
  row({
    ref: 40,
    flipped: 'unit-backed',
    section: '`CollectionReference` — collection operations',
    api: 'CollectionReference.addDocument(data:)',
    behavior: 'Auto-generates document ID, writes data payload, and returns document reference.',
    featureKeys: ['addDocument'],
  }),

  // ── 4. Query: Filters & Constraints ──────────────────────────────────────
  row({
    ref: 41,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.whereField(_:isEqualTo:)',
    behavior: 'Filters documents matching exact field equality.',
    featureKeys: ['whereFieldEqualTo'],
  }),
  row({
    ref: 42,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.whereField(_:isNotEqualTo:)',
    behavior: 'Filters documents where field does not equal value.',
    featureKeys: ['whereFieldNotEqualTo'],
  }),
  row({
    ref: 43,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.whereField(_:isLessThan:)',
    behavior: 'Filters documents where field is strictly less than value.',
    featureKeys: ['whereFieldLessThan'],
  }),
  row({
    ref: 44,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.whereField(_:isLessThanOrEqualTo:)',
    behavior: 'Filters documents where field is less than or equal to value.',
    featureKeys: ['whereFieldLessThanOrEqualTo'],
  }),
  row({
    ref: 45,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.whereField(_:isGreaterThan:)',
    behavior: 'Filters documents where field is strictly greater than value.',
    featureKeys: ['whereFieldGreaterThan'],
  }),
  row({
    ref: 46,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.whereField(_:isGreaterThanOrEqualTo:)',
    behavior: 'Filters documents where field is greater than or equal to value.',
    featureKeys: ['whereFieldGreaterThanOrEqualTo'],
  }),
  row({
    ref: 47,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.whereField(_:arrayContains:)',
    behavior: 'Filters documents where array field contains argument element.',
    featureKeys: ['whereFieldArrayContains'],
  }),
  row({
    ref: 48,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.whereField(_:arrayContainsAny:)',
    behavior: 'Filters documents where array field contains any element from argument list.',
    featureKeys: ['whereFieldArrayContainsAny'],
  }),
  row({
    ref: 49,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.whereField(_:in:)',
    behavior: 'Filters documents where field value matches any element in argument list.',
    featureKeys: ['whereFieldIn'],
  }),
  row({
    ref: 50,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.whereField(_:notIn:)',
    behavior: 'Filters documents where field value matches none in argument list.',
    featureKeys: ['whereFieldNotIn'],
  }),
  row({
    ref: 51,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.whereFilter(_:)',
    behavior: 'Applies composite boolean Filter using andFilter or orFilter disjunctions.',
    featureKeys: ['whereFilter'],
  }),
  row({
    ref: 52,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.order(by:)',
    behavior: 'Sorts query results by field ascending.',
    featureKeys: ['orderBy'],
  }),
  row({
    ref: 53,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.order(by:descending:)',
    behavior: 'Sorts query results by field ascending or descending.',
    featureKeys: ['orderByDescending'],
  }),
  row({
    ref: 54,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.limit(to:)',
    behavior: 'Limits maximum number of matching documents from start of query results.',
    featureKeys: ['limitTo'],
  }),
  row({
    ref: 55,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.limit(toLast:)',
    behavior: 'Limits results to last N documents requiring explicit orderBy constraint.',
    featureKeys: ['limitToLast'],
  }),
  row({
    ref: 56,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.start(at:) / start(after:)',
    behavior: 'Positions starting cursor using ordered field values.',
    featureKeys: ['startAt', 'startAfter'],
  }),
  row({
    ref: 57,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.end(before:) / end(at:)',
    behavior: 'Positions ending cursor using ordered field values.',
    featureKeys: ['endBefore', 'endAt'],
  }),
  row({
    ref: 58,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.start(atDocument:) / start(afterDocument:)',
    behavior: 'Positions starting cursor using DocumentSnapshot position.',
    featureKeys: ['startAtDocument', 'startAfterDocument'],
  }),
  row({
    ref: 59,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.end(beforeDocument:) / end(atDocument:)',
    behavior: 'Positions ending cursor using DocumentSnapshot position.',
    featureKeys: ['endBeforeDocument', 'endAtDocument'],
  }),
  row({
    ref: 60,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.getDocuments(source:)',
    behavior: 'Executes query and returns QuerySnapshot from server, cache, or default source.',
    featureKeys: ['getDocuments'],
  }),
  row({
    ref: 61,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.addSnapshotListener(_:)',
    behavior: 'Attaches real-time query listener returning ListenerRegistration handle.',
    featureKeys: ['addQuerySnapshotListener'],
  }),
  row({
    ref: 62,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.addSnapshotListener(includeMetadataChanges:listener:)',
    behavior: 'Attaches real-time query listener receiving metadata-only change notifications.',
    featureKeys: ['addQuerySnapshotListenerMetadata'],
  }),
  row({
    ref: 63,
    flipped: 'unit-backed',
    section: '`Query` — filters & constraints',
    api: 'Query.addSnapshotListener(options:listener:)',
    behavior: 'Attaches real-time query listener configured with SnapshotListenOptions.',
    featureKeys: ['addQuerySnapshotListenerOptions'],
  }),

  // ── 5. Snapshots & Metadata ──────────────────────────────────────────────
  row({
    ref: 64,
    flipped: 'unit-backed',
    section: 'Snapshots & metadata',
    api: 'DocumentSnapshot.exists',
    behavior: 'Boolean indicating whether document currently exists in Firestore.',
    featureKeys: ['exists'],
  }),
  row({
    ref: 65,
    flipped: 'unit-backed',
    section: 'Snapshots & metadata',
    api: 'DocumentSnapshot.documentID',
    behavior: 'Unique key string identifying the snapshot document.',
    featureKeys: ['snapshotDocumentID'],
  }),
  row({
    ref: 66,
    flipped: 'unit-backed',
    section: 'Snapshots & metadata',
    api: 'DocumentSnapshot.reference',
    behavior: 'DocumentReference pointing to the snapshot document location.',
    featureKeys: ['reference'],
  }),
  row({
    ref: 67,
    flipped: 'unit-backed',
    section: 'Snapshots & metadata',
    api: 'DocumentSnapshot.metadata',
    behavior: 'SnapshotMetadata describing cache origin and pending write status.',
    featureKeys: ['snapshotMetadata'],
  }),
  row({
    ref: 68,
    flipped: 'unit-backed',
    section: 'Snapshots & metadata',
    api: 'DocumentSnapshot.data()',
    behavior: 'Returns dictionary of document fields or nil if document does not exist.',
    featureKeys: ['data'],
  }),
  row({
    ref: 69,
    flipped: 'unit-backed',
    section: 'Snapshots & metadata',
    api: 'DocumentSnapshot.data(with:)',
    behavior: 'Returns document fields configuring ServerTimestampBehavior handling.',
    featureKeys: ['dataWithServerTimestampBehavior'],
  }),
  row({
    ref: 70,
    flipped: 'unit-backed',
    section: 'Snapshots & metadata',
    api: 'DocumentSnapshot.get(_:)',
    behavior: 'Extracts nested field value supporting dot-delimited string or FieldPath.',
    featureKeys: ['get'],
  }),
  row({
    ref: 71,
    flipped: 'unit-backed',
    section: 'Snapshots & metadata',
    api: 'DocumentSnapshot.subscript',
    behavior: 'Provides subscript syntax snapshot[key] to access document fields.',
    featureKeys: ['subscript'],
  }),
  row({
    ref: 72,
    flipped: 'unit-backed',
    section: 'Snapshots & metadata',
    api: 'QueryDocumentSnapshot',
    behavior: 'Guaranteed-existent document snapshot subclass where data() is non-optional.',
    featureKeys: ['queryDocumentSnapshot'],
  }),
  row({
    ref: 73,
    flipped: 'unit-backed',
    section: 'Snapshots & metadata',
    api: 'SnapshotMetadata (hasPendingWrites, isFromCache)',
    behavior: 'Flags indicating uncommitted local writes and cache data origin.',
    featureKeys: ['hasPendingWrites', 'isFromCache'],
  }),
  row({
    ref: 74,
    flipped: 'unit-backed',
    section: 'Snapshots & metadata',
    api: 'QuerySnapshot.documents',
    behavior: 'Ordered array of QueryDocumentSnapshot instances matched by query.',
    featureKeys: ['documents'],
  }),
  row({
    ref: 75,
    flipped: 'unit-backed',
    section: 'Snapshots & metadata',
    api: 'QuerySnapshot.documentChanges',
    behavior: 'List of DocumentChange deltas since previous snapshot emission.',
    featureKeys: ['documentChanges'],
  }),
  row({
    ref: 76,
    flipped: 'unit-backed',
    section: 'Snapshots & metadata',
    api: 'QuerySnapshot.documentChanges(includeMetadataChanges:)',
    behavior: 'List of DocumentChange deltas including metadata-only changes.',
    featureKeys: ['documentChangesIncludeMetadata'],
  }),
  row({
    ref: 77,
    flipped: 'unit-backed',
    section: 'Snapshots & metadata',
    api: 'QuerySnapshot.isEmpty / count',
    behavior: 'Inspection properties reporting empty status and count of matched documents.',
    featureKeys: ['isEmpty', 'count'],
  }),
  row({
    ref: 78,
    flipped: 'unit-backed',
    section: 'Snapshots & metadata',
    api: 'DocumentChange (type, document, oldIndex, newIndex)',
    behavior: 'Delta change descriptor indicating added, modified, or removed mutations.',
    featureKeys: ['documentChange'],
  }),

  // ── 6. WriteBatch: Atomic Batches ────────────────────────────────────────
  row({
    ref: 79,
    flipped: 'unit-backed',
    section: '`WriteBatch` — atomic batches',
    api: 'WriteBatch.setData(_:forDocument:)',
    behavior: 'Enqueues set overwrite operation into atomic mutation batch.',
    featureKeys: ['batchSetData'],
  }),
  row({
    ref: 80,
    flipped: 'unit-backed',
    section: '`WriteBatch` — atomic batches',
    api: 'WriteBatch.setData(_:forDocument:merge:)',
    behavior: 'Enqueues set merge operation into atomic mutation batch.',
    featureKeys: ['batchSetDataMerge'],
  }),
  row({
    ref: 81,
    flipped: 'unit-backed',
    section: '`WriteBatch` — atomic batches',
    api: 'WriteBatch.setData(_:forDocument:mergeFields:)',
    behavior: 'Enqueues selective field merge operation into atomic mutation batch.',
    featureKeys: ['batchSetDataMergeFields'],
  }),
  row({
    ref: 82,
    flipped: 'unit-backed',
    section: '`WriteBatch` — atomic batches',
    api: 'WriteBatch.updateData(_:forDocument:)',
    behavior: 'Enqueues update operation into atomic mutation batch.',
    featureKeys: ['batchUpdateData'],
  }),
  row({
    ref: 83,
    flipped: 'unit-backed',
    section: '`WriteBatch` — atomic batches',
    api: 'WriteBatch.deleteDocument(_:)',
    behavior: 'Enqueues document deletion into atomic mutation batch.',
    featureKeys: ['batchDeleteDocument'],
  }),
  row({
    ref: 84,
    flipped: 'unit-backed',
    section: '`WriteBatch` — atomic batches',
    api: 'WriteBatch.commit()',
    behavior: 'Atomically commits all enqueued batch mutations in a single transaction.',
    featureKeys: ['batchCommit'],
  }),

  // ── 7. Transaction: Interactive Transactions ─────────────────────────────
  row({
    ref: 85,
    flipped: 'unit-backed',
    section: '`Transaction` — interactive transactions',
    api: 'Transaction.getDocument(_:)',
    behavior: 'Reads document snapshot within transaction and establishes read lock.',
    featureKeys: ['transactionGetDocument'],
  }),
  row({
    ref: 86,
    flipped: 'unit-backed',
    section: '`Transaction` — interactive transactions',
    api: 'Transaction.setData(_:forDocument:)',
    behavior: 'Stages transactional set overwrite mutation.',
    featureKeys: ['transactionSetData'],
  }),
  row({
    ref: 87,
    flipped: 'unit-backed',
    section: '`Transaction` — interactive transactions',
    api: 'Transaction.setData(_:forDocument:merge:)',
    behavior: 'Stages transactional set merge mutation.',
    featureKeys: ['transactionSetDataMerge'],
  }),
  row({
    ref: 88,
    flipped: 'unit-backed',
    section: '`Transaction` — interactive transactions',
    api: 'Transaction.setData(_:forDocument:mergeFields:)',
    behavior: 'Stages transactional selective field merge mutation.',
    featureKeys: ['transactionSetDataMergeFields'],
  }),
  row({
    ref: 89,
    flipped: 'unit-backed',
    section: '`Transaction` — interactive transactions',
    api: 'Transaction.updateData(_:forDocument:)',
    behavior: 'Stages transactional update mutation for existing document.',
    featureKeys: ['transactionUpdateData'],
  }),
  row({
    ref: 90,
    flipped: 'unit-backed',
    section: '`Transaction` — interactive transactions',
    api: 'Transaction.deleteDocument(_:)',
    behavior: 'Stages transactional document deletion.',
    featureKeys: ['transactionDeleteDocument'],
  }),
  row({
    ref: 91,
    flipped: 'unit-backed',
    section: '`Transaction` — interactive transactions',
    api: 'TransactionOptions.maxAttempts',
    behavior: 'Configures maximum retry attempts upon transactional concurrent contention.',
    featureKeys: ['transactionOptionsMaxAttempts'],
  }),

  // ── 8. FieldValue: Sentinels & Transformations ───────────────────────────
  row({
    ref: 92,
    flipped: 'unit-backed',
    section: '`FieldValue` — sentinels & transformations',
    api: 'FieldValue.serverTimestamp()',
    behavior: 'Sentinel replaced by server commit timestamp during write processing.',
    featureKeys: ['serverTimestamp'],
  }),
  row({
    ref: 93,
    flipped: 'unit-backed',
    section: '`FieldValue` — sentinels & transformations',
    api: 'FieldValue.delete()',
    behavior: 'Sentinel deleting target field during document update operation.',
    featureKeys: ['deleteField'],
  }),
  row({
    ref: 94,
    flipped: 'unit-backed',
    section: '`FieldValue` — sentinels & transformations',
    api: 'FieldValue.increment(_:)',
    behavior: 'Operand atomically incrementing numeric integer or double field value.',
    featureKeys: ['increment'],
  }),
  row({
    ref: 95,
    flipped: 'unit-backed',
    section: '`FieldValue` — sentinels & transformations',
    api: 'FieldValue.arrayUnion(_:)',
    behavior: 'Transformation adding unique elements to array field if absent.',
    featureKeys: ['arrayUnion'],
  }),
  row({
    ref: 96,
    flipped: 'unit-backed',
    section: '`FieldValue` — sentinels & transformations',
    api: 'FieldValue.arrayRemove(_:)',
    behavior: 'Transformation removing matching elements from array field.',
    featureKeys: ['arrayRemove'],
  }),
  row({
    ref: 97,
    flipped: 'unit-backed',
    section: '`FieldValue` — sentinels & transformations',
    api: 'FieldValue.vector(_:)',
    behavior: 'Constructs dense vector embedding from Double or Float array.',
    featureKeys: ['vector'],
  }),

  // ── 9. Data Types & Value Codecs ─────────────────────────────────────────
  row({
    ref: 98,
    flipped: 'unit-backed',
    section: 'Data types & value codecs',
    api: 'Timestamp',
    behavior: 'UTC timestamp representing 64-bit seconds and nanosecond resolution.',
    featureKeys: ['timestamp'],
  }),
  row({
    ref: 99,
    flipped: 'unit-backed',
    section: 'Data types & value codecs',
    api: 'GeoPoint',
    behavior: 'Immutable geographic coordinate pair with latitude and longitude bounds.',
    featureKeys: ['geoPoint'],
  }),
  row({
    ref: 100,
    flipped: 'unit-backed',
    section: 'Data types & value codecs',
    api: 'FieldPath',
    behavior: 'Path pointing to nested document field or documentID sentinel.',
    featureKeys: ['fieldPath'],
  }),

  // ── 10. Concurrency & Async Sequences ────────────────────────────────────
  row({
    ref: 101,
    flipped: 'unit-backed',
    section: 'Concurrency & async sequences',
    api: 'DocumentReference.snapshots',
    behavior: 'AsyncSequence streaming real-time DocumentSnapshot updates via Swift concurrency.',
    featureKeys: ['documentSnapshotsSequence'],
  }),
  row({
    ref: 102,
    flipped: 'unit-backed',
    section: 'Concurrency & async sequences',
    api: 'Query.snapshots',
    behavior: 'AsyncSequence streaming real-time QuerySnapshot updates via Swift concurrency.',
    featureKeys: ['querySnapshotsSequence'],
  }),

  // ── 11. Codable Integration ──────────────────────────────────────────────
  row({
    ref: 103,
    section: 'Codable integration',
    api: '@DocumentID',
    behavior: 'Property wrapper populating document ID on decoding; omitted from write payloads.',
    featureKeys: ['documentIDPropertyWrapper'],
  }),
  row({
    ref: 104,
    section: 'Codable integration',
    api: '@ServerTimestamp',
    behavior: 'Property wrapper encoding nil as serverTimestamp sentinel on write.',
    featureKeys: ['serverTimestampPropertyWrapper'],
  }),
  row({
    ref: 105,
    section: 'Codable integration',
    api: 'DocumentSnapshot.data(as:decoder:)',
    behavior: 'Decodes document snapshot fields directly into Decodable model.',
    featureKeys: ['dataAsDecodable'],
  }),
];

const INTRO = `# Swift Cloud Firestore integration compatibility

## Status legend

| Status | Meaning |
|---|---|
| ✓ | **Conforming** — Swift test matches FirebaseFirestore API surface |
| ⚠ | **Diverged (documented)** — intentional difference with a written reason |
| ✗ | **Bug** — should match FirebaseFirestore API surface but does not |
| — | **Not implemented yet** — explicitly outside the implemented slice |
| ? | **Unverified** — FirebaseFirestore behavior not yet verified locally |
`;

export const firestoreSwiftRegistry: CompatibilitySurfaceRegistry = {
  surface: 'firestore-swift',
  label: 'Firestore · Swift',
  compatPath: 'packages/conformance/docs/firestore-swift/COMPAT.md',
  blocks: [
    { kind: 'markdown', markdown: INTRO },
    {
      kind: 'table',
      prefix: '## `Firestore` — instance & lifecycle\n',
      rows: firestoreSwiftRows.filter((r) => r.section === '`Firestore` — instance & lifecycle'),
    },
    {
      kind: 'table',
      prefix: '## `DocumentReference` — document operations\n',
      rows: firestoreSwiftRows.filter((r) => r.section === '`DocumentReference` — document operations'),
    },
    {
      kind: 'table',
      prefix: '## `CollectionReference` — collection operations\n',
      rows: firestoreSwiftRows.filter((r) => r.section === '`CollectionReference` — collection operations'),
    },
    {
      kind: 'table',
      prefix: '## `Query` — filters & constraints\n',
      rows: firestoreSwiftRows.filter((r) => r.section === '`Query` — filters & constraints'),
    },
    {
      kind: 'table',
      prefix: '## Snapshots & metadata\n',
      rows: firestoreSwiftRows.filter((r) => r.section === 'Snapshots & metadata'),
    },
    {
      kind: 'table',
      prefix: '## `WriteBatch` — atomic batches\n',
      rows: firestoreSwiftRows.filter((r) => r.section === '`WriteBatch` — atomic batches'),
    },
    {
      kind: 'table',
      prefix: '## `Transaction` — interactive transactions\n',
      rows: firestoreSwiftRows.filter((r) => r.section === '`Transaction` — interactive transactions'),
    },
    {
      kind: 'table',
      prefix: '## `FieldValue` — sentinels & transformations\n',
      rows: firestoreSwiftRows.filter((r) => r.section === '`FieldValue` — sentinels & transformations'),
    },
    {
      kind: 'table',
      prefix: '## Data types & value codecs\n',
      rows: firestoreSwiftRows.filter((r) => r.section === 'Data types & value codecs'),
    },
    {
      kind: 'table',
      prefix: '## Concurrency & async sequences\n',
      rows: firestoreSwiftRows.filter((r) => r.section === 'Concurrency & async sequences'),
    },
    {
      kind: 'table',
      prefix: '## Codable integration\n',
      rows: firestoreSwiftRows.filter((r) => r.section === 'Codable integration'),
    },
  ],
};

export default firestoreSwiftRegistry;
