import { defineRows } from './define-rows.ts';
import type { CompatibilitySurfaceRegistry } from './types.ts';

/**
 * The shared NATIVE rules surface registry. Hosts the rules-ENGINE fidelity
 * rows for ALL THREE rules engines — the Firestore rules simulator
 * (firestore-rules), the Storage rules engine (storage-rules), and the RTDB
 * rules simulator (rtdb-rules) — per the rules-native-surface design's dividing
 * line: a row comparing a pyric rules engine to production lives here; a row
 * describing how an SDK surface enforces a rules verdict stays with that SDK.
 *
 * Three contracts (surfaces/firestore-rules.json, surfaces/storage-rules.json,
 * surfaces/rtdb-rules.json) resolve their registry: 'rules' key to this object, on
 * the rtdb / rtdb-modular -> rtdb registry precedent. rtdb-rules was admitted
 * last: it is the engine with no server-side rules test API, so it could not be
 * claimed until its deploy-observe-restore oracle chain landed and produced the
 * `rules-rtdb-` captures its rows cite.
 */

const row1 = defineRows({
  surface: "firestore-rules",
  defaults: {
    section: "Rules engine — production simulator conformance (rules-firestore corpus)",
    api: "Rules simulator",
    automation: "oracle-backed",
    conformanceTests: ["packages/pyric/test/rules/oracle-conformance.test.ts"],
  },
});

const row2 = defineRows({
  surface: "storage-rules",
  defaults: {
    section: "Rules — `parseStorageRules` / `evaluateStorageRules` / `getStorage(ctx, { rules })`",
    api: "Rules",
  },
});

const row3 = defineRows({
  surface: "rtdb-rules",
  defaults: {
    section: "RTDB rules engine — production simulator conformance (rules-rtdb corpus)",
    api: "Rules simulator",
    status: "conforms",
    automation: "oracle-backed",
    conformanceTests: ["packages/pyric/test/rules/rtdb/rules-conformance.test.ts"],
  },
});

export const rulesRegistry = {
  surface: "rules",
  label: "Rules",
  compatPath: "packages/pyric/docs/rules/COMPAT.md",
  blocks: [
    { kind: 'markdown', markdown: "# `pyric/rules` compatibility matrix\n\n## Status legend\n\n| Status | Meaning |\n|---|---|\n| ✓ | **Conforming** — the simulator matches the production verdict, locked by a replayed observation |\n| ⚠ | **Diverged (documented)** — a known simulator divergence from production with a written reason |\n| ✗ | **Bug** — should match production but doesn't; a failing replay pins it |\n| — | **Not implemented yet** — not modeled (deliberately or pending) |\n| ? | **Unverified** — a claim we haven't yet observed against the production engine |\n" },
    {
      kind: 'table',
      prefix: "## Firestore rules engine — production simulator conformance (rules-firestore corpus)\n",
      rows: [
        row1({
          rowRef: "160",
          featureKeys: ["math","timestamp","duration"],
          behavior: "CEL builtins `math.*`/`timestamp.*`/`duration.*` (FM3) — arithmetic, date, and duration comparisons in rules",
          status: "conforms",
          evidence: "`oracle:rules-firestore-builtins-time-and-math` — production Firestore Rules Test API verdicts for corpus scenario \"builtins-time-and-math\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.",
          oracleObservations: ["rules-firestore-builtins-time-and-math"],
        }),
        row1({
          rowRef: "161",
          featureKeys: [],
          behavior: "`Bytes`, `String.toUtf8()`, and `hashing.{md5,sha256,crc32,crc32c}()` (Item 5.3) in rules",
          status: "conforms",
          evidence: "`oracle:rules-firestore-bytes-toutf8-and-hashing` — a 2026-07-21 production Firestore Rules Test API recapture supplies 20 verdicts, including paired negative and positive witnesses for padded base64url, the URL-safe alphabet, uppercase hexadecimal MD5/SHA-256, and production's little-endian CRC32/CRC32C byte serialization. `unit:rules/oracle-conformance.test.ts` replays all verdicts against the local simulator; `unit:rules/simulator/wrappers/bytes.test.ts` pins the exact representations and reference digests.",
          risk: ["specific-value","rules-denial"],
          riskScore: 3,
          riskReasons: ["asserts 1 specific value(s)","asserts rules-denial behavior"],
          oracleObservations: ["rules-firestore-bytes-toutf8-and-hashing"],
          constructs: ["firestore.method.string.toUtf8","firestore.function.hashing.md5","firestore.function.hashing.sha256","firestore.function.hashing.crc32","firestore.function.hashing.crc32c","firestore.method.bytes.size","firestore.method.bytes.toBase64","firestore.method.bytes.toHexString"],
        }),
        row1({
          rowRef: "162",
          featureKeys: ["Timestamp","Duration","crossTypeOperators"],
          behavior: "Typed cross-type operator overloads for `Timestamp`/`Duration` (Item 2) in rules — no silent numeric coercion / type-identity loss",
          status: "conforms",
          evidence: "`oracle:rules-firestore-cross-type-operator-overloads` — production Firestore Rules Test API verdicts for corpus scenario \"cross-type-operator-overloads\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.",
          oracleObservations: ["rules-firestore-cross-type-operator-overloads"],
        }),
        row1({
          rowRef: "163",
          featureKeys: [],
          behavior: "CEL tri-state error absorption in `||`/`&&` (RULES-B3) — `error || true` → ALLOW, `error && false` → DENY, commutative absorption (not JS left-to-right short-circuit)",
          status: "conforms",
          evidence: "`oracle:rules-firestore-error-absorption-and-or` — production Firestore Rules Test API verdicts for corpus scenario \"error-absorption-and-or\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.",
          oracleObservations: ["rules-firestore-error-absorption-and-or"],
          constructs: ["firestore.semantic.error-absorption-and","firestore.semantic.error-absorption-or","firestore.operator.and","firestore.operator.or"],
        }),
        row1({
          rowRef: "164",
          featureKeys: ["getAfter","existsAfter"],
          behavior: "`getAfter()`/`existsAfter()` (Item 7) in rules — post-write document identity and existence semantics",
          status: "diverged-documented",
          conformanceDisposition: "probe-limitation",
          evidence: "`oracle:rules-firestore-get-after-and-exists-after` records five DENY verdicts from the production Rules Test API. The retained production diagnostics identify the observable boundary precisely: every case reports `Function not found` for `getAfter`/`existsAfter`, so this endpoint cannot evaluate the documented atomic-write semantics. The official Firestore Rules reference defines `getAfter(path)` as the projected document after the current atomic request and `existsAfter(path)` as its existence check; local `unit:sandbox/firestore/simulator/get-after.test.ts` and `get-after-batch.test.ts` suites exercise target, sibling-write, delete, and atomicity behavior. Forcing these cases to DENY would regress that contract; the negative observation remains score-contaminating and is explicitly classified as a probe limitation.",
          risk: ["specific-value","rules-denial"],
          riskScore: 3,
          riskReasons: ["asserts 1 specific value(s)","asserts rules-denial behavior"],
          oracleObservations: ["rules-firestore-get-after-and-exists-after"],
          constructs: ["firestore.function.getAfter","firestore.function.existsAfter"],
        }),
        row1({
          rowRef: "165",
          featureKeys: [],
          behavior: "`get()` of a missing document (RULES-B8) in rules — resource identity (`id`/`__name__`) exposure on a mocked/missing get() result",
          status: "conforms",
          evidence: "`oracle:rules-firestore-get-missing-doc` — production Firestore Rules Test API verdicts for corpus scenario \"get-missing-doc\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`. Serializable `functionMocks` now retain their production data-only shape, so mocked `get()` results leave `id`/`__name__` absent and both identity reads error to DENY; real DocStore lookups retain their separate identity-bearing path. All 8 cases match production.",
          risk: ["specific-value","rules-denial"],
          riskScore: 3,
          riskReasons: ["asserts 1 specific value(s)","asserts rules-denial behavior"],
          oracleObservations: ["rules-firestore-get-missing-doc"],
          constructs: ["firestore.function.get","firestore.function.exists","firestore.binding.resource.id","firestore.binding.resource.__name__"],
        }),
        row1({
          rowRef: "166",
          featureKeys: [],
          behavior: "`request.path`/`request.query`/`resource.id`/`resource.__name__` globals (Item 6) in rules",
          status: "conforms",
          evidence: "`oracle:rules-firestore-globals-request-path-and-resource-id` — production Firestore Rules Test API verdicts for corpus scenario \"globals-request-path-and-resource-id\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`. `request.query` is now absent on non-list operations, so reading it on create errors to DENY instead of false-ALLOWing through an invented empty map. `request.path` and the create-time absent-resource controls remain unchanged; all 6 cases match production. Resource identity on an EXISTING document is scoped to firestore-rules#183.",
          risk: ["specific-value","rules-denial"],
          riskScore: 3,
          riskReasons: ["asserts 1 specific value(s)","asserts rules-denial behavior"],
          oracleObservations: ["rules-firestore-globals-request-path-and-resource-id"],
          constructs: ["firestore.binding.request.query"],
        }),
        row1({
          rowRef: "167",
          featureKeys: [],
          behavior: "`int`/`float` division and type distinction (RULES-B5) in rules — truncating int÷int, float division stays float, div-by-zero denies, `is int`/`is float` distinct",
          status: "conforms",
          evidence: "`oracle:rules-firestore-int-float-and-division` — production Firestore Rules Test API verdicts for all ten corpus cases, replayed verdict-for-verdict by `unit:rules/oracle-conformance.test.ts`. The simulator now revives non-integral JSON wire numbers as RulesFloat values, preserving production's float payload type while retaining bare integral numbers as ints; `unit:rules/simulator/handler.test.ts` pins both literal and payload distinctions.",
          risk: ["specific-value","rules-denial"],
          riskScore: 3,
          riskReasons: ["asserts 1 specific value(s)","asserts rules-denial behavior"],
          oracleObservations: ["rules-firestore-int-float-and-division"],
          constructs: ["firestore.operator.div","firestore.operator.is","firestore.function.cast.int","firestore.function.cast.float"],
        }),
        row1({
          rowRef: "168",
          featureKeys: ["concat","removeAll","toSet"],
          behavior: "`List.concat()`/`removeAll()`/`toSet()` (Item 5.2) in rules",
          status: "conforms",
          evidence: "`oracle:rules-firestore-list-methods-concat-removeall-toset` — production Firestore Rules Test API verdicts for all nine cases, replayed verdict-for-verdict by `unit:rules/oracle-conformance.test.ts`. The seven positive List witnesses and the concat DENY witness match; the historical `toSet().difference(list)` case remains DENY because production requires a Set argument.",
          oracleObservations: ["rules-firestore-list-methods-concat-removeall-toset"],
        }),
        row1({
          rowRef: "169",
          featureKeys: ["Map.get"],
          behavior: "`Map.get(key, default)`, including list-form nested-path traversal (Item 3), in rules",
          status: "conforms",
          evidence: "`oracle:rules-firestore-map-get-string-and-list-form` — production Firestore Rules Test API verdicts for corpus scenario \"map-get-string-and-list-form\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.",
          oracleObservations: ["rules-firestore-map-get-string-and-list-form"],
        }),
        row1({
          rowRef: "170",
          featureKeys: ["matches"],
          behavior: "`matches()` as an anchored full-string RE2 match (RULES-B4) in rules — a pattern matching only a substring is `false`",
          status: "conforms",
          evidence: "`oracle:rules-firestore-matches-full-string-regex` — production Firestore Rules Test API verdicts for corpus scenario \"matches-full-string-regex\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.",
          oracleObservations: ["rules-firestore-matches-full-string-regex"],
        }),
        row1({
          rowRef: "171",
          featureKeys: [],
          behavior: "`Path` wrapper, `path()` constructor, and `Path.bind()` (Item 5.4) in rules",
          status: "conforms",
          evidence: "`oracle:rules-firestore-path-constructor-and-bind` — production Firestore Rules Test API verdicts for all nine corpus cases in \"path-constructor-and-bind\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`, including production's rejection of a Path argument to `path()`.",
          risk: ["specific-value","rules-denial"],
          riskScore: 3,
          riskReasons: ["asserts 1 specific value(s)","asserts rules-denial behavior"],
          oracleObservations: ["rules-firestore-path-constructor-and-bind"],
          constructs: ["firestore.function.cast.path","firestore.method.path.bind"],
        }),
        row1({
          rowRef: "172",
          featureKeys: ["mapMembership","constructorAccess"],
          behavior: "Own-keys-only map membership and constructor-access denial (RULES-B7) in rules — `'toString' in map` is `false`, `.constructor` access errors (no JS prototype-chain leakage)",
          status: "conforms",
          evidence: "`oracle:rules-firestore-prototype-chain-keys` — production Firestore Rules Test API verdicts for corpus scenario \"prototype-chain-keys\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.",
          oracleObservations: ["rules-firestore-prototype-chain-keys"],
        }),
        row1({
          rowRef: "173",
          featureKeys: [],
          behavior: "Range-slice `[i:j]` syntax for `List` and `String` (Item 4) in rules",
          status: "conforms",
          evidence: "`oracle:rules-firestore-range-slice-list-and-string` — production Firestore Rules Test API verdicts for all ten corpus cases in \"range-slice-list-and-string\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`, including out-of-bounds slice-end rejection for both lists and strings.",
          risk: ["specific-value","rules-denial"],
          riskScore: 3,
          riskReasons: ["asserts 1 specific value(s)","asserts rules-denial behavior"],
          oracleObservations: ["rules-firestore-range-slice-list-and-string"],
          constructs: ["firestore.operator.slice"],
        }),
        row1({
          rowRef: "174",
          featureKeys: ["difference","union","intersection"],
          behavior: "`Set.difference()`/`union()`/`intersection()` (Item 5.1) in rules",
          status: "conforms",
          evidence: "`oracle:rules-firestore-set-algebra-difference-union-intersection` captures the receiver and argument boundary in twelve production cases: Map.keys() is a List and rejects Set-only algebra, explicit toSet() receivers ALLOW difference/union/intersection with Set arguments, and a wrong-result control DENIES. The local simulator replays every verdict and the per-construct acceptance probes use the same positive toSet() shapes.",
          oracleObservations: ["rules-firestore-set-algebra-difference-union-intersection"],
        }),
        row1({
          rowRef: "175",
          featureKeys: ["matches","stringEscapes"],
          behavior: "String-literal escape handling feeding `matches()` (Class B) in rules — `\\\\.` is unescaped before RE2 compilation, not forwarded raw to a JS `RegExp`",
          status: "conforms",
          evidence: "`oracle:rules-firestore-string-literals-and-regex` — production Firestore Rules Test API verdicts for corpus scenario \"string-literals-and-regex\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.",
          oracleObservations: ["rules-firestore-string-literals-and-regex"],
        }),
        row1({
          rowRef: "176",
          featureKeys: ["missingFieldAccess"],
          behavior: "Missing-field access as a runtime error (RULES-B2) in rules — `typo == null` denies (missing access is not null); `!(key in map)` is the real absence check",
          status: "conforms",
          evidence: "`oracle:rules-firestore-undefined-field-access` — production Firestore Rules Test API verdicts for corpus scenario \"undefined-field-access\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.",
          oracleObservations: ["rules-firestore-undefined-field-access"],
        }),
        row1({
          rowRef: "177",
          featureKeys: ["unsupportedBuiltins"],
          behavior: "Explicit `UNSUPPORTED` reporting for unimplemented built-ins (Item 0.A) in rules — an unimplemented built-in abstains rather than silently DENYing",
          status: "conforms",
          evidence: "`oracle:rules-firestore-unsupported-feature-witness` — production Firestore Rules Test API verdicts for corpus scenario \"unsupported-feature-witness\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.",
          oracleObservations: ["rules-firestore-unsupported-feature-witness"],
        }),
        row1({
          rowRef: "178",
          featureKeys: ["keys","diff","requiredFields"],
          behavior: "Required-fields validation idiom in rules — `request.resource.data.keys().hasAll()/hasOnly()` and the `diff().addedKeys()/removedKeys()/changedKeys()/affectedKeys()/unchangedKeys()` MapDiff family gating field-level mutations",
          status: "conforms",
          evidence: "NEW ROW, 2026-07-12: production capture proves the simulator matches the production Firestore Rules Test API verdict-for-verdict on all 7 cases (exact required-field set on create, field-scoped update via MapDiff). `oracle:rules-firestore-required-fields-and-mapdiff` — replayed by `unit:rules/oracle-conformance.test.ts`.",
          oracleObservations: ["rules-firestore-required-fields-and-mapdiff"],
        }),
        row1({
          rowRef: "179",
          featureKeys: ["String","List","Map.values"],
          behavior: "`String.split()/lower()/upper()/trim()/replace()/size()`, `List.hasAll()/hasAny()/hasOnly()/join()`, and `Map.values()` in rules",
          status: "conforms",
          evidence: "NEW ROW, 2026-07-12: production capture proves the simulator matches the production Firestore Rules Test API verdict-for-verdict on all 4 cases (CSV-split membership, slug/title/code normalization). `oracle:rules-firestore-list-and-string-methods` — replayed by `unit:rules/oracle-conformance.test.ts`.",
          oracleObservations: ["rules-firestore-list-and-string-methods"],
        }),
        row1({
          rowRef: "180",
          featureKeys: ["request.time","math","int","float","string"],
          behavior: "`request.time` Timestamp accessors (year/month/day/hours/minutes/seconds/nanos/dayOfWeek/dayOfYear/toMillis/date/time), `math.floor/round/sqrt/pow/isNaN`, `int()/float()/string()` casts, `request.method`, and `>=` / `*` operators in rules",
          status: "conforms",
          evidence: "NEW ROW, 2026-07-12: production capture proves the simulator matches the production Firestore Rules Test API verdict-for-verdict on all 3 cases (request.time pinned via requestTime for determinism). `oracle:rules-firestore-time-math-and-casts` — replayed by `unit:rules/oracle-conformance.test.ts`.",
          oracleObservations: ["rules-firestore-time-math-and-casts"],
        }),
        row1({
          rowRef: "181",
          featureKeys: ["latlng","duration"],
          behavior: "`latlng.value().latitude()/longitude()/distance()` and `duration.value()/time()/abs()` in rules",
          status: "conforms",
          evidence: "Production captures from 2026-07-12 and the 2026-07-21 recapture prove the simulator matches the Firestore Rules Test API verdict-for-verdict on all 3 cases: coordinate and duration bounds plus exact `duration.value(1500, 'ms').seconds()` / `.nanos()` components. `oracle:rules-firestore-duration-and-latlng` — replayed by `unit:rules/oracle-conformance.test.ts`.",
          oracleObservations: ["rules-firestore-duration-and-latlng"],
        }),
        row1({
          rowRef: "182",
          featureKeys: ["function","let","allow","ternary","recursiveMatch"],
          behavior: "User-defined `function`/`let`, granular `allow get/list/update/write` verbs, the ternary operator, and a recursive `{document=**}` match in rules",
          status: "conforms",
          evidence: "NEW ROW, 2026-07-12: production capture proves the simulator matches the production Firestore Rules Test API verdict-for-verdict on all 7 cases (role-gated docs + public recursive subtree). `oracle:rules-firestore-functions-verbs-and-recursive` — replayed by `unit:rules/oracle-conformance.test.ts`.",
          oracleObservations: ["rules-firestore-functions-verbs-and-recursive"],
        }),
        row1({
          rowRef: "183",
          featureKeys: [],
          behavior: "Resource identity (`resource.id`/`resource.__name__`/`request.resource.id`) on an EXISTING document (RULES-B12) — production leaves the identity keys ABSENT, so reading one errors → DENY, the error survives negation, and only a determining `||` operand absorbs it",
          status: "conforms",
          evidence: "NEW ROW, 2026-07-12: production capture proves the simulator matches the production Firestore Rules Test API verdict-for-verdict on all 13 cases. Production builds `resource` (and `request.resource`) from the supplied document alone and derives NO identity from the request path, so `resource.id`/`resource.__name__`/`request.resource.id` read as absent properties — verbatim `Property id is undefined on object.` / `Property __name__ is undefined on object.` — which absorb to DENY. The simulator previously SYNTHESIZED `id`/`__name__` from the request path on get/list/update/delete, so `resource.id == id` ALLOWed where production DENIES: an over-permissive divergence, now removed. The negation cases (`resource.id != 'zzz'`, `!(resource.id == 'zzz')`) pin that the absent read is a propagating error rather than a false, which an absent-as-undefined model would false-ALLOW. `oracle:rules-firestore-resource-document-identity` — replayed by `unit:rules/oracle-conformance.test.ts`.",
          oracleObservations: ["rules-firestore-resource-document-identity"],
          constructs: ["firestore.binding.resource.id","firestore.binding.resource.__name__","firestore.binding.request.resource.id","firestore.binding.resource.data","firestore.binding.request.resource.data"],
        }),
        row1({
          rowRef: "184",
          featureKeys: [],
          behavior: "Request-target `resource` on a missing document (RULES-B13) — get/update/delete existence guards, null comparison, and data access all error to DENY",
          status: "conforms",
          evidence: "NEW ROW, 2026-07-12: production capture proves the simulator matches the Firestore Rules Test API verdict-for-verdict on all 9 cases. A missing request target makes the `resource` global an error value: `resource != null`, `resource == null`, and `resource.data.value` all DENY. The simulator previously constructed `{ data: {} }` for missing get/update/delete requests, so the ordinary `resource != null` existence guard false-ALLOWed all three operations. Modeling the target as raw null fixes that guard but makes `resource == null` false-ALLOW, so the evaluator now raises `Null value error.` when the absent `resource` identifier itself is evaluated. Existing-document get/update/delete and data-access controls still ALLOW. `oracle:rules-firestore-resource-missing-document` — replayed by `packages/pyric/test/rules/oracle-conformance.test.ts`.",
          risk: ["rules-denial"],
          riskScore: 2,
          riskReasons: ["asserts rules-denial behavior"],
          oracleObservations: ["rules-firestore-resource-missing-document"],
          constructs: ["firestore.binding.resource","firestore.binding.resource.data"],
        }),
        row1({
          rowRef: "185",
          featureKeys: [],
          behavior: "A ruleset with NO `rules_version` declaration — production accepts it and defaults to v1",
          status: "conforms",
          evidence: "NEW ROW, 2026-07-17: production capture proves a version-less ruleset deploys and evaluates (production defaults `rules_version` to v1; the shared grammar previously rejected the file at parse — PR #333 grammar fix, the same evidence that reclassified corpus file 001-missing-version.rules from invalid to edge-cases). `oracle:rules-firestore-optional-rules-version` matches the local simulator verdict-for-verdict on all 3 cases.",
          oracleObservations: ["rules-firestore-optional-rules-version"],
          constructs: ["firestore.rule-kind.rules_version"],
        }),
        row1({
          rowRef: "186",
          featureKeys: [],
          behavior: "Function declarations at GLOBAL and SERVICE scope in a Firestore ruleset, with match-scope shadowing",
          status: "conforms",
          evidence: "ROW CORRECTED, 2026-07-17 (same day): the simulator now seeds the match-tree walk with global- and service-scope function declarations (declaration order global → service → match preserves inner-shadows-outer), so the previously-abstaining cases evaluate. `oracle:rules-firestore-global-and-service-scope-functions` — production Firestore Rules Test API verdicts captured 2026-07-17 — now replays verdict-for-verdict against the local simulator with all 5 cases matching (shadowing included), asserted by `unit:rules/oracle-conformance.test.ts`. The prior unsupported row recorded the honest UNSUPPORTED abstention; that gap is closed (#346).",
          oracleObservations: ["rules-firestore-global-and-service-scope-functions"],
          constructs: ["firestore.rule-kind.function"],
        }),
        row1({
          rowRef: "187",
          featureKeys: [],
          behavior: "Hierarchical nested `match` composition — a child match resolves relative to its parent and grants only the exact nested document path",
          status: "conforms",
          evidence: "`oracle:rules-firestore-hierarchical-match-cascade` captures the exact nested child ALLOW plus parent, sibling, and over-deep DENY controls from the production Firestore Rules Test API, replayed verdict-for-verdict by `packages/pyric/test/rules/oracle-conformance.test.ts`.",
          oracleObservations: ["rules-firestore-hierarchical-match-cascade"],
          constructs: ["firestore.semantic.hierarchical-match-cascade"],
        }),
        row1({
          rowRef: "188",
          featureKeys: [],
          behavior: "Strict boolean operands for `&&`, `||`, and ternary control flow, plus create-time `resource` / `request.resource` semantics",
          status: "conforms",
          evidence: "`oracle:rules-firestore-strict-boolean-control-flow` captures three direct non-boolean DENYs, three tautological error discriminators that still DENY, a boolean ALLOW control, create-time `resource == null` DENY, and incoming `request.resource.data` ALLOW; replayed verdict-for-verdict by `packages/pyric/test/rules/oracle-conformance.test.ts`.",
          risk: ["rules-denial","specific-field"],
          riskScore: 3,
          riskReasons: ["asserts rules-denial behavior","asserts a specific field/property value"],
          oracleObservations: ["rules-firestore-strict-boolean-control-flow"],
          constructs: ["firestore.operator.and","firestore.operator.or","firestore.operator.ternary","firestore.binding.resource","firestore.binding.request.resource","firestore.binding.request.resource.data"],
        }),
      ],
    },
    {
      kind: 'table',
      prefix: "## Storage rules engine — `parseStorageRules` / `evaluateStorageRules` (rules-storage corpus)\n",
      rows: [
        row2({
          rowRef: "94",
          featureKeys: ["parseStorageRules"],
          behavior: "`parseStorageRules(source)` returns an opaque handle",
          status: "conforms",
          evidence: "`unit:rules.test.ts` (\"parses the canonical session-archive ruleset\")",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/rules.test.ts"],
        }),
        row2({
          rowRef: "95",
          featureKeys: ["parseStorageRules"],
          behavior: "`parseStorageRules` rejects non-`firebase.storage` service headers",
          status: "conforms",
          evidence: "`unit:rules.test.ts` (\"rejects unknown service header\")",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/rules.test.ts"],
        }),
        row2({
          rowRef: "96",
          featureKeys: [],
          behavior: "`evaluateStorageRules` supports granular verbs (`get`/`list`/`create`/`update`/`delete`) alongside `read`/`write` umbrella expansion, comma-separated verb lists, and per-verb default-deny",
          status: "conforms",
          evidence: "STALE ROW, corrected 2026-07-10: production capture proves the evaluator already supports the full six-verb grant surface (umbrella read→{get,list}, write→{create,update,delete}, single granular grants, comma-separated grants, per-verb deny-by-default), matching production verdict-for-verdict on 12 of the scenario's 13 non-existence cases. `oracle:rules-storage-verbs-umbrella-granular` (all `read`/`write`/`get`/comma-verb cases). One related existence-semantics case in the same scenario diverges over-permissively and is carried by `#118 Rules` (the `resource == null` create-if-absent guard), not by this granular-verb row.",
          automation: "oracle-backed",
          oracleObservations: ["rules-storage-verbs-umbrella-granular"],
          conformanceTests: ["packages/pyric/test/storage/rules-oracle-conformance.test.ts"],
          constructs: ["storage.rule-kind.allow-read","storage.rule-kind.allow-write","storage.rule-kind.allow-get","storage.rule-kind.allow-list","storage.rule-kind.allow-create","storage.rule-kind.allow-update","storage.rule-kind.allow-delete","storage.semantic.read-umbrella","storage.semantic.write-umbrella","storage.semantic.deny-by-default"],
        }),
        row2({
          rowRef: "97",
          featureKeys: ["parseStorageRules"],
          behavior: "`parseStorageRules` rejects unterminated string literals with `SyntaxError`",
          status: "conforms",
          evidence: "`unit:rules.test.ts` (\"rejects unterminated strings\")",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/rules.test.ts"],
        }),
        row2({
          rowRef: "98",
          featureKeys: ["evaluateStorageRules","request.auth"],
          behavior: "`evaluateStorageRules` matches `match /sessions/{id} { allow read: if request.auth != null; }` for an authed read",
          status: "conforms",
          evidence: "`unit:rules.test.ts` (\"allows authenticated reads of /sessions/{id}\")",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/rules.test.ts"],
        }),
        row2({
          rowRef: "99",
          featureKeys: ["evaluateStorageRules","request.auth"],
          behavior: "`evaluateStorageRules` denies anonymous reads when the rule requires `request.auth != null`",
          status: "conforms",
          evidence: "`unit:rules.test.ts` (\"denies anonymous reads\")",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/rules.test.ts"],
        }),
        row2({
          rowRef: "100",
          featureKeys: ["evaluateStorageRules","request.resource.size"],
          behavior: "`evaluateStorageRules` supports `request.resource.size < N` constraints (with arithmetic literals like `10 * 1024 * 1024`)",
          status: "conforms",
          evidence: "`unit:rules.test.ts` (\"allows JSON writes under 10MB\")",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/rules.test.ts"],
        }),
        row2({
          rowRef: "101",
          featureKeys: ["evaluateStorageRules","request.resource.contentType"],
          behavior: "`evaluateStorageRules` supports `request.resource.contentType == '<mime>'` constraints",
          status: "conforms",
          evidence: "`unit:rules.test.ts` (mime constraint inside the session-archive ruleset)",
          risk: ["metadata"],
          riskScore: 1,
          riskReasons: ["asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/rules.test.ts"],
        }),
        row2({
          rowRef: "102",
          featureKeys: ["recursiveWildcard"],
          behavior: "Multi-segment wildcard `{allPaths=**}` matches zero-or-more remaining segments",
          status: "conforms",
          evidence: "`unit:rules.test.ts` (parser + evaluator both honor the `**` form)",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/rules.test.ts"],
        }),
        row2({
          rowRef: "103",
          featureKeys: ["pathParameters"],
          behavior: "Path-parameter binding (`{sessionId}`) accessible inside the `if` expression",
          status: "conforms",
          evidence: "`unit:rules.test.ts`",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/rules.test.ts"],
        }),
        row2({
          rowRef: "104",
          featureKeys: ["function","let","lexicalScope"],
          behavior: "User-defined `function` definitions — `let` bindings, functions calling functions, and match-block-scoped helper functions (lexical scoping)",
          status: "conforms",
          evidence: "STALE ROW, corrected 2026-07-10: production capture proves the evaluator supports user-defined functions with `let` bindings, nested function calls, and block-scoped helpers. `oracle:rules-storage-functions-let-scope` matches production verdict-for-verdict on all 5 cases. Same-name shadowing and undefined-function calls are compile-time rejections in production and are covered by evaluator unit tests instead (they cannot be captured as a clean production verdict).",
          automation: "oracle-backed",
          oracleObservations: ["rules-storage-functions-let-scope"],
          conformanceTests: ["packages/pyric/test/storage/rules-oracle-conformance.test.ts"],
        }),
        row2({
          rowRef: "112",
          featureKeys: ["request.time","timestamp.date","timestamp.value"],
          behavior: "`request.time` compared against `timestamp.date(y,m,d)` and `timestamp.value(ms)` constructors",
          status: "conforms",
          evidence: "NEW ROW, 2026-07-10: production capture proves the evaluator supports `request.time` comparisons against both timestamp constructors. `oracle:rules-storage-request-time-timestamp` matches production verdict-for-verdict on all 4 cases (deadline-before/after via `timestamp.date()`, epoch-bound before/after via `timestamp.value()`).",
          automation: "oracle-backed",
          oracleObservations: ["rules-storage-request-time-timestamp"],
          conformanceTests: ["packages/pyric/test/storage/rules-oracle-conformance.test.ts"],
        }),
        row2({
          rowRef: "113",
          featureKeys: ["matches"],
          behavior: "`string.matches(regex)` with whole-string anchoring (a partial match denies)",
          status: "conforms",
          evidence: "NEW ROW, 2026-07-10: production capture proves `matches()` is whole-string anchored, matching a RE2 pattern only when it covers the entire string. `oracle:rules-storage-matches-regex` matches production verdict-for-verdict on all 3 cases. RE2-inexpressible patterns are rejected at ruleset compile time by production and are covered by evaluator unit tests instead.",
          automation: "oracle-backed",
          oracleObservations: ["rules-storage-matches-regex"],
          conformanceTests: ["packages/pyric/test/storage/rules-oracle-conformance.test.ts"],
        }),
        row2({
          rowRef: "114",
          featureKeys: ["resource.metadata"],
          behavior: "`resource.metadata.<key>` custom-metadata access in dotted (`resource.metadata.owner`) and bracket (`resource.metadata['owner']`) form, including missing-key deny",
          status: "conforms",
          evidence: "NEW ROW, 2026-07-10: production capture proves dotted and bracket metadata access resolve identically, and a missing key denies. `oracle:rules-storage-metadata-access` matches production verdict-for-verdict on all 5 cases.",
          risk: ["metadata"],
          riskScore: 1,
          riskReasons: ["asserts metadata shape"],
          automation: "oracle-backed",
          oracleObservations: ["rules-storage-metadata-access"],
          conformanceTests: ["packages/pyric/test/storage/rules-oracle-conformance.test.ts"],
        }),
        row2({
          rowRef: "115",
          featureKeys: ["firestore.get","firestore.exists"],
          behavior: "Cross-service `firestore.get()` / `firestore.exists()` lookups from a Storage ruleset, with `$(expr)` path interpolation and qualified function-mock names",
          status: "conforms",
          evidence: "NEW ROW, 2026-07-10: production capture proves the evaluator resolves cross-service Firestore lookups from Storage rules, including interpolated document paths and both the map-returning `get()` and bool-returning `exists()` forms. `oracle:rules-storage-firestore-lookup` matches production verdict-for-verdict on all 4 cases.",
          automation: "oracle-backed",
          oracleObservations: ["rules-storage-firestore-lookup"],
          conformanceTests: ["packages/pyric/test/storage/rules-oracle-conformance.test.ts"],
        }),
        row2({
          rowRef: "116",
          featureKeys: [],
          behavior: "`resource.name` (full object path), `resource.timeCreated`, `resource.updated`, `resource.bucket` — the object-identity and time fields of the existing-object binding, plus `duration.value(n, unit)`",
          status: "conforms",
          evidence: "ROW CORRECTED, 2026-07-12: the fields are now modeled, sourced from the persisted object record. `oracle:rules-storage-resource-object-identity` matches production verdict-for-verdict on all 9 cases — an extension guard (`resource.name.matches`), a freshness window (`resource.timeCreated + duration.value(1, 'h')`), an immutability check (`resource.timeCreated == resource.updated`), and an absent-property negation. Production semantics pinned by the capture: `resource.name` is the object's FULL path within the bucket (GCS object-name convention, sourced from the persisted record's `fullPath`, not the client SDK's last-segment `name`); `timeCreated`/`updated` are timestamps (production rejects an int with \"Unsupported operation error. Received: int < timestamp\"); the update-time field is `updated` — there is NO `resource.timeUpdated`. An absent property is an evaluation error that absorbs to DENY and SURVIVES negation, so `resource.name != 'x'` on an object with no name denies rather than false-allowing. The prior row recorded these fields as an unsupported gap; that gap is closed.",
          risk: ["specific-value"],
          riskScore: 2,
          riskReasons: ["asserts 2 specific value(s)"],
          automation: "oracle-backed",
          oracleObservations: ["rules-storage-resource-object-identity"],
          conformanceTests: ["packages/pyric/test/storage/rules-oracle-conformance.test.ts"],
          constructs: ["storage.binding.resource.name","storage.binding.resource.timeCreated","storage.binding.resource.updated","storage.binding.resource.bucket","storage.function.duration.value"],
        }),
        row2({
          rowRef: "117",
          featureKeys: ["request.resource","resource","request.method","request.path"],
          behavior: "`request.resource.size` arithmetic bounds (`+`/`-`/`*`/`/`, `>=`/`<=`), request/existing content-type and custom `metadata` checks, `request.method`/`request.path`, a `request.auth.token` custom-claim branch, granular `allow list`, and a recursive `{allPaths=**}` public read tree",
          status: "conforms",
          evidence: "NEW ROW, 2026-07-12: production capture proves the evaluator matches the production Storage Rules Test API verdict-for-verdict on all 8 cases (owner-scoped size-bounded upload, immutable-content-type update, list grant, public recursive read). `oracle:rules-storage-metadata-verbs-and-arithmetic` — replayed by `packages/pyric/test/storage/rules-oracle-conformance.test.ts`.",
          automation: "oracle-backed",
          oracleObservations: ["rules-storage-metadata-verbs-and-arithmetic"],
          conformanceTests: ["packages/pyric/test/storage/rules-oracle-conformance.test.ts"],
        }),
        row2({
          rowRef: "118",
          featureKeys: [],
          behavior: "`resource` on a create where no object exists: the create-if-absent guard `allow create: if resource == null`",
          status: "diverged-documented",
          evidence: "divergence, over-permissive (the evaluator ALLOWs where production DENIEs, the highest-severity direction defined in `docs/storage/reference/conformance-gaps.md`). `oracle:rules-storage-verbs-umbrella-granular`, case \"create allowed when object does not exist (resource == null)\": production DENIES. Production raises a null value error on a `resource` reference in a create where no object exists, and the errored expression denies, so a `create` rule guarded by `resource == null` never allows. The evaluator models `resource` as null on create, evaluates the comparison as documented, and ALLOWS. Live-probed against production before pinning with both an omitted `resource` field and an explicit null, which denied identically, ruling out a capture-harness wire-shape bug. Both sides pinned in `unit:storage/rules-oracle-conformance.test.ts` KNOWN_DIVERGENCES. Same error-value class as the Firestore `resource` identity on a missing document.",
          risk: ["specific-value","rules-denial"],
          riskScore: 3,
          riskReasons: ["asserts 1 specific value(s)","asserts rules-denial behavior"],
          automation: "oracle-backed",
          oracleObservations: ["rules-storage-verbs-umbrella-granular"],
          conformanceTests: ["packages/pyric/test/storage/rules-oracle-conformance.test.ts"],
          constructs: ["storage.binding.resource"],
        }),
        row2({
          rowRef: "119",
          featureKeys: [],
          behavior: "Ternary `?:` — branch selection, error-in-condition deny, and `error || true` absorption",
          status: "conforms",
          evidence: "NEW ROW, 2026-07-17: production capture proves the evaluator selects ternary branches by condition, denies when the CONDITION errors (even with identical `true` branches — production errors the whole conditional rather than falling through to a branch), and still absorbs the same error through `|| true`. `oracle:rules-storage-ternary-and-error-absorption` matches production verdict-for-verdict on all 5 cases. A division-by-zero in the condition previously yielded JS Infinity (no error) and false-ALLOWed the erroring-condition case; zero divisors now error-and-deny.",
          risk: ["rules-denial"],
          riskScore: 1,
          riskReasons: ["asserts rules-denial behavior"],
          automation: "oracle-backed",
          oracleObservations: ["rules-storage-ternary-and-error-absorption"],
          conformanceTests: ["packages/pyric/test/storage/rules-oracle-conformance.test.ts"],
          constructs: ["storage.operator.ternary","storage.operator.or","storage.operator.div"],
        }),
        row2({
          rowRef: "120",
          featureKeys: [],
          behavior: "`in` on list literals (membership) and on maps (OWN-key membership) — prototype names (`toString`/`constructor`/`hasOwnProperty`) are never keys",
          status: "conforms",
          evidence: "NEW ROW, 2026-07-17: production capture proves `in` tests list membership and map OWN keys only — `'toString' in metadata` is false unless the map literally carries that key, for both custom-metadata maps and map literals. `oracle:rules-storage-in-membership-and-proto-keys` matches production verdict-for-verdict on all 8 cases. Pre-fix the evaluator used JS `in`, which walks the prototype chain and false-ALLOWed the proto-key cases (the same bug class the Firestore simulator fixed under RULES-B7); the own-key check now guards it, pinned by `unit:rules.test.ts` JS-semantics guards.",
          risk: ["rules-denial"],
          riskScore: 1,
          riskReasons: ["asserts rules-denial behavior"],
          automation: "oracle-backed",
          oracleObservations: ["rules-storage-in-membership-and-proto-keys"],
          conformanceTests: ["packages/pyric/test/storage/rules-oracle-conformance.test.ts"],
          constructs: ["storage.operator.in"],
        }),
        row2({
          rowRef: "121",
          featureKeys: [],
          behavior: "`is` type tests over the storage bindings (`size is int`, `contentType is string`, `metadata is map`, `split() is list`) and int/float LITERAL typing (`1.0 is float`, `1 is int`, cross checks false)",
          status: "conforms",
          evidence: "ROW CORRECTED, 2026-07-17 (same day): the evaluator now adopts the simulator's RULES-B5 float model — a `RulesFloat` wrapper tags float values (a numeric literal written with a decimal point converts to one) while a bare JS number means int — so `1.0 is float` / `!(1.0 is int)` type by literal form exactly as production does. `oracle:rules-storage-type-checks-is` now matches production verdict-for-verdict on all 3 cases with no knownGap abstentions. The prior same-day row recorded the value-typed divergence; that gap is closed.",
          risk: ["rules-denial"],
          riskScore: 1,
          riskReasons: ["asserts rules-denial behavior"],
          automation: "oracle-backed",
          oracleObservations: ["rules-storage-type-checks-is"],
          conformanceTests: ["packages/pyric/test/storage/rules-oracle-conformance.test.ts"],
          constructs: ["storage.operator.is"],
        }),
        row2({
          rowRef: "122",
          featureKeys: [],
          behavior: "List/map literals, range-slice access `[i:j]` on lists and strings (out-of-range bounds ERROR, no JS clamp), and structural `==` on lists",
          status: "conforms",
          evidence: "NEW ROW, 2026-07-17: production capture proves slices evaluate on `split()` lists and on strings, that an out-of-range slice END errors and denies (production does NOT clamp to length the way JS `.slice()` does — same semantics the Firestore capture pinned in rules-firestore-range-slice-list-and-string), and that a slice compares equal to a list literal structurally. `oracle:rules-storage-list-map-literals-and-slice` matches production verdict-for-verdict on all 6 cases. Pre-fix the evaluator clamped bounds JS-style and compared lists by reference identity; both fixed and pinned by `unit:rules.test.ts` JS-semantics guards.",
          risk: ["rules-denial"],
          riskScore: 1,
          riskReasons: ["asserts rules-denial behavior"],
          automation: "oracle-backed",
          oracleObservations: ["rules-storage-list-map-literals-and-slice"],
          conformanceTests: ["packages/pyric/test/storage/rules-oracle-conformance.test.ts"],
          constructs: ["storage.operator.slice","storage.operator.eq","storage.method.string.split","storage.method.size"],
        }),
        row2({
          rowRef: "123",
          featureKeys: [],
          behavior: "Float literals, `%`, unary minus, float division, negative-dividend modulo (`-7 % 2 == -1`), and TRUNCATING int division (`10 / 4 == 2`, `-7 / 2 == -3`)",
          status: "conforms",
          evidence: "ROW CORRECTED, 2026-07-17 (same day): with the RULES-B5 float model adopted from the simulator, int ÷ int truncates toward zero, float division stays float (re-tagged), and int-op-float promotes to float. `oracle:rules-storage-float-modulo-unary-minus` now matches production verdict-for-verdict on all 6 cases with no knownGap abstentions. An int zero divisor errors-and-denies; a float zero divisor follows the simulator's CEL-pinned ±Infinity/NaN. The prior same-day row recorded the truncation divergence; that gap is closed.",
          risk: ["specific-value"],
          riskScore: 1,
          riskReasons: ["asserts 1 specific value(s)"],
          automation: "oracle-backed",
          oracleObservations: ["rules-storage-float-modulo-unary-minus"],
          conformanceTests: ["packages/pyric/test/storage/rules-oracle-conformance.test.ts"],
          constructs: ["storage.operator.mod","storage.operator.unary-minus","storage.operator.div","storage.operator.mul"],
        }),
        row2({
          rowRef: "124",
          featureKeys: [],
          behavior: "Function declarations at GLOBAL scope (above `service`) and SERVICE scope (inside `service`, outside any match), with inner-shadows-outer resolution",
          status: "conforms",
          evidence: "NEW ROW, 2026-07-17: production capture proves production accepts functions declared at global and service scope and resolves a match-scope function over a same-named global (inner shadows outer). `oracle:rules-storage-function-scopes-and-shadowing` matches production verdict-for-verdict on all 5 cases. The shared grammar previously rejected both placements at parse (PR #333 grammar fix); the storage evaluator attaches global- and service-scope functions to the root match block, which the capture proves is verdict-equivalent to production's scoping for this surface.",
          automation: "oracle-backed",
          oracleObservations: ["rules-storage-function-scopes-and-shadowing"],
          conformanceTests: ["packages/pyric/test/storage/rules-oracle-conformance.test.ts"],
          constructs: ["storage.rule-kind.function"],
        }),
      ],
    },
    {
      kind: 'table',
      prefix: "## RTDB rules engine — production simulator conformance (rules-rtdb corpus)\n",
      rows: [
        row3({
          rowRef: "1",
          featureKeys: ["auth"],
          behavior: "`auth != null` gate on `.read`/`.write` — authed ops allow, signed-out ops deny",
          evidence: "`oracle:rules-rtdb-r1-auth-only` — production verdicts captured by deploy-observe-restore against the live oracle database (RTDB has no server-side rules test API), replayed verdict-for-verdict against the in-process simulator by `packages/pyric/test/rules/rtdb/rules-conformance.test.ts`; all 4 cases match production.",
          oracleObservations: ["rules-rtdb-r1-auth-only"],
        }),
        row3({
          rowRef: "2",
          featureKeys: ["pathVariables","auth.uid"],
          behavior: "`$uid` path-variable ownership (`$uid === auth.uid`) — the owner path allows, a foreign uid and an anonymous request deny",
          evidence: "`oracle:rules-rtdb-r2-own-uid` — production verdicts captured by deploy-observe-restore, replayed verdict-for-verdict against the in-process simulator; all 5 cases match production, so the simulator binds the path variable against `auth.uid` exactly as production does.",
          oracleObservations: ["rules-rtdb-r2-own-uid"],
        }),
        row3({
          rowRef: "3",
          featureKeys: [],
          behavior: "Write-rule CASCADE — a truthy ancestor `.write` grants the write regardless of a deeper `!data.exists()` rule, so the populated-path write ALLOWS",
          evidence: "`oracle:rules-rtdb-r3-data-exists` — production verdicts captured by deploy-observe-restore, replayed verdict-for-verdict. Production ALLOWS the write to the populated path even though the child rule is `!data.exists()`: the ancestor `.write: auth != null` already granted it, and RTDB never consults a deeper rule to revoke a grant. All 3 cases match; the simulator models the same cascade.",
          oracleObservations: ["rules-rtdb-r3-data-exists"],
          constructs: ["rtdb.semantic.write-cascade","rtdb.semantic.read-cascade"],
        }),
        row3({
          rowRef: "4",
          featureKeys: [],
          behavior: "`.validate` VETO — a failing child `.validate` denies a write the `.write` rule would otherwise permit (validate does not cascade and cannot be overridden)",
          evidence: "`oracle:rules-rtdb-r4-validate-structure` — production verdicts captured by deploy-observe-restore, replayed verdict-for-verdict; both cases match production. This row was the corpus's one historical simulator-vs-production divergence: at the 2026-05-18 agreement capture the simulator ALLOWED the missing-body write because it did not veto on the child `.validate`. The simulator now denies it, and this fresh capture re-confirms production's DENY, so the divergence is RESOLVED and needs no pin.",
          oracleObservations: ["rules-rtdb-r4-validate-structure"],
          constructs: ["rtdb.semantic.validate-non-cascade","rtdb.semantic.write-cascade"],
        }),
        row3({
          rowRef: "5",
          featureKeys: [],
          behavior: "Cascade is GRANT-ONLY — a root `.read: true` grants every descendant read (authed and anonymous), and a deeper `.write: false` cannot revoke a truthy ancestor `.write` grant",
          evidence: "`oracle:rules-rtdb-r5-cascade-root-grant` — production verdicts captured by deploy-observe-restore, replayed verdict-for-verdict; all 4 cases ALLOW in production, including the write to a node whose own `.write` is literal `false`. The simulator reproduces grant-only cascade rather than treating the deeper `false` as a veto.",
          oracleObservations: ["rules-rtdb-r5-cascade-root-grant"],
          constructs: ["rtdb.semantic.read-cascade","rtdb.semantic.write-cascade"],
        }),
        row3({
          rowRef: "6",
          featureKeys: ["denyByDefault"],
          behavior: "Literal `.read`/`.write: false` — the deny-all baseline denies every op, authed or anonymous, read or write",
          evidence: "`oracle:rules-rtdb-r6-deny-everything` — production verdicts captured by deploy-observe-restore, replayed verdict-for-verdict; all 3 cases DENY in production and in the simulator.",
          oracleObservations: ["rules-rtdb-r6-deny-everything"],
        }),
        row3({
          rowRef: "7",
          featureKeys: ["pathVariables"],
          behavior: "Nested path variable in an expression (`$sessionId === auth.uid`) — the matching session allows, a mismatched session denies, and an unmatched anonymous op denies with no matching rule",
          evidence: "`oracle:rules-rtdb-r7-pathvar-binding` — production verdicts captured by deploy-observe-restore, replayed verdict-for-verdict; all 4 cases match. The simulator binds the nested variable identically and returns NO_MATCHING_RULE (read as deny) where production denies for want of a rule.",
          oracleObservations: ["rules-rtdb-r7-pathvar-binding"],
        }),
        row3({
          rowRef: "8",
          featureKeys: [],
          behavior: "`newData` is projected at the RULE node, not the written path — a root `.write` reading `newData.hasChildren(['owner'])` sees `{item:{...}}` for a write one level deeper, so the predicate is false and the write DENIES",
          evidence: "`oracle:rules-rtdb-r8-combined-check` — production verdicts captured by deploy-observe-restore, replayed verdict-for-verdict. Production DENIES all three writes, including the \"matching owner\" case whose `owner` field lives under `/item` rather than at the rule node; only the auth-gated read allows. All 4 cases match, so the simulator projects `newData` at the same node production does — rule placement relative to the written path decides the outcome.",
          oracleObservations: ["rules-rtdb-r8-combined-check"],
          constructs: ["rtdb.semantic.read-cascade"],
        }),
        row3({
          rowRef: "9",
          featureKeys: ["arithmetic","comparison","ternary"],
          behavior: "Arithmetic and comparison operators in quota rules — `+` `-` `*` `/` `%`, `>` `>=` `<` `<=`, `!==`, loose `==`, `||`, the ternary, and unary minus",
          evidence: "NEW ROW, 2026-07-12: production capture proves the simulator evaluates every arithmetic and ordering operator as production does, across increment-only counters, doubling and halving deltas, a parity check, inclusive and exclusive range caps, a negative sentinel, loose equality against zero, a disjunction, and a ternary tier bound. `oracle:rules-rtdb-r9-quota-arithmetic` matches production verdict-for-verdict on all 23 cases.",
          oracleObservations: ["rules-rtdb-r9-quota-arithmetic"],
        }),
        row3({
          rowRef: "10",
          featureKeys: [],
          behavior: "Snapshot structure and type guards — `hasChild`, `parent()`, `isString`, `isNumber`, `isBoolean`",
          evidence: "NEW ROW, 2026-07-12: production capture proves the simulator resolves the type predicates and the `parent()` path climb as production does, including RTDB's rule that a child `.validate` runs only for children PRESENT in `newData` — the name-without-age write is denied by that field's own parent guard, not by the absent sibling's type rule, which never runs. `oracle:rules-rtdb-r10-snapshot-type-guards` matches production verdict-for-verdict on all 7 cases.",
          oracleObservations: ["rules-rtdb-r10-snapshot-type-guards"],
          constructs: ["rtdb.semantic.validate-non-cascade","rtdb.semantic.read-cascade"],
        }),
        row3({
          rowRef: "11",
          featureKeys: ["String","matches","replace"],
          behavior: "String methods on a snapshot value — `beginsWith`, `contains`, `endsWith`, `matches` with a regex literal, `.length`, `toLowerCase`, `toUpperCase`, and replace-ALL `replace`",
          evidence: "NEW ROW, 2026-07-12: production capture proves `String.replace` substitutes EVERY occurrence of the substring, not only the first — production ALLOWS the write whose rule is `newData.val().replace('_', '-') === 'a-b-c'` for the value `a_b_c`, which holds only under replace-all. The simulator delegated to JavaScript's `String.prototype.replace`, which given a string pattern substitutes only the first occurrence, and DENIED that write; the substitution now replaces every occurrence and the two-underscore case guards the regression. The same capture proves `toUpperCase` is a valid production rule method that the simulator's validator previously rejected outright as unknown. `oracle:rules-rtdb-r11-string-validation` matches production verdict-for-verdict on all 18 cases.",
          oracleObservations: ["rules-rtdb-r11-string-validation"],
        }),
        row3({
          rowRef: "12",
          featureKeys: ["now","auth.token"],
          behavior: "`now` (the server evaluation clock) and `auth.token` claims, read both dotted (`auth.token.firebase.sign_in_provider`) and subscripted (`auth.token['firebase']['sign_in_provider']`)",
          evidence: "NEW ROW, 2026-07-12: production capture proves the simulator resolves the server clock and the decoded ID-token claims as production does, through both access forms. The subscript's receiver is load-bearing: production's rules compiler ACCEPTS `auth.token[...]`, a map indexed by key, but REJECTS the same subscript applied to a snapshot value — `newData.val()['kind']` fails to compile with \"No such method/property\" — so `[]` is a map accessor, not a general indexing operator. `oracle:rules-rtdb-r12-server-time-and-token` matches production verdict-for-verdict on all 7 cases.",
          oracleObservations: ["rules-rtdb-r12-server-time-and-token"],
        }),
        row3({
          rowRef: "13",
          featureKeys: ["getPriority","indexOn"],
          behavior: "`getPriority()` on a plain `set` (an unset priority reads null) and the `.indexOn` query-planner directive",
          evidence: "NEW ROW, 2026-07-12: production capture proves a plain `set` leaves a node's priority unset, so `getPriority()` reports null in production exactly as the simulator does, and that a ruleset carrying `.indexOn` deploys and evaluates with every verdict intact. The scope is exactly that: `.indexOn` never changes an allow/deny verdict, so the twin evidences only that production's compiler accepts and deploys the directive, and it says nothing about query behavior. A NON-null priority stays unverified because writing one requires `setWithPriority`, outside the corpus op vocabulary of read and set. `oracle:rules-rtdb-r13-priority-and-index-directive` matches production verdict-for-verdict on all 4 cases.",
          oracleObservations: ["rules-rtdb-r13-priority-and-index-directive"],
        }),
        row3({
          rowRef: "14",
          featureKeys: ["root"],
          behavior: "The `root` binding — `root.child(...).exists()` resolved against the database root",
          evidence: "NEW ROW, 2026-07-12: production capture proves the simulator resolves the `root` binding and reports a missing child as absent exactly as production does. The scope is bounded by the rig: the capture runner mounts the scenario subtree under a per-run randomly-named namespace while the replay suite mounts it at the root, so a rule naming any PRESENT path through `root` would address a different node on each side and diverge for harness reasons. Only a sentinel key absent under BOTH roots is mount-invariant, so that is what this row verifies; a populated `root` lookup remains unverified and needs a rig that can seed outside the scenario subtree and mount both sides at the same depth. `oracle:rules-rtdb-r14-root-lookup` matches production verdict-for-verdict on all 3 cases.",
          oracleObservations: ["rules-rtdb-r14-root-lookup"],
        }),
        row3({
          rowRef: "15",
          featureKeys: [],
          behavior: "`.validate` reaches ancestors of the written path — each applicable rule is evaluated against the merged post-write value at its own location",
          evidence: "`oracle:rules-rtdb-r15-validate-ancestor-scope` — production DENIES a deep write that leaves its validated ancestor without the required child, while the same write under a rule-free ancestor ALLOWS and the write ALLOWS once the ancestor requirement is seeded. The simulator now walks validation from the root through the write location against the merged post-write tree and matches all 5 captured production cases.",
          risk: ["rules-denial"],
          riskScore: 2,
          riskReasons: ["asserts rules-denial behavior"],
          oracleObservations: ["rules-rtdb-r15-validate-ancestor-scope"],
          constructs: ["rtdb.semantic.validate-non-cascade"],
        }),
      ],
    },
  ],
} satisfies CompatibilitySurfaceRegistry;

export default rulesRegistry;
