import type { CompatibilitySurfaceRegistry } from './types.ts';

/**
 * The shared NATIVE rules surface registry. Hosts the rules-ENGINE fidelity
 * rows for BOTH the Firestore rules simulator (firestore-rules) and the Storage
 * rules engine (storage-rules), moved out of firestore.ts / storage.ts per the
 * rules-native-surface design's dividing line: a row comparing the pyric rules
 * engine to the production Rules Test API lives here; a row describing how an
 * SDK surface enforces a rules verdict stays with that SDK.
 *
 * Two descriptors (surfaces/firestore-rules.ts, surfaces/storage-rules.ts)
 * resolve their registry: 'rules' key to this object, on the
 * rtdb / rtdb-modular -> rtdb registry precedent.
 */
export const rulesRegistry = {
  surface: "rules",
  compatPath: "packages/pyric/docs/rules/COMPAT.md",
  blocks: [
    { kind: 'markdown', markdown: "# `pyric/rules` compatibility matrix\n\nRules is a NATIVE conformance surface: there is no `firebase/rules` module to\nmirror, so this contract is NOT measured against an upstream SDK. It is measured\ntwo ways. The claimable API is the public export set of `pyric/rules` (and the\nStorage rules exports on `pyric/storage`); the fidelity is the in-process rules\nsimulators replayed verdict-for-verdict against the production Firestore and\nStorage **Rules Test API** engines. There is no export-breadth percentage here\n(no upstream denominator); completeness is measured against the surface's own\npublic API.\n\nThe two engines share this one document because `pyric/rules` is one package\nfront door: its engine-agnostic exports (`lint`, `eachCase`, `assertCase`,\n`explainCase`, the value helpers) cannot be partitioned across per-engine\nregistries. Firestore rules and Storage rules each carry their own engine table\nbelow, partitioned by observation prefix (`rules-firestore-` / `rules-storage-`).\n\n## Status legend\n\n| Status | Meaning |\n|---|---|\n| ✓ | **Conforming** — the simulator matches the production Rules Test API verdict, locked by a replayed observation |\n| ⚠ | **Diverged (documented)** — a known simulator divergence from production with a written reason |\n| ✗ | **Bug** — should match production but doesn't; a failing replay pins it |\n| — | **Unsupported** — not modeled yet (deliberately or pending) |\n| ? | **Unverified** — a claim we haven't yet observed against the production engine |\n\nOracle references: `oracle:rules-firestore-<pack>` / `oracle:rules-storage-<pack>` cite\nan observation captured by `packages/conformance/src/run-rules.ts` /\n`run-rules-storage.ts` against the production Rules Test API and replayed by the\nrules oracle-conformance suites. The corpus lives at\n`packages/conformance/rules-corpus/{firestore,storage}/`.\n\n---\n" },
    {
      kind: 'table',
      prefix: "## Firestore rules engine — production simulator conformance (rules-firestore corpus)\n",
      rows: [
        {"id":"firestore-rules#160","surface":"firestore-rules","aliases":[],"rowRef":"160","rowNumber":160,"section":"Rules engine — production simulator conformance (rules-firestore corpus)","api":"Rules simulator","behavior":"CEL builtins `math.*`/`timestamp.*`/`duration.*` (FM3) — arithmetic, date, and duration comparisons in rules","status":"conforms","evidence":"`oracle:rules-firestore-builtins-time-and-math` — production Firestore Rules Test API verdicts for corpus pack \"builtins-time-and-math\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.","risk":[],"riskScore":0,"riskReasons":[],"automation":"oracle-backed","oracleObservations":["rules-firestore-builtins-time-and-math"],"conformanceTests":["packages/pyric/test/rules/oracle-conformance.test.ts"]},
        {"id":"firestore-rules#161","surface":"firestore-rules","aliases":[],"rowRef":"161","rowNumber":161,"section":"Rules engine — production simulator conformance (rules-firestore corpus)","api":"Rules simulator","behavior":"`Bytes`, `String.toUtf8()`, and `hashing.{md5,sha256,crc32,crc32c}()` (Item 5.3) in rules","status":"diverged-documented","evidence":"`oracle:rules-firestore-bytes-toutf8-and-hashing` — production Firestore Rules Test API verdicts for corpus pack \"bytes-toutf8-and-hashing\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`. simulator's toUtf8/md5/sha256/crc32/crc32c byte-encoding and reference-hash implementations diverge from production on all 5 pack cases, so a rule that should DENY on hash mismatch ALLOWs locally — pinned KNOWN_DIVERGENCE","risk":["specific-value","rules-denial"],"riskScore":3,"riskReasons":["asserts 1 specific value(s)","asserts rules-denial behavior"],"automation":"oracle-backed","oracleObservations":["rules-firestore-bytes-toutf8-and-hashing"],"conformanceTests":["packages/pyric/test/rules/oracle-conformance.test.ts"]},
        {"id":"firestore-rules#162","surface":"firestore-rules","aliases":[],"rowRef":"162","rowNumber":162,"section":"Rules engine — production simulator conformance (rules-firestore corpus)","api":"Rules simulator","behavior":"Typed cross-type operator overloads for `Timestamp`/`Duration` (Item 2) in rules — no silent numeric coercion / type-identity loss","status":"conforms","evidence":"`oracle:rules-firestore-cross-type-operator-overloads` — production Firestore Rules Test API verdicts for corpus pack \"cross-type-operator-overloads\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.","risk":[],"riskScore":0,"riskReasons":[],"automation":"oracle-backed","oracleObservations":["rules-firestore-cross-type-operator-overloads"],"conformanceTests":["packages/pyric/test/rules/oracle-conformance.test.ts"]},
        {"id":"firestore-rules#163","surface":"firestore-rules","aliases":[],"rowRef":"163","rowNumber":163,"section":"Rules engine — production simulator conformance (rules-firestore corpus)","api":"Rules simulator","behavior":"CEL tri-state error absorption in `||`/`&&` (RULES-B3) — `error || true` → ALLOW, `error && false` → DENY, commutative absorption (not JS left-to-right short-circuit)","status":"conforms","evidence":"`oracle:rules-firestore-error-absorption-and-or` — production Firestore Rules Test API verdicts for corpus pack \"error-absorption-and-or\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.","risk":[],"riskScore":0,"riskReasons":[],"automation":"oracle-backed","oracleObservations":["rules-firestore-error-absorption-and-or"],"conformanceTests":["packages/pyric/test/rules/oracle-conformance.test.ts"]},
        {"id":"firestore-rules#164","surface":"firestore-rules","aliases":[],"rowRef":"164","rowNumber":164,"section":"Rules engine — production simulator conformance (rules-firestore corpus)","api":"Rules simulator","behavior":"`getAfter()`/`existsAfter()` (Item 7) in rules — post-write document identity and existence semantics","status":"diverged-documented","evidence":"`oracle:rules-firestore-get-after-and-exists-after` — production Firestore Rules Test API verdicts for corpus pack \"get-after-and-exists-after\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`. simulator does not model the post-write document identity/existence production compares against on 4 pack cases (getAfter target identity, existsAfter on create/delete, existsAfter over an unrelated mocked path) — pinned KNOWN_DIVERGENCE","risk":["specific-value","rules-denial"],"riskScore":3,"riskReasons":["asserts 1 specific value(s)","asserts rules-denial behavior"],"automation":"oracle-backed","oracleObservations":["rules-firestore-get-after-and-exists-after"],"conformanceTests":["packages/pyric/test/rules/oracle-conformance.test.ts"]},
        {"id":"firestore-rules#165","surface":"firestore-rules","aliases":[],"rowRef":"165","rowNumber":165,"section":"Rules engine — production simulator conformance (rules-firestore corpus)","api":"Rules simulator","behavior":"`get()` of a missing document (RULES-B8) in rules — resource identity (`id`/`__name__`) exposure on a mocked/missing get() result","status":"diverged-documented","evidence":"`oracle:rules-firestore-get-missing-doc` — production Firestore Rules Test API verdicts for corpus pack \"get-missing-doc\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`. simulator synthesizes a resource identity (`id`, `__name__`) for mocked get() results that production leaves absent, on 2 pack cases — pinned KNOWN_DIVERGENCE","risk":["specific-value","rules-denial"],"riskScore":3,"riskReasons":["asserts 1 specific value(s)","asserts rules-denial behavior"],"automation":"oracle-backed","oracleObservations":["rules-firestore-get-missing-doc"],"conformanceTests":["packages/pyric/test/rules/oracle-conformance.test.ts"]},
        {"id":"firestore-rules#166","surface":"firestore-rules","aliases":[],"rowRef":"166","rowNumber":166,"section":"Rules engine — production simulator conformance (rules-firestore corpus)","api":"Rules simulator","behavior":"`request.path`/`request.query`/`resource.id`/`resource.__name__` globals (Item 6) in rules","status":"diverged-documented","evidence":"`oracle:rules-firestore-globals-request-path-and-resource-id` — production Firestore Rules Test API verdicts for corpus pack \"globals-request-path-and-resource-id\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`. simulator models `request.query` as an empty map on the empty-query case where production denies the equivalent comparison — pinned KNOWN_DIVERGENCE","risk":["specific-value","rules-denial"],"riskScore":3,"riskReasons":["asserts 1 specific value(s)","asserts rules-denial behavior"],"automation":"oracle-backed","oracleObservations":["rules-firestore-globals-request-path-and-resource-id"],"conformanceTests":["packages/pyric/test/rules/oracle-conformance.test.ts"]},
        {"id":"firestore-rules#167","surface":"firestore-rules","aliases":[],"rowRef":"167","rowNumber":167,"section":"Rules engine — production simulator conformance (rules-firestore corpus)","api":"Rules simulator","behavior":"`int`/`float` division and type distinction (RULES-B5) in rules — truncating int÷int, float division stays float, div-by-zero denies, `is int`/`is float` distinct","status":"diverged-documented","evidence":"`oracle:rules-firestore-int-float-and-division` — production Firestore Rules Test API verdicts for corpus pack \"int-float-and-division\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`. simulator narrows a float-valued payload field toward int on the float-payload case, unlike production which preserves the float type — pinned KNOWN_DIVERGENCE","risk":["specific-value","rules-denial"],"riskScore":3,"riskReasons":["asserts 1 specific value(s)","asserts rules-denial behavior"],"automation":"oracle-backed","oracleObservations":["rules-firestore-int-float-and-division"],"conformanceTests":["packages/pyric/test/rules/oracle-conformance.test.ts"]},
        {"id":"firestore-rules#168","surface":"firestore-rules","aliases":[],"rowRef":"168","rowNumber":168,"section":"Rules engine — production simulator conformance (rules-firestore corpus)","api":"Rules simulator","behavior":"`List.concat()`/`removeAll()`/`toSet()` (Item 5.2) in rules","status":"conforms","evidence":"`oracle:rules-firestore-list-methods-concat-removeall-toset` — production Firestore Rules Test API verdicts for corpus pack \"list-methods-concat-removeall-toset\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.","risk":[],"riskScore":0,"riskReasons":[],"automation":"oracle-backed","oracleObservations":["rules-firestore-list-methods-concat-removeall-toset"],"conformanceTests":["packages/pyric/test/rules/oracle-conformance.test.ts"]},
        {"id":"firestore-rules#169","surface":"firestore-rules","aliases":[],"rowRef":"169","rowNumber":169,"section":"Rules engine — production simulator conformance (rules-firestore corpus)","api":"Rules simulator","behavior":"`Map.get(key, default)`, including list-form nested-path traversal (Item 3), in rules","status":"conforms","evidence":"`oracle:rules-firestore-map-get-string-and-list-form` — production Firestore Rules Test API verdicts for corpus pack \"map-get-string-and-list-form\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.","risk":[],"riskScore":0,"riskReasons":[],"automation":"oracle-backed","oracleObservations":["rules-firestore-map-get-string-and-list-form"],"conformanceTests":["packages/pyric/test/rules/oracle-conformance.test.ts"]},
        {"id":"firestore-rules#170","surface":"firestore-rules","aliases":[],"rowRef":"170","rowNumber":170,"section":"Rules engine — production simulator conformance (rules-firestore corpus)","api":"Rules simulator","behavior":"`matches()` as an anchored full-string RE2 match (RULES-B4) in rules — a pattern matching only a substring is `false`","status":"conforms","evidence":"`oracle:rules-firestore-matches-full-string-regex` — production Firestore Rules Test API verdicts for corpus pack \"matches-full-string-regex\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.","risk":[],"riskScore":0,"riskReasons":[],"automation":"oracle-backed","oracleObservations":["rules-firestore-matches-full-string-regex"],"conformanceTests":["packages/pyric/test/rules/oracle-conformance.test.ts"]},
        {"id":"firestore-rules#171","surface":"firestore-rules","aliases":[],"rowRef":"171","rowNumber":171,"section":"Rules engine — production simulator conformance (rules-firestore corpus)","api":"Rules simulator","behavior":"`Path` wrapper, `path()` constructor, and `Path.bind()` (Item 5.4) in rules","status":"diverged-documented","evidence":"`oracle:rules-firestore-path-constructor-and-bind` — production Firestore Rules Test API verdicts for corpus pack \"path-constructor-and-bind\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`. simulator treats `path()` as idempotent on an already-Path argument where production denies — pinned KNOWN_DIVERGENCE","risk":["specific-value","rules-denial"],"riskScore":3,"riskReasons":["asserts 1 specific value(s)","asserts rules-denial behavior"],"automation":"oracle-backed","oracleObservations":["rules-firestore-path-constructor-and-bind"],"conformanceTests":["packages/pyric/test/rules/oracle-conformance.test.ts"]},
        {"id":"firestore-rules#172","surface":"firestore-rules","aliases":[],"rowRef":"172","rowNumber":172,"section":"Rules engine — production simulator conformance (rules-firestore corpus)","api":"Rules simulator","behavior":"Own-keys-only map membership and constructor-access denial (RULES-B7) in rules — `'toString' in map` is `false`, `.constructor` access errors (no JS prototype-chain leakage)","status":"conforms","evidence":"`oracle:rules-firestore-prototype-chain-keys` — production Firestore Rules Test API verdicts for corpus pack \"prototype-chain-keys\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.","risk":[],"riskScore":0,"riskReasons":[],"automation":"oracle-backed","oracleObservations":["rules-firestore-prototype-chain-keys"],"conformanceTests":["packages/pyric/test/rules/oracle-conformance.test.ts"]},
        {"id":"firestore-rules#173","surface":"firestore-rules","aliases":[],"rowRef":"173","rowNumber":173,"section":"Rules engine — production simulator conformance (rules-firestore corpus)","api":"Rules simulator","behavior":"Range-slice `[i:j]` syntax for `List` and `String` (Item 4) in rules","status":"diverged-documented","evidence":"`oracle:rules-firestore-range-slice-list-and-string` — production Firestore Rules Test API verdicts for corpus pack \"range-slice-list-and-string\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`. simulator clamps an out-of-bounds slice end to the collection length on both the list and string OOB-slice cases; production denies — pinned KNOWN_DIVERGENCE","risk":["specific-value","rules-denial"],"riskScore":3,"riskReasons":["asserts 1 specific value(s)","asserts rules-denial behavior"],"automation":"oracle-backed","oracleObservations":["rules-firestore-range-slice-list-and-string"],"conformanceTests":["packages/pyric/test/rules/oracle-conformance.test.ts"]},
        {"id":"firestore-rules#174","surface":"firestore-rules","aliases":[],"rowRef":"174","rowNumber":174,"section":"Rules engine — production simulator conformance (rules-firestore corpus)","api":"Rules simulator","behavior":"`Set.difference()`/`union()`/`intersection()` (Item 5.1) in rules","status":"conforms","evidence":"`oracle:rules-firestore-set-algebra-difference-union-intersection` — production Firestore Rules Test API verdicts for corpus pack \"set-algebra-difference-union-intersection\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.","risk":[],"riskScore":0,"riskReasons":[],"automation":"oracle-backed","oracleObservations":["rules-firestore-set-algebra-difference-union-intersection"],"conformanceTests":["packages/pyric/test/rules/oracle-conformance.test.ts"]},
        {"id":"firestore-rules#175","surface":"firestore-rules","aliases":[],"rowRef":"175","rowNumber":175,"section":"Rules engine — production simulator conformance (rules-firestore corpus)","api":"Rules simulator","behavior":"String-literal escape handling feeding `matches()` (Class B) in rules — `\\\\.` is unescaped before RE2 compilation, not forwarded raw to a JS `RegExp`","status":"conforms","evidence":"`oracle:rules-firestore-string-literals-and-regex` — production Firestore Rules Test API verdicts for corpus pack \"string-literals-and-regex\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.","risk":[],"riskScore":0,"riskReasons":[],"automation":"oracle-backed","oracleObservations":["rules-firestore-string-literals-and-regex"],"conformanceTests":["packages/pyric/test/rules/oracle-conformance.test.ts"]},
        {"id":"firestore-rules#176","surface":"firestore-rules","aliases":[],"rowRef":"176","rowNumber":176,"section":"Rules engine — production simulator conformance (rules-firestore corpus)","api":"Rules simulator","behavior":"Missing-field access as a runtime error (RULES-B2) in rules — `typo == null` denies (missing access is not null); `!(key in map)` is the real absence check","status":"conforms","evidence":"`oracle:rules-firestore-undefined-field-access` — production Firestore Rules Test API verdicts for corpus pack \"undefined-field-access\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.","risk":[],"riskScore":0,"riskReasons":[],"automation":"oracle-backed","oracleObservations":["rules-firestore-undefined-field-access"],"conformanceTests":["packages/pyric/test/rules/oracle-conformance.test.ts"]},
        {"id":"firestore-rules#177","surface":"firestore-rules","aliases":[],"rowRef":"177","rowNumber":177,"section":"Rules engine — production simulator conformance (rules-firestore corpus)","api":"Rules simulator","behavior":"Explicit `UNSUPPORTED` reporting for unimplemented built-ins (Item 0.A) in rules — an unimplemented built-in abstains rather than silently DENYing","status":"conforms","evidence":"`oracle:rules-firestore-unsupported-feature-witness` — production Firestore Rules Test API verdicts for corpus pack \"unsupported-feature-witness\", replayed verdict-for-verdict against the local rules simulator by `unit:rules/oracle-conformance.test.ts`; all cases match production.","risk":[],"riskScore":0,"riskReasons":[],"automation":"oracle-backed","oracleObservations":["rules-firestore-unsupported-feature-witness"],"conformanceTests":["packages/pyric/test/rules/oracle-conformance.test.ts"]},
      ],
    },
    {
      kind: 'table',
      prefix: "## Storage rules engine — `parseStorageRules` / `evaluateStorageRules` (rules-storage corpus)\n",
      rows: [
        {"id":"storage-rules#94","surface":"storage-rules","aliases":[],"rowRef":"94","rowNumber":94,"section":"Rules — `parseStorageRules` / `evaluateStorageRules` / `getStorage(ctx, { rules })`","api":"Rules","behavior":"`parseStorageRules(source)` returns an opaque handle","status":"conforms","evidence":"`unit:rules.test.ts` (\"parses the canonical session-archive ruleset\")","risk":[],"riskScore":0,"riskReasons":[],"automation":"unit-backed","oracleObservations":[],"conformanceTests":["packages/pyric/test/storage/rules.test.ts"]},
        {"id":"storage-rules#95","surface":"storage-rules","aliases":[],"rowRef":"95","rowNumber":95,"section":"Rules — `parseStorageRules` / `evaluateStorageRules` / `getStorage(ctx, { rules })`","api":"Rules","behavior":"`parseStorageRules` rejects non-`firebase.storage` service headers","status":"conforms","evidence":"`unit:rules.test.ts` (\"rejects unknown service header\")","risk":[],"riskScore":0,"riskReasons":[],"automation":"unit-backed","oracleObservations":[],"conformanceTests":["packages/pyric/test/storage/rules.test.ts"]},
        {"id":"storage-rules#96","surface":"storage-rules","aliases":[],"rowRef":"96","rowNumber":96,"section":"Rules — `parseStorageRules` / `evaluateStorageRules` / `getStorage(ctx, { rules })`","api":"Rules","behavior":"`evaluateStorageRules` supports granular verbs (`get`/`list`/`create`/`update`/`delete`) alongside `read`/`write` umbrella expansion, comma-separated verb lists, and per-verb default-deny","status":"conforms","evidence":"STALE ROW, corrected 2026-07-10: production capture proves the evaluator already supports the full six-verb grant surface (umbrella read→{get,list}, write→{create,update,delete}, single granular grants, comma-separated grants, per-verb deny-by-default), matching production verdict-for-verdict on 12 of the pack's 13 non-existence cases. `oracle:rules-storage-verbs-umbrella-granular` (all `read`/`write`/`get`/comma-verb cases). One related existence-semantics case in the same pack diverges — pinned separately as a KNOWN_DIVERGENCE, not a granular-verb gap.","risk":[],"riskScore":0,"riskReasons":[],"automation":"oracle-backed","oracleObservations":["rules-storage-verbs-umbrella-granular"],"conformanceTests":["packages/pyric/test/storage/rules-oracle-conformance.test.ts"]},
        {"id":"storage-rules#97","surface":"storage-rules","aliases":[],"rowRef":"97","rowNumber":97,"section":"Rules — `parseStorageRules` / `evaluateStorageRules` / `getStorage(ctx, { rules })`","api":"Rules","behavior":"`parseStorageRules` rejects unterminated string literals with `SyntaxError`","status":"conforms","evidence":"`unit:rules.test.ts` (\"rejects unterminated strings\")","risk":[],"riskScore":0,"riskReasons":[],"automation":"unit-backed","oracleObservations":[],"conformanceTests":["packages/pyric/test/storage/rules.test.ts"]},
        {"id":"storage-rules#98","surface":"storage-rules","aliases":[],"rowRef":"98","rowNumber":98,"section":"Rules — `parseStorageRules` / `evaluateStorageRules` / `getStorage(ctx, { rules })`","api":"Rules","behavior":"`evaluateStorageRules` matches `match /sessions/{id} { allow read: if request.auth != null; }` for an authed read","status":"conforms","evidence":"`unit:rules.test.ts` (\"allows authenticated reads of /sessions/{id}\")","risk":[],"riskScore":0,"riskReasons":[],"automation":"unit-backed","oracleObservations":[],"conformanceTests":["packages/pyric/test/storage/rules.test.ts"]},
        {"id":"storage-rules#99","surface":"storage-rules","aliases":[],"rowRef":"99","rowNumber":99,"section":"Rules — `parseStorageRules` / `evaluateStorageRules` / `getStorage(ctx, { rules })`","api":"Rules","behavior":"`evaluateStorageRules` denies anonymous reads when the rule requires `request.auth != null`","status":"conforms","evidence":"`unit:rules.test.ts` (\"denies anonymous reads\")","risk":[],"riskScore":0,"riskReasons":[],"automation":"unit-backed","oracleObservations":[],"conformanceTests":["packages/pyric/test/storage/rules.test.ts"]},
        {"id":"storage-rules#100","surface":"storage-rules","aliases":[],"rowRef":"100","rowNumber":100,"section":"Rules — `parseStorageRules` / `evaluateStorageRules` / `getStorage(ctx, { rules })`","api":"Rules","behavior":"`evaluateStorageRules` supports `request.resource.size < N` constraints (with arithmetic literals like `10 * 1024 * 1024`)","status":"conforms","evidence":"`unit:rules.test.ts` (\"allows JSON writes under 10MB\")","risk":[],"riskScore":0,"riskReasons":[],"automation":"unit-backed","oracleObservations":[],"conformanceTests":["packages/pyric/test/storage/rules.test.ts"]},
        {"id":"storage-rules#101","surface":"storage-rules","aliases":[],"rowRef":"101","rowNumber":101,"section":"Rules — `parseStorageRules` / `evaluateStorageRules` / `getStorage(ctx, { rules })`","api":"Rules","behavior":"`evaluateStorageRules` supports `request.resource.contentType == '<mime>'` constraints","status":"conforms","evidence":"`unit:rules.test.ts` (mime constraint inside the session-archive ruleset)","risk":["metadata"],"riskScore":1,"riskReasons":["asserts metadata shape"],"automation":"unit-backed","oracleObservations":[],"conformanceTests":["packages/pyric/test/storage/rules.test.ts"]},
        {"id":"storage-rules#102","surface":"storage-rules","aliases":[],"rowRef":"102","rowNumber":102,"section":"Rules — `parseStorageRules` / `evaluateStorageRules` / `getStorage(ctx, { rules })`","api":"Rules","behavior":"Multi-segment wildcard `{allPaths=**}` matches zero-or-more remaining segments","status":"conforms","evidence":"`unit:rules.test.ts` (parser + evaluator both honor the `**` form)","risk":[],"riskScore":0,"riskReasons":[],"automation":"unit-backed","oracleObservations":[],"conformanceTests":["packages/pyric/test/storage/rules.test.ts"]},
        {"id":"storage-rules#103","surface":"storage-rules","aliases":[],"rowRef":"103","rowNumber":103,"section":"Rules — `parseStorageRules` / `evaluateStorageRules` / `getStorage(ctx, { rules })`","api":"Rules","behavior":"Path-parameter binding (`{sessionId}`) accessible inside the `if` expression","status":"conforms","evidence":"`unit:rules.test.ts`","risk":[],"riskScore":0,"riskReasons":[],"automation":"unit-backed","oracleObservations":[],"conformanceTests":["packages/pyric/test/storage/rules.test.ts"]},
        {"id":"storage-rules#104","surface":"storage-rules","aliases":[],"rowRef":"104","rowNumber":104,"section":"Rules — `parseStorageRules` / `evaluateStorageRules` / `getStorage(ctx, { rules })`","api":"Rules","behavior":"User-defined `function` definitions — `let` bindings, functions calling functions, and match-block-scoped helper functions (lexical scoping)","status":"conforms","evidence":"STALE ROW, corrected 2026-07-10: production capture proves the evaluator supports user-defined functions with `let` bindings, nested function calls, and block-scoped helpers. `oracle:rules-storage-functions-let-scope` matches production verdict-for-verdict on all 5 cases. Same-name shadowing and undefined-function calls are compile-time rejections in production and are covered by evaluator unit tests instead (they cannot be captured as a clean production verdict).","risk":[],"riskScore":0,"riskReasons":[],"automation":"oracle-backed","oracleObservations":["rules-storage-functions-let-scope"],"conformanceTests":["packages/pyric/test/storage/rules-oracle-conformance.test.ts"]},
        {"id":"storage-rules#112","surface":"storage-rules","aliases":[],"rowRef":"112","rowNumber":112,"section":"Rules — `parseStorageRules` / `evaluateStorageRules` / `getStorage(ctx, { rules })`","api":"Rules","behavior":"`request.time` compared against `timestamp.date(y,m,d)` and `timestamp.value(ms)` constructors","status":"conforms","evidence":"NEW ROW, 2026-07-10: production capture proves the evaluator supports `request.time` comparisons against both timestamp constructors. `oracle:rules-storage-request-time-timestamp` matches production verdict-for-verdict on all 4 cases (deadline-before/after via `timestamp.date()`, epoch-bound before/after via `timestamp.value()`).","risk":[],"riskScore":0,"riskReasons":[],"automation":"oracle-backed","oracleObservations":["rules-storage-request-time-timestamp"],"conformanceTests":["packages/pyric/test/storage/rules-oracle-conformance.test.ts"]},
        {"id":"storage-rules#113","surface":"storage-rules","aliases":[],"rowRef":"113","rowNumber":113,"section":"Rules — `parseStorageRules` / `evaluateStorageRules` / `getStorage(ctx, { rules })`","api":"Rules","behavior":"`string.matches(regex)` with whole-string anchoring (a partial match denies)","status":"conforms","evidence":"NEW ROW, 2026-07-10: production capture proves `matches()` is whole-string anchored, matching a RE2 pattern only when it covers the entire string. `oracle:rules-storage-matches-regex` matches production verdict-for-verdict on all 3 cases. RE2-inexpressible patterns are rejected at ruleset compile time by production and are covered by evaluator unit tests instead.","risk":[],"riskScore":0,"riskReasons":[],"automation":"oracle-backed","oracleObservations":["rules-storage-matches-regex"],"conformanceTests":["packages/pyric/test/storage/rules-oracle-conformance.test.ts"]},
        {"id":"storage-rules#114","surface":"storage-rules","aliases":[],"rowRef":"114","rowNumber":114,"section":"Rules — `parseStorageRules` / `evaluateStorageRules` / `getStorage(ctx, { rules })`","api":"Rules","behavior":"`resource.metadata.<key>` custom-metadata access in dotted (`resource.metadata.owner`) and bracket (`resource.metadata['owner']`) form, including missing-key deny","status":"conforms","evidence":"NEW ROW, 2026-07-10: production capture proves dotted and bracket metadata access resolve identically, and a missing key denies. `oracle:rules-storage-metadata-access` matches production verdict-for-verdict on all 5 cases.","risk":["metadata"],"riskScore":1,"riskReasons":["asserts metadata shape"],"automation":"oracle-backed","oracleObservations":["rules-storage-metadata-access"],"conformanceTests":["packages/pyric/test/storage/rules-oracle-conformance.test.ts"]},
        {"id":"storage-rules#115","surface":"storage-rules","aliases":[],"rowRef":"115","rowNumber":115,"section":"Rules — `parseStorageRules` / `evaluateStorageRules` / `getStorage(ctx, { rules })`","api":"Rules","behavior":"Cross-service `firestore.get()` / `firestore.exists()` lookups from a Storage ruleset, with `$(expr)` path interpolation and qualified function-mock names","status":"conforms","evidence":"NEW ROW, 2026-07-10: production capture proves the evaluator resolves cross-service Firestore lookups from Storage rules, including interpolated document paths and both the map-returning `get()` and bool-returning `exists()` forms. `oracle:rules-storage-firestore-lookup` matches production verdict-for-verdict on all 4 cases.","risk":[],"riskScore":0,"riskReasons":[],"automation":"oracle-backed","oracleObservations":["rules-storage-firestore-lookup"],"conformanceTests":["packages/pyric/test/storage/rules-oracle-conformance.test.ts"]},
        {"id":"storage-rules#116","surface":"storage-rules","aliases":[],"rowRef":"116","rowNumber":116,"section":"Rules — `parseStorageRules` / `evaluateStorageRules` / `getStorage(ctx, { rules })`","api":"Rules","behavior":"`resource.timeCreated` / `resource.updated` — server-populated object timestamps","status":"diverged-documented","evidence":"NEW ROW, 2026-07-10: witness capture confirms the evaluator's resource model carries only size/contentType/metadata, so `resource.timeCreated`/`resource.updated` read `undefined` and any comparison denies in-process, while production evaluates a real server timestamp. `oracle:rules-storage-resource-timestamp-witness` records production's DENY verdict on both cases; the evaluator's DENY happens to match here because both operands are non-comparable rather than because the field is modeled — the underlying field is still unsupported.","risk":["specific-value"],"riskScore":2,"riskReasons":["asserts 2 specific value(s)"],"automation":"oracle-backed","oracleObservations":["rules-storage-resource-timestamp-witness"],"conformanceTests":["packages/pyric/test/storage/rules-oracle-conformance.test.ts"],"exceptionReason":"unsupported field, oracle-confirmed gap — resource.timeCreated/resource.updated not modeled by the evaluator"},
      ],
    },
  ],
} satisfies CompatibilitySurfaceRegistry;

export default rulesRegistry;
