import { defineRows } from './define-rows.ts';
import type { CompatibilitySurfaceRegistry } from './types.ts';

const row1 = defineRows({
  surface: "storage",
  defaults: {
    section: "`getStorage(app, bucketUrl?)` / `getStorageSandbox(target, options?)` — initializer",
    api: "getStorage(app, bucketUrl?)` / `getStorageSandbox(target, options?)",
    automation: "unit-backed",
  },
});

const row2 = defineRows({
  surface: "storage",
  defaults: {
    featureKeys: ["ref"],
    section: "`ref(storage[, path])` / `ref(parent, path)` — reference constructor",
    api: "ref(storage[, path])` / `ref(parent, path)",
    status: "conforms",
    automation: "unit-backed",
    conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
  },
});

const row3 = defineRows({
  surface: "storage",
  defaults: {
    featureKeys: ["uploadBytes"],
    section: "`uploadBytes(ref, data, metadata?)` — write blob",
    api: "uploadBytes(ref, data, metadata?)",
    status: "conforms",
  },
});

const row4 = defineRows({
  surface: "storage",
  defaults: {
    featureKeys: ["uploadString"],
    section: "`uploadString(ref, value, format?, metadata?)` — write string-form",
    api: "uploadString(ref, value, format?, metadata?)",
  },
});

const row5 = defineRows({
  surface: "storage",
  defaults: {
    featureKeys: ["uploadBytesResumable"],
    section: "`uploadBytesResumable(ref, data, metadata?)` — resumable upload + task observers",
    api: "uploadBytesResumable(ref, data, metadata?)",
    status: "unsupported",
    automation: "unsupported",
    exceptionReason: "Behavior is unimplemented; availability is contract-owned.",
  },
});

const row6 = defineRows({
  surface: "storage",
  defaults: {
    featureKeys: ["getDownloadURL"],
    section: "`getDownloadURL(ref)` — read URL",
    api: "getDownloadURL(ref)",
    automation: "oracle-backed",
  },
});

const row7 = defineRows({
  surface: "storage",
  defaults: {
    featureKeys: ["getBytes"],
    section: "`getBytes(ref, maxDownloadSize?)` — read as ArrayBuffer",
    api: "getBytes(ref, maxDownloadSize?)",
    status: "conforms",
  },
});

const row8 = defineRows({
  surface: "storage",
  defaults: {
    featureKeys: ["getBlob"],
    section: "`getBlob(ref, maxDownloadSize?)` — read as Blob",
    api: "getBlob(ref, maxDownloadSize?)",
    status: "conforms",
  },
});

const row9 = defineRows({ surface: "storage" });

const row10 = defineRows({
  surface: "storage",
  defaults: {
    featureKeys: ["deleteObject"],
    section: "`deleteObject(ref)` — delete",
    api: "deleteObject(ref)",
  },
});

const row11 = defineRows({
  surface: "storage",
  defaults: {
    featureKeys: ["listAll"],
    section: "`listAll(ref)` — list all children under a ref",
    api: "listAll(ref)",
    status: "conforms",
  },
});

const row12 = defineRows({ surface: "storage" });

const row13 = defineRows({
  surface: "storage",
  defaults: {
    section: "`getMetadata(ref)` / `updateMetadata(ref, metadata)` — metadata ops",
    api: "getMetadata(ref)` / `updateMetadata(ref, metadata)",
  },
});

const row14 = defineRows({ surface: "storage" });

const row15 = defineRows({
  surface: "storage",
  defaults: {
    featureKeys: ["setRules"],
    section: "Op-level rules enforcement — a denied op throws `storage/unauthorized`",
    api: "Rules enforcement",
    status: "conforms",
  },
});

export const storageRegistry = {
  surface: "storage",
  label: "Storage",
  compatPath: "packages/pyric/docs/storage/COMPAT.md",
  blocks: [
    { kind: 'markdown', markdown: "# `pyric/storage` compatibility matrix\n\n## Status legend\n\n| Status | Meaning |\n|---|---|\n| ✓ | **Conforming** — sandbox matches prod, locked by a passing probe |\n| ⚠ | **Diverged (documented)** — intentional difference with a written reason |\n| ✗ | **Bug** — should match prod but doesn't; failing probe pins it |\n| — | **Not implemented yet** — deliberately or pending |\n| ? | **Unverified** — claim from docs that we haven't yet observed prod-side |\n" },
    {
      kind: 'table',
      prefix: "## `getStorage(app, bucketUrl?)` / `getStorageSandbox(target, options?)` — initializer\n",
      rows: [
        row1({
          rowRef: "1",
          featureKeys: ["getStorageSandbox"],
          behavior: "`getStorageSandbox(ctx)` returns a tagged sandbox-target handle (frozen identity)",
          status: "conforms",
          evidence: "`unit:service.test.ts`",
          risk: ["structural"],
          riskReasons: ["structural / routing-only claim"],
          conformanceTests: ["packages/pyric/test/storage/service.test.ts"],
        }),
        row1({
          rowRef: "2",
          featureKeys: ["getStorageSandbox"],
          behavior: "`getStorageSandbox(sandbox)` wraps a bare Sandbox with an anonymous context (`auth: null`)",
          status: "conforms",
          evidence: "`unit:service.test.ts`",
          risk: ["specific-field"],
          riskScore: 1,
          riskReasons: ["asserts a specific field/property value"],
          conformanceTests: ["packages/pyric/test/storage/service.test.ts"],
        }),
        row1({
          rowRef: "3",
          featureKeys: ["getStorage"],
          behavior: "`getStorage(app)` returns the sandbox handle selected by package resolution",
          status: "conforms",
          evidence: "`entry-path:storage` runs the canonical `initializeApp` → `getStorage(app)` → `ref` → `uploadBytes` flow",
          risk: ["structural"],
          riskReasons: ["structural / routing-only claim"],
          conformanceTests: ["packages/conformance/entry-path/storage.ts"],
        }),
        row1({
          rowRef: "4",
          featureKeys: ["getStorageSandbox"],
          behavior: "Two `getStorageSandbox(ctx)` calls on the same context return the SAME wrapper (identity-stable)",
          status: "conforms",
          evidence: "`unit:service.test.ts` (\"returns the same handle for repeated calls on the same context\")",
          conformanceTests: ["packages/pyric/test/storage/service.test.ts"],
        }),
        row1({
          rowRef: "4a",
          featureKeys: ["getStorageSandbox"],
          behavior: "Two `getStorageSandbox(sandbox)` calls on a bare `Sandbox` return the SAME wrapper (identity-stable)",
          status: "conforms",
          evidence: "ST-B3 fixed: `withAuth(null)` mints a fresh context per call, so the per-context cache missed and bare-Sandbox calls returned different handles. A `Sandbox`-keyed cache makes the convenience path stable, matching the docstring. Probe: `unit:service.test.ts` (\"ST-B3: returns the same handle for repeated bare-Sandbox calls\").",
          conformanceTests: ["packages/pyric/test/storage/service.test.ts"],
          rowNumber: 4,
        }),
        row1({
          rowRef: "5",
          featureKeys: ["getStorage","getStorageSandbox"],
          behavior: "Two different `SandboxContext`s on the same `Sandbox` get DIFFERENT handles but share the underlying `StorageService` (IDB)",
          status: "conforms",
          evidence: "`unit:service.test.ts` (\"shares the underlying StorageService across contexts on the same sandbox\")",
          conformanceTests: ["packages/pyric/test/storage/service.test.ts"],
        }),
        row1({
          rowRef: "6",
          featureKeys: ["getStorage","getStorageSandbox"],
          behavior: "`options.bucket` round-trips on metadata records; v1 has a single implicit bucket but the field is preserved",
          status: "conforms",
          evidence: "`unit:service.test.ts` (\"records the bucket value on the handle\")",
          risk: ["metadata"],
          riskScore: 1,
          riskReasons: ["asserts metadata shape"],
          conformanceTests: ["packages/pyric/test/storage/service.test.ts"],
        }),
        row1({
          rowRef: "7",
          featureKeys: ["getStorage","getStorageSandbox"],
          behavior: "`options.dbName` honored on the FIRST call per `Sandbox`; second-call overrides ignored",
          status: "conforms",
          evidence: "`unit:service.test.ts` (\"dbName only takes effect on the sandbox's first getStorage call\")",
          conformanceTests: ["packages/pyric/test/storage/service.test.ts"],
        }),
        row1({
          rowRef: "8",
          featureKeys: ["getStorage","getStorageSandbox"],
          behavior: "`options.rules` parsed eagerly — malformed rules throw `SyntaxError` at config time",
          status: "conforms",
          evidence: "`unit:storage/sandbox/rules.test.ts` (parse errors propagate from `parseStorageRules`)",
          conformanceTests: ["packages/pyric/test/storage/sandbox/rules.test.ts"],
        }),
        row1({
          rowRef: "9",
          featureKeys: ["getStorage","getStorageSandbox"],
          behavior: "The `TARGET_SYMBOL` brand keeps each handle bound to its owning sandbox service and identity",
          status: "conforms",
          evidence: "`unit:service.test.ts` (distinct contexts share one service while retaining distinct handles)",
          risk: ["structural"],
          riskReasons: ["structural / routing-only claim"],
          conformanceTests: ["packages/pyric/test/storage/service.test.ts"],
          exceptionReason: "sandbox-only behavior — no prod equivalent to observe",
        }),
        row1({
          rowRef: "10",
          featureKeys: ["getStorage","getStorageSandbox"],
          behavior: "Unrecognized handle (not produced by a factory) → `TypeError` \"not a FirebaseStorage handle\"",
          status: "conforms",
          evidence: "`unit:service.test.ts` (\"rejects an object that was not produced by a factory\")",
          conformanceTests: ["packages/pyric/test/storage/service.test.ts"],
        }),
        row1({
          rowRef: "11",
          featureKeys: ["getStorage"],
          behavior: "`getStorage(app, bucketUrl?)` accepts Firebase's bucket argument; the sandbox remains bound to its configured single bucket",
          status: "diverged-documented",
          evidence: "Package resolution owns production selection. The sandbox accepts the canonical argument but does not model production multi-bucket routing; `unit:service.test.ts` pins the configured `pyric-default` bucket.",
          conformanceTests: ["packages/pyric/test/storage/service.test.ts"],
        }),
        row1({
          rowRef: "12",
          featureKeys: ["getStorage"],
          behavior: "The served `firebase/storage` entry accepts bare `getStorage()` and returns the page's shared sandbox handle",
          status: "conforms",
          evidence: "The canonical served entry supplies the page sandbox when the app argument is omitted; the entry-path and bundler suites execute the public package shape.",
          conformanceTests: ["packages/conformance/entry-path/storage.ts","packages/cli/test/serve/bundler.test.ts"],
          exceptionReason: "package-resolution behavior — production package selection is outside the mirror",
        }),
      ],
    },
    {
      kind: 'table',
      prefix: "## `ref(storage[, path])` / `ref(parent, path)` — reference constructor\n",
      rows: [
        row2({
          rowRef: "13",
          behavior: "`ref(storage)` returns the root ref — `fullPath === ''`, `name === ''`, `parent === null`, `root === self`",
          evidence: "`unit:reference.test.ts` (\"root reference has empty fullPath, null parent, and equal root\")",
          risk: ["specific-field"],
          riskScore: 1,
          riskReasons: ["asserts a specific field/property value"],
        }),
        row2({
          rowRef: "14",
          behavior: "`ref(storage, 'sessions/s1.json')` populates `fullPath`, `name` (last segment), `parent` (path without last segment)",
          evidence: "`unit:reference.test.ts` (\"ref(storage, path) populates fullPath and name from the last segment\")",
        }),
        row2({
          rowRef: "15",
          behavior: "Path normalization: leading slashes stripped (`/sessions/s1` → `sessions/s1`)",
          evidence: "`unit:reference.test.ts` (\"normalizes leading/trailing/double slashes\")",
          risk: ["specific-value"],
          riskScore: 2,
          riskReasons: ["asserts 1 specific value(s)"],
        }),
        row2({
          rowRef: "16",
          behavior: "Path normalization: trailing slashes stripped",
          evidence: "`unit:reference.test.ts`",
        }),
        row2({
          rowRef: "17",
          behavior: "Path normalization: repeated internal slashes collapsed (`a//b` → `a/b`)",
          evidence: "`unit:reference.test.ts`",
          risk: ["specific-value"],
          riskScore: 2,
          riskReasons: ["asserts 1 specific value(s)"],
        }),
        row2({
          rowRef: "18",
          behavior: "`ref(parent, child)` joins relative to parent's `fullPath`",
          evidence: "`unit:reference.test.ts` (\"ref(parent, child) joins relative to the parent\")",
        }),
        row2({
          rowRef: "19",
          behavior: "`parent` chain walks back to root (each `.parent` strips one segment until empty, then `null`)",
          evidence: "`unit:reference.test.ts` (\"parent traversal walks back to root\")",
        }),
        row2({
          rowRef: "20",
          behavior: "`root` accessor returns the bucket-root ref regardless of starting depth",
          evidence: "`unit:reference.test.ts`",
        }),
        row2({
          rowRef: "21",
          behavior: "`toString()` returns `gs://<bucket>/<fullPath>`",
          evidence: "`unit:reference.test.ts` (\"toString returns gs://bucket/path\")",
        }),
        row2({
          rowRef: "22",
          behavior: "Reference identity: two `ref(s, 'a/b')` calls are equal-by-`toString` but NOT `===` (value objects, not interned)",
          evidence: "(implicit in `unit:reference.test.ts` parent-chain test — each `.parent` returns a fresh object)",
        }),
        row2({
          rowRef: "23",
          behavior: "References are mirror-owned value objects; `parent` and `root` preserve the same storage handle and path semantics",
          evidence: "`unit:reference.test.ts` pins parent traversal, root identity, bucket, and path behavior through the public reference interface.",
          risk: ["specific-value"],
          riskScore: 2,
          riskReasons: ["asserts 1 specific value(s)"],
        }),
      ],
    },
    {
      kind: 'table',
      prefix: "## `uploadBytes(ref, data, metadata?)` — write blob\n",
      rows: [
        row3({
          rowRef: "24",
          behavior: "Accepts `Blob` payload; returns `UploadResult` with populated `metadata`",
          evidence: "`unit:reference.test.ts` (\"accepts a Blob and round-trips through getBlob\")",
          risk: ["metadata"],
          riskScore: 1,
          riskReasons: ["asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row3({
          rowRef: "25",
          behavior: "Accepts `Uint8Array` payload",
          evidence: "`unit:reference.test.ts` (\"accepts a Uint8Array\")",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row3({
          rowRef: "26",
          behavior: "Accepts `ArrayBuffer` payload",
          evidence: "`unit:reference.test.ts` (\"accepts an ArrayBuffer\")",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row3({
          rowRef: "27",
          behavior: "ContentType precedence: caller's `metadata.contentType` > `Blob.type` > `application/octet-stream`",
          evidence: "`unit:reference.test.ts` (\"metadata.contentType overrides the Blob's intrinsic type\" + \"falls back to application/octet-stream when no type is supplied\")",
          risk: ["specific-value","metadata"],
          riskScore: 3,
          riskReasons: ["asserts 1 specific value(s)","asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row3({
          rowRef: "28",
          behavior: "`Blob.type === ''` (no intrinsic type) falls through to `application/octet-stream`, NOT to `''`",
          evidence: "`unit:reference.test.ts` (\"falls back to application/octet-stream when no type is supplied\")",
          risk: ["specific-value"],
          riskScore: 2,
          riskReasons: ["asserts 1 specific value(s)"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row3({
          rowRef: "29",
          behavior: "`customMetadata` round-trips through the upload pipeline",
          evidence: "`unit:reference.test.ts` (\"round-trips customMetadata\") + `unit:metadata.test.ts`",
          risk: ["metadata"],
          riskScore: 1,
          riskReasons: ["asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/metadata.test.ts","packages/pyric/test/storage/reference.test.ts"],
        }),
        row3({
          rowRef: "30",
          behavior: "Empty `Blob.type` rewrap: when caller hint differs from `Blob.type`, the blob is re-wrapped with the caller's type (same bytes)",
          evidence: "implicit in `unit:reference.test.ts` (\"metadata.contentType overrides the Blob's intrinsic type\")",
          risk: ["metadata"],
          riskScore: 1,
          riskReasons: ["asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row3({
          rowRef: "31",
          behavior: "Throws `storage/invalid-root-operation` when called on the root reference",
          evidence: "`unit:reference.test.ts` (\"throws on root reference\")",
          risk: ["specific-value","error-code"],
          riskScore: 5,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `storage/invalid-root-operation`"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row3({
          rowRef: "32",
          behavior: "Returned `metadata.fullPath` matches the ref's `fullPath`",
          evidence: "`unit:reference.test.ts`",
          risk: ["metadata"],
          riskScore: 1,
          riskReasons: ["asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row3({
          rowRef: "33",
          behavior: "Returned `metadata.size` matches the input blob's byte length",
          evidence: "`unit:reference.test.ts`",
          risk: ["metadata"],
          riskScore: 1,
          riskReasons: ["asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row3({
          rowRef: "34",
          behavior: "Returned `metadata.bucket` matches the storage handle's bucket",
          evidence: "`unit:reference.test.ts`",
          risk: ["metadata"],
          riskScore: 1,
          riskReasons: ["asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row3({
          rowRef: "35",
          behavior: "Replaces any existing object at the path (overwrite, not append)",
          evidence: "`unit:upstream-storage-probes.test.ts` (\"second uploadBytes at the same path replaces bytes and metadata\")",
          risk: ["specific-value"],
          riskScore: 1,
          riskReasons: ["asserts overwritten bytes and contentType"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/upstream-storage-probes.test.ts"],
        }),
        row3({
          rowRef: "36",
          behavior: "Prod: round-trips uploaded bytes through `getDownloadURL` + fetch (byte-for-byte equality)",
          statusNote: "(prod-only)",
          evidence: "oracle: `packages/conformance/observations/storage/storage-upload-bytes-roundtrip.json` (against blockingfun, fb-js-sdk 12.13.0: 6-byte payload → uploadBytes → getDownloadURL → HTTPS fetch → `bytesMatch: true`, `urlIsHttps: true`, `bodyLen === payloadLen === 6`). This row records the production answer key; row #51 compares the sandbox's page-local URL behavior against it.",
          risk: ["specific-field"],
          riskScore: 1,
          riskReasons: ["asserts a specific field/property value"],
          automation: "oracle-backed",
          oracleObservations: ["storage-upload-bytes-roundtrip"],
        }),
        row3({
          rowRef: "37",
          behavior: "Returned `metadata.contentType` matches what the caller hinted (when set)",
          evidence: "`unit:reference.test.ts` + oracle: `packages/conformance/observations/storage/storage-upload-then-getmetadata.json` (`contentType: 'application/octet-stream'` round-trip against blockingfun, fb-js-sdk 12.13.0; `contentTypeMatches: true`)",
          risk: ["specific-field","metadata"],
          riskScore: 2,
          riskReasons: ["asserts a specific field/property value","asserts metadata shape"],
          automation: "oracle-backed",
          oracleObservations: ["storage-upload-then-getmetadata"],
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row3({
          rowRef: "38",
          behavior: "Returned `metadata.generation` / `metageneration` are stringified counters (`'1'` after fresh upload)",
          evidence: "`unit:metadata.test.ts`",
          risk: ["specific-value","metadata"],
          riskScore: 3,
          riskReasons: ["asserts 1 specific value(s)","asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/metadata.test.ts"],
        }),
      ],
    },
    {
      kind: 'table',
      prefix: "## `uploadString(ref, value, format?, metadata?)` — write string-form\n",
      rows: [
        row4({
          rowRef: "39",
          behavior: "`format='raw'` (default): UTF-8 encodes the string; `contentType` defaults to `text/plain;charset=utf-8`",
          status: "conforms",
          evidence: "`unit:reference.test.ts` (\"raw format encodes UTF-8 and defaults contentType to text/plain\")",
          risk: ["metadata"],
          riskScore: 1,
          riskReasons: ["asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row4({
          rowRef: "40",
          behavior: "`format='base64'`: decodes payload bytes from standard base64",
          status: "conforms",
          evidence: "`unit:reference.test.ts` (\"base64 format decodes payload bytes\")",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row4({
          rowRef: "41",
          behavior: "Sandbox: `format='base64url'` (or any unknown format) rejected with `storage/invalid-format` naming the bad format. Prod: `base64url` is ACCEPTED (upload succeeds); a genuinely-unrecognized format throws `storage/unknown`",
          status: "diverged-documented",
          evidence: "divergence, both halves oracle-locked by `packages/conformance/observations/storage/storage-uploadstring-unknown-format.json`: prod accepts `base64url` (`base64urlOk: true`) and throws `storage/unknown` for an unrecognized format — not `storage/invalid-format`. The v1 sandbox ships only `raw`/`base64`/`data_url` (matches `StringFormat`) and throws `storage/invalid-format` for anything else (ST-B3 replaced the old mis-parse-as-data_url behavior). Both sides pinned in `oracle-conformance.test.ts`; sandbox code path documented in `upload.ts`'s `decodeString`. Implementing base64url decoding is still one line in `decodeString`.",
          risk: ["specific-value","error-code","specific-field"],
          riskScore: 6,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `storage/invalid-format`","asserts a specific field/property value"],
          automation: "oracle-backed",
          oracleObservations: ["storage-uploadstring-unknown-format"],
          conformanceTests: ["packages/pyric/test/storage/error-codes.test.ts","packages/pyric/test/storage/oracle-conformance.test.ts"],
        }),
        row4({
          rowRef: "42",
          behavior: "`format='data_url'`: parses `data:<mime>;base64,<payload>`, infers `contentType` from prefix",
          status: "conforms",
          evidence: "`unit:reference.test.ts` (\"data_url format infers contentType from the prefix\")",
          risk: ["metadata"],
          riskScore: 1,
          riskReasons: ["asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row4({
          rowRef: "43",
          behavior: "`format='data_url'` with non-base64 payload: percent-decodes the body",
          status: "conforms",
          evidence: "`unit:upstream-storage-probes.test.ts` (\"non-base64 data_url percent-decodes the body\"; malformed `%%0` → `storage/invalid-format`)",
          risk: ["specific-value","error-code"],
          riskScore: 5,
          riskReasons: ["asserts decoded bytes","asserts Firebase error code(s): `storage/invalid-format`"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/upstream-storage-probes.test.ts"],
        }),
        row4({
          rowRef: "44",
          behavior: "Caller's `metadata.contentType` beats data_url inference",
          status: "conforms",
          evidence: "`unit:reference.test.ts` (\"caller metadata.contentType beats data_url inference\")",
          risk: ["metadata"],
          riskScore: 1,
          riskReasons: ["asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row4({
          rowRef: "45",
          behavior: "Malformed `data_url` (no comma / doesn't start with `data:`) throws `TypeError` with \"data_url format\" message",
          status: "conforms",
          evidence: "`unit:reference.test.ts` (\"throws on malformed data_url\")",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row4({
          rowRef: "46",
          behavior: "Prod: `uploadString(ref, value, 'base64')` round-trips via `getDownloadURL` + fetch",
          status: "conforms",
          statusNote: "(prod-only)",
          evidence: "oracle: `packages/conformance/observations/storage/storage-uploadstring-base64-roundtrip.json` (`'aGVsbG8='` → `'hello'` against blockingfun, fb-js-sdk 12.13.0; `textMatches: true`)",
          risk: ["specific-value","specific-field"],
          riskScore: 3,
          riskReasons: ["asserts 2 specific value(s)","asserts a specific field/property value"],
          automation: "oracle-backed",
          oracleObservations: ["storage-uploadstring-base64-roundtrip"],
        }),
      ],
    },
    {
      kind: 'table',
      prefix: "## `uploadBytesResumable(ref, data, metadata?)` — resumable upload + task observers\n",
      rows: [
        row5({
          rowRef: "47",
          behavior: "Exported by `firebase/storage`; returns an `UploadTask` with `pause()` / `resume()` / `cancel()`",
          evidence: "No `pyric/storage` implementation or behavioral probe exists; availability is classified by the owning surface contract.",
          risk: ["specific-value"],
          riskScore: 2,
          riskReasons: ["asserts 2 specific value(s)"],
        }),
        row5({
          rowRef: "48",
          behavior: "`task.on('state_changed', next, error, complete)` fires `next` with `{bytesTransferred, totalBytes, state}` snapshots",
          evidence: "not implemented",
          risk: ["listener"],
          riskScore: 2,
          riskReasons: ["asserts listener semantics"],
        }),
        row5({
          rowRef: "49",
          behavior: "`task.pause()` flips `state` to `'paused'`; `task.resume()` continues",
          evidence: "not implemented",
          risk: ["specific-value"],
          riskScore: 2,
          riskReasons: ["asserts 1 specific value(s)"],
        }),
        row5({
          rowRef: "50",
          behavior: "`task.cancel()` rejects the upload with `storage/canceled`",
          evidence: "not implemented",
          risk: ["specific-value","error-code"],
          riskScore: 5,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `storage/canceled`"],
        }),
      ],
    },
    {
      kind: 'table',
      prefix: "## `getDownloadURL(ref)` — read URL\n",
      rows: [
        row6({
          rowRef: "51",
          behavior: "Exported by `firebase/storage`; returns a token-signed HTTPS URL that fetches the blob",
          status: "diverged-documented",
          evidence: "Implemented with a two-sided pin. Production observation `storage-upload-bytes-roundtrip` records `urlIsHttps: true` and a byte-identical fetch. The sandbox oracle replay now calls the same public `getDownloadURL` + `fetch` path and proves byte-identical content, while explicitly asserting its URL starts with `blob:`. The client↔host integration proves SharedWorker mode creates that URL in the calling page after the rules-checked Blob crosses the port. The remaining divergence is URL identity and lifetime: the sandbox URL is a page-local snapshot, not token-signed HTTPS and not shareable outside that page.",
          risk: ["specific-value"],
          riskScore: 2,
          riskReasons: ["asserts 2 specific value(s)"],
          oracleObservations: ["storage-upload-bytes-roundtrip"],
          conformanceTests: ["packages/pyric/test/storage/oracle-conformance.test.ts","packages/cli/test/serve/worker/integration.test.ts"],
        }),
        row6({
          rowRef: "52",
          behavior: "Throws `storage/object-not-found` for missing objects",
          status: "conforms",
          evidence: "Production observation `storage-delete-then-get-throws` records `getDownloadURL` throwing `storage/object-not-found` after deletion. The sandbox oracle replay now invokes `getDownloadURL` itself and matches that code; the public error-code suite also pins the never-existing-object case.",
          risk: ["specific-value","error-code"],
          riskScore: 5,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `storage/object-not-found`"],
          oracleObservations: ["storage-delete-then-get-throws"],
          conformanceTests: ["packages/pyric/test/storage/error-codes.test.ts","packages/pyric/test/storage/oracle-conformance.test.ts"],
        }),
      ],
    },
    {
      kind: 'table',
      prefix: "## `getBytes(ref, maxDownloadSize?)` — read as ArrayBuffer\n",
      rows: [
        row7({
          rowRef: "53",
          behavior: "Returns the blob's contents as an `ArrayBuffer`",
          evidence: "`unit:reference.test.ts` (\"accepts a Uint8Array\" round-trip via `getBytes`)",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row7({
          rowRef: "54",
          behavior: "Throws `storage/object-not-found` when no object exists at the path",
          evidence: "`unit:reference.test.ts` (\"throws storage/object-not-found for missing paths\") + oracle: `packages/conformance/observations/storage/storage-delete-then-get-throws.json` (against blockingfun, fb-js-sdk 12.13.0: upload → delete → `getDownloadURL` on the deleted ref throws `FirebaseError` with `code: 'storage/object-not-found'`)",
          risk: ["specific-value","error-code"],
          riskScore: 5,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `storage/object-not-found`"],
          automation: "oracle-backed",
          oracleObservations: ["storage-delete-then-get-throws"],
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row7({
          rowRef: "55",
          behavior: "When the object exceeds `maxDownloadSize`, returns a truncated prefix of that byte length (does not throw)",
          evidence: "`unit:upstream-storage-probes.test.ts` (\"getBytes / getBlob return a truncated prefix when the object exceeds the cap\"). Matches upstream `getBytesInternal` / `getBlobInternal` post-fetch slice (GCS may ignore Range on small files). Prior COMPAT claim that the cap throws was wrong.",
          risk: ["specific-value"],
          riskScore: 1,
          riskReasons: ["asserts truncated byte length and contents"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/upstream-storage-probes.test.ts"],
        }),
        row7({
          rowRef: "56",
          behavior: "Just-under-cap reads succeed and return the full byte length",
          evidence: "`unit:upstream-storage-probes.test.ts` (\"just-under-cap reads return the full object\") + `unit:reference.test.ts` (\"honors maxDownloadSizeBytes when the blob is too large\")",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/upstream-storage-probes.test.ts","packages/pyric/test/storage/reference.test.ts"],
        }),
        row7({
          rowRef: "57",
          behavior: "Throws `storage/invalid-root-operation` when called on the root reference",
          evidence: "`unit:reference.test.ts` (\"throws invalid-root-operation on root reads\")",
          risk: ["specific-value","error-code"],
          riskScore: 5,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `storage/invalid-root-operation`"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
      ],
    },
    {
      kind: 'table',
      prefix: "## `getBlob(ref, maxDownloadSize?)` — read as Blob\n",
      rows: [
        row8({
          rowRef: "58",
          behavior: "Returns the stored bytes wrapped as a `Blob` (with `.type` from metadata)",
          evidence: "`unit:reference.test.ts` (\"accepts a Blob and round-trips through getBlob\")",
          risk: ["metadata"],
          riskScore: 1,
          riskReasons: ["asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row8({
          rowRef: "59",
          behavior: "Throws `storage/object-not-found` for missing paths",
          evidence: "`unit:reference.test.ts` (\"throws storage/object-not-found for missing paths\")",
          risk: ["specific-value","error-code"],
          riskScore: 5,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `storage/object-not-found`"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row8({
          rowRef: "60",
          behavior: "Honors `maxDownloadSize` same as `getBytes`",
          evidence: "`unit:upstream-storage-probes.test.ts` (\"getBytes / getBlob return a truncated prefix when the object exceeds the cap\"; shared `fetchBlob` helper in `download.ts`)",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/upstream-storage-probes.test.ts"],
        }),
        row8({
          rowRef: "61",
          behavior: "Root-ref read throws `storage/invalid-root-operation`",
          evidence: "shared via `guardNonRoot` in `download.ts`",
          risk: ["specific-value","error-code"],
          riskScore: 5,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `storage/invalid-root-operation`"],
          automation: "unverified",
        }),
      ],
    },
    {
      kind: 'table',
      prefix: "## `getStream(ref, maxDownloadSize?)` — Node-specific\n",
      rows: [
        row9({
          rowRef: "62",
          featureKeys: ["getStream"],
          section: "`getStream(ref, maxDownloadSize?)` — Node-specific",
          api: "getStream(ref, maxDownloadSize?)",
          behavior: "Exported by `firebase/storage` (Node entry only); returns a Node `Readable`",
          status: "unsupported",
          evidence: "No `pyric/storage` implementation or behavioral probe exists; availability is classified by the owning surface contract.",
          risk: ["specific-value"],
          riskScore: 2,
          riskReasons: ["asserts 2 specific value(s)"],
          automation: "unsupported",
          exceptionReason: "Behavior is unimplemented; availability is contract-owned.",
        }),
      ],
    },
    {
      kind: 'table',
      prefix: "## `deleteObject(ref)` — delete\n",
      rows: [
        row10({
          rowRef: "63",
          behavior: "Removes both the blob AND the metadata atomically (post-delete `getBlob` throws `object-not-found`)",
          status: "conforms",
          evidence: "`unit:reference.test.ts` (\"removes both blob and metadata\")",
          risk: ["specific-value","error-code","sentinel","atomicity","metadata"],
          riskScore: 10,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `object-not-found`","asserts sentinel or atomic transform semantics","asserts transaction/batch atomicity","asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row10({
          rowRef: "64",
          behavior: "Sandbox: no-op on missing path (does NOT throw)",
          status: "diverged-documented",
          evidence: "divergence: sandbox is no-op via `persistence.ts`'s `delete`. Prod's `deleteObject` on a missing path throws `storage/object-not-found`. Oracle-locked: `packages/conformance/observations/storage/storage-delete-missing-throws.json` (`code: 'storage/object-not-found'`, `name: 'FirebaseError'` against blockingfun, fb-js-sdk 12.13.0). Both sides pinned in `oracle-conformance.test.ts`; documented in `download.ts`.",
          risk: ["specific-value","error-code","specific-field"],
          riskScore: 6,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `storage/object-not-found`","asserts a specific field/property value"],
          automation: "oracle-backed",
          oracleObservations: ["storage-delete-missing-throws"],
          conformanceTests: ["packages/pyric/test/storage/oracle-conformance.test.ts"],
        }),
        row10({
          rowRef: "65",
          behavior: "Throws `storage/invalid-root-operation` on the root reference",
          status: "conforms",
          evidence: "`unit:reference.test.ts` (\"throws invalid-root-operation on root\")",
          risk: ["specific-value","error-code"],
          riskScore: 5,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `storage/invalid-root-operation`"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/reference.test.ts"],
        }),
        row10({
          rowRef: "66",
          behavior: "Prod: a successful `deleteObject` followed by `getDownloadURL` on the same ref throws `storage/object-not-found`",
          status: "conforms",
          statusNote: "(prod-only)",
          evidence: "oracle: `packages/conformance/observations/storage/storage-delete-then-get-throws.json` (against blockingfun, fb-js-sdk 12.13.0: upload + delete succeed, then `getDownloadURL` throws `code: 'storage/object-not-found'`, message `\"Firebase Storage: Object '…' does not exist.\"`, `isFirebaseError: true`)",
          risk: ["specific-value","error-code","specific-field"],
          riskScore: 6,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `storage/object-not-found`","asserts a specific field/property value"],
          automation: "oracle-backed",
          oracleObservations: ["storage-delete-then-get-throws"],
        }),
        row10({
          rowRef: "67",
          behavior: "Sandbox: writes-then-delete leaves no metadata (post-delete `getMetadata` throws `object-not-found`)",
          status: "conforms",
          evidence: "follows from #63 + `getMetadata`",
          risk: ["specific-value","error-code","metadata"],
          riskScore: 6,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `object-not-found`","asserts metadata shape"],
          automation: "unverified",
        }),
      ],
    },
    {
      kind: 'table',
      prefix: "## `listAll(ref)` — list all children under a ref\n",
      rows: [
        row11({
          rowRef: "68",
          behavior: "Returns `ListResult` with `items` (direct child files) + `prefixes` (sub-folder refs) + `nextPageToken: undefined`",
          evidence: "`unit:list.test.ts`",
          risk: ["specific-field"],
          riskScore: 1,
          riskReasons: ["asserts a specific field/property value"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/list.test.ts"],
        }),
        row11({
          rowRef: "69",
          behavior: "Empty bucket → both arrays empty, `nextPageToken: undefined`",
          evidence: "`unit:list.test.ts` (\"returns empty arrays on an empty bucket\")",
          risk: ["specific-field"],
          riskScore: 1,
          riskReasons: ["asserts a specific field/property value"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/list.test.ts"],
        }),
        row11({
          rowRef: "70",
          behavior: "Direct children only — does NOT recurse into grandchildren as items",
          evidence: "`unit:list.test.ts` (\"does not recurse into grandchildren as items\")",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/list.test.ts"],
        }),
        row11({
          rowRef: "71",
          behavior: "Sub-folders surface as `prefixes` and are deduplicated (many files under one folder → ONE prefix entry)",
          evidence: "`unit:list.test.ts` (\"promotes sub-folders into prefixes (deduplicated)\")",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/list.test.ts"],
        }),
        row11({
          rowRef: "72",
          behavior: "`items` sorted by path (IDB key order, lexicographic)",
          evidence: "`unit:list.test.ts` (\"lists direct children of a folder\")",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/list.test.ts"],
        }),
        row11({
          rowRef: "73",
          behavior: "`prefixes` sorted lexicographically by `fullPath` (for determinism)",
          evidence: "`unit:list.test.ts` (root-scan example asserts `configs` < `sessions`)",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/list.test.ts"],
        }),
        row11({
          rowRef: "74",
          behavior: "The scanned ref itself is NEVER included in `items` (even when an object exists at the exact prefix path)",
          evidence: "`unit:list.test.ts` (\"does not include the scanned ref itself\")",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/list.test.ts"],
        }),
        row11({
          rowRef: "75",
          behavior: "`listAll(ref(storage))` (root) scans the entire bucket",
          evidence: "`unit:list.test.ts` (\"listAll on the root scans the entire bucket\")",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/list.test.ts"],
        }),
        row11({
          rowRef: "76",
          behavior: "Items expose the full `StorageReference` shape (storage, bucket, name, parent)",
          evidence: "`unit:list.test.ts` (\"items expose the StorageReference shape\")",
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/list.test.ts"],
        }),
        row11({
          rowRef: "77",
          behavior: "Prod: items + prefixes shape matches sandbox after `N` uploads under a directory",
          evidence: "oracle: `packages/conformance/observations/storage/storage-listall-shape.json` (against blockingfun, fb-js-sdk 12.13.0: 3 direct children + 1 grandchild → `items` has all 3 direct children sorted, `prefixes` has the single sub-folder, `itemCount: 3`, `prefixCount: 1`, `threeDirectChildren: true`, `oneSubPrefix: true`)",
          risk: ["specific-field"],
          riskScore: 1,
          riskReasons: ["asserts a specific field/property value"],
          automation: "oracle-backed",
          oracleObservations: ["storage-listall-shape"],
        }),
        row11({
          rowRef: "77a",
          behavior: "`listAll` enforces rules: `read` permission on the scanned prefix path governs list (Firebase: `read` covers download AND list), denied prefix → `storage/unauthorized`",
          evidence: "ST-B2 fixed: `list.ts` now calls `enforceRules` with `method: 'read'` on the listed prefix (was a silent bypass — a denied tree was still fully enumerable). With no rules configured the check is a no-op. Probe: `unit:list-rules.test.ts` (\"denies an anonymous listAll of a tree the rules protect\" / \"allows an authed listAll\"). Note: a `read` rule scoped to `match /sessions/{id}` does NOT grant list on `/sessions` — the folder needs its own read rule, matching prod; the session-archive demo ruleset adds `match /sessions { allow read }`.",
          risk: ["specific-value","error-code","specific-field","rules-denial"],
          riskScore: 8,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `storage/unauthorized`","asserts a specific field/property value","asserts rules-denial behavior"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/list-rules.test.ts"],
          rowNumber: 77,
        }),
      ],
    },
    {
      kind: 'table',
      prefix: "## `list(ref, options?)` — paginated list\n",
      rows: [
        row12({
          rowRef: "78",
          featureKeys: ["list"],
          section: "`list(ref, options?)` — paginated list",
          api: "list(ref, options?)",
          behavior: "Exported by `firebase/storage`; accepts `{ maxResults, pageToken }`, returns a `ListResult` with `nextPageToken` set when more pages remain",
          status: "unsupported",
          evidence: "No paginated `list` implementation or behavioral probe exists; availability is classified by the owning surface contract. `ListResult.nextPageToken` remains optional for forward-compatible consumer code.",
          risk: ["specific-value"],
          riskScore: 2,
          riskReasons: ["asserts 2 specific value(s)"],
          automation: "unsupported",
          exceptionReason: "Behavior is unimplemented; availability is contract-owned.",
        }),
      ],
    },
    {
      kind: 'table',
      prefix: "## `getMetadata(ref)` / `updateMetadata(ref, metadata)` — metadata ops\n",
      rows: [
        row13({
          rowRef: "79",
          featureKeys: ["getMetadata"],
          behavior: "`getMetadata(ref)` returns the same `FullMetadata` shape `uploadBytes` produced",
          status: "conforms",
          evidence: "`unit:metadata.test.ts` (\"returns the FullMetadata uploadBytes wrote\")",
          risk: ["metadata"],
          riskScore: 1,
          riskReasons: ["asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/metadata.test.ts"],
        }),
        row13({
          rowRef: "80",
          featureKeys: ["getMetadata"],
          behavior: "`getMetadata(ref)` throws `storage/object-not-found` for missing paths",
          status: "conforms",
          evidence: "`unit:metadata.test.ts` (\"throws object-not-found for missing paths\")",
          risk: ["specific-value","error-code","metadata"],
          riskScore: 6,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `storage/object-not-found`","asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/metadata.test.ts"],
        }),
        row13({
          rowRef: "81",
          featureKeys: ["getMetadata"],
          behavior: "`getMetadata(ref)` throws `storage/invalid-root-operation` on the root",
          status: "conforms",
          evidence: "`unit:metadata.test.ts` (\"throws invalid-root-operation on the root reference\")",
          risk: ["specific-value","error-code","metadata"],
          riskScore: 6,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `storage/invalid-root-operation`","asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/metadata.test.ts"],
        }),
        row13({
          rowRef: "82",
          featureKeys: ["updateMetadata"],
          behavior: "`updateMetadata(ref, patch)` replaces the listed client-settable fields wholesale (per Firebase semantics)",
          status: "conforms",
          evidence: "`unit:metadata.test.ts` (\"replaces settable fields, bumps metageneration, refreshes updated\")",
          risk: ["metadata"],
          riskScore: 1,
          riskReasons: ["asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/metadata.test.ts"],
        }),
        row13({
          rowRef: "83",
          featureKeys: ["updateMetadata"],
          behavior: "`updateMetadata` bumps `metageneration` by 1 on each call",
          status: "conforms",
          evidence: "`unit:metadata.test.ts`",
          risk: ["metadata"],
          riskScore: 1,
          riskReasons: ["asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/metadata.test.ts"],
        }),
        row13({
          rowRef: "84",
          featureKeys: ["updateMetadata"],
          behavior: "`updateMetadata` refreshes `updated` to the call moment; `timeCreated` and `generation` stay pinned",
          status: "conforms",
          evidence: "`unit:metadata.test.ts`",
          risk: ["metadata"],
          riskScore: 1,
          riskReasons: ["asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/metadata.test.ts"],
        }),
        row13({
          rowRef: "85",
          featureKeys: ["updateMetadata"],
          behavior: "`updateMetadata` preserves the blob bytes (only metadata changes)",
          status: "conforms",
          evidence: "`unit:metadata.test.ts` (\"leaves the blob content untouched\")",
          risk: ["metadata"],
          riskScore: 1,
          riskReasons: ["asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/metadata.test.ts"],
        }),
        row13({
          rowRef: "86",
          featureKeys: ["updateMetadata"],
          behavior: "`updateMetadata` with `undefined` field values preserves the prior value (does NOT clear it)",
          status: "diverged-documented",
          evidence: "divergence: prod accepts `null` to explicitly clear a field. Sandbox doesn't model `null`-clear (per `metadata.ts` doc comment). Documented; not probe-locked.",
          risk: ["metadata"],
          riskScore: 1,
          riskReasons: ["asserts metadata shape"],
          automation: "unverified",
        }),
        row13({
          rowRef: "87",
          featureKeys: ["updateMetadata"],
          behavior: "`updateMetadata` throws `storage/object-not-found` for missing paths",
          status: "conforms",
          evidence: "`unit:metadata.test.ts` (\"throws object-not-found when the path is missing\")",
          risk: ["specific-value","error-code","metadata"],
          riskScore: 6,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `storage/object-not-found`","asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/metadata.test.ts"],
        }),
        row13({
          rowRef: "88",
          featureKeys: ["updateMetadata"],
          behavior: "`updateMetadata` throws `storage/invalid-root-operation` on the root",
          status: "conforms",
          evidence: "`unit:metadata.test.ts` (\"throws invalid-root-operation on the root reference\")",
          risk: ["specific-value","error-code","metadata"],
          riskScore: 6,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `storage/invalid-root-operation`","asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/metadata.test.ts"],
        }),
        row13({
          rowRef: "89",
          featureKeys: ["getMetadata"],
          behavior: "Prod: `getMetadata` after `uploadBytes` returns `contentType` and `size` matching what was uploaded",
          status: "conforms",
          statusNote: "(prod-only)",
          evidence: "oracle: `packages/conformance/observations/storage/storage-upload-then-getmetadata.json` (against blockingfun, fb-js-sdk 12.13.0: upload 128-byte payload with `contentType: 'application/octet-stream'`, getMetadata returns `metadataSize: 128`, `metadataContentType: 'application/octet-stream'`, `metadataBucket: 'blockingfun.firebasestorage.app'`, `metadataMetageneration: '1'`, `fullPathMatches: true`)",
          risk: ["specific-field","metadata"],
          riskScore: 2,
          riskReasons: ["asserts a specific field/property value","asserts metadata shape"],
          automation: "oracle-backed",
          oracleObservations: ["storage-upload-then-getmetadata"],
        }),
        row13({
          rowRef: "90",
          featureKeys: ["getMetadata","updateMetadata"],
          behavior: "Prod: `updateMetadata({customMetadata: {...}})` round-trips through a follow-up `getMetadata`",
          status: "conforms",
          statusNote: "(prod-only)",
          evidence: "oracle: `packages/conformance/observations/storage/storage-update-metadata-roundtrip.json` (against blockingfun, fb-js-sdk 12.13.0: post-update `getMetadata` returns the exact `customMetadata` object, `metageneration` bumps `'1'` → `'2'`, `customSurvived: true`, `metagenerationBumped: true`)",
          risk: ["specific-value","specific-field","metadata"],
          riskScore: 4,
          riskReasons: ["asserts 2 specific value(s)","asserts a specific field/property value","asserts metadata shape"],
          automation: "oracle-backed",
          oracleObservations: ["storage-update-metadata-roundtrip"],
        }),
        row13({
          rowRef: "91",
          featureKeys: ["getMetadata","updateMetadata"],
          behavior: "`FullMetadata.md5Hash` populated on uploads",
          status: "diverged-documented",
          evidence: "divergence: sandbox does NOT compute `md5Hash`. Oracle-locked: `packages/conformance/observations/storage/storage-upload-then-getmetadata.json` confirms prod sets `md5Hash` (`hasMd5Hash: true` after a vanilla `uploadBytes`). Both sides pinned in `oracle-conformance.test.ts`. Aligning the sandbox is a one-spot fix in `upload.ts`'s `buildStoredMetadata`.",
          risk: ["specific-field","metadata"],
          riskScore: 2,
          riskReasons: ["asserts a specific field/property value","asserts metadata shape"],
          automation: "oracle-backed",
          oracleObservations: ["storage-upload-then-getmetadata"],
          conformanceTests: ["packages/pyric/test/storage/oracle-conformance.test.ts"],
        }),
        row13({
          rowRef: "92",
          featureKeys: ["getMetadata","updateMetadata"],
          behavior: "`FullMetadata.ref` lazy population (prod populates lazily)",
          status: "unsupported",
          evidence: "not modeled in `pyric/storage` — `metadata.ts` explicitly omits `ref` from `FullMetadata`",
          risk: ["specific-value","metadata"],
          riskScore: 3,
          riskReasons: ["asserts 1 specific value(s)","asserts metadata shape"],
          automation: "unsupported",
          exceptionReason: "unsupported / intentionally out of scope",
        }),
      ],
    },
    {
      kind: 'table',
      prefix: "## `connectStorageEmulator(storage, host, port)` — emulator hook\n",
      rows: [
        row14({
          rowRef: "93",
          featureKeys: ["connectStorageEmulator"],
          section: "`connectStorageEmulator(storage, host, port)` — emulator hook",
          api: "connectStorageEmulator(storage, host, port)",
          behavior: "Exported by `firebase/storage`; reroutes a `FirebaseStorage` handle to a local emulator",
          status: "unsupported",
          evidence: "not implemented in `pyric/storage` — the sandbox IS the local-target alternative; emulator parity is out of scope per `index.ts`",
          risk: ["specific-value"],
          riskScore: 2,
          riskReasons: ["asserts 2 specific value(s)"],
          automation: "unsupported",
          exceptionReason: "unsupported / intentionally out of scope",
        }),
      ],
    },
    {
      kind: 'table',
      prefix: "## Op-level rules enforcement — a denied op throws `storage/unauthorized`\n\nThese are Storage SDK behaviors: how an upload / read / metadata / delete op\nsurfaces a rules deny verdict. The rules-engine fidelity rows\n(`parseStorageRules` / `evaluateStorageRules` vs the production Rules Test\nAPI) moved to the native `storage-rules` surface (`docs/rules/COMPAT.md`).\n",
      rows: [
        row15({
          rowRef: "105",
          behavior: "Op-level enforcement: `uploadBytes` against a denied path throws `storage/unauthorized` on sandbox / `storage/unauthorized` on prod, `.code` exposed on both",
          evidence: "ST-B1 fixed: sandbox now throws a `StorageError` (see `src/storage/errors.ts`) whose `.code === 'storage/unauthorized'` — matching prod's `FirebaseError.code`. Probe: `unit:error-codes.test.ts` (\"unauthorized when rules deny the operation\"). Residual divergence (documented, not a `.code` gap): the sandbox `StorageError.name` is `'StorageError'` (plain `Error` subclass, same shape as Firestore's `SandboxError`) where prod reports `name: 'FirebaseError'` / `isFirebaseError: true`, and the message wording differs (sandbox embeds the matched-rule reason chain). Oracle-locked: `packages/conformance/observations/storage/storage-rules-denied-error-code.json` (against blockingfun, fb-js-sdk 12.13.0: `code: 'storage/unauthorized'`, message `\"Firebase Storage: User does not have permission to access '<path>'.\"`, `name: 'FirebaseError'`, `isFirebaseError: true`).",
          risk: ["specific-value","error-code","specific-field","rules-denial"],
          riskScore: 8,
          riskReasons: ["asserts 3 specific value(s)","asserts Firebase error code(s): `storage/unauthorized`, `storage/unauthorized`","asserts a specific field/property value","asserts rules-denial behavior"],
          automation: "oracle-backed",
          oracleObservations: ["storage-rules-denied-error-code"],
          conformanceTests: ["packages/pyric/test/storage/error-codes.test.ts"],
        }),
        row15({
          rowRef: "106",
          behavior: "`getMetadata` against a denied path throws `storage/unauthorized`",
          evidence: "`unit:storage/enforce.test.ts` (operation-integration section)",
          risk: ["specific-value","error-code","rules-denial","metadata"],
          riskScore: 8,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `storage/unauthorized`","asserts rules-denial behavior","asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/enforce.test.ts"],
        }),
        row15({
          rowRef: "107",
          behavior: "`updateMetadata` against a denied path throws `storage/unauthorized`",
          evidence: "`unit:storage/enforce.test.ts`",
          risk: ["specific-value","error-code","rules-denial","metadata"],
          riskScore: 8,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `storage/unauthorized`","asserts rules-denial behavior","asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/enforce.test.ts"],
        }),
        row15({
          rowRef: "108",
          behavior: "`deleteObject` against a denied path throws `storage/unauthorized`",
          evidence: "`unit:storage/enforce.test.ts`",
          risk: ["specific-value","error-code","rules-denial"],
          riskScore: 7,
          riskReasons: ["asserts 1 specific value(s)","asserts Firebase error code(s): `storage/unauthorized`","asserts rules-denial behavior"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/enforce.test.ts"],
        }),
        row15({
          rowRef: "109",
          behavior: "Ordinary SDK object paths are evaluated under Firebase Storage's canonical `/b/{bucket}/o/{object}` rules namespace while metadata preserves the ordinary object path",
          evidence: "`unit:storage/enforce.test.ts` (\"maps ordinary SDK object paths into the canonical bucket rules namespace\"). Production's canonical `/b/{bucket}/o/...` namespace is independently captured on the `storage-rules` surface; this adapter mapping seam is unit-backed rather than presented as a production observation.",
          risk: ["specific-value","rules-denial","metadata"],
          riskScore: 6,
          riskReasons: ["asserts 1 specific value(s)","asserts rules allow/deny routing behavior","asserts metadata shape"],
          automation: "unit-backed",
          conformanceTests: ["packages/pyric/test/storage/enforce.test.ts"],
        }),
      ],
    },
  ],
} satisfies CompatibilitySurfaceRegistry;

export default storageRegistry;
