#!/usr/bin/env bun
/**
 * Render the surface manifest from the directory listing.
 *
 * The directory is the index: `tools/<tool>.ts` is one service tool and
 * `methods/<tool>/<method>.ts` is one method, the filename is the key and
 * appears nowhere else, and the aggregate is computed rather than maintained by
 * hand, the same way the service-command registry is built. Adding a method is
 * one new file and no shared list to edit.
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const surfaceDirectory = dirname(fileURLToPath(import.meta.url));
const toolsDirectory = resolve(surfaceDirectory, 'tools');
const methodsDirectory = resolve(surfaceDirectory, 'methods');
const outputPath = resolve(surfaceDirectory, 'manifest.generated.ts');

/** `<tool>.ts`, a lower-case service name. */
const TOOL_PATTERN = /^[a-z][a-z0-9_]*\.ts$/;

/** `<method>.ts`, the SDK's own spelling, which is camelCase. */
const METHOD_PATTERN = /^[a-z][A-Za-z0-9]*\.ts$/;

/** One tool and the methods its directory holds, both sorted by filename. */
export interface SurfaceSource {
  tool: string;
  methods: string[];
}

/** The name a record file carries, which is the filename without its extension. */
function keyOf(file: string): string {
  return file.replace(/\.ts$/, '');
}

/** The camelCase binding one tool and method import under. */
function identifierFor(tool: string, method: string): string {
  const head = tool.replace(/_(.)/g, (_match, letter: string) => letter.toUpperCase());
  return `${head}${method[0]!.toUpperCase()}${method.slice(1)}`;
}

/** The tools and methods a listing pair describes, sorted for a stable manifest. */
export function surfaceSources(
  toolFiles: readonly string[],
  methodFiles: (tool: string) => readonly string[],
): SurfaceSource[] {
  return toolFiles
    .filter((file) => TOOL_PATTERN.test(file))
    .sort()
    .map((file) => {
      const tool = keyOf(file);
      const methods = methodFiles(tool)
        .filter((candidate) => METHOD_PATTERN.test(candidate))
        .sort()
        .map(keyOf);
      return { tool, methods };
    });
}

/** The generated manifest source for one set of sources. */
export function renderSurfaceManifest(sources: readonly SurfaceSource[]): string {
  const imports: string[] = [];
  const toolEntries: string[] = [];
  const methodEntries: string[] = [];
  for (const { tool, methods } of sources) {
    imports.push(`import ${tool}Tool from './tools/${tool}.js';`);
    toolEntries.push(`  ['${tool}', ${tool}Tool],`);
    for (const method of methods) {
      const binding = identifierFor(tool, method);
      imports.push(`import ${binding} from './methods/${tool}/${method}.js';`);
      methodEntries.push(`  ['${tool}', '${method}', ${binding}],`);
    }
  }
  return [
    '// Generated by ./generate-manifest.ts. Do not edit.',
    "import type { MethodRecord, ToolRecord } from './method-types.js';",
    ...imports,
    '',
    'export const TOOL_RECORDS: ReadonlyArray<readonly [string, ToolRecord]> = [',
    ...toolEntries,
    '];',
    '',
    'export const METHOD_RECORDS: ReadonlyArray<readonly [string, string, MethodRecord]> = [',
    ...methodEntries,
    '];',
    '',
  ].join('\n');
}

export function generateSurfaceManifest(): void {
  const sources = surfaceSources(readdirSync(toolsDirectory), (tool) =>
    readdirSync(resolve(methodsDirectory, tool)),
  );
  writeFileSync(outputPath, renderSurfaceManifest(sources));
}

if (import.meta.main) generateSurfaceManifest();
