#!/usr/bin/env bun
/**
 * Render the operation manifest from the directory listing.
 *
 * The directory is the index: one record per file, the filename is the
 * canonical id and appears nowhere inside the file, and the aggregate is
 * computed rather than maintained by hand, the same way the service-command
 * and tool-family registries are built. A record file is named for its
 * canonical id, so the pattern below is what separates records from the
 * loader and this generator.
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const operationsDirectory = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(operationsDirectory, 'manifest.generated.ts');

/** `verb_service_object.ts`, the canonical id itself. */
const RECORD_PATTERN = /^[a-z]+(_[a-z]+)+\.ts$/;

/** The canonical ids the directory holds, sorted. */
export function operationRecordFiles(files: readonly string[]): string[] {
  return files.filter((file) => RECORD_PATTERN.test(file)).sort();
}

/** The generated manifest source for one directory listing. */
export function renderOperationManifest(files: readonly string[]): string {
  const records = operationRecordFiles(files).map((file) => file.replace(/\.ts$/, ''));
  const imports = records.map(
    (id) => `import ${identifierFor(id)} from './${id}.js';`,
  );
  const entries = records.map((id) => `  ['${id}', ${identifierFor(id)}],`);
  return [
    '// Generated by ./generate-manifest.ts. Do not edit.',
    "import type { OperationRecord } from '../types.js';",
    ...imports,
    '',
    'export const OPERATION_RECORDS: ReadonlyArray<readonly [string, OperationRecord]> = [',
    ...entries,
    '];',
    '',
  ].join('\n');
}

/** The camelCase binding one canonical id imports under. */
function identifierFor(id: string): string {
  const [head, ...rest] = id.split('_');
  return head + rest.map((word) => word[0]!.toUpperCase() + word.slice(1)).join('');
}

export function generateOperationManifest(): void {
  writeFileSync(outputPath, renderOperationManifest(readdirSync(operationsDirectory)));
}

if (import.meta.main) generateOperationManifest();
