// Generated by ./generate-manifest.ts. Do not edit.
import type { OperationRecord } from '../types.js';
import addFirestoreDocument from './add_firestore_document.js';
import batchFirestoreWrites from './batch_firestore_writes.js';
import createAuthUser from './create_auth_user.js';
import deleteAuthUser from './delete_auth_user.js';
import deleteDatabaseValue from './delete_database_value.js';
import deleteFirestoreDocument from './delete_firestore_document.js';
import deleteStorageFile from './delete_storage_file.js';
import diagnoseFirestoreDenial from './diagnose_firestore_denial.js';
import downloadStorageFile from './download_storage_file.js';
import getAuthUser from './get_auth_user.js';
import getDatabaseValue from './get_database_value.js';
import getFirestoreDocument from './get_firestore_document.js';
import getRulesStdlib from './get_rules_stdlib.js';
import getStorageMetadata from './get_storage_metadata.js';
import inspectSandbox from './inspect_sandbox.js';
import lintDatabaseRules from './lint_database_rules.js';
import lintFirestoreRules from './lint_firestore_rules.js';
import lintStorageRules from './lint_storage_rules.js';
import listAuthUsers from './list_auth_users.js';
import listFirestoreDocuments from './list_firestore_documents.js';
import listRulesStdlib from './list_rules_stdlib.js';
import listStorageFiles from './list_storage_files.js';
import queryDatabaseValues from './query_database_values.js';
import queryFirestoreDocuments from './query_firestore_documents.js';
import resetSandbox from './reset_sandbox.js';
import seedSandbox from './seed_sandbox.js';
import setAuthClaims from './set_auth_claims.js';
import simulateDatabaseRules from './simulate_database_rules.js';
import simulateFirestoreRules from './simulate_firestore_rules.js';
import simulateStorageRules from './simulate_storage_rules.js';
import switchAuthIdentity from './switch_auth_identity.js';
import updateAuthUser from './update_auth_user.js';
import updateDatabaseValue from './update_database_value.js';
import updateFirestoreDocument from './update_firestore_document.js';
import uploadStorageFile from './upload_storage_file.js';
import writeDatabaseValue from './write_database_value.js';
import writeFirestoreDocument from './write_firestore_document.js';

export const OPERATION_RECORDS: ReadonlyArray<readonly [string, OperationRecord]> = [
  ['add_firestore_document', addFirestoreDocument],
  ['batch_firestore_writes', batchFirestoreWrites],
  ['create_auth_user', createAuthUser],
  ['delete_auth_user', deleteAuthUser],
  ['delete_database_value', deleteDatabaseValue],
  ['delete_firestore_document', deleteFirestoreDocument],
  ['delete_storage_file', deleteStorageFile],
  ['diagnose_firestore_denial', diagnoseFirestoreDenial],
  ['download_storage_file', downloadStorageFile],
  ['get_auth_user', getAuthUser],
  ['get_database_value', getDatabaseValue],
  ['get_firestore_document', getFirestoreDocument],
  ['get_rules_stdlib', getRulesStdlib],
  ['get_storage_metadata', getStorageMetadata],
  ['inspect_sandbox', inspectSandbox],
  ['lint_database_rules', lintDatabaseRules],
  ['lint_firestore_rules', lintFirestoreRules],
  ['lint_storage_rules', lintStorageRules],
  ['list_auth_users', listAuthUsers],
  ['list_firestore_documents', listFirestoreDocuments],
  ['list_rules_stdlib', listRulesStdlib],
  ['list_storage_files', listStorageFiles],
  ['query_database_values', queryDatabaseValues],
  ['query_firestore_documents', queryFirestoreDocuments],
  ['reset_sandbox', resetSandbox],
  ['seed_sandbox', seedSandbox],
  ['set_auth_claims', setAuthClaims],
  ['simulate_database_rules', simulateDatabaseRules],
  ['simulate_firestore_rules', simulateFirestoreRules],
  ['simulate_storage_rules', simulateStorageRules],
  ['switch_auth_identity', switchAuthIdentity],
  ['update_auth_user', updateAuthUser],
  ['update_database_value', updateDatabaseValue],
  ['update_firestore_document', updateFirestoreDocument],
  ['upload_storage_file', uploadStorageFile],
  ['write_database_value', writeDatabaseValue],
  ['write_firestore_document', writeFirestoreDocument],
];
