import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SNAPSHOT_PATH = join(HERE, '..', 'rules-language', 'firestore.json');

export const RULES_MODULE_CAPABILITIES_PATH = join(
  HERE,
  '..',
  '..',
  'pyric',
  'src',
  'rules',
  'modules',
  'firestore-capabilities.generated.ts',
);

interface Construct {
  id: string;
  kind: string;
  status: string;
}

function literal(values: readonly string[]): string {
  return `[${values.map((value) => JSON.stringify(value)).join(', ')}] as const`;
}

/** Render the resolver vocabulary from accepted production inventory rows. */
export function renderRulesModuleCapabilities(): string {
  const snapshot = JSON.parse(readFileSync(SNAPSHOT_PATH, 'utf8')) as { constructs: Construct[] };
  const accepted = snapshot.constructs.filter((construct) => construct.status === 'accepted');
  const methods = [...new Set(
    accepted.filter((construct) => construct.kind === 'method')
      .map((construct) => construct.id.split('.').at(-1)!),
  )].sort();
  const directFunctions: string[] = [];
  const namespaces = new Map<string, string[]>();
  for (const construct of accepted.filter((candidate) => candidate.kind === 'function')) {
    const path = construct.id.replace(/^firestore\.function\./, '').split('.');
    if (path.length === 1) directFunctions.push(path[0]!);
    else {
      const [namespace, method] = path;
      const values = namespaces.get(namespace!) ?? [];
      values.push(method!);
      namespaces.set(namespace!, values);
    }
  }

  const namespaceSource = [...namespaces.entries()].sort(([left], [right]) => left.localeCompare(right))
    .map(([namespace, values]) => `  ${namespace}: ${literal(values.sort())},`)
    .join('\n');
  return `// Generated by packages/conformance/src/rules-module-capabilities.ts. Do not edit.\n` +
    `// Source: packages/conformance/rules-language/firestore.json accepted constructs.\n` +
    `export const FIRESTORE_DIRECT_FUNCTIONS = ${literal(directFunctions.sort())};\n` +
    `export const FIRESTORE_METHODS = ${literal(methods)};\n` +
    `export const FIRESTORE_NAMESPACE_METHODS = {\n${namespaceSource}\n} as const;\n`;
}
