import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SNAPSHOT_DIR = join(HERE, '..', 'rules-language');

export const RULES_MODULE_CAPABILITIES_PATH = join(
  HERE,
  '..',
  '..',
  'pyric',
  'src',
  'rules',
  'modules',
  'rules-capabilities.generated.ts',
);

interface Construct {
  id: string;
  kind: string;
  status: string;
  receiverType?: string;
}

function literal(values: readonly string[]): string {
  return `[${values.map((value) => JSON.stringify(value)).join(', ')}] as const`;
}

function renderEngineCapabilities(engine: 'firestore' | 'storage'): string {
  const snapshot = JSON.parse(
    readFileSync(join(SNAPSHOT_DIR, `${engine}.json`), 'utf8'),
  ) as { constructs: Construct[] };
  const accepted = snapshot.constructs.filter((construct) => construct.status === 'accepted');
  const bindings = accepted.filter((construct) => construct.kind === 'binding')
    .map((construct) => construct.id.replace(new RegExp(`^${engine}\\.binding\\.`), ''))
    .filter((binding) => binding !== 'path-variable')
    .sort();
  const methods = [...new Set(
    accepted.filter((construct) => construct.kind === 'method')
      .map((construct) => construct.id.split('.').at(-1)!),
  )].sort();
  const methodReceiverTypes = new Map<string, Set<string>>();
  for (const construct of accepted.filter((candidate) => candidate.kind === 'method')) {
    const method = construct.id.split('.').at(-1)!;
    if (!construct.receiverType) {
      throw new Error(`${construct.id}: accepted method is missing receiverType`);
    }
    const receiverTypes = methodReceiverTypes.get(method) ?? new Set<string>();
    for (const receiverType of construct.receiverType.split('|')) receiverTypes.add(receiverType);
    methodReceiverTypes.set(method, receiverTypes);
  }
  const directFunctions: string[] = [];
  const namespaces = new Map<string, string[]>();
  for (const construct of accepted.filter((candidate) => candidate.kind === 'function')) {
    const path = construct.id.replace(new RegExp(`^${engine}\\.function\\.`), '').split('.');
    if (path.length === 1) directFunctions.push(path[0]!);
    else {
      const [namespace, method] = path;
      const values = namespaces.get(namespace!) ?? [];
      values.push(method!);
      namespaces.set(namespace!, values);
    }
  }

  const namespaceSource = [...namespaces.entries()].sort(([left], [right]) => left.localeCompare(right))
    .map(([namespace, values]) => `  ${namespace}: ${literal(values.sort())},`)
    .join('\n');
  const prefix = engine.toUpperCase();
  const receiverSource = [...methodReceiverTypes.entries()].sort(([left], [right]) => left.localeCompare(right))
    .map(([method, receiverTypes]) => `  ${JSON.stringify(method)}: ${literal([...receiverTypes].sort())},`)
    .join('\n');
  return `export const ${prefix}_BINDING_PATHS = ${literal(bindings)};\n` +
    `export const ${prefix}_DIRECT_FUNCTIONS = ${literal(directFunctions.sort())};\n` +
    `export const ${prefix}_METHODS = ${literal(methods)};\n` +
    `export const ${prefix}_METHOD_RECEIVER_TYPES = {\n${receiverSource}\n} as const;\n` +
    `export const ${prefix}_NAMESPACE_METHODS = {\n${namespaceSource}\n} as const;\n`;
}

/** Render the resolver vocabulary from accepted production inventory rows. */
export function renderRulesModuleCapabilities(): string {
  return `// Generated by packages/conformance/src/rules-module-capabilities.ts. Do not edit.\n` +
    `// Sources: packages/conformance/rules-language/{firestore,storage}.json accepted constructs.\n` +
    renderEngineCapabilities('firestore') +
    renderEngineCapabilities('storage');
}
