import type * as Firebase from 'firebase/ai';
import type * as Mirror from '../../src/ai/types.js';

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

/** One admitted-name map: every entry must be mutually assignable. */
type Parity = {
  AILocation: Same<Mirror.AI['location'], Firebase.AI['location']>;
  Citation: Same<Mirror.Citation, Firebase.Citation>;
  CitationMetadata: Same<Mirror.CitationMetadata, Firebase.CitationMetadata>;
  CodeExecutionResult: Same<Mirror.CodeExecutionResult, Firebase.CodeExecutionResult>;
  CodeExecutionResultPart: Same<Mirror.CodeExecutionResultPart, Firebase.CodeExecutionResultPart>;
  CodeExecutionTool: Same<Mirror.CodeExecutionTool, Firebase.CodeExecutionTool>;
  Content: Same<Mirror.Content, Firebase.Content>;
  CountTokensRequest: Same<Mirror.CountTokensRequest, Firebase.CountTokensRequest>;
  CountTokensResponse: Same<Mirror.CountTokensResponse, Firebase.CountTokensResponse>;
  Date: Same<Mirror.Date, Firebase.Date>;
  EnhancedGenerateContentResponse: Same<Mirror.EnhancedGenerateContentResponse, Firebase.EnhancedGenerateContentResponse>;
  ErrorDetails: Same<Mirror.ErrorDetails, Firebase.ErrorDetails>;
  ExecutableCode: Same<Mirror.ExecutableCode, Firebase.ExecutableCode>;
  ExecutableCodePart: Same<Mirror.ExecutableCodePart, Firebase.ExecutableCodePart>;
  FileData: Same<Mirror.FileData, Firebase.FileData>;
  FileDataPart: Same<Mirror.FileDataPart, Firebase.FileDataPart>;
  FunctionCall: Same<Mirror.FunctionCall, Firebase.FunctionCall>;
  FunctionCallingConfig: Same<Mirror.FunctionCallingConfig, Firebase.FunctionCallingConfig>;
  FunctionCallPart: Same<Mirror.FunctionCallPart, Firebase.FunctionCallPart>;
  FunctionDeclaration: Same<Mirror.FunctionDeclaration, Firebase.FunctionDeclaration>;
  FunctionDeclarationsTool: Same<Mirror.FunctionDeclarationsTool, Firebase.FunctionDeclarationsTool>;
  FunctionResponse: Same<Mirror.FunctionResponse, Firebase.FunctionResponse>;
  FunctionResponsePart: Same<Mirror.FunctionResponsePart, Firebase.FunctionResponsePart>;
  GenerateContentCandidate: Same<Mirror.GenerateContentCandidate, Firebase.GenerateContentCandidate>;
  GenerateContentRequest: Same<Mirror.GenerateContentRequest, Firebase.GenerateContentRequest>;
  GenerateContentResponse: Same<Mirror.GenerateContentResponse, Firebase.GenerateContentResponse>;
  GenerationConfig: Same<Mirror.GenerationConfig, Firebase.GenerationConfig>;
  GenerativeContentBlob: Same<Mirror.GenerativeContentBlob, Firebase.GenerativeContentBlob>;
  GoogleMaps: Same<Mirror.GoogleMaps, Firebase.GoogleMaps>;
  GoogleMapsGroundingChunk: Same<Mirror.GoogleMapsGroundingChunk, Firebase.GoogleMapsGroundingChunk>;
  GoogleMapsTool: Same<Mirror.GoogleMapsTool, Firebase.GoogleMapsTool>;
  GoogleSearch: Same<Mirror.GoogleSearch, Firebase.GoogleSearch>;
  GoogleSearchTool: Same<Mirror.GoogleSearchTool, Firebase.GoogleSearchTool>;
  GroundingChunk: Same<Mirror.GroundingChunk, Firebase.GroundingChunk>;
  GroundingMetadata: Same<Mirror.GroundingMetadata, Firebase.GroundingMetadata>;
  GroundingSupport: Same<Mirror.GroundingSupport, Firebase.GroundingSupport>;
  ImageConfig: Same<Mirror.ImageConfig, Firebase.ImageConfig>;
  InlineDataPart: Same<Mirror.InlineDataPart, Firebase.InlineDataPart>;
  LatLng: Same<Mirror.LatLng, Firebase.LatLng>;
  ModalityTokenCount: Same<Mirror.ModalityTokenCount, Firebase.ModalityTokenCount>;
  ObjectSchemaRequest: Same<Mirror.ObjectSchemaRequest, Firebase.ObjectSchemaRequest>;
  Part: Same<Mirror.Part, Firebase.Part>;
  PromptFeedback: Same<Mirror.PromptFeedback, Firebase.PromptFeedback>;
  RetrievalConfig: Same<Mirror.RetrievalConfig, Firebase.RetrievalConfig>;
  SafetyRating: Same<Mirror.SafetyRating, Firebase.SafetyRating>;
  SafetySetting: Same<Mirror.SafetySetting, Firebase.SafetySetting>;
  SchemaInterface: Same<Mirror.SchemaInterface, Firebase.SchemaInterface>;
  SchemaRequest: Same<Mirror.SchemaRequest, Firebase.SchemaRequest>;
  SchemaShared: Same<Mirror.SchemaShared<unknown>, Firebase.SchemaShared<unknown>>;
  SearchEntrypoint: Same<Mirror.SearchEntrypoint, Firebase.SearchEntrypoint>;
  Segment: Same<Mirror.Segment, Firebase.Segment>;
  TextPart: Same<Mirror.TextPart, Firebase.TextPart>;
  ThinkingConfig: Same<Mirror.ThinkingConfig, Firebase.ThinkingConfig>;
  Tool: Same<Mirror.Tool, Firebase.Tool>;
  ToolConfig: Same<Mirror.ToolConfig, Firebase.ToolConfig>;
  URLContext: Same<Mirror.URLContext, Firebase.URLContext>;
  URLContextMetadata: Same<Mirror.URLContextMetadata, Firebase.URLContextMetadata>;
  URLContextTool: Same<Mirror.URLContextTool, Firebase.URLContextTool>;
  URLMetadata: Same<Mirror.URLMetadata, Firebase.URLMetadata>;
  UsageMetadata: Same<Mirror.UsageMetadata, Firebase.UsageMetadata>;
  VideoMetadata: Same<Mirror.VideoMetadata, Firebase.VideoMetadata>;
  WebGroundingChunk: Same<Mirror.WebGroundingChunk, Firebase.WebGroundingChunk>;
};

declare const parity: Parity;
const allParity: { [K in keyof Parity]: true } = parity;
