import type * as Firebase from 'firebase/ai';
import type * as Mirror from '../../src/ai/types.js';

type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;

type Names =
  | 'Citation'
  | 'CitationMetadata'
  | 'CodeExecutionResult'
  | 'CodeExecutionResultPart'
  | 'CodeExecutionTool'
  | 'Content'
  | 'CountTokensRequest'
  | 'CountTokensResponse'
  | 'Date'
  | 'EnhancedGenerateContentResponse'
  | 'ErrorDetails'
  | 'ExecutableCode'
  | 'ExecutableCodePart'
  | 'FileData'
  | 'FileDataPart'
  | 'FunctionCall'
  | 'FunctionCallingConfig'
  | 'FunctionCallPart'
  | 'FunctionDeclaration'
  | 'FunctionDeclarationsTool'
  | 'FunctionResponse'
  | 'FunctionResponsePart'
  | 'GenerateContentCandidate'
  | 'GenerateContentRequest'
  | 'GenerateContentResponse'
  | 'GenerationConfig'
  | 'GenerativeContentBlob'
  | 'GoogleMaps'
  | 'GoogleMapsGroundingChunk'
  | 'GoogleMapsTool'
  | 'GoogleSearch'
  | 'GoogleSearchTool'
  | 'GroundingChunk'
  | 'GroundingMetadata'
  | 'GroundingSupport'
  | 'ImageConfig'
  | 'InlineDataPart'
  | 'LatLng'
  | 'ModalityTokenCount'
  | 'ObjectSchemaRequest'
  | 'Part'
  | 'PromptFeedback'
  | 'RetrievalConfig'
  | 'SafetyRating'
  | 'SafetySetting'
  | 'SchemaInterface'
  | 'SchemaRequest'
  | 'SchemaShared'
  | 'SearchEntrypoint'
  | 'Segment'
  | 'TextPart'
  | 'ThinkingConfig'
  | 'Tool'
  | 'ToolConfig'
  | 'URLContext'
  | 'URLContextMetadata'
  | 'URLContextTool'
  | 'URLMetadata'
  | 'UsageMetadata'
  | 'VideoMetadata'
  | 'WebGroundingChunk';

type MirrorTypes = {
  Citation: Mirror.Citation;
  CitationMetadata: Mirror.CitationMetadata;
  CodeExecutionResult: Mirror.CodeExecutionResult;
  CodeExecutionResultPart: Mirror.CodeExecutionResultPart;
  CodeExecutionTool: Mirror.CodeExecutionTool;
  Content: Mirror.Content;
  CountTokensRequest: Mirror.CountTokensRequest;
  CountTokensResponse: Mirror.CountTokensResponse;
  Date: Mirror.Date;
  EnhancedGenerateContentResponse: Mirror.EnhancedGenerateContentResponse;
  ErrorDetails: Mirror.ErrorDetails;
  ExecutableCode: Mirror.ExecutableCode;
  ExecutableCodePart: Mirror.ExecutableCodePart;
  FileData: Mirror.FileData;
  FileDataPart: Mirror.FileDataPart;
  FunctionCall: Mirror.FunctionCall;
  FunctionCallingConfig: Mirror.FunctionCallingConfig;
  FunctionCallPart: Mirror.FunctionCallPart;
  FunctionDeclaration: Mirror.FunctionDeclaration;
  FunctionDeclarationsTool: Mirror.FunctionDeclarationsTool;
  FunctionResponse: Mirror.FunctionResponse;
  FunctionResponsePart: Mirror.FunctionResponsePart;
  GenerateContentCandidate: Mirror.GenerateContentCandidate;
  GenerateContentRequest: Mirror.GenerateContentRequest;
  GenerateContentResponse: Mirror.GenerateContentResponse;
  GenerationConfig: Mirror.GenerationConfig;
  GenerativeContentBlob: Mirror.GenerativeContentBlob;
  GoogleMaps: Mirror.GoogleMaps;
  GoogleMapsGroundingChunk: Mirror.GoogleMapsGroundingChunk;
  GoogleMapsTool: Mirror.GoogleMapsTool;
  GoogleSearch: Mirror.GoogleSearch;
  GoogleSearchTool: Mirror.GoogleSearchTool;
  GroundingChunk: Mirror.GroundingChunk;
  GroundingMetadata: Mirror.GroundingMetadata;
  GroundingSupport: Mirror.GroundingSupport;
  ImageConfig: Mirror.ImageConfig;
  InlineDataPart: Mirror.InlineDataPart;
  LatLng: Mirror.LatLng;
  ModalityTokenCount: Mirror.ModalityTokenCount;
  ObjectSchemaRequest: Mirror.ObjectSchemaRequest;
  Part: Mirror.Part;
  PromptFeedback: Mirror.PromptFeedback;
  RetrievalConfig: Mirror.RetrievalConfig;
  SafetyRating: Mirror.SafetyRating;
  SafetySetting: Mirror.SafetySetting;
  SchemaInterface: Mirror.SchemaInterface;
  SchemaRequest: Mirror.SchemaRequest;
  SchemaShared: Mirror.SchemaShared<unknown>;
  SearchEntrypoint: Mirror.SearchEntrypoint;
  Segment: Mirror.Segment;
  TextPart: Mirror.TextPart;
  ThinkingConfig: Mirror.ThinkingConfig;
  Tool: Mirror.Tool;
  ToolConfig: Mirror.ToolConfig;
  URLContext: Mirror.URLContext;
  URLContextMetadata: Mirror.URLContextMetadata;
  URLContextTool: Mirror.URLContextTool;
  URLMetadata: Mirror.URLMetadata;
  UsageMetadata: Mirror.UsageMetadata;
  VideoMetadata: Mirror.VideoMetadata;
  WebGroundingChunk: Mirror.WebGroundingChunk;
};

type FirebaseTypes = {
  Citation: Firebase.Citation;
  CitationMetadata: Firebase.CitationMetadata;
  CodeExecutionResult: Firebase.CodeExecutionResult;
  CodeExecutionResultPart: Firebase.CodeExecutionResultPart;
  CodeExecutionTool: Firebase.CodeExecutionTool;
  Content: Firebase.Content;
  CountTokensRequest: Firebase.CountTokensRequest;
  CountTokensResponse: Firebase.CountTokensResponse;
  Date: Firebase.Date;
  EnhancedGenerateContentResponse: Firebase.EnhancedGenerateContentResponse;
  ErrorDetails: Firebase.ErrorDetails;
  ExecutableCode: Firebase.ExecutableCode;
  ExecutableCodePart: Firebase.ExecutableCodePart;
  FileData: Firebase.FileData;
  FileDataPart: Firebase.FileDataPart;
  FunctionCall: Firebase.FunctionCall;
  FunctionCallingConfig: Firebase.FunctionCallingConfig;
  FunctionCallPart: Firebase.FunctionCallPart;
  FunctionDeclaration: Firebase.FunctionDeclaration;
  FunctionDeclarationsTool: Firebase.FunctionDeclarationsTool;
  FunctionResponse: Firebase.FunctionResponse;
  FunctionResponsePart: Firebase.FunctionResponsePart;
  GenerateContentCandidate: Firebase.GenerateContentCandidate;
  GenerateContentRequest: Firebase.GenerateContentRequest;
  GenerateContentResponse: Firebase.GenerateContentResponse;
  GenerationConfig: Firebase.GenerationConfig;
  GenerativeContentBlob: Firebase.GenerativeContentBlob;
  GoogleMaps: Firebase.GoogleMaps;
  GoogleMapsGroundingChunk: Firebase.GoogleMapsGroundingChunk;
  GoogleMapsTool: Firebase.GoogleMapsTool;
  GoogleSearch: Firebase.GoogleSearch;
  GoogleSearchTool: Firebase.GoogleSearchTool;
  GroundingChunk: Firebase.GroundingChunk;
  GroundingMetadata: Firebase.GroundingMetadata;
  GroundingSupport: Firebase.GroundingSupport;
  ImageConfig: Firebase.ImageConfig;
  InlineDataPart: Firebase.InlineDataPart;
  LatLng: Firebase.LatLng;
  ModalityTokenCount: Firebase.ModalityTokenCount;
  ObjectSchemaRequest: Firebase.ObjectSchemaRequest;
  Part: Firebase.Part;
  PromptFeedback: Firebase.PromptFeedback;
  RetrievalConfig: Firebase.RetrievalConfig;
  SafetyRating: Firebase.SafetyRating;
  SafetySetting: Firebase.SafetySetting;
  SchemaInterface: Firebase.SchemaInterface;
  SchemaRequest: Firebase.SchemaRequest;
  SchemaShared: Firebase.SchemaShared<unknown>;
  SearchEntrypoint: Firebase.SearchEntrypoint;
  Segment: Firebase.Segment;
  TextPart: Firebase.TextPart;
  ThinkingConfig: Firebase.ThinkingConfig;
  Tool: Firebase.Tool;
  ToolConfig: Firebase.ToolConfig;
  URLContext: Firebase.URLContext;
  URLContextMetadata: Firebase.URLContextMetadata;
  URLContextTool: Firebase.URLContextTool;
  URLMetadata: Firebase.URLMetadata;
  UsageMetadata: Firebase.UsageMetadata;
  VideoMetadata: Firebase.VideoMetadata;
  WebGroundingChunk: Firebase.WebGroundingChunk;
};

type Parity = { [K in Names]: Same<MirrorTypes[K], FirebaseTypes[K]> };
type Forward = { [K in Names]: [MirrorTypes[K]] extends [FirebaseTypes[K]] ? true : false };
type Reverse = { [K in Names]: [FirebaseTypes[K]] extends [MirrorTypes[K]] ? true : false };
declare const parity: Parity;
const allParity: { [K in Names]: true } = parity;
