import { describe, expect, it } from 'bun:test';
import { parseToolRecord, renderToolRegistry } from '../../scripts/generate-tool-registry.ts';

describe('tool registry generation', () => {
  it('derives the record key and identifier exclusively from the record filename', () => {
    expect(parseToolRecord('firestore-simulator.ts')).toEqual({
      file: 'firestore-simulator.ts',
      identifier: 'firestoreSimulator',
      key: 'firestore-simulator',
    });
    expect(parseToolRecord('pyric.ts')).toEqual({
      file: 'pyric.ts',
      identifier: 'pyric',
      key: 'pyric',
    });
  });

  it('renders static imports and spreads each record under its key, in filename order', () => {
    const source = renderToolRegistry(['rules-stdlib.ts', 'pyric.ts']);
    expect(source).toStartWith('// Generated by scripts/generate-tool-registry.ts. Do not edit.');
    expect(source).toContain("import type { RegisteredToolRecord } from './tool-records.js';");
    expect(source).toContain("import pyric from './tool-records/pyric.js';");
    expect(source).toContain("import rulesStdlib from './tool-records/rules-stdlib.js';");
    expect(source).toContain('{ key: "pyric", ...pyric },');
    expect(source).toContain('{ key: "rules-stdlib", ...rulesStdlib },');
    expect(source.indexOf('key: "pyric"')).toBeLessThan(source.indexOf('key: "rules-stdlib"'));
    expect(source).toContain('satisfies readonly RegisteredToolRecord[]');
    expect(source).not.toContain('readdirSync');
  });

  it('rejects filenames that are not one lowercase kebab-case tool key', () => {
    for (const file of ['FirestoreRules.ts', 'firestore_rules.ts', '-rules.ts', 'rules-.ts', 'rules.js']) {
      expect(() => parseToolRecord(file)).toThrow('expected lowercase kebab-case <tool>.ts');
    }
  });
});
