import { describe, expect, it } from 'bun:test';
import { render } from '../../scripts/generate-tool-reference.ts';
import { toolOps, toolRecords } from '../../src/bridge/tool-records.js';

const rendered = render();

function toolHeadingCount(name: string): number {
  const pattern = new RegExp(`^## \`${name}\`$`, 'gm');
  return [...rendered.matchAll(pattern)].length;
}

function opHeadingCount(tool: string, op: string): number {
  const pattern = new RegExp(`^### \`${tool}\\.${op}\`$`, 'gm');
  return [...rendered.matchAll(pattern)].length;
}

describe('MCP tool reference generation', () => {
  it('names the generator in a header', () => {
    expect(rendered).toContain(
      '<!-- Generated by packages/cli/scripts/generate-tool-reference.ts. Do not edit. -->',
    );
  });

  it('carries front matter matching the other reference pages', () => {
    expect(rendered).toStartWith('---\ntitle: "MCP tool reference"');
    expect(rendered).toContain('group: "API reference"');
    expect(rendered).toContain('section: "@pyric/cli"');
  });

  it('lists every live tool exactly once, in tools/list order', () => {
    const records = toolRecords();
    expect(records.length).toBeGreaterThan(0);
    for (const record of records) {
      expect(toolHeadingCount(record.name)).toBe(1);
    }
    const positions = records.map((record) => rendered.indexOf(`## \`${record.name}\``));
    expect(positions).toEqual([...positions].sort((a, b) => a - b));
  });

  it('lists every live operation exactly once, as `tool.op`', () => {
    const ops = toolOps();
    expect(ops.length).toBeGreaterThan(0);
    for (const op of ops) {
      expect(opHeadingCount(op.tool, op.op)).toBe(1);
    }
  });

  it('renders no operation outside the live registry', () => {
    const live = new Set(toolOps().map((op) => `${op.tool}.${op.op}`));
    const headings = [...rendered.matchAll(/^### `([a-z][a-z0-9_]*\.[a-z][a-z0-9_]*)`$/gm)].map(
      (match) => match[1]!,
    );
    expect(headings.length).toBe(live.size);
    for (const heading of headings) {
      expect(live.has(heading)).toBe(true);
    }
  });

  it('states each operation\'s transport', () => {
    expect(rendered).toContain('Transport: forwarded to the connected sandbox.');
    expect(rendered).toContain('Transport: in-process.');
  });

  it('prints a union field type as its variants joined with "or"', () => {
    expect(rendered).toContain('| `as` | string or object | no |');
  });
});
