import { describe, expect, it } from 'bun:test';
import {
  parseToolFamilyRecord,
  renderToolFamilyRegistry,
} from '../../scripts/generate-tool-family-registry.ts';

describe('tool-family registry generation', () => {
  it('derives the family key and identifier exclusively from the record filename', () => {
    expect(parseToolFamilyRecord('firestore-simulator.ts')).toEqual({
      file: 'firestore-simulator.ts',
      identifier: 'firestoreSimulator',
      key: 'firestore-simulator',
    });
    expect(parseToolFamilyRecord('conformance.ts')).toEqual({
      file: 'conformance.ts',
      identifier: 'conformance',
      key: 'conformance',
    });
  });

  it('renders static imports and spreads each record under its key, in filename order', () => {
    const source = renderToolFamilyRegistry(['rtdb-inspection.ts', 'conformance.ts']);
    expect(source).toStartWith(
      '// Generated by scripts/generate-tool-family-registry.ts. Do not edit.',
    );
    expect(source).toContain("import type { ToolFamily } from './tool-families.js';");
    expect(source).toContain("import conformance from './tool-family-records/conformance.js';");
    expect(source).toContain("import rtdbInspection from './tool-family-records/rtdb-inspection.js';");
    expect(source).toContain('{ key: "conformance", ...conformance },');
    expect(source).toContain('{ key: "rtdb-inspection", ...rtdbInspection },');
    expect(source.indexOf('key: "conformance"')).toBeLessThan(source.indexOf('key: "rtdb-inspection"'));
    expect(source).toContain('satisfies readonly ToolFamily[]');
    expect(source).not.toContain('readdirSync');
  });

  it('rejects filenames that are not one lowercase kebab-case family key', () => {
    for (const file of ['FirestoreRules.ts', 'firestore_rules.ts', '-rules.ts', 'rules-.ts', 'rules.js']) {
      expect(() => parseToolFamilyRecord(file)).toThrow('expected lowercase kebab-case <family>.ts');
    }
  });
});
