/**
 * Tool record composition: the Node side lists folded tools over MCP, the
 * browser side executes forwarded operations, and the records pin both.
 * These tests pin the properties that must survive any change in how the
 * tools are composed:
 *
 *  1. The records directory, the generated aggregate, and the two side
 *     factory maps agree on the set of records and factories, and each
 *     record is pure.
 *  2. Every operation resolves to a handler its factory yields, and every
 *     handler a factory yields is either mapped or deliberately unmapped.
 *  3. The listed order equals the pinned contract order.
 *  4. Every operation the browser peer advertises resolves in its dispatcher.
 *  5. The per-op schema the Node side advertises equals the schema of the
 *     handler the browser executes, minus pinned fields.
 *  6. The folded tool carries a required `op` enum, the union of its fields,
 *     and a description that lists every op with its fields.
 *  7. A call with an unknown op or invalid fields yields the structured error.
 */
import { describe, expect, it } from 'bun:test';
import { readdirSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { initializeSandbox } from 'pyric/sandbox';
import { getInternalEnv } from 'pyric/sandbox/internal';
import { getAdminFirestore } from 'pyric/firestore';
import {
  buildSandboxDispatcher,
  SANDBOX_OP_KEYS,
  UnknownToolError,
} from '../../src/bridge/client/dispatch.js';
import { SANDBOX_FACTORIES, type SandboxBinding } from '../../src/bridge/client/tool-factories.js';
import {
  FORWARDED_FACTORIES,
  IN_PROCESS_FACTORIES,
} from '../../src/bridge/server/tool-factories.js';
import { composeMcpTools, resolveToolCall } from '../../src/bridge/server/tool-surface.js';
import {
  DEFAULT_MCP_OP_KEYS,
  DEFAULT_MCP_TOOL_NAMES,
  getDefaultMcpToolSurface,
} from '../../src/bridge/server/mcp-contract.js';
import {
  assertExactOpKeys,
  bindOpArgs,
  opKey,
  toolOps,
  toolRecords,
  TOOL_SERVICE_WORDS,
} from '../../src/bridge/tool-records.js';
import { TOOL_RECORDS } from '../../src/bridge/tool-records.generated.js';

const bridgeDir = resolve(import.meta.dir, '../../src/bridge');
const recordsDir = resolve(bridgeDir, 'tool-records');

/**
 * Handlers a factory yields that no record maps. Each entry says why. A new
 * handler must be mapped by a record or added here deliberately.
 */
const UNMAPPED_HANDLERS: Record<string, string> = {
  firestore_rules_stdlib_list: 'Firestore-only spelling; rules_stdlib.list with service firestore replaces it',
  firestore_rules_stdlib_get: 'Firestore-only spelling; rules_stdlib.get with service firestore replaces it',
  firestore_resolve_modules: 'Firestore-only resolver; firestore_rules.resolve pins the neutral resolver to firestore',
};

function importLines(path: string): string[] {
  return readFileSync(path, 'utf8')
    .split('\n')
    .filter((line) => /^\s*import\b/.test(line));
}

const stub = () => {
  throw new Error('stub resolver must not run');
};

describe('tool records', () => {
  it('generated aggregate matches the records directory in filename order', () => {
    const files = readdirSync(recordsDir)
      .filter((file) => file.endsWith('.ts'))
      .sort();
    expect(TOOL_RECORDS.map((record) => record.key)).toEqual(
      files.map((file) => file.replace(/\.ts$/, '')),
    );
    expect(readFileSync(resolve(bridgeDir, 'tool-records.generated.ts'), 'utf8')).toStartWith(
      '// Generated by scripts/generate-tool-registry.ts. Do not edit.',
    );
  });

  it('each record imports only the contract type, so either side can load it', () => {
    for (const file of readdirSync(recordsDir)) {
      expect(importLines(resolve(recordsDir, file))).toEqual([
        "import type { ToolRecord } from '../tool-records.js';",
      ]);
    }
  });

  it('the contract module imports only the generated aggregate', () => {
    expect(importLines(resolve(bridgeDir, 'tool-records.ts'))).toEqual([
      "import { TOOL_RECORDS } from './tool-records.generated.js';",
    ]);
  });

  it('names follow the grammar: a closed service word, at most one artifact, filename equals name', () => {
    for (const record of toolRecords()) {
      const [service, ...rest] = record.name.split('_');
      expect(TOOL_SERVICE_WORDS).toContain(service);
      expect(rest.length).toBeLessThanOrEqual(1);
      expect(record.key.replace(/-/g, '_')).toBe(record.name);
      expect(record.name).not.toContain('rtdb');
      expect(record.name).not.toContain('firebase');
    }
  });

  it('keys, orders, names and op keys are unique and records sort by order', () => {
    const records = toolRecords();
    expect(records.length).toBe(TOOL_RECORDS.length);
    expect(new Set(records.map((record) => record.key)).size).toBe(records.length);
    expect(new Set(records.map((record) => record.order)).size).toBe(records.length);
    expect(new Set(records.map((record) => record.name)).size).toBe(records.length);
    const orders = records.map((record) => record.order);
    expect(orders).toEqual([...orders].sort((a, b) => a - b));
    const keys = toolOps().map((op) => opKey(op.tool, op.op));
    expect(new Set(keys).size).toBe(keys.length);
  });

  it('every factory a record names has exactly one entry on each side that serves its transport', () => {
    const forwarded = [...new Set(toolOps('forwarded').map((op) => op.factory))].sort();
    const inProcess = [...new Set(toolOps('in-process').map((op) => op.factory))].sort();
    expect(Object.keys(FORWARDED_FACTORIES).sort()).toEqual(forwarded);
    expect(Object.keys(SANDBOX_FACTORIES).sort()).toEqual(forwarded);
    expect(Object.keys(IN_PROCESS_FACTORIES).sort()).toEqual(inProcess);
  });

  it('every operation maps to a handler its factory yields, and every yielded handler is mapped or listed', () => {
    const yielded = new Map<string, Set<string>>();
    for (const [key, factory] of Object.entries(FORWARDED_FACTORIES)) {
      yielded.set(key, new Set(factory(stub as never).map((handler) => handler.name)));
    }
    for (const [key, factory] of Object.entries(IN_PROCESS_FACTORIES)) {
      yielded.set(key, new Set(factory().map((handler) => handler.name)));
    }
    const mapped = new Set<string>();
    for (const op of toolOps()) {
      expect(yielded.get(op.factory)?.has(op.handler)).toBe(true);
      mapped.add(op.handler);
    }
    const unmapped = [...yielded.values()]
      .flatMap((names) => [...names])
      .filter((name) => !mapped.has(name))
      .sort();
    expect(unmapped).toEqual(Object.keys(UNMAPPED_HANDLERS).sort());
  });

  it('assertExactOpKeys fails closed naming the label and both lists', () => {
    expect(() => assertExactOpKeys('x', ['b', 'a'], ['a', 'b'])).not.toThrow();
    expect(() => assertExactOpKeys('forwarded sandbox operations', ['a', 'b'], ['a'])).toThrow(
      /forwarded sandbox operations drifted from the default MCP contract\nexpected: a\nactual: {3}a, b/,
    );
    expect(() => assertExactOpKeys('in-process operations', ['a'], ['a', 'c'])).toThrow(
      'in-process operations drifted',
    );
  });

  it('bindOpArgs injects pinned fields over the caller fields', () => {
    expect(bindOpArgs({ fixed: { service: 'storage' } }, { source: 'x', service: 'firestore' })).toEqual({
      source: 'x',
      service: 'storage',
    });
    const args = { source: 'x' };
    expect(bindOpArgs({}, args)).toBe(args);
  });
});

describe('tool composition', () => {
  it('lists the folded tools in the pinned contract order with every op', () => {
    const tools = getDefaultMcpToolSurface();
    expect(tools.map((tool) => tool.name)).toEqual([...DEFAULT_MCP_TOOL_NAMES]);
    expect(tools.flatMap((tool) => tool.ops.map((op) => opKey(tool.name, op.op)))).toEqual([
      ...DEFAULT_MCP_OP_KEYS,
    ]);
  });

  it('advertises a required op enum plus the union of op fields, and describes every op with its fields', () => {
    for (const tool of composeMcpTools()) {
      const schema = tool.parameters;
      expect(schema.type).toBe('object');
      expect(schema.required).toEqual(['op']);
      expect(schema.properties!.op!.enum).toEqual(tool.ops.map((op) => op.op));
      const union = new Set(Object.keys(schema.properties!));
      for (const op of tool.ops) {
        expect(tool.description).toContain(`- ${op.op}: ${op.description}`);
        expect(op.parameters.properties).not.toHaveProperty('op');
        for (const field of op.fields) {
          expect(union.has(field.name)).toBe(true);
          expect(tool.description).toContain(field.name);
        }
      }
      expect(union.size).toBe(
        new Set(tool.ops.flatMap((op) => op.fields.map((field) => field.name))).size + 1,
      );
    }
  });

  it('shares one `as` field across every firestore_data op', () => {
    const tool = composeMcpTools().find((candidate) => candidate.name === 'firestore_data')!;
    for (const op of tool.ops) expect(op.fields.map((field) => field.name)).toContain('as');
    expect(tool.parameters.properties!.as).toHaveProperty('oneOf');
  });

  it('pins a fixed field out of the op schema and back into the handler call', async () => {
    const tools = composeMcpTools();
    for (const [name, service] of [
      ['firestore_rules', 'cloud.firestore'],
      ['storage_rules', 'firebase.storage'],
    ] as const) {
      const resolve = tools.find((tool) => tool.name === name)!.ops.find((op) => op.op === 'resolve')!;
      expect(resolve.handler).toBe('rules_resolve_modules');
      expect(resolve.fields.map((field) => field.name)).not.toContain('service');
      const rejected = await resolve.execute!({ source: "rules_version = '2+modules';\nservice other { }" });
      expect(rejected.ok).toBe(false);
      expect(rejected.summary).toContain(service);
    }
  });

  it('resolves every advertised forwarded operation in the browser dispatcher', async () => {
    const dispatch = buildSandboxDispatcher(initializeSandbox());
    for (const key of SANDBOX_OP_KEYS) {
      const [tool, op] = key.split('.') as [string, string];
      try {
        await dispatch(tool, op, {});
      } catch (error) {
        expect(error).not.toBeInstanceOf(UnknownToolError);
      }
    }
    await expect(dispatch('firestore_data', 'not_an_op', {})).rejects.toBeInstanceOf(UnknownToolError);
    await expect(dispatch('not_a_tool', 'get', {})).rejects.toBeInstanceOf(UnknownToolError);
  });

  it('advertises the same per-op schema the browser executes, minus pinned fields', () => {
    const sandbox = initializeSandbox();
    const binding: SandboxBinding = {
      sandbox,
      env: getInternalEnv(sandbox),
      resolveDb: () => getAdminFirestore(sandbox),
    };
    const advertised = new Map(
      composeMcpTools().flatMap((tool) => tool.ops.map((op) => [opKey(tool.name, op.op), op])),
    );
    for (const spec of toolOps('forwarded')) {
      const handler = SANDBOX_FACTORIES[spec.factory as keyof typeof SANDBOX_FACTORIES](binding).find(
        (candidate) => candidate.name === spec.handler,
      )!;
      const op = advertised.get(opKey(spec.tool, spec.op))!;
      expect(op.transport).toBe('forwarded');
      expect(op.description).toBe(spec.description ?? handler.description);
      const params = handler.parameters as { properties?: Record<string, unknown>; required?: string[] };
      expect(op.parameters.properties).toEqual(params.properties ?? {});
      expect(op.parameters.required ?? []).toEqual(params.required ?? []);
    }
  });
});

describe('tool call resolution', () => {
  const tools = composeMcpTools();
  const firestoreData = tools.find((tool) => tool.name === 'firestore_data')!;

  it('rejects a missing or unknown op with the valid ops', () => {
    const missing = resolveToolCall(firestoreData, { path: 'users/u1' });
    expect(missing.ok).toBe(false);
    if (missing.ok) return;
    expect(missing.result.summary).toBe(
      "firestore_data: 'op' is required; valid ops: get, list, set, add, update, delete, batch_write, query",
    );
    expect(missing.result.data).toEqual({
      error: 'unknown_op',
      tool: 'firestore_data',
      op: '',
      validOps: ['get', 'list', 'set', 'add', 'update', 'delete', 'batch_write', 'query'],
    });

    const unknown = resolveToolCall(firestoreData, { op: 'fetch', path: 'users/u1' });
    expect(unknown.ok).toBe(false);
    if (unknown.ok) return;
    expect(unknown.result.summary).toStartWith("firestore_data: unknown op 'fetch'; valid ops: get,");
    expect(unknown.result.data).toMatchObject({ error: 'unknown_op', op: 'fetch' });
  });

  it('rejects fields the op does not accept, naming the fields of the attempted op', () => {
    const call = resolveToolCall(firestoreData, { op: 'get', collection: 'users' });
    expect(call.ok).toBe(false);
    if (call.ok) return;
    expect(call.result.summary).toBe(
      "firestore_data.get: invalid fields: 'path' is required; 'collection' is not a field of op 'get'",
    );
    expect(call.result.data).toMatchObject({
      error: 'invalid_fields',
      tool: 'firestore_data',
      op: 'get',
      fields: [
        { name: 'path', required: true, type: 'string' },
        { name: 'as', required: false, type: 'union' },
      ],
    });
  });

  it('accepts a valid call and strips op from the handler arguments', () => {
    const call = resolveToolCall(firestoreData, { op: 'get', path: 'users/u1', as: { uid: 'u1' } });
    expect(call.ok).toBe(true);
    if (!call.ok) return;
    expect(call.op.op).toBe('get');
    expect(call.args).toEqual({ path: 'users/u1', as: { uid: 'u1' } });
  });

  it('validates enum fields per op rather than against the union', () => {
    const simulator = tools.find((tool) => tool.name === 'firestore_simulator')!;
    const read = resolveToolCall(simulator, { op: 'read', path: 'users/u1', method: 'create' });
    expect(read.ok).toBe(false);
    const execute = resolveToolCall(simulator, {
      op: 'execute',
      path: 'users/u1',
      method: 'create',
      auth: null,
      data: {},
    });
    expect(execute.ok).toBe(true);
  });
});
