/**
 * Tool family composition: the Node side lists tool metadata over MCP, the
 * browser side executes handlers, and the family records pin the names.
 * These tests pin the properties that must survive any change in how the
 * families are composed:
 *
 *  1. The records directory, the generated aggregate, and the two side
 *     factory maps agree on the set of families, and each record is pure.
 *  2. Each factory yields exactly the names its record pins, in record order.
 *  3. The listed order equals the pinned contract order, per transport.
 *  4. Every name the browser peer advertises resolves in its dispatcher.
 *  5. The metadata the Node side advertises (description and parameters)
 *     equals the metadata of the handlers the browser executes, per family.
 */
import { describe, expect, it } from 'bun:test';
import { readdirSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { initializeSandbox } from 'pyric/sandbox';
import { getInternalEnv } from 'pyric/sandbox/internal';
import { getAdminFirestore } from 'pyric/firestore';
import {
  buildSandboxDispatcher,
  SANDBOX_TOOL_NAMES,
  UnknownToolError,
} from '../../src/bridge/client/dispatch.js';
import {
  SANDBOX_HANDLER_FACTORIES,
  type SandboxBinding,
} from '../../src/bridge/client/tool-family-factories.js';
import {
  FORWARDED_METADATA_FACTORIES,
  IN_PROCESS_HANDLER_FACTORIES,
} from '../../src/bridge/server/tool-family-factories.js';
import { getSandboxToolMetadata } from '../../src/bridge/server/tool-metadata.js';
import {
  DEFAULT_MCP_FORWARDED_TOOL_NAMES,
  DEFAULT_MCP_IN_PROCESS_TOOL_NAMES,
  getDefaultMcpToolSurface,
} from '../../src/bridge/server/mcp-contract.js';
import { assertExactToolNames, toolFamilies } from '../../src/bridge/tool-families.js';
import { TOOL_FAMILIES } from '../../src/bridge/tool-families.generated.js';

const bridgeDir = resolve(import.meta.dir, '../../src/bridge');
const recordsDir = resolve(bridgeDir, 'tool-family-records');

function importLines(path: string): string[] {
  return readFileSync(path, 'utf8')
    .split('\n')
    .filter((line) => /^\s*import\b/.test(line));
}

const stub = () => {
  throw new Error('stub resolver must not run');
};

describe('tool family records', () => {
  it('generated aggregate matches the records directory in filename order', () => {
    const files = readdirSync(recordsDir)
      .filter((file) => file.endsWith('.ts'))
      .sort();
    expect(TOOL_FAMILIES.map((family) => family.key)).toEqual(
      files.map((file) => file.replace(/\.ts$/, '')),
    );
    expect(readFileSync(resolve(bridgeDir, 'tool-families.generated.ts'), 'utf8')).toStartWith(
      '// Generated by scripts/generate-tool-family-registry.ts. Do not edit.',
    );
  });

  it('each record imports only the contract type, so either side can load it', () => {
    for (const file of readdirSync(recordsDir)) {
      expect(importLines(resolve(recordsDir, file))).toEqual([
        "import type { ToolFamilyRecord } from '../tool-families.js';",
      ]);
    }
  });

  it('the contract module imports only the generated aggregate', () => {
    expect(importLines(resolve(bridgeDir, 'tool-families.ts'))).toEqual([
      "import { TOOL_FAMILIES } from './tool-families.generated.js';",
    ]);
  });

  it('keys, orders and tool names are unique and families sort by order', () => {
    const families = [...toolFamilies('forwarded'), ...toolFamilies('in-process')];
    expect(families.length).toBe(TOOL_FAMILIES.length);
    expect(new Set(families.map((family) => family.key)).size).toBe(families.length);
    expect(new Set(families.map((family) => family.order)).size).toBe(families.length);
    const names = families.flatMap((family) => family.tools);
    expect(new Set(names).size).toBe(names.length);
    for (const transport of ['forwarded', 'in-process'] as const) {
      const orders = toolFamilies(transport).map((family) => family.order);
      expect(orders).toEqual([...orders].sort((a, b) => a - b));
    }
  });

  it('every family has exactly one factory on each side that serves its transport', () => {
    const forwarded = toolFamilies('forwarded')
      .map((family) => family.key)
      .sort();
    const inProcess = toolFamilies('in-process')
      .map((family) => family.key)
      .sort();
    expect(Object.keys(FORWARDED_METADATA_FACTORIES).sort()).toEqual(forwarded);
    expect(Object.keys(SANDBOX_HANDLER_FACTORIES).sort()).toEqual(forwarded);
    expect(Object.keys(IN_PROCESS_HANDLER_FACTORIES).sort()).toEqual(inProcess);
  });

  it('each factory yields exactly the names its record pins, in record order', () => {
    for (const family of toolFamilies('forwarded')) {
      const names = FORWARDED_METADATA_FACTORIES[family.key](stub as never).map((h) => h.name);
      expect(names).toEqual([...family.tools]);
    }
    for (const family of toolFamilies('in-process')) {
      const names = IN_PROCESS_HANDLER_FACTORIES[family.key](undefined).map((h) => h.name);
      expect(names).toEqual([...family.tools]);
    }
  });

  it('assertExactToolNames fails closed naming the label and both lists', () => {
    expect(() => assertExactToolNames('x', ['b', 'a'], ['a', 'b'])).not.toThrow();
    expect(() => assertExactToolNames('forwarded sandbox tools', ['a', 'b'], ['a'])).toThrow(
      /forwarded sandbox tools drifted from the default MCP contract\nexpected: a\nactual: {3}a, b/,
    );
    expect(() => assertExactToolNames('in-process tools', ['a'], ['a', 'c'])).toThrow(
      'in-process tools drifted',
    );
  });
});

describe('tool family composition', () => {
  it('lists forwarded and in-process tools in the pinned contract order', () => {
    const surface = getDefaultMcpToolSurface();
    expect(surface.forwarded.map((tool) => tool.name)).toEqual([
      ...DEFAULT_MCP_FORWARDED_TOOL_NAMES,
    ]);
    expect(surface.inProcess.map((tool) => tool.name)).toEqual([
      ...DEFAULT_MCP_IN_PROCESS_TOOL_NAMES,
    ]);
  });

  it('resolves every advertised sandbox tool name in the browser dispatcher', async () => {
    const dispatch = buildSandboxDispatcher(initializeSandbox());
    for (const name of SANDBOX_TOOL_NAMES) {
      try {
        await dispatch(name, {});
      } catch (error) {
        expect(error).not.toBeInstanceOf(UnknownToolError);
      }
    }
    await expect(dispatch('not_a_tool', {})).rejects.toBeInstanceOf(UnknownToolError);
  });

  it('advertises the same description and parameters the browser executes, per family', () => {
    const sandbox = initializeSandbox();
    const binding: SandboxBinding = {
      sandbox,
      env: getInternalEnv(sandbox),
      resolveDb: () => getAdminFirestore(sandbox),
    };
    const advertised = new Map(getSandboxToolMetadata().map((tool) => [tool.name, tool]));
    for (const family of toolFamilies('forwarded')) {
      const handlers = SANDBOX_HANDLER_FACTORIES[family.key](binding);
      expect(handlers.map((handler) => handler.name)).toEqual([...family.tools]);
      for (const handler of handlers) {
        const tool = advertised.get(handler.name)!;
        expect(tool.description).toBe(handler.description);
        expect(tool.parameters).toEqual(handler.parameters as Record<string, unknown>);
      }
    }
  });
});
