/**
 * `pyric dev` SDK bundler — builds the browser-standalone ESM bundles the
 * import map points `firebase/*` at (`/__pyric/sdk/*.js`).
 *
 * esbuild (a real dependency — the `pyric` bin runs under node via npx, so
 * Bun.build is unavailable) bundles the wrapper entries in `entries/` with
 * SPLITTING so the shared runtime chunk holds exactly ONE sandbox per page:
 * both the auth and firestore bundles must close over the same instance.
 *
 * Three bundler plugins make pyric browser-standalone:
 *   - `pyric/*` resolver — resolves `pyric/...` specifiers from THIS package's
 *     dependency context (entries may live in a temp dir that lacks pyric).
 *   - `firebase/*` peer stubs — pyric's PROD backends import the real SDK; the
 *     sandbox-served page never takes those code paths, so each `firebase/x`
 *     resolves to an INERT proxy module (every member returns the proxy on
 *     get/call/construct — it never throws, because pyric builds its prod
 *     representations EAGERLY even on the sandbox path, e.g. `where()` calls
 *     `fb.where(...)`). The export-name list is GENERATED by scanning pyric's
 *     dist — both `import/export { … } from 'firebase/x'` named bindings AND
 *     `import * as fb` namespace-member accesses (`fb.where`, …) — so it cannot
 *     drift when pyric does. See `collectFirebaseBindings` / `stubModuleSource`.
 *   - node-builtin shims (`url`/`fs`/`path`) — still load-bearing despite the
 *     Phase U resolver split: `pyric/firestore` re-exports the agent tool
 *     factories (`firestore/index.js` → `rules/tools.js`), and tools.js
 *     statically imports the NODE module resolver. The browser path never
 *     calls into disk reads, so benign shims suffice. Droppable only when
 *     pyric breaks that static chain (tracked in #553).
 *
 * Output is cached under `~/.pyric/serve-cache/<pyric-version>-<hash>/` so a
 * warm `pyric dev` start skips the (~seconds) bundle step. `--no-cache`
 * bypasses.
 */
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, readdirSync, existsSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as esbuild from 'esbuild';

/** Modules the import map serves. Keys are the bare specifiers app code uses. */
export const SDK_MODULES = [
  'firebase/ai',
  'firebase/app',
  'firebase/auth',
  'firebase/firestore',
  'firebase/database',
  'firebase/storage',
] as const;

/**
 * The wrapper entries shipped with @pyric/cli, located relative to this
 * module: compiled `.js` siblings when running from dist (npx install), `.ts`
 * sources in the workspace (tests / dev). esbuild bundles either.
 */
export function defaultSdkEntries(): Record<string, string> {
  const here = dirname(fileURLToPath(import.meta.url));
  const pick = (name: string): string => {
    const js = join(here, 'entries', `${name}.js`);
    if (existsSync(js)) return js;
    const ts = join(here, 'entries', `${name}.ts`);
    if (existsSync(ts)) return ts;
    throw new Error(`pyric dev: missing SDK entry '${name}' next to ${here}`);
  };
  return {
    ai: pick('ai'),
    app: pick('app'),
    auth: pick('auth'),
    firestore: pick('firestore'),
    database: pick('database'),
    storage: pick('storage'),
    init: pick('init'),
  };
}

/**
 * Resolve the built Studio app dir (the plugin's `ui` option + the CLI's
 * `--ui`). Reached by file path so @pyric/cli never imports `@pyric/studio`:
 * the packaged location (`dist/serve/studio-ui`, copied at build) or, in the
 * monorepo, the sibling studio build. Null when neither exists. The standalone
 * binary embeds these same bytes instead (see `standalone-assets.ts`).
 */
export function resolveStudioUiDir(): string | null {
  const candidates = [
    new URL('./studio-ui/', import.meta.url),
    new URL('../../../studio/dist/app/', import.meta.url),
  ];
  for (const candidate of candidates) {
    const dir = fileURLToPath(candidate);
    if (existsSync(dir)) return dir;
  }
  return null;
}

/**
 * Resolve the built playground app dir. `pyric dev --ui` embeds this as the
 * first-class Studio Playground tab under `/__pyric/playground/`.
 */
export function resolvePlaygroundUiDir(): string | null {
  const candidates = [
    new URL('./playground-ui/', import.meta.url),
  ];
  for (const candidate of candidates) {
    const dir = fileURLToPath(candidate);
    if (existsSync(dir)) return dir;
  }
  return null;
}

/**
 * Resolve the built docs site dir (site-docs). `pyric dev --ui` embeds it so
 * the Studio Docs tab has local docs without the hosted site. Built with base
 * `/__pyric/ui/` (see scripts/build.sh) so every page/asset/twin URL resolves
 * under the CLI mount: pages at `/__pyric/ui/docs/<slug>/`, assets at
 * `/__pyric/ui/_astro/*`, the search index at `/__pyric/ui/docs/index.json`,
 * and the shell chrome's tab links back at `/__pyric/ui/<tab>`. The dir holds
 * the site-docs `dist/` verbatim: `docs/`, `_astro/`, `index.html`, `llms.txt`.
 */
export function resolveDocsUiDir(): string | null {
  const candidates = [
    new URL('./docs-ui/', import.meta.url),
  ];
  for (const candidate of candidates) {
    const dir = fileURLToPath(candidate);
    if (existsSync(dir)) return dir;
  }
  return null;
}

// ─── pyric dist discovery ─────────────────────────────────────────────

/** Locate the installed pyric package root (works in the workspace and when
 *  @pyric/cli is npm-installed — pyric is a direct dependency). */
export function pyricPackageRoot(): string {
  // Resolve a real exported subpath, then walk up to the package root.
  const entry = fileURLToPath(import.meta.resolve('pyric/firestore'));
  let dir = dirname(entry);
  while (dir.includes(sep) && !existsSync(join(dir, 'package.json'))) {
    dir = dirname(dir);
  }
  const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')) as { name?: string };
  if (pkg.name !== 'pyric') {
    throw new Error(`pyric dev: expected to resolve the pyric package, found '${pkg.name}' at ${dir}`);
  }
  return dir;
}

export function pyricVersion(root: string = pyricPackageRoot()): string {
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')) as { version?: string };
  return pkg.version ?? '0.0.0';
}

// ─── firebase/* stub generation ───────────────────────────────────────

/**
 * Scan pyric's dist for every binding it pulls from each `firebase/<mod>` peer,
 * so the stub module can export all of them:
 *   - named imports / re-exports (`import { X }` / `export { X } from`), which
 *     hard-fail the build when missing; AND
 *   - namespace-import members (`import * as fb` → `fb.where`, `fb.query`, …).
 *     These MUST be covered too: pyric builds its prod representation eagerly
 *     even on the sandbox path (e.g. `where()` calls `fb.where(...)`), so a
 *     missing namespace member is hit at runtime ("(void 0) is not a function").
 * Scanning the COMPILED dist means TS type-only accesses are already erased.
 */
export function collectFirebaseBindings(distDir: string): Map<string, Set<string>> {
  const bindings = new Map<string, Set<string>>();
  const files = readdirSync(distDir, { recursive: true }) as string[];
  const re = /(?:import|export)\s*\{([^}]*)\}\s*from\s*['"]firebase\/([a-z-]+)['"]/g;
  // Namespace imports: `import * as fb from 'firebase/x'`. pyric accesses these
  // peers via `fb.<member>` and — crucially — builds the prod representation
  // EAGERLY even on the sandbox path (e.g. `where()` calls `fb.where(...)` to
  // populate `_fbFilter`, which the sandbox path then ignores). So `fb.<member>`
  // IS touched in a sandbox-served page; the stub MUST export every accessed
  // member or the call hits `undefined` ("(void 0) is not a function"). We scan
  // the COMPILED dist, so TS type-only accesses (`fb.WhereFilterOp`) are already
  // erased and don't pollute the set.
  const nsRe = /import\s*\*\s*as\s+([A-Za-z_$][\w$]*)\s+from\s*['"]firebase\/([a-z-]+)['"]/g;
  for (const rel of files) {
    if (!rel.endsWith('.js')) continue;
    const source = readFileSync(join(distDir, rel), 'utf8');
    for (const m of source.matchAll(re)) {
      const mod = `firebase/${m[2]}`;
      const set = bindings.get(mod) ?? new Set<string>();
      for (const piece of m[1]!.split(',')) {
        // `X as Y` — the EXPORT name (X) is what the stub must provide.
        const name = piece.trim().split(/\s+as\s+/)[0]?.trim();
        if (name) set.add(name);
      }
      bindings.set(mod, set);
    }
    for (const m of source.matchAll(nsRe)) {
      const alias = m[1]!;
      const mod = `firebase/${m[2]}`;
      const set = bindings.get(mod) ?? new Set<string>();
      const memberRe = new RegExp(`\\b${alias}\\.([A-Za-z_$][\\w$]*)`, 'g');
      for (const mm of source.matchAll(memberRe)) set.add(mm[1]!);
      bindings.set(mod, set);
    }
  }
  return bindings;
}

/**
 * Synthesize the stub module source for one `firebase/<mod>` specifier.
 *
 * The stub is an INERT proxy: every access returns the proxy, every call /
 * construct returns the proxy (NOT a throw). pyric builds prod representations
 * eagerly even on the sandbox path — `where()` calls `fb.where(...)`, `or()`
 * calls `fb.or(...)`, `new fb.Bytes()` — and the SANDBOX path then ignores the
 * result. A throwing stub would break those constructors; an inert one lets
 * them produce a harmless sentinel that's never used. The sandbox-served page
 * never takes the real prod path, so the inert result is never consumed. (The
 * loud provenance banner remains the "this is not the real SDK" signal.)
 */
export function stubModuleSource(_specifier: string, names: ReadonlySet<string>): string {
  const deny = `const deny = new Proxy(function () {}, {
  apply() { return deny; },
  construct() { return deny; },
  get() { return deny; },
});
export default deny;`;
  const named = [...names]
    .map((n) => `export const ${n} = deny;`)
    .join('\n');
  return `${deny}\n${named}\n`;
}

// ─── plugins ──────────────────────────────────────────────────────────

function firebaseStubPlugin(bindings: Map<string, Set<string>>): esbuild.Plugin {
  return {
    name: 'pyric-serve-firebase-stub',
    setup(build) {
      build.onResolve({ filter: /^firebase\// }, (args) => ({
        path: args.path,
        namespace: 'pyric-firebase-stub',
      }));
      build.onLoad({ filter: /.*/, namespace: 'pyric-firebase-stub' }, (args) => ({
        contents: stubModuleSource(args.path, bindings.get(args.path) ?? new Set()),
        loader: 'js',
      }));
    },
  };
}

/** Resolve `pyric/*` specifiers from THIS package's own dependency context
 *  (`import.meta.resolve`) rather than from the entry file's directory —
 *  entries may live in a temp dir or the user's project, neither of which
 *  has pyric in scope; @pyric/cli always does (direct dependency). */
function pyricResolvePlugin(): esbuild.Plugin {
  return {
    name: 'pyric-serve-resolve-pyric',
    setup(build) {
      build.onResolve({ filter: /^pyric(\/|$)/ }, (args) => ({
        path: fileURLToPath(import.meta.resolve(args.path)),
      }));
    },
  };
}

/** The node builtins pyric's browser graph reaches for (via the rules module
 *  resolver). Bare and `node:`-prefixed both match. */
export const NODE_BUILTIN_RE = /^(node:)?(url|fs|path)$/;

/** Benign browser shim SOURCE per builtin (see header — droppable only when
 *  pyric breaks the `firestore/index → rules/tools → modules/resolver` static
 *  chain, #553). Exported so the Vite plugin (`./vite`) reuses the SAME shims
 *  through its own resolveId/load + optimizeDeps esbuild pass, instead of
 *  re-deriving them. */
export const NODE_BUILTIN_SHIMS: Record<string, string> = {
  fs: `const no = () => { throw new Error('pyric dev: fs is not available in the browser'); };
export const readFileSync = no; export const existsSync = () => false;
export const readdirSync = no; export const writeFileSync = no; export const mkdirSync = no;
export default { readFileSync, existsSync, readdirSync, writeFileSync, mkdirSync };`,
  url: `export const fileURLToPath = (u) => String(u).replace('file://', '');
export const pathToFileURL = (p) => new URL('file://' + p);
export default { fileURLToPath, pathToFileURL };`,
  path: `export const join = (...p) => p.join('/');
export const dirname = (p) => p.split('/').slice(0, -1).join('/') || '/';
export const resolve = (...p) => p.join('/');
export const basename = (p) => p.split('/').pop() ?? '';
export default { join, dirname, resolve, basename };`,
};

function nodeShimPlugin(): esbuild.Plugin {
  return {
    name: 'pyric-serve-node-shims',
    setup(build) {
      build.onResolve({ filter: NODE_BUILTIN_RE }, (args) => ({
        path: args.path.replace(/^node:/, ''),
        namespace: 'pyric-node-shim',
      }));
      build.onLoad({ filter: /.*/, namespace: 'pyric-node-shim' }, (args) => ({
        contents: NODE_BUILTIN_SHIMS[args.path]!,
        loader: 'js',
      }));
    },
  };
}

// ─── cache ────────────────────────────────────────────────────────────

export interface BundleOptions {
  /** Entry files (the wrapper modules in `entries/`), keyed by the served
   *  basename (`auth` → `/__pyric/sdk/auth.js`). */
  entries: Record<string, string>;
  /** Bypass + overwrite the cache. */
  noCache?: boolean;
  /** Override the cache root (tests). Default `~/.pyric/serve-cache`. */
  cacheRoot?: string;
  minify?: boolean;
}

export interface BundleResult {
  outDir: string;
  /** Served basename → absolute file path (entry bundles + shared chunks). */
  files: string[];
  cached: boolean;
}

/** Bump when bundler logic changes in a way that must invalidate caches. */
const BUNDLER_REV = 5; // 5: app owns FirebaseError; all Firebase stubs are uniformly inert

export function cacheKey(opts: BundleOptions, version: string): string {
  const h = createHash('sha256');
  h.update(`rev${BUNDLER_REV}`);
  h.update(version);
  // Hash the WHOLE local graph, not just the entry files: entries import
  // sibling modules (runtime, auth-helper-*) whose edits must invalidate the
  // cache — hashing entries alone served stale bundles (caught by the P3
  // browser gate). pyric's own dist is covered by the version component.
  const dirs = new Set<string>();
  for (const [name, file] of Object.entries(opts.entries).sort()) {
    h.update(name);
    h.update(readFileSync(file, 'utf8'));
    dirs.add(dirname(file));
  }
  for (const dir of [...dirs].sort()) {
    for (const sibling of (readdirSync(dir) as string[]).sort()) {
      if (!sibling.endsWith('.ts') && !sibling.endsWith('.js')) continue;
      h.update(sibling);
      h.update(readFileSync(join(dir, sibling), 'utf8'));
    }
  }
  return `${version}-${h.digest('hex').slice(0, 12)}`;
}

// ─── the bundle step ──────────────────────────────────────────────────

export async function bundleSdk(opts: BundleOptions): Promise<BundleResult> {
  const root = pyricPackageRoot();
  const version = pyricVersion(root);
  const key = cacheKey(opts, version);
  const cacheRoot = opts.cacheRoot ?? join(homedir(), '.pyric', 'serve-cache');
  const outDir = join(cacheRoot, key, 'sdk');

  if (!opts.noCache && existsSync(join(outDir, '.complete'))) {
    const files = (readdirSync(outDir) as string[])
      .filter((f) => f.endsWith('.js'))
      .map((f) => join(outDir, f));
    return { outDir, files, cached: true };
  }

  mkdirSync(outDir, { recursive: true });
  const bindings = collectFirebaseBindings(join(root, 'dist'));
  const result = await esbuild.build({
    entryPoints: Object.fromEntries(
      Object.entries(opts.entries).map(([name, file]) => [name, file]),
    ),
    outdir: outDir,
    bundle: true,
    format: 'esm',
    platform: 'browser',
    splitting: true,
    sourcemap: 'linked',
    minify: opts.minify ?? true,
    logLevel: 'silent',
    // Provenance: any stack frame or "view source" into these bundles must
    // self-identify as the sandbox shim, not the real Firebase SDK.
    chunkNames: 'pyric-sandbox-[hash]',
    banner: {
      js: '/* pyric dev: pyric sandbox shim serving firebase/* — NOT the real Firebase SDK */',
    },
    plugins: [pyricResolvePlugin(), nodeShimPlugin(), firebaseStubPlugin(bindings)],
  });
  if (result.errors.length > 0) {
    throw new Error(
      `pyric dev: SDK bundle failed:\n${result.errors.map((e) => e.text).join('\n')}`,
    );
  }
  writeFileSync(join(outDir, '.complete'), new Date().toISOString());
  const files = (readdirSync(outDir) as string[])
    .filter((f) => f.endsWith('.js'))
    .map((f) => join(outDir, f));
  return { outDir, files, cached: false };
}

// ─── the SharedWorker bundle (Phase 3c.A) ─────────────────────────────────

/**
 * Locate the SharedWorker entry (`worker/entry.ts`) — compiled `.js` sibling
 * from dist, `.ts` source in the workspace. Same dual-resolution as
 * `defaultSdkEntries`.
 */
export function workerEntryPath(): string {
  const here = dirname(fileURLToPath(import.meta.url));
  const js = join(here, 'worker', 'entry.js');
  if (existsSync(js)) return js;
  const ts = join(here, 'worker', 'entry.ts');
  if (existsSync(ts)) return ts;
  throw new Error(`pyric dev: missing SharedWorker entry next to ${here}`);
}

export interface WorkerBundleOptions {
  /** Where to write `worker.js` — normally the SDK bundle's `outDir` so the
   *  existing `/__pyric/sdk/<file>` route serves it with no extra wiring. */
  outDir: string;
  /** Bypass + overwrite the cached worker bundle. */
  noCache?: boolean;
  minify?: boolean;
}

/**
 * Content hash of the worker source graph + pyric version. The worker bundle
 * shares the SDK `outDir` (keyed by the SDK entries), which does NOT cover the
 * `worker/` sources — so the worker bundle carries its OWN content marker: a
 * worker-only edit changes this hash and forces a rebuild even when the SDK
 * cache is warm. (pyric library changes are covered by the version component,
 * the same model `bundleSdk` uses.)
 */
export function workerSourceHash(): string {
  const h = createHash('sha256');
  h.update(`rev${BUNDLER_REV}`);
  h.update(pyricVersion());
  const dir = dirname(workerEntryPath());
  for (const f of (readdirSync(dir) as string[]).sort()) {
    if (!f.endsWith('.ts') && !f.endsWith('.js')) continue;
    h.update(f);
    h.update(readFileSync(join(dir, f), 'utf8'));
  }
  return h.digest('hex').slice(0, 16);
}

/**
 * Bundle the SharedWorker entry into a single classic worker script served at
 * `/__pyric/sdk/worker.js`.
 *
 * WHY A SEPARATE BUILD (not part of `bundleSdk`'s splitting graph): a
 * SharedWorker script is loaded by URL into its OWN realm — it cannot share
 * the page's runtime chunk. So it is bundled standalone: `splitting: false`,
 * `format: 'iife'` (the client opens it with `new SharedWorker(url, { type:
 * 'classic' })`), everything inlined into one file. It reuses the same three
 * browser-standalone plugins as the SDK bundle (pyric-resolve + node-shims +
 * firebase-stub) so `pyric/*`, node builtins, and the `firebase/*` peer stubs
 * resolve identically.
 *
 * NOTE: the worker legitimately holds the whole sandbox engine — it IS the
 * backend — so this bundle is large, but it loads ONCE per origin (not per
 * page). Trimming node/admin dead paths is tracked as Phase 3b.
 *
 * The `.worker-complete` marker is independent of `bundleSdk`'s `.complete`.
 * Folding the worker source graph into `bundleSdk`'s cache key (so a
 * worker-only edit invalidates the shared `outDir`) lands with the serve
 * wiring in 3c.E; until then callers pass `noCache` when iterating.
 */
export async function bundleWorker(opts: WorkerBundleOptions): Promise<string> {
  const outFile = join(opts.outDir, 'worker.js');
  const marker = join(opts.outDir, '.worker-complete');
  const hash = workerSourceHash();
  if (
    !opts.noCache &&
    existsSync(outFile) &&
    existsSync(marker) &&
    readFileSync(marker, 'utf8') === hash
  ) {
    return outFile;
  }

  mkdirSync(opts.outDir, { recursive: true });
  const root = pyricPackageRoot();
  const bindings = collectFirebaseBindings(join(root, 'dist'));
  const result = await esbuild.build({
    entryPoints: [workerEntryPath()],
    outfile: outFile,
    bundle: true,
    format: 'iife',
    platform: 'browser',
    splitting: false,
    sourcemap: 'linked',
    minify: opts.minify ?? true,
    logLevel: 'silent',
    // Bake the build hash so the worker can report its version (staleness
    // guard): the page warns when a still-running OLD worker is older than the
    // served bundle. Matches the `<meta name="pyric-worker-v">` value.
    define: { __PYRIC_WORKER_VERSION__: JSON.stringify(hash) },
    banner: {
      js: '/* pyric dev: SharedWorker sandbox host serving firebase/* — NOT the real Firebase SDK */',
    },
    plugins: [pyricResolvePlugin(), nodeShimPlugin(), firebaseStubPlugin(bindings)],
  });
  if (result.errors.length > 0) {
    throw new Error(
      `pyric dev: SharedWorker bundle failed:\n${result.errors.map((e) => e.text).join('\n')}`,
    );
  }
  writeFileSync(marker, hash);
  return outFile;
}
