// Generated by packages/conformance/src/rules-module-capabilities.ts. Do not edit.
// Source: packages/conformance/rules-language/firestore.json accepted constructs.
export const FIRESTORE_DIRECT_FUNCTIONS = ["exists", "get"] as const;
export const FIRESTORE_METHODS = ["addedKeys", "affectedKeys", "bind", "changedKeys", "concat", "date", "day", "dayOfWeek", "dayOfYear", "diff", "difference", "distance", "get", "hasAll", "hasAny", "hasOnly", "hours", "intersection", "join", "keys", "latitude", "longitude", "lower", "matches", "minutes", "month", "nanos", "removeAll", "removedKeys", "replace", "seconds", "size", "split", "time", "toBase64", "toHexString", "toMillis", "toSet", "toUtf8", "trim", "unchangedKeys", "union", "upper", "values", "year"] as const;
export const FIRESTORE_NAMESPACE_METHODS = {
  cast: ["float", "int", "path", "string"] as const,
  duration: ["abs", "time", "value"] as const,
  hashing: ["crc32", "crc32c", "md5", "sha256"] as const,
  latlng: ["value"] as const,
  math: ["abs", "ceil", "floor", "isNaN", "pow", "round", "sqrt"] as const,
  timestamp: ["date", "value"] as const,
} as const;
