// Generated by packages/pyric/scripts/inline-stdlib.ts. Do not edit.
// Directory convention: storage/* is Storage-only; auth and membership
// are cross-service; every other bundled module is Firestore-only.
export type BundledRulesService = 'cloud.firestore' | 'firebase.storage';
export const STDLIB_SERVICE_CONTRACTS = {
  "atomic": ["cloud.firestore"],
  "auth": ["cloud.firestore","firebase.storage"],
  "content": ["cloud.firestore"],
  "counters": ["cloud.firestore"],
  "geometry": ["cloud.firestore"],
  "joining": ["cloud.firestore"],
  "lifecycle": ["cloud.firestore"],
  "lobby": ["cloud.firestore"],
  "membership": ["cloud.firestore","firebase.storage"],
  "spaces": ["cloud.firestore"],
  "state": ["cloud.firestore"],
  "storage/metadata": ["firebase.storage"],
  "storage/objects": ["firebase.storage"],
  "storage/time": ["firebase.storage"],
  "storage/uploads": ["firebase.storage"],
  "timing": ["cloud.firestore"],
  "transitions": ["cloud.firestore"],
  "turns": ["cloud.firestore"],
  "validation": ["cloud.firestore"],
} as const satisfies Readonly<Record<string, readonly BundledRulesService[]>>;
export const STDLIB_SERVICE_CONTRACT_MODULES = Object.freeze(
  Object.keys(STDLIB_SERVICE_CONTRACTS).sort(),
);
