// Generated by packages/pyric/scripts/inline-stdlib.ts. Do not edit.
// Source: each module-owned @pyric-services and @pyric-evidence declaration.
export type BundledRulesService = 'cloud.firestore' | 'firebase.storage';
export const STDLIB_SERVICE_CONTRACTS = {
  "atomic": ["cloud.firestore"],
  "auth": ["cloud.firestore","firebase.storage"],
  "content": ["cloud.firestore"],
  "counters": ["cloud.firestore"],
  "geometry": ["cloud.firestore"],
  "joining": ["cloud.firestore"],
  "lifecycle": ["cloud.firestore"],
  "lobby": ["cloud.firestore"],
  "membership": ["cloud.firestore","firebase.storage"],
  "spaces": ["cloud.firestore"],
  "state": ["cloud.firestore"],
  "storage/metadata": ["firebase.storage"],
  "storage/objects": ["firebase.storage"],
  "storage/time": ["firebase.storage"],
  "storage/uploads": ["firebase.storage"],
  "timing": ["cloud.firestore"],
  "transitions": ["cloud.firestore"],
  "turns": ["cloud.firestore"],
  "validation": ["cloud.firestore"],
} as const satisfies Readonly<Record<string, readonly BundledRulesService[]>>;
export const STDLIB_SERVICE_CONTRACT_MODULES = Object.freeze(
  Object.keys(STDLIB_SERVICE_CONTRACTS).sort(),
);
export const STDLIB_MODULE_EVIDENCE = {
  "atomic": [],
  "auth": ["storage-rules#125","firestore-rules#189"],
  "content": [],
  "counters": [],
  "geometry": [],
  "joining": [],
  "lifecycle": [],
  "lobby": [],
  "membership": ["storage-rules#125","firestore-rules#189"],
  "spaces": [],
  "state": [],
  "storage/metadata": ["storage-rules#132"],
  "storage/objects": ["storage-rules#132"],
  "storage/time": ["storage-rules#132"],
  "storage/uploads": ["storage-rules#132"],
  "timing": [],
  "transitions": [],
  "turns": [],
  "validation": [],
} as const satisfies Readonly<Record<string, readonly string[]>>;
