import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

/**
 * The docs content collection. One markdown file per page under
 * src/content/docs/; the file name is the route slug
 * (`pyric-tools.md` → /docs/pyric-tools).
 *
 * Almost every file is GENERATED by scripts/port-content.ts from the
 * four package docs trees (packages/{pyric,pyric-admin,pyric-tools,ui}/
 * docs) — edit the source trees, not these files. rhythm.md is the one
 * hand-written page.
 *
 * Front matter:
 * - `title`    — page title (llms.txt, index.json, <title>).
 * - `navLabel` — shorter nav-item label; defaults to `title`.
 * - `group`    — nav top level: the source package / subtree. One
 *                disclosure per group in the sidebar.
 * - `section`  — nav group's inner heading (the source tree's subdir:
 *                Tutorials / How-to / Reference / …). Empty for a
 *                group's overview (README) page.
 * - `order`    — sort key across the whole nav.
 * - `description` — one-liner used by llms.txt and index.json.
 * - `internal` — excluded from nav, llms.txt, and index.json (the
 *                /docs/_rhythm audit page). Still gets a route + twin.
 * - `slug`     — route slug override. Needed for /docs/_rhythm: the
 *                glob loader skips `_`-prefixed files, so the source
 *                file is rhythm.md with `slug: _rhythm`.
 */
const docs = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/docs' }),
  schema: z.object({
    title: z.string(),
    navLabel: z.string().optional(),
    group: z.string(),
    section: z.string().default(''),
    order: z.number(),
    description: z.string().optional(),
    internal: z.boolean().default(false),
    slug: z.string().optional(),
  }),
});

export const collections = { docs };
