import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser = await chromium.launch();
try {
 const context = await browser.newContext();
 const request = await context.newPage();
 const origin = process.env.KIN_URL ?? 'http://127.0.0.1:5227/';
 await request.goto(origin);
 assert.equal(await request.locator('input[type=password]').count(),0);
 await request.getByLabel('Email',{exact:true}).fill('emma@kin.example');
 await request.getByRole('button',{name:'Send sign-in link',exact:true}).click();
 const mail = request.getByRole('link',{name:'Open sign-in link'});
 const url = await mail.getAttribute('href');
 await request.evaluate(()=>localStorage.removeItem('kin:sign-in-email'));
 const [callback] = await Promise.all([context.waitForEvent('page'),mail.click()]);
 await callback.getByLabel('Email',{exact:true}).fill('wrong@kin.example');
 await callback.getByRole('button',{name:'Confirm & sign in'}).click();
 await callback.getByRole('alert').waitFor();
 await callback.getByLabel('Email',{exact:true}).fill('emma@kin.example');
 await callback.getByRole('button',{name:'Confirm & sign in'}).click();
 await callback.getByRole('heading',{name:'Our family',exact:true}).waitFor();
 assert.equal(new URL(callback.url()).search,'');
 await callback.goto(url);
 await callback.getByLabel('Email',{exact:true}).fill('emma@kin.example');
 await callback.getByRole('button',{name:'Confirm & sign in'}).click();
 await callback.getByRole('alert').waitFor();
 await callback.getByRole('button',{name:'Request a new link'}).click();
 await callback.getByRole('button',{name:'Send sign-in link',exact:true}).waitFor();
 await callback.screenshot({path:'/tmp/kin-email-signin.png'});
 await context.close();
 const fallback = await browser.newPage();
 await fallback.addInitScript(()=>{globalThis.__PYRIC_FORCE_INPAGE__=true});
 await fallback.goto(origin);
 await fallback.getByLabel('Email',{exact:true}).fill('sam@kin.example');
 await fallback.getByRole('button',{name:'Send sign-in link',exact:true}).click();
 await fallback.getByRole('link',{name:'Open sign-in link'}).click();
 await fallback.getByRole('heading',{name:'Our family',exact:true}).waitFor();
 console.log('PASS email confirmation, mismatch, single-use replay, recovery, and in-page fallback');
} finally { await browser.close(); }
