import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch();
try{
 const context=await browser.newContext({viewport:{width:390,height:844}});
 const request=await context.newPage();
 await request.goto(process.env.KIN_URL??'http://127.0.0.1:5227/');
 await request.getByLabel('Email',{exact:true}).fill('emma@kin.example');
 await request.getByRole('button',{name:'Send sign-in link',exact:true}).click();
 const [page]=await Promise.all([context.waitForEvent('page'),request.getByRole('link',{name:'Open sign-in link'}).click()]);
 await page.getByRole('heading',{name:'Our family',exact:true}).waitFor();
 await page.evaluate(()=>location.hash='compose');
 await page.getByLabel('Title',{exact:true}).fill('Keep this draft');
 const open=page.getByRole('button',{name:'Toggle navigation'});
 await open.click();
 await page.mouse.click(360,350);
 assert.equal(await page.locator('.sidebar.open').count(),0,'Outside tap must dismiss navigation');
 await open.click();
 await page.getByRole('button',{name:'Close navigation',exact:true}).click();
 assert.equal(await page.locator('.sidebar.open').count(),0);
 await open.click();
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('.sidebar.open').count(),0);
 assert.equal(await open.evaluate(el=>el===document.activeElement),true,'Focus returns to menu toggle');
 assert.equal(await page.getByLabel('Title',{exact:true}).inputValue(),'Keep this draft');
 await page.evaluate(()=>location.hash='feed');
 await page.getByRole('heading',{name:'Our family',exact:true}).waitFor();
 await open.click();
 await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('link',{name:'Family',exact:true}).click();
 assert.equal(await page.locator('.sidebar.open').count(),0,'Selecting the current route also dismisses navigation');
 await page.screenshot({path:'/tmp/kin-nav-closed.png'});
 await open.click();
 await page.screenshot({path:'/tmp/kin-nav-open.png'});
 await page.setViewportSize({width:1440,height:1000});
 await page.waitForFunction(()=>!document.querySelector('.sidebar.open'));
 assert.equal(await page.locator('.sidebar').isVisible(),true,'Desktop navigation remains visible');
 console.log('PASS outside tap, close control, Escape, focus restore, current route, draft preservation and desktop navigation');
}finally{await browser.close()}
