import type { CompatibilitySurfaceRegistry } from './types.ts';

export const authRegistry = {
  surface: "auth",
  compatPath: "packages/pyric/docs/auth/COMPAT.md",
  blocks: [
    { kind: 'markdown', markdown: "# `pyric/auth` compatibility matrix\n\nThe single readable contract for \"what this shim guarantees vs the\nproduction `firebase/auth` SDK.\"\n\nSee the design rationale for the methodology (vocabulary\nof conformance / oracle / matrix; how to add rows; how the runner\nattributes failures).\n\n## Status legend\n\n| Status | Meaning |\n|---|---|\n| ✓ | **Conforming** — sandbox matches prod, locked by a passing probe |\n| ⚠ | **Diverged (documented)** — intentional difference with a written reason |\n| ✗ | **Bug** — should match prod but doesn't; failing probe pins it |\n| — | **Unsupported** — not implemented yet (deliberately or pending) |\n| ? | **Unverified** — claim from docs that we haven't yet observed prod-side |\n\nProbe references: `playground:<name>` means a fixture under\n`packages/playground/scripts/fixtures/<name>.tsx`. `unit:<file>`\nmeans a Bun test in `packages/auth/test/<file>`.\n\n---\n" },
    {
      kind: 'table',
      prefix: "## `getAuth(target)` — initializer\n",
      rows: [
        {
          "id": "auth#1",
          "surface": "auth",
          "aliases": [],
          "rowRef": "1",
          "rowNumber": 1,
          "section": "`getAuth(target)` — initializer",
          "api": "getAuth(target)",
          "behavior": "Returns a stable `Auth` handle for repeat calls with the same target — idempotent on BOTH the sandbox target (per-sandbox WeakMap) and the prod target (per-resolved-`fb.Auth` WeakMap; previously the prod wrapper was minted fresh per call)",
          "status": "✓",
          "evidence": "`unit:sandbox-anonymous.test.ts` (sandbox) + `unit:prod-getauth-memo.test.ts` (prod, locks AUTH-B6)",
          "risk": ["structural"],
          "riskScore": 0,
          "riskReasons": ["structural / routing-only claim"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/prod-getauth-memo.test.ts", "packages/pyric/test/auth/sandbox-anonymous.test.ts"]
        },
        {
          "id": "auth#2",
          "surface": "auth",
          "aliases": [],
          "rowRef": "2",
          "rowNumber": 2,
          "section": "`getAuth(target)` — initializer",
          "api": "getAuth(target)",
          "behavior": "`getAuth(sandbox)` dispatches to the sandbox backend",
          "status": "✓",
          "evidence": "`unit:sandbox-anonymous.test.ts`",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-anonymous.test.ts"]
        },
        {
          "id": "auth#3",
          "surface": "auth",
          "aliases": [],
          "rowRef": "3",
          "rowNumber": 3,
          "section": "`getAuth(target)` — initializer",
          "api": "getAuth(target)",
          "behavior": "`getAuth(app)` dispatches to the production backend",
          "status": "?",
          "evidence": "(no prod test harness yet)",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unverified",
          "oracleObservations": [],
          "conformanceTests": []
        },
        {
          "id": "auth#4",
          "surface": "auth",
          "aliases": [],
          "rowRef": "4",
          "rowNumber": 4,
          "section": "`getAuth(target)` — initializer",
          "api": "getAuth(target)",
          "behavior": "`getAuth(undefined)` — wrapped in the playground preview to default to the sandbox; raw call delegates to prod which throws `app/no-app`",
          "status": "✓ (wrap)",
          "evidence": "`playground:firestore-bare-getfirestore` (mirrors the `getFirestore` wrap from #397) + oracle: `scripts/oracle/observations/auth-bare-getauth-no-default-app.json` (`code: 'app/no-app'` against blockingfun, fb-js-sdk 12.13.0 — confirms prod throw shape)",
          "risk": ["specific-value", "error-code", "specific-field"],
          "riskScore": 6,
          "riskReasons": ["asserts 1 specific value(s)", "asserts Firebase error code(s): `app/no-app`", "asserts a specific field/property value"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-bare-getauth-no-default-app"],
          "conformanceTests": [],
          "exceptionReason": "playground / preview behavior — no firebase-js-sdk counterpart to observe"
        },
        {
          "id": "auth#5",
          "surface": "auth",
          "aliases": [],
          "rowRef": "5",
          "rowNumber": 5,
          "section": "`getAuth(target)` — initializer",
          "api": "getAuth(target)",
          "behavior": "`auth.currentUser` is a live getter, not a snapshot — reads through to the backend on every access",
          "status": "✓",
          "evidence": "implicit in `unit:sandbox-anonymous.test.ts`",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-anonymous.test.ts"]
        },
      ],
    },
    {
      kind: 'table',
      prefix: "## `signInAnonymously(auth)` — anonymous\n",
      rows: [
        {
          "id": "auth#6",
          "surface": "auth",
          "aliases": [],
          "rowRef": "6",
          "rowNumber": 6,
          "section": "`signInAnonymously(auth)` — anonymous",
          "api": "signInAnonymously(auth)",
          "behavior": "Returns `UserCredential` with `providerId: null`, `operationType: 'signIn'`, and a `User` with `isAnonymous: true`, `email: null`, `displayName: null`",
          "status": "✓",
          "evidence": "`unit:sandbox-anonymous.test.ts`, `playground:auth-anonymous` (bundled) + `playground:auth-row-6-anon-credential-shape` (one-claim) + oracle: `scripts/oracle/observations/auth-anonymous-credential-providerid.json` (`providerId: null` against blockingfun, fb-js-sdk 12.13.0). Prior matrix language said `providerId: 'anonymous'`; corrected after empirical observation. Sandbox aligned to prod in the same commit.",
          "risk": ["specific-field"],
          "riskScore": 1,
          "riskReasons": ["asserts a specific field/property value"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-anonymous-credential-providerid"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-anonymous.test.ts"],
          "exceptionReason": "playground / preview behavior — no firebase-js-sdk counterpart to observe"
        },
        {
          "id": "auth#7",
          "surface": "auth",
          "aliases": [],
          "rowRef": "7",
          "rowNumber": 7,
          "section": "`signInAnonymously(auth)` — anonymous",
          "api": "signInAnonymously(auth)",
          "behavior": "Auto-generates a uid for fresh sign-ins (sandbox format: `anonymous-{N}`)",
          "status": "⚠ format",
          "evidence": "`unit:sandbox-anonymous.test.ts` — prod uids are 28-char base64-ish; sandbox uses a readable counter for debuggability",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-anonymous.test.ts"]
        },
        {
          "id": "auth#8",
          "surface": "auth",
          "aliases": [],
          "rowRef": "8",
          "rowNumber": 8,
          "section": "`signInAnonymously(auth)` — anonymous",
          "api": "signInAnonymously(auth)",
          "behavior": "If an anonymous user is already signed in, returns the SAME user (no fresh uid mint)",
          "status": "✓",
          "evidence": "`unit:sandbox-anonymous.test.ts` (\"idempotent while signed in\") — fix from #399",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-anonymous.test.ts"]
        },
        {
          "id": "auth#9",
          "surface": "auth",
          "aliases": [],
          "rowRef": "9",
          "rowNumber": 9,
          "section": "`signInAnonymously(auth)` — anonymous",
          "api": "signInAnonymously(auth)",
          "behavior": "After `signOut`, a subsequent `signInAnonymously` mints a fresh uid",
          "status": "✓",
          "evidence": "`unit:sandbox-anonymous.test.ts`, `playground:auth-anonymous` (bundled) + `playground:auth-row-9-anon-fresh-uid-after-signout` (one-claim)",
          "risk": ["specific-field"],
          "riskScore": 1,
          "riskReasons": ["asserts a specific field/property value"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-anonymous.test.ts"],
          "exceptionReason": "playground / preview behavior — no firebase-js-sdk counterpart to observe"
        },
        {
          "id": "auth#10",
          "surface": "auth",
          "aliases": [],
          "rowRef": "10",
          "rowNumber": 10,
          "section": "`signInAnonymously(auth)` — anonymous",
          "api": "signInAnonymously(auth)",
          "behavior": "Fires `onAuthStateChanged` exactly once per state transition (no same-value double-fire)",
          "status": "✓",
          "evidence": "`unit:sandbox-listeners.test.ts`, `playground:auth-anonymous` (bundled) + `playground:auth-row-10-onauthstatechanged-one-per-transition` (one-claim) — fix from #399 + oracle: `scripts/oracle/observations/auth-row-10-onauthstatechanged-one-per-transition.json` (against blockingfun, fb-js-sdk 12.13.0: subscribe → 1 initial null fire → `signInAnonymously` → +1 → `signOut` → +1 → `signInAnonymously` → +1. `eachTransitionFiredExactlyOnce: true` — every transition produces exactly one fire)",
          "risk": ["listener-fire-count", "specific-field", "listener"],
          "riskScore": 5,
          "riskReasons": ["asserts a specific listener fire count", "asserts a specific field/property value", "asserts listener semantics"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-row-10-onauthstatechanged-one-per-transition"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-listeners.test.ts"],
          "exceptionReason": "playground / preview behavior — no firebase-js-sdk counterpart to observe"
        },
        {
          "id": "auth#11",
          "surface": "auth",
          "aliases": [],
          "rowRef": "11",
          "rowNumber": 11,
          "section": "`signInAnonymously(auth)` — anonymous",
          "api": "signInAnonymously(auth)",
          "behavior": "Writes through to `sandbox.currentUser` so rules engines see `request.auth.uid`",
          "status": "✓",
          "evidence": "`unit:sandbox-anonymous.test.ts`, `playground:auth-anonymous` (bundled) + `playground:auth-row-11-anon-uid-visible-to-rules` (one-claim)",
          "risk": ["specific-field"],
          "riskScore": 1,
          "riskReasons": ["asserts a specific field/property value"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-anonymous.test.ts"],
          "exceptionReason": "playground / preview behavior — no firebase-js-sdk counterpart to observe"
        },
        {
          "id": "auth#12",
          "surface": "auth",
          "aliases": [],
          "rowRef": "12",
          "rowNumber": 12,
          "section": "`signInAnonymously(auth)` — anonymous",
          "api": "signInAnonymously(auth)",
          "behavior": "Anonymous users persist across page reload via configured `Persistence` (prod only — sandbox has no persistence layer)",
          "status": "⚠",
          "evidence": "divergence: sandbox memory only; within one tab the user persists, across reload they don't",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unverified",
          "oracleObservations": [],
          "conformanceTests": []
        },
      ],
    },
    {
      kind: 'table',
      prefix: "## `signInWithEmailAndPassword(auth, email, password)` — password\n",
      rows: [
        {
          "id": "auth#13",
          "surface": "auth",
          "aliases": [],
          "rowRef": "13",
          "rowNumber": 13,
          "section": "`signInWithEmailAndPassword(auth, email, password)` — password",
          "api": "signInWithEmailAndPassword(auth, email, password)",
          "behavior": "Returns `UserCredential` with `providerId: null` (NOT `'password'` — only OAuth/phone responses carry a providerId; upstream `providerIdForResponse` returns null for email/password), `operationType: 'signIn'`, and a `User` with the stored uid + email",
          "status": "✓",
          "evidence": "`unit:sandbox-email-password.test.ts` + oracle: `scripts/oracle/observations/auth-createUser-operationType.json` (`providerId: null` against blockingfun, fb-js-sdk 12.13.0). Prior matrix language said `providerId: 'password'`; corrected after the oracle contradicted it (AUTH-B2).",
          "risk": ["specific-value", "specific-field"],
          "riskScore": 3,
          "riskReasons": ["asserts 1 specific value(s)", "asserts a specific field/property value"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-createUser-operationType"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-email-password.test.ts"]
        },
        {
          "id": "auth#14",
          "surface": "auth",
          "aliases": [],
          "rowRef": "14",
          "rowNumber": 14,
          "section": "`signInWithEmailAndPassword(auth, email, password)` — password",
          "api": "signInWithEmailAndPassword(auth, email, password)",
          "behavior": "Throws `auth/user-not-found` when the email isn't seeded / hasn't been created",
          "status": "✓",
          "evidence": "`unit:sandbox-email-password.test.ts` + oracle: `scripts/oracle/observations/auth-user-not-found-error-code.json` (`code: 'auth/user-not-found'` against blockingfun, fb-js-sdk 12.13.0; matches sandbox)",
          "risk": ["specific-value", "error-code"],
          "riskScore": 5,
          "riskReasons": ["asserts 1 specific value(s)", "asserts Firebase error code(s): `auth/user-not-found`"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-user-not-found-error-code"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-email-password.test.ts"]
        },
        {
          "id": "auth#15",
          "surface": "auth",
          "aliases": [],
          "rowRef": "15",
          "rowNumber": 15,
          "section": "`signInWithEmailAndPassword(auth, email, password)` — password",
          "api": "signInWithEmailAndPassword(auth, email, password)",
          "behavior": "Throws `auth/wrong-password` when the password doesn't match",
          "status": "✓",
          "evidence": "`unit:sandbox-email-password.test.ts`, `playground:auth-email-password` (bundled) + `playground:auth-row-15-wrong-password-rejects` (one-claim) + oracle: `scripts/oracle/observations/auth-wrong-password-error-code.json` (`code: 'auth/wrong-password'` against blockingfun, fb-js-sdk 12.13.0; matches sandbox)",
          "risk": ["specific-value", "error-code", "specific-field"],
          "riskScore": 6,
          "riskReasons": ["asserts 1 specific value(s)", "asserts Firebase error code(s): `auth/wrong-password`", "asserts a specific field/property value"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-wrong-password-error-code"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-email-password.test.ts"],
          "exceptionReason": "playground / preview behavior — no firebase-js-sdk counterpart to observe"
        },
        {
          "id": "auth#15a",
          "surface": "auth",
          "aliases": [],
          "rowRef": "15a",
          "rowNumber": 15,
          "section": "`signInWithEmailAndPassword(auth, email, password)` — password",
          "api": "signInWithEmailAndPassword(auth, email, password)",
          "behavior": "An EMPTY password throws `auth/missing-password` (message \"A non-empty password must be provided\"), fired before the user-DB lookup so it can't be used to enumerate seeded emails. Upstream maps the `MISSING_PASSWORD` server error (`core/errors.ts:92,282,563`). ⚠ best-known semantics — message text not yet captured against a live project (STOP-flagged for an oracle pass; the `.code` is the load-bearing part).",
          "status": "⚠",
          "evidence": "`unit:sandbox-cluster-b9-b12.test.ts` (locks AUTH-B11)",
          "risk": ["specific-value", "error-code", "listener"],
          "riskScore": 7,
          "riskReasons": ["asserts 1 specific value(s)", "asserts Firebase error code(s): `auth/missing-password`", "asserts listener semantics"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-cluster-b9-b12.test.ts"]
        },
        {
          "id": "auth#16",
          "surface": "auth",
          "aliases": [],
          "rowRef": "16",
          "rowNumber": 16,
          "section": "`signInWithEmailAndPassword(auth, email, password)` — password",
          "api": "signInWithEmailAndPassword(auth, email, password)",
          "behavior": "Re-signing in after `signOut` returns the **same** uid (passwords persist within the sandbox lifetime)",
          "status": "✓",
          "evidence": "`playground:auth-email-password` (bundled) + `playground:auth-row-16-resignin-same-uid` (one-claim)",
          "risk": ["specific-field"],
          "riskScore": 1,
          "riskReasons": ["asserts a specific field/property value"],
          "automation": "playground-only",
          "oracleObservations": [],
          "conformanceTests": [],
          "exceptionReason": "playground / preview behavior — no firebase-js-sdk counterpart to observe"
        },
        {
          "id": "auth#17",
          "surface": "auth",
          "aliases": [],
          "rowRef": "17",
          "rowNumber": 17,
          "section": "`signInWithEmailAndPassword(auth, email, password)` — password",
          "api": "signInWithEmailAndPassword(auth, email, password)",
          "behavior": "Fires `onAuthStateChanged` with the new user once",
          "status": "✓",
          "evidence": "`unit:sandbox-listeners.test.ts` + oracle: `scripts/oracle/observations/auth-row-17-signin-email-password-fires-once.json` (against blockingfun, fb-js-sdk 12.13.0: createUser → signOut → subscribe (1 initial null fire) → `signInWithEmailAndPassword` → `firesForSignIn: 1` with the signed-in uid, `lastFireUidMatches: true`)",
          "risk": ["specific-field", "listener"],
          "riskScore": 3,
          "riskReasons": ["asserts a specific field/property value", "asserts listener semantics"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-row-17-signin-email-password-fires-once"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-listeners.test.ts"]
        },
        {
          "id": "auth#18",
          "surface": "auth",
          "aliases": [],
          "rowRef": "18",
          "rowNumber": 18,
          "section": "`signInWithEmailAndPassword(auth, email, password)` — password",
          "api": "signInWithEmailAndPassword(auth, email, password)",
          "behavior": "Email validation (RFC 5322ish) — rejects empty, missing `@`, missing local-part, missing domain with `auth/invalid-email`. Runs on both `signInWithEmailAndPassword` and `createUserWithEmailAndPassword` before any user-DB lookup, so consumers shipping malformed input see the same error sandbox vs prod.",
          "status": "✓",
          "evidence": "`unit:sandbox-email-password.test.ts` + oracle: `scripts/oracle/observations/auth-row-18-invalid-email-error-code.json` (`code: 'auth/invalid-email'`, message `Firebase: Error (auth/invalid-email).` against blockingfun, fb-js-sdk 12.13.0)",
          "risk": ["specific-value", "error-code"],
          "riskScore": 5,
          "riskReasons": ["asserts 1 specific value(s)", "asserts Firebase error code(s): `auth/invalid-email`"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-row-18-invalid-email-error-code"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-email-password.test.ts"]
        },
        {
          "id": "auth#19",
          "surface": "auth",
          "aliases": [],
          "rowRef": "19",
          "rowNumber": 19,
          "section": "`signInWithEmailAndPassword(auth, email, password)` — password",
          "api": "signInWithEmailAndPassword(auth, email, password)",
          "behavior": "Password strength requirements — rejects passwords shorter than 6 chars with `auth/weak-password` on `createUserWithEmailAndPassword`. Strength is NOT enforced on `signInWithEmailAndPassword` so previously-seeded weak passwords still let the user in (matches prod's separation of registration vs sign-in).",
          "status": "✓",
          "evidence": "`unit:sandbox-email-password.test.ts` + oracle: `scripts/oracle/observations/auth-row-19-weak-password-error-code.json` (`code: 'auth/weak-password'`, message `Firebase: Password should be at least 6 characters (auth/weak-password).` against blockingfun, fb-js-sdk 12.13.0; matrix language \"≥6 chars per prod default\" empirically confirmed)",
          "risk": ["specific-value", "error-code"],
          "riskScore": 5,
          "riskReasons": ["asserts 1 specific value(s)", "asserts Firebase error code(s): `auth/weak-password`"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-row-19-weak-password-error-code"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-email-password.test.ts"]
        },
        {
          "id": "auth#69",
          "surface": "auth",
          "aliases": [],
          "rowRef": "69",
          "rowNumber": 69,
          "section": "`signInWithEmailAndPassword(auth, email, password)` — password",
          "api": "signInWithEmailAndPassword(auth, email, password)",
          "behavior": "Disabled accounts (`sandbox.updateUser(…, {disabled: true})`) reject sign-in with `auth/user-disabled` and prod's documented message (`The user account has been disabled by an administrator.`). Sandbox checks disabled BEFORE the password compare (anti-probing); the exact prod ordering of disabled-vs-wrong-password needs an oracle capture",
          "status": "✓ code / ? ordering",
          "evidence": "`unit:sandbox-user-admin.test.ts` (\"disabled users\")",
          "risk": ["specific-value", "error-code"],
          "riskScore": 5,
          "riskReasons": ["asserts 1 specific value(s)", "asserts Firebase error code(s): `auth/user-disabled`"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-user-admin.test.ts"]
        },
      ],
    },
    {
      kind: 'table',
      prefix: "## `createUserWithEmailAndPassword(auth, email, password)` — register\n",
      rows: [
        {
          "id": "auth#20",
          "surface": "auth",
          "aliases": [],
          "rowRef": "20",
          "rowNumber": 20,
          "section": "`createUserWithEmailAndPassword(auth, email, password)` — register",
          "api": "createUserWithEmailAndPassword(auth, email, password)",
          "behavior": "Creates a new user, signs them in automatically (currentUser becomes the new user)",
          "status": "✓",
          "evidence": "`playground:auth-email-password` (bundled) + `playground:auth-row-20-create-user-auto-signs-in` (one-claim), `unit:sandbox-email-password.test.ts`",
          "risk": ["specific-field"],
          "riskScore": 1,
          "riskReasons": ["asserts a specific field/property value"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-email-password.test.ts"],
          "exceptionReason": "playground / preview behavior — no firebase-js-sdk counterpart to observe"
        },
        {
          "id": "auth#21",
          "surface": "auth",
          "aliases": [],
          "rowRef": "21",
          "rowNumber": 21,
          "section": "`createUserWithEmailAndPassword(auth, email, password)` — register",
          "api": "createUserWithEmailAndPassword(auth, email, password)",
          "behavior": "Returns `UserCredential` with `operationType: 'signIn'` (NOT `'register'` — matches prod)",
          "status": "✓",
          "evidence": "`unit:sandbox-email-password.test.ts` + oracle: `scripts/oracle/observations/auth-createUser-operationType.json` (`operationType: 'signIn'` against blockingfun, fb-js-sdk 12.13.0; matches sandbox)",
          "risk": ["specific-value", "specific-field"],
          "riskScore": 3,
          "riskReasons": ["asserts 1 specific value(s)", "asserts a specific field/property value"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-createUser-operationType"],
          "conformanceTests": ["packages/pyric/test/auth/oracle-conformance.test.ts", "packages/pyric/test/auth/sandbox-email-password.test.ts"],
          "conformanceChecks": [
            {
              "finding": "AUTH-B2",
              "observation": "auth-createUser-operationType",
              "expect": {
                "providerId": null,
                "operationType": "signIn"
              },
              "probe": "packages/pyric/test/auth/oracle-conformance.test.ts",
              "guards": "createUserWithEmailAndPassword returns providerId: null + operationType: 'signIn' (not 'password')."
            }
          ]
        },
        {
          "id": "auth#22",
          "surface": "auth",
          "aliases": [],
          "rowRef": "22",
          "rowNumber": 22,
          "section": "`createUserWithEmailAndPassword(auth, email, password)` — register",
          "api": "createUserWithEmailAndPassword(auth, email, password)",
          "behavior": "Throws `auth/email-already-in-use` when the email is already registered",
          "status": "✓",
          "evidence": "`unit:sandbox-email-password.test.ts` + oracle: `scripts/oracle/observations/auth-email-already-in-use-error-code.json` (`code: 'auth/email-already-in-use'` against blockingfun, fb-js-sdk 12.13.0; matches sandbox)",
          "risk": ["specific-value", "error-code"],
          "riskScore": 5,
          "riskReasons": ["asserts 1 specific value(s)", "asserts Firebase error code(s): `auth/email-already-in-use`"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-email-already-in-use-error-code"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-email-password.test.ts"]
        },
        {
          "id": "auth#23",
          "surface": "auth",
          "aliases": [],
          "rowRef": "23",
          "rowNumber": 23,
          "section": "`createUserWithEmailAndPassword(auth, email, password)` — register",
          "api": "createUserWithEmailAndPassword(auth, email, password)",
          "behavior": "The created user has `isAnonymous: false`, `email: <input>`, `displayName: null`",
          "status": "✓",
          "evidence": "`unit:sandbox-email-password.test.ts` + `playground:auth-row-23-create-user-shape` (one-claim)",
          "risk": ["specific-field"],
          "riskScore": 1,
          "riskReasons": ["asserts a specific field/property value"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-email-password.test.ts"],
          "exceptionReason": "playground / preview behavior — no firebase-js-sdk counterpart to observe"
        },
        {
          "id": "auth#24",
          "surface": "auth",
          "aliases": [],
          "rowRef": "24",
          "rowNumber": 24,
          "section": "`createUserWithEmailAndPassword(auth, email, password)` — register",
          "api": "createUserWithEmailAndPassword(auth, email, password)",
          "behavior": "Fires `onAuthStateChanged` with the new user once",
          "status": "✓",
          "evidence": "`unit:sandbox-listeners.test.ts` + oracle: `scripts/oracle/observations/auth-row-24-createuser-fires-once.json` (against blockingfun, fb-js-sdk 12.13.0: subscribe (1 initial null fire) → `createUserWithEmailAndPassword` → `firesForCreate: 1` with the newly-created uid, `lastFireUidMatches: true`)",
          "risk": ["specific-field", "listener"],
          "riskScore": 3,
          "riskReasons": ["asserts a specific field/property value", "asserts listener semantics"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-row-24-createuser-fires-once"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-listeners.test.ts"]
        },
      ],
    },
    {
      kind: 'table',
      prefix: "## `signOut(auth)`\n",
      rows: [
        {
          "id": "auth#25",
          "surface": "auth",
          "aliases": [],
          "rowRef": "25",
          "rowNumber": 25,
          "section": "`signOut(auth)`",
          "api": "signOut(auth)",
          "behavior": "Sets `currentUser` to `null` synchronously after resolution",
          "status": "✓",
          "evidence": "`playground:auth-anonymous` (bundled) + `playground:auth-row-25-signout-currentuser-null` (one-claim), `unit:sandbox-anonymous.test.ts` + oracle: `scripts/oracle/observations/auth-row-25-signout-currentuser-null-sync.json` (`currentUserIsNullSync: true` against blockingfun, fb-js-sdk 12.13.0 — `auth.currentUser` read in the synchronous continuation immediately after `await signOut(auth)` is already `null`, with no microtask/macrotask required to settle)",
          "risk": ["specific-field", "timing"],
          "riskScore": 3,
          "riskReasons": ["asserts a specific field/property value", "asserts timing semantics"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-row-25-signout-currentuser-null-sync"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-anonymous.test.ts"],
          "exceptionReason": "playground / preview behavior — no firebase-js-sdk counterpart to observe"
        },
        {
          "id": "auth#26",
          "surface": "auth",
          "aliases": [],
          "rowRef": "26",
          "rowNumber": 26,
          "section": "`signOut(auth)`",
          "api": "signOut(auth)",
          "behavior": "Fires `onAuthStateChanged` with `null` exactly once",
          "status": "✓",
          "evidence": "`unit:sandbox-listeners.test.ts`, `playground:auth-anonymous` (bundled) + `playground:auth-row-26-signout-fires-null-once` (one-claim) + oracle: `scripts/oracle/observations/auth-row-26-signout-fires-null-once.json` (against blockingfun, fb-js-sdk 12.13.0: subscribe (1 initial null fire) → `signInAnonymously` → `signOut` → `firesForSignOut: 1` with `lastFireUidWasNull: true`)",
          "risk": ["specific-field", "listener"],
          "riskScore": 3,
          "riskReasons": ["asserts a specific field/property value", "asserts listener semantics"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-row-26-signout-fires-null-once"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-listeners.test.ts"],
          "exceptionReason": "playground / preview behavior — no firebase-js-sdk counterpart to observe"
        },
        {
          "id": "auth#27",
          "surface": "auth",
          "aliases": [],
          "rowRef": "27",
          "rowNumber": 27,
          "section": "`signOut(auth)`",
          "api": "signOut(auth)",
          "behavior": "Idempotent — `signOut` on already-signed-out user is a no-op (no listener fire)",
          "status": "✓",
          "evidence": "`playground:auth-signout-idempotent` + oracle-confirmed: `scripts/oracle/observations/auth-signout-idempotent.json` (`threw: false, redundantSignOutFiredListener: false` against blockingfun)",
          "risk": ["specific-field", "listener"],
          "riskScore": 3,
          "riskReasons": ["asserts a specific field/property value", "asserts listener semantics"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-signout-idempotent"],
          "conformanceTests": [],
          "exceptionReason": "playground / preview behavior — no firebase-js-sdk counterpart to observe"
        },
        {
          "id": "auth#28",
          "surface": "auth",
          "aliases": [],
          "rowRef": "28",
          "rowNumber": 28,
          "section": "`signOut(auth)`",
          "api": "signOut(auth)",
          "behavior": "Clears the active session's persistence in prod; sandbox has no persistence",
          "status": "⚠",
          "evidence": "divergence: same memory-only constraint as the anonymous persistence row",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unverified",
          "oracleObservations": [],
          "conformanceTests": []
        },
      ],
    },
    {
      kind: 'table',
      prefix: "## `onAuthStateChanged(auth, observer)`\n",
      rows: [
        {
          "id": "auth#29",
          "surface": "auth",
          "aliases": [],
          "rowRef": "29",
          "rowNumber": 29,
          "section": "`onAuthStateChanged(auth, observer)`",
          "api": "onAuthStateChanged(auth, observer)",
          "behavior": "Fires immediately on subscribe with the current value (microtask-deferred)",
          "status": "✓",
          "evidence": "`unit:sandbox-listeners.test.ts` + oracle: `scripts/oracle/observations/auth-row-29-onauthstatechanged-initial-fire-timing.json` (`firedSynchronously: 0, firedAfterMicrotask: 1` against blockingfun, fb-js-sdk 12.13.0 — initial fire does NOT arrive in the synchronous tick of `onAuthStateChanged(...)`; it lands after the first microtask flush)",
          "risk": ["listener", "timing"],
          "riskScore": 4,
          "riskReasons": ["asserts listener semantics", "asserts timing semantics"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-row-29-onauthstatechanged-initial-fire-timing"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-listeners.test.ts"]
        },
        {
          "id": "auth#30",
          "surface": "auth",
          "aliases": [],
          "rowRef": "30",
          "rowNumber": 30,
          "section": "`onAuthStateChanged(auth, observer)`",
          "api": "onAuthStateChanged(auth, observer)",
          "behavior": "Fires on every subsequent identity change",
          "status": "✓",
          "evidence": "`unit:sandbox-listeners.test.ts`, `playground:auth-anonymous` + oracle: `scripts/oracle/observations/auth-row-30-onauthstatechanged-fires-on-every-transition.json` (against blockingfun, fb-js-sdk 12.13.0: subscribe → `signIn` → `signOut` → `signIn` → `signOut`, each of the 4 transitions produced exactly 1 fire; `eachTransitionFiredExactlyOnce: true`)",
          "risk": ["listener-fire-count", "specific-field", "listener"],
          "riskScore": 5,
          "riskReasons": ["asserts a specific listener fire count", "asserts a specific field/property value", "asserts listener semantics"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-row-30-onauthstatechanged-fires-on-every-transition"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-listeners.test.ts"],
          "exceptionReason": "playground / preview behavior — no firebase-js-sdk counterpart to observe"
        },
        {
          "id": "auth#30a",
          "surface": "auth",
          "aliases": [],
          "rowRef": "30a",
          "rowNumber": 30,
          "section": "`onAuthStateChanged(auth, observer)`",
          "api": "onAuthStateChanged(auth, observer)",
          "behavior": "Dedups by uid: a same-uid update (profile-shape change, or a same-uid re-sign-in) does NOT re-fire `onAuthStateChanged` — only an actual uid change does. Mirrors upstream `notifyAuthListeners`'s `lastNotifiedUid` gate (`auth_impl.ts:718-723`). (`onIdTokenChanged` still fires on those same-uid updates — see row 38a.)",
          "status": "✓",
          "evidence": "`unit:sandbox-uid-dedup.test.ts` (locks AUTH-B7 / B8)",
          "risk": ["listener"],
          "riskScore": 2,
          "riskReasons": ["asserts listener semantics"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-uid-dedup.test.ts"]
        },
        {
          "id": "auth#31",
          "surface": "auth",
          "aliases": [],
          "rowRef": "31",
          "rowNumber": 31,
          "section": "`onAuthStateChanged(auth, observer)`",
          "api": "onAuthStateChanged(auth, observer)",
          "behavior": "**No duplicate fire** when subscribe is followed by a synchronous `setCurrentUser` — dedup ensures observer sees the new value once, not twice. Sandbox-only concern: prod has no synchronous state-change API, so the dedup window can't be exercised against the cloud SDK; subscribe-then-async-signIn naturally fires twice (initial + new value) because the microtask between them flushes the initial fire",
          "status": "✓",
          "evidence": "`unit:sandbox-listeners.test.ts` (regression test from #399), `playground:auth-anonymous` + oracle baseline: `scripts/oracle/observations/auth-row-31-onauthstatechanged-no-dup-on-sync-transition.json` (against blockingfun, fb-js-sdk 12.13.0: subscribe + async `signInAnonymously` in the same tick produces `totalFires: 2` — `{uid: null, ts: 0}` then `{uid: <user>, ts: ~400ms}`. Confirms prod cannot exhibit the same-tick race; the dedup behavior remains a sandbox-only property)",
          "risk": ["listener-fire-count", "specific-field", "listener"],
          "riskScore": 5,
          "riskReasons": ["asserts a specific listener fire count", "asserts a specific field/property value", "asserts listener semantics"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-row-31-onauthstatechanged-no-dup-on-sync-transition"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-listeners.test.ts"],
          "exceptionReason": "sandbox-only behavior — no prod equivalent to observe"
        },
        {
          "id": "auth#32",
          "surface": "auth",
          "aliases": [],
          "rowRef": "32",
          "rowNumber": 32,
          "section": "`onAuthStateChanged(auth, observer)`",
          "api": "onAuthStateChanged(auth, observer)",
          "behavior": "Returned `Unsubscribe` removes the observer; subsequent state changes do NOT fire it",
          "status": "✓",
          "evidence": "`unit:sandbox-listeners.test.ts`, `playground:auth-listener-unsub` (bundled) + `playground:auth-row-32-unsubscribe-stops-fires` (one-claim) + oracle: `scripts/oracle/observations/auth-row-32-unsubscribe-stops-fires.json` (against blockingfun, fb-js-sdk 12.13.0: subscribe → 1 fire on `signInAnonymously` → call `unsub()` → `signOut` + `signInAnonymously` + `signOut` produce zero further fires; `postUnsubFires: 0, unsubscribeStoppedFires: true`)",
          "risk": ["specific-field", "listener"],
          "riskScore": 3,
          "riskReasons": ["asserts a specific field/property value", "asserts listener semantics"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-row-32-unsubscribe-stops-fires"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-listeners.test.ts"],
          "exceptionReason": "playground / preview behavior — no firebase-js-sdk counterpart to observe"
        },
        {
          "id": "auth#33",
          "surface": "auth",
          "aliases": [],
          "rowRef": "33",
          "rowNumber": 33,
          "section": "`onAuthStateChanged(auth, observer)`",
          "api": "onAuthStateChanged(auth, observer)",
          "behavior": "Multiple subscribers all fire on each change",
          "status": "✓",
          "evidence": "`unit:sandbox-listeners.test.ts` + oracle: `scripts/oracle/observations/auth-row-33-multiple-subscribers-all-fire.json` (against blockingfun, fb-js-sdk 12.13.0: two subscribers registered back-to-back each see 1 initial null fire, +1 on `signInAnonymously`, +1 on `signOut`; `bothFiredOnSignIn: true, bothFiredOnSignOut: true`)",
          "risk": ["listener"],
          "riskScore": 2,
          "riskReasons": ["asserts listener semantics"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-row-33-multiple-subscribers-all-fire"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-listeners.test.ts"]
        },
        {
          "id": "auth#33a",
          "surface": "auth",
          "aliases": [],
          "rowRef": "33a",
          "rowNumber": 33,
          "section": "`onAuthStateChanged(auth, observer)`",
          "api": "onAuthStateChanged(auth, observer)",
          "behavior": "Registry is array-backed (matches upstream `util/subscribe.ts`): the SAME observer fn registered N times produces N independent registrations that each fire, and one `Unsubscribe` removes exactly one registration. A resubscribe of a previously-unsubscribed fn fires its initial value again. (Per-registration initial-fire bookkeeping, not a shared per-observer dedup.)",
          "status": "✓",
          "evidence": "`unit:sandbox-listener-registry.test.ts` (locks AUTH-B3 + AUTH-B4)",
          "risk": ["listener"],
          "riskScore": 2,
          "riskReasons": ["asserts listener semantics"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-listener-registry.test.ts"]
        },
        {
          "id": "auth#34",
          "surface": "auth",
          "aliases": [],
          "rowRef": "34",
          "rowNumber": 34,
          "section": "`onAuthStateChanged(auth, observer)`",
          "api": "onAuthStateChanged(auth, observer)",
          "behavior": "Unsubscribing during emission does not skip remaining subscribers (snapshotted iteration)",
          "status": "✓",
          "evidence": "`unit:sandbox-listeners.test.ts`",
          "risk": ["listener"],
          "riskScore": 2,
          "riskReasons": ["asserts listener semantics"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-listeners.test.ts"]
        },
        {
          "id": "auth#35",
          "surface": "auth",
          "aliases": [],
          "rowRef": "35",
          "rowNumber": 35,
          "section": "`onAuthStateChanged(auth, observer)`",
          "api": "onAuthStateChanged(auth, observer)",
          "behavior": "A throwing observer doesn't block other observers from firing",
          "status": "✓",
          "evidence": "`unit:sandbox-listeners.test.ts` + oracle: `scripts/oracle/observations/auth-row-35-throwing-observer-doesnt-block-others.json` (`secondObserverContinuedFiring: true` against blockingfun, fb-js-sdk 12.13.0 — observer #1 throws on every call, observer #2 still counts the initial fire AND the post-sign-in fire)",
          "risk": ["specific-field", "listener"],
          "riskScore": 3,
          "riskReasons": ["asserts a specific field/property value", "asserts listener semantics"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-row-35-throwing-observer-doesnt-block-others"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-listeners.test.ts"]
        },
        {
          "id": "auth#36",
          "surface": "auth",
          "aliases": [],
          "rowRef": "36",
          "rowNumber": 36,
          "section": "`onAuthStateChanged(auth, observer)`",
          "api": "onAuthStateChanged(auth, observer)",
          "behavior": "Observer object form (`{next, error, complete}`) works alongside the function form",
          "status": "✓",
          "evidence": "`unit:sandbox-listeners.test.ts` + oracle: `scripts/oracle/observations/auth-row-36-observer-object-form-works.json` (against blockingfun, fb-js-sdk 12.13.0: one observer as `NextFn`, another as `{next, error, complete}`. Both forms see 1 initial null fire, +1 on `signInAnonymously`, +1 on `signOut`; `bothFormsFiredOnSignIn: true, bothFormsFiredOnSignOut: true`)",
          "risk": ["listener"],
          "riskScore": 2,
          "riskReasons": ["asserts listener semantics"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-row-36-observer-object-form-works"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-listeners.test.ts"]
        },
        {
          "id": "auth#37",
          "surface": "auth",
          "aliases": [],
          "rowRef": "37",
          "rowNumber": 37,
          "section": "`onAuthStateChanged(auth, observer)`",
          "api": "onAuthStateChanged(auth, observer)",
          "behavior": "Setting the same user twice does NOT double-fire (structural-equality no-op). Sandbox-internal `setCurrentUser` claim; the prod analog is `signInAnonymously` called twice in a row (per fix #399, the second call returns the same user).",
          "status": "✓",
          "evidence": "`unit:sandbox-listeners.test.ts` + oracle: `scripts/oracle/observations/auth-row-37-same-user-no-double-fire.json` (against blockingfun, fb-js-sdk 12.13.0: first `signInAnonymously` fires the listener once; second call returns the same uid (`sameUserAcrossCalls: true`) and does NOT produce a fresh fire (`secondSignInProducedFire: false`). Prod also recognizes the same-user no-op)",
          "risk": ["specific-field", "listener"],
          "riskScore": 3,
          "riskReasons": ["asserts a specific field/property value", "asserts listener semantics"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-row-37-same-user-no-double-fire"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-listeners.test.ts"]
        },
      ],
    },
    {
      kind: 'table',
      prefix: "## `onIdTokenChanged(auth, observer)`\n",
      rows: [
        {
          "id": "auth#38",
          "surface": "auth",
          "aliases": [],
          "rowRef": "38",
          "rowNumber": 38,
          "section": "`onIdTokenChanged(auth, observer)`",
          "api": "onIdTokenChanged(auth, observer)",
          "behavior": "Fires on user change (sandbox shares the auth-state path)",
          "status": "✓",
          "evidence": "`unit:sandbox-listeners.test.ts` + oracle: `scripts/oracle/observations/auth-row-38-onidtokenchanged-fires-on-user-change.json` (against blockingfun, fb-js-sdk 12.13.0: subscribe → 1 initial fire (null) → `signInAnonymously` → +1 (user₁) → `signOut` → +1 (null) → `signInAnonymously` → +1 (user₂ with fresh uid). Every identity transition produces exactly one fire, matching `onAuthStateChanged`)",
          "risk": ["listener-fire-count", "listener"],
          "riskScore": 4,
          "riskReasons": ["asserts a specific listener fire count", "asserts listener semantics"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-row-38-onidtokenchanged-fires-on-user-change"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-listeners.test.ts"]
        },
        {
          "id": "auth#38a",
          "surface": "auth",
          "aliases": [],
          "rowRef": "38a",
          "rowNumber": 38,
          "section": "`onIdTokenChanged(auth, observer)`",
          "api": "onIdTokenChanged(auth, observer)",
          "behavior": "Fires on EVERY sign-in, including a same-uid re-sign-in (no `signOut` first) — which mints a fresh token, so a subsequent `getIdToken()` returns a new string. Mirrors upstream `notifyAuthListeners`, which calls `idTokenSubscription.next` on every identity update (`auth_impl.ts:716`). `onAuthStateChanged` stays silent on the same-uid case (row 30a).",
          "status": "✓",
          "evidence": "`unit:sandbox-uid-dedup.test.ts` (locks AUTH-B8)",
          "risk": ["listener"],
          "riskScore": 2,
          "riskReasons": ["asserts listener semantics"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-uid-dedup.test.ts"]
        },
        {
          "id": "auth#39",
          "surface": "auth",
          "aliases": [],
          "rowRef": "39",
          "rowNumber": 39,
          "section": "`onIdTokenChanged(auth, observer)`",
          "api": "onIdTokenChanged(auth, observer)",
          "behavior": "Fires on token refresh (`getIdToken(true)`)",
          "status": "✓",
          "evidence": "`unit:sandbox-token-refresh.test.ts` — was ⚠ (documented divergence); aligned to prod in commit on branch `claude/close-auth-token-refresh` — sandbox now mints a fresh token on forceRefresh and fires `onIdTokenChanged` (NOT `onAuthStateChanged`, since identity is unchanged). Oracle: `scripts/oracle/observations/auth-onidtokenchanged-force-refresh.json` defines the target shape (`refreshFiredListener: true` against blockingfun; subscribe → null fire → `signInAnonymously` → +1 → `getIdToken(true)` → +1 for a total of 3 fires).",
          "risk": ["specific-value", "specific-field", "listener"],
          "riskScore": 5,
          "riskReasons": ["asserts 1 specific value(s)", "asserts a specific field/property value", "asserts listener semantics"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-onidtokenchanged-force-refresh"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-token-refresh.test.ts"]
        },
        {
          "id": "auth#40",
          "surface": "auth",
          "aliases": [],
          "rowRef": "40",
          "rowNumber": 40,
          "section": "`onIdTokenChanged(auth, observer)`",
          "api": "onIdTokenChanged(auth, observer)",
          "behavior": "Initial-fire semantics match `onAuthStateChanged`",
          "status": "✓",
          "evidence": "`unit:sandbox-listeners.test.ts` + oracle: `scripts/oracle/observations/auth-row-40-onidtokenchanged-matches-onauthstatechanged-initial-fire.json` (against blockingfun, fb-js-sdk 12.13.0: subscribing both listeners in the same tick yields `sync: {auth: 0, idToken: 0}` → `microtask: {auth: 1, idToken: 1}` → no further fires. Both listeners share the microtask-deferred initial-fire timing)",
          "risk": ["listener", "timing"],
          "riskScore": 4,
          "riskReasons": ["asserts listener semantics", "asserts timing semantics"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-row-40-onidtokenchanged-matches-onauthstatechanged-initial-fire"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-listeners.test.ts"]
        },
      ],
    },
    {
      kind: 'table',
      prefix: "## `setPersistence(auth, persistence)`\n",
      rows: [
        {
          "id": "auth#41",
          "surface": "auth",
          "aliases": [],
          "rowRef": "41",
          "rowNumber": 41,
          "section": "`setPersistence(auth, persistence)`",
          "api": "setPersistence(auth, persistence)",
          "behavior": "Accepts `inMemoryPersistence` / `browserSessionPersistence` / `browserLocalPersistence` markers without throwing",
          "status": "✓",
          "evidence": "`unit:types.test.ts`",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/types.test.ts"]
        },
        {
          "id": "auth#42",
          "surface": "auth",
          "aliases": [],
          "rowRef": "42",
          "rowNumber": 42,
          "section": "`setPersistence(auth, persistence)`",
          "api": "setPersistence(auth, persistence)",
          "behavior": "Returns `Promise<void>`",
          "status": "✓",
          "evidence": "`unit:types.test.ts`",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/types.test.ts"]
        },
        {
          "id": "auth#43",
          "surface": "auth",
          "aliases": [],
          "rowRef": "43",
          "rowNumber": 43,
          "section": "`setPersistence(auth, persistence)`",
          "api": "setPersistence(auth, persistence)",
          "behavior": "Actually changes where the auth state is persisted",
          "status": "⚠",
          "evidence": "divergence: sandbox is a no-op. Prod respects the marker.",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unverified",
          "oracleObservations": [],
          "conformanceTests": []
        },
        {
          "id": "auth#43a",
          "surface": "auth",
          "aliases": [],
          "rowRef": "43a",
          "rowNumber": 43,
          "section": "`setPersistence(auth, persistence)`",
          "api": "setPersistence(auth, persistence)",
          "behavior": "An unrecognized persistence marker (not one of the three) is rejected with `auth/argument-error` on the prod backend, rather than silently coerced to LOCAL",
          "status": "✓",
          "evidence": "`unit:sandbox-cluster-b9-b12.test.ts` (locks AUTH-B12)",
          "risk": ["specific-value", "error-code"],
          "riskScore": 5,
          "riskReasons": ["asserts 1 specific value(s)", "asserts Firebase error code(s): `auth/argument-error`"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-cluster-b9-b12.test.ts"]
        },
      ],
    },
    {
      kind: 'table',
      prefix: "## `signInWithPopup(auth, provider)` / `signInWithCredential(auth, credential)`\n",
      rows: [
        {
          "id": "auth#44",
          "surface": "auth",
          "aliases": [],
          "rowRef": "44",
          "rowNumber": 44,
          "section": "`signInWithPopup(auth, provider)` / `signInWithCredential(auth, credential)`",
          "api": "signInWithPopup(auth, provider)` / `signInWithCredential(auth, credential)",
          "behavior": "Returns the pre-staged `UserCredential` registered via `sandbox.mockSignInResult(auth, …)`",
          "status": "✓",
          "evidence": "`unit:sandbox-providers.test.ts`",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-providers.test.ts"],
          "exceptionReason": "sandbox-only behavior — no prod equivalent to observe"
        },
        {
          "id": "auth#45",
          "surface": "auth",
          "aliases": [],
          "rowRef": "45",
          "rowNumber": 45,
          "section": "`signInWithPopup(auth, provider)` / `signInWithCredential(auth, credential)`",
          "api": "signInWithPopup(auth, provider)` / `signInWithCredential(auth, credential)",
          "behavior": "Throws `auth/no-mock-configured` when no mock is pre-staged",
          "status": "✓",
          "evidence": "`unit:sandbox-providers.test.ts`",
          "risk": ["specific-value", "error-code"],
          "riskScore": 5,
          "riskReasons": ["asserts 1 specific value(s)", "asserts Firebase error code(s): `auth/no-mock-configured`"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-providers.test.ts"],
          "exceptionReason": "sandbox-only behavior — no prod equivalent to observe"
        },
        {
          "id": "auth#46",
          "surface": "auth",
          "aliases": [],
          "rowRef": "46",
          "rowNumber": 46,
          "section": "`signInWithPopup(auth, provider)` / `signInWithCredential(auth, credential)`",
          "api": "signInWithPopup(auth, provider)` / `signInWithCredential(auth, credential)",
          "behavior": "Mock is consumed after one read (subsequent call without a fresh stage throws again)",
          "status": "✓",
          "evidence": "`unit:sandbox-providers.test.ts`",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-providers.test.ts"]
        },
        {
          "id": "auth#47",
          "surface": "auth",
          "aliases": [],
          "rowRef": "47",
          "rowNumber": 47,
          "section": "`signInWithPopup(auth, provider)` / `signInWithCredential(auth, credential)`",
          "api": "signInWithPopup(auth, provider)` / `signInWithCredential(auth, credential)",
          "behavior": "After successful sign-in, `currentUser` becomes the mock's `user`, listeners fire",
          "status": "✓",
          "evidence": "`unit:sandbox-providers.test.ts`",
          "risk": ["listener"],
          "riskScore": 2,
          "riskReasons": ["asserts listener semantics"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-providers.test.ts"],
          "exceptionReason": "sandbox-only behavior — no prod equivalent to observe"
        },
        {
          "id": "auth#47a",
          "surface": "auth",
          "aliases": [],
          "rowRef": "47a",
          "rowNumber": 47,
          "section": "`signInWithPopup(auth, provider)` / `signInWithCredential(auth, credential)`",
          "api": "signInWithPopup(auth, provider)` / `signInWithCredential(auth, credential)",
          "behavior": "The credential's rich `User` (email / displayName / isAnonymous) survives the transition — popup/redirect/credential/`setUser` do NOT clobber it down to the bare `AuthState`; `cred.user === auth.currentUser` (reference identity, matches upstream `_updateCurrentUser(userCredential.user)`)",
          "status": "✓",
          "evidence": "`unit:sandbox-user-identity.test.ts` (locks AUTH-B1)",
          "risk": ["specific-field"],
          "riskScore": 1,
          "riskReasons": ["asserts a specific field/property value"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-user-identity.test.ts"]
        },
        {
          "id": "auth#48",
          "surface": "auth",
          "aliases": [],
          "rowRef": "48",
          "rowNumber": 48,
          "section": "`signInWithPopup(auth, provider)` / `signInWithCredential(auth, credential)`",
          "api": "signInWithPopup(auth, provider)` / `signInWithCredential(auth, credential)",
          "behavior": "Opens a popup window in prod",
          "status": "⚠",
          "evidence": "divergence: sandbox skips the popup; mock pre-stage replaces the popup result",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unverified",
          "oracleObservations": [],
          "conformanceTests": []
        },
        {
          "id": "auth#49",
          "surface": "auth",
          "aliases": [],
          "rowRef": "49",
          "rowNumber": 49,
          "section": "`signInWithPopup(auth, provider)` / `signInWithCredential(auth, credential)`",
          "api": "signInWithPopup(auth, provider)` / `signInWithCredential(auth, credential)",
          "behavior": "Cancels with `auth/popup-closed-by-user` when the user dismisses the popup (prod)",
          "status": "—",
          "evidence": "not modeled — would require the host to expose a \"cancel\" affordance on the mock",
          "risk": ["specific-value", "error-code"],
          "riskScore": 5,
          "riskReasons": ["asserts 1 specific value(s)", "asserts Firebase error code(s): `auth/popup-closed-by-user`"],
          "automation": "unsupported",
          "oracleObservations": [],
          "conformanceTests": [],
          "exceptionReason": "unsupported / intentionally out of scope"
        },
        {
          "id": "auth#70",
          "surface": "auth",
          "aliases": [],
          "rowRef": "70",
          "rowNumber": 70,
          "section": "`signInWithPopup(auth, provider)` / `signInWithCredential(auth, credential)`",
          "api": "signInWithPopup(auth, provider)` / `signInWithCredential(auth, credential)",
          "behavior": "Provider-flow sign-ins (popup / redirect / credential) record the flow's `providerId` on the identity in the user DB (upsert for unknown uids; append-if-missing for known ones) and reject disabled accounts with `auth/user-disabled` before any state change",
          "status": "✓",
          "evidence": "`unit:sandbox-user-admin.test.ts` (\"provider tracking\", \"disabled users\") — provider recording is sandbox bookkeeping for `listIdentities`/`listUsers`; prod's auto-link semantics are narrower (same-email Google auto-link only) and not modeled",
          "risk": ["specific-value", "error-code"],
          "riskScore": 5,
          "riskReasons": ["asserts 1 specific value(s)", "asserts Firebase error code(s): `auth/user-disabled`"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-user-admin.test.ts"]
        },
      ],
    },
    {
      kind: 'table',
      prefix: "## `signInWithRedirect` / `getRedirectResult` / resolver seam\n",
      rows: [
        {
          "id": "auth#49a",
          "surface": "auth",
          "aliases": [],
          "rowRef": "49a",
          "rowNumber": 49,
          "section": "`signInWithRedirect` / `getRedirectResult` / resolver seam",
          "api": "signInWithRedirect` / `getRedirectResult` / resolver seam",
          "behavior": "`signInWithRedirect(auth, provider, resolver?)` resolves the flow (per-call resolver → injected → one-shot mock → `auth/argument-error`), signs the user in, and stashes the credential for one `getRedirectResult`",
          "status": "✓",
          "evidence": "`unit:sandbox-resolver.test.ts`",
          "risk": ["specific-value", "error-code"],
          "riskScore": 5,
          "riskReasons": ["asserts 1 specific value(s)", "asserts Firebase error code(s): `auth/argument-error`"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-resolver.test.ts"]
        },
        {
          "id": "auth#49b",
          "surface": "auth",
          "aliases": [],
          "rowRef": "49b",
          "rowNumber": 49,
          "section": "`signInWithRedirect` / `getRedirectResult` / resolver seam",
          "api": "signInWithRedirect` / `getRedirectResult` / resolver seam",
          "behavior": "`getRedirectResult(auth)` returns the stashed credential once, then `null` (one-shot, matches prod)",
          "status": "✓",
          "evidence": "`unit:sandbox-resolver.test.ts`",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-resolver.test.ts"]
        },
        {
          "id": "auth#49c",
          "surface": "auth",
          "aliases": [],
          "rowRef": "49c",
          "rowNumber": 49,
          "section": "`signInWithRedirect` / `getRedirectResult` / resolver seam",
          "api": "signInWithRedirect` / `getRedirectResult` / resolver seam",
          "behavior": "`sandbox.setAuthFlowResolver(auth, resolver | null)` installs / clears the popup/redirect resolver (the analog of browser `getAuth` wiring `browserPopupRedirectResolver`)",
          "status": "✓",
          "evidence": "`unit:sandbox-resolver.test.ts`",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-resolver.test.ts"]
        },
        {
          "id": "auth#49d",
          "surface": "auth",
          "aliases": [],
          "rowRef": "49d",
          "rowNumber": 49,
          "section": "`signInWithRedirect` / `getRedirectResult` / resolver seam",
          "api": "signInWithRedirect` / `getRedirectResult` / resolver seam",
          "behavior": "`sandbox.listIdentities(auth)` snapshots every seeded/created identity for a host account-picker (sandbox-only — no `firebase/auth` equivalent)",
          "status": "✓",
          "evidence": "`unit:sandbox-resolver.test.ts`",
          "risk": ["specific-value"],
          "riskScore": 2,
          "riskReasons": ["asserts 1 specific value(s)"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-resolver.test.ts"],
          "exceptionReason": "sandbox-only behavior — no prod equivalent to observe"
        },
      ],
    },
    {
      kind: 'table',
      prefix: "## `Auth` surface + error shape\n",
      rows: [
        {
          "id": "auth#49e",
          "surface": "auth",
          "aliases": [],
          "rowRef": "49e",
          "rowNumber": 49,
          "section": "`Auth` surface + error shape",
          "api": "Auth` surface + error shape",
          "behavior": "`auth.signOut()` method form works alongside the free `signOut(auth)` function (`firebase/auth`'s `Auth` exposes both) (AUTH-GAP)",
          "status": "✓",
          "evidence": "`unit:auth-gap-surface.test.ts`",
          "risk": ["specific-value"],
          "riskScore": 2,
          "riskReasons": ["asserts 1 specific value(s)"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/auth-gap-surface.test.ts"]
        },
        {
          "id": "auth#49f",
          "surface": "auth",
          "aliases": [],
          "rowRef": "49f",
          "rowNumber": 49,
          "section": "`Auth` surface + error shape",
          "api": "Auth` surface + error shape",
          "behavior": "Sandbox auth errors are real `FirebaseError` instances (`err instanceof FirebaseError`) carrying the prod message wrapper `Firebase: <message> (<auth/...>).` — e.g. `Firebase: Error (auth/invalid-email).`, matching the oracle (AUTH-GAP)",
          "status": "✓",
          "evidence": "`unit:auth-gap-surface.test.ts`",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/auth-gap-surface.test.ts"]
        },
      ],
    },
    {
      kind: 'table',
      prefix: "## Provider classes (`GoogleAuthProvider`, `EmailAuthProvider`, etc.)\n",
      rows: [
        {
          "id": "auth#50",
          "surface": "auth",
          "aliases": [],
          "rowRef": "50",
          "rowNumber": 50,
          "section": "Provider classes (`GoogleAuthProvider`, `EmailAuthProvider`, etc.)",
          "api": "Provider classes (`GoogleAuthProvider`, `EmailAuthProvider`, etc.)",
          "behavior": "Exports the same constructor signatures as `firebase/auth` for each provider",
          "status": "✓",
          "evidence": "type-only smoke in `unit:types.test.ts`",
          "risk": ["specific-value"],
          "riskScore": 2,
          "riskReasons": ["asserts 1 specific value(s)"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/types.test.ts"],
          "exceptionReason": "structural / type shape — verified without a prod observation"
        },
        {
          "id": "auth#51",
          "surface": "auth",
          "aliases": [],
          "rowRef": "51",
          "rowNumber": 51,
          "section": "Provider classes (`GoogleAuthProvider`, `EmailAuthProvider`, etc.)",
          "api": "Provider classes (`GoogleAuthProvider`, `EmailAuthProvider`, etc.)",
          "behavior": "`Provider.credential(...)` static factories produce `AuthCredential`-shaped objects",
          "status": "✓",
          "evidence": "`unit:sandbox-providers.test.ts`",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-providers.test.ts"]
        },
        {
          "id": "auth#52",
          "surface": "auth",
          "aliases": [],
          "rowRef": "52",
          "rowNumber": 52,
          "section": "Provider classes (`GoogleAuthProvider`, `EmailAuthProvider`, etc.)",
          "api": "Provider classes (`GoogleAuthProvider`, `EmailAuthProvider`, etc.)",
          "behavior": "`GoogleAuthProvider.providerId === 'google.com'` (and per-provider analogs)",
          "status": "✓",
          "evidence": "`unit:sandbox-providers.test.ts`",
          "risk": ["specific-field"],
          "riskScore": 1,
          "riskReasons": ["asserts a specific field/property value"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-providers.test.ts"]
        },
        {
          "id": "auth#53",
          "surface": "auth",
          "aliases": [],
          "rowRef": "53",
          "rowNumber": 53,
          "section": "Provider classes (`GoogleAuthProvider`, `EmailAuthProvider`, etc.)",
          "api": "Provider classes (`GoogleAuthProvider`, `EmailAuthProvider`, etc.)",
          "behavior": "Custom scopes / params / language code",
          "status": "—",
          "evidence": "sandbox ignores; prod forwards",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unsupported",
          "oracleObservations": [],
          "conformanceTests": [],
          "exceptionReason": "unsupported / intentionally out of scope"
        },
      ],
    },
    {
      kind: 'table',
      prefix: "## `User` methods\n",
      rows: [
        {
          "id": "auth#54",
          "surface": "auth",
          "aliases": [],
          "rowRef": "54",
          "rowNumber": 54,
          "section": "`User` methods",
          "api": "User` methods",
          "behavior": "`user.getIdToken()` returns a stable opaque token in sandbox (`sandbox-id-token-…`)",
          "status": "✓",
          "evidence": "`unit:sandbox-anonymous.test.ts`",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-anonymous.test.ts"]
        },
        {
          "id": "auth#55",
          "surface": "auth",
          "aliases": [],
          "rowRef": "55",
          "rowNumber": 55,
          "section": "`User` methods",
          "api": "User` methods",
          "behavior": "`user.getIdToken(true)` (forceRefresh) returns a NEW token; subsequent `getIdToken(false)` returns the cached new token",
          "status": "✓",
          "evidence": "`unit:sandbox-token-refresh.test.ts` — was ⚠ (documented divergence); aligned to prod in commit on branch `claude/close-auth-token-refresh` — sandbox now mints a fresh token on forceRefresh and fires `onIdTokenChanged`. Oracle: `scripts/oracle/observations/auth-getidtoken-force-refresh.json` defines the target shape (`forceRefreshReturnedDifferentString: true`, `token1EqualsToken2: true` against blockingfun — the refreshed token is cached, so a subsequent non-forced read returns it, not yet another fresh one). Sandbox tokens stay `sandbox-id-token-<uid>-<hash>` strings; prod's are real JWTs.",
          "risk": ["specific-value", "specific-field", "listener"],
          "riskScore": 5,
          "riskReasons": ["asserts 1 specific value(s)", "asserts a specific field/property value", "asserts listener semantics"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-getidtoken-force-refresh"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-token-refresh.test.ts"]
        },
        {
          "id": "auth#56",
          "surface": "auth",
          "aliases": [],
          "rowRef": "56",
          "rowNumber": 56,
          "section": "`User` methods",
          "api": "User` methods",
          "behavior": "`user.getIdTokenResult()` returns claims",
          "status": "✓",
          "evidence": "`unit:sandbox-providers.test.ts` (custom-claims path)",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-providers.test.ts"]
        },
        {
          "id": "auth#57",
          "surface": "auth",
          "aliases": [],
          "rowRef": "57",
          "rowNumber": 57,
          "section": "`User` methods",
          "api": "User` methods",
          "behavior": "`user.uid`, `user.email`, `user.displayName`, `user.isAnonymous` reflect the source",
          "status": "✓",
          "evidence": "`playground:auth-anonymous`, `playground:auth-email-password`",
          "risk": ["specific-field"],
          "riskScore": 1,
          "riskReasons": ["asserts a specific field/property value"],
          "automation": "playground-only",
          "oracleObservations": [],
          "conformanceTests": [],
          "exceptionReason": "playground / preview behavior — no firebase-js-sdk counterpart to observe"
        },
        {
          "id": "auth#58",
          "surface": "auth",
          "aliases": [],
          "rowRef": "58",
          "rowNumber": 58,
          "section": "`User` methods",
          "api": "User` methods",
          "behavior": "`user.emailVerified` — present on every sandbox-minted `User` (default `false`; sandbox has no verification flow). Prod passes the real value through (no longer stripped). The admin record (`sandbox.listUsers`) carries it too",
          "status": "✓",
          "evidence": "`unit:auth-gap-surface.test.ts` (locks AUTH-GAP)",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/auth-gap-surface.test.ts"]
        },
        {
          "id": "auth#58a",
          "surface": "auth",
          "aliases": [],
          "rowRef": "58a",
          "rowNumber": 58,
          "section": "`User` methods",
          "api": "User` methods",
          "behavior": "`user.photoURL` / `user.phoneNumber` — present (sandbox default `null`; prod passes through, no longer stripped)",
          "status": "✓",
          "evidence": "`unit:auth-gap-surface.test.ts`",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/auth-gap-surface.test.ts"]
        },
        {
          "id": "auth#58b",
          "surface": "auth",
          "aliases": [],
          "rowRef": "58b",
          "rowNumber": 58,
          "section": "`User` methods",
          "api": "User` methods",
          "behavior": "`user.providerId` (aggregate, `'firebase'`) + `user.providerData: UserInfo[]` — sandbox synthesizes one provider entry for non-anonymous users, empty for anonymous; prod passes the real array through (no longer stripped). The admin record carries the emulator-shaped `providerUserInfo`",
          "status": "✓",
          "evidence": "`unit:auth-gap-surface.test.ts`",
          "risk": ["specific-value"],
          "riskScore": 2,
          "riskReasons": ["asserts 1 specific value(s)"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/auth-gap-surface.test.ts"]
        },
        {
          "id": "auth#59",
          "surface": "auth",
          "aliases": [],
          "rowRef": "59",
          "rowNumber": 59,
          "section": "`User` methods",
          "api": "User` methods",
          "behavior": "`user.metadata.creationTime` / `lastSignInTime`",
          "status": "—",
          "evidence": "client `User.metadata` not exposed (AUTH-GAP); the admin record carries `createdAt`/`lastLoginAt` (ISO)",
          "risk": ["metadata"],
          "riskScore": 1,
          "riskReasons": ["asserts metadata shape"],
          "automation": "unsupported",
          "oracleObservations": [],
          "conformanceTests": [],
          "exceptionReason": "unsupported / intentionally out of scope"
        },
        {
          "id": "auth#68",
          "surface": "auth",
          "aliases": [],
          "rowRef": "68",
          "rowNumber": 68,
          "section": "`User` methods",
          "api": "User` methods",
          "behavior": "`IdTokenResult.signInProvider` reflects the session's provider per flow (`'anonymous'` / `'password'` / `'google.com'` / …); claims include the reserved `firebase.sign_in_provider` (custom claims can't shadow it)",
          "status": "✓",
          "evidence": "`unit:sandbox-user-admin.test.ts` (\"IdTokenResult.signInProvider\") — prod shape is documented SDK behavior; no oracle capture yet",
          "risk": ["specific-value"],
          "riskScore": 2,
          "riskReasons": ["asserts 3 specific value(s)"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-signinprovider-per-flow"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-user-admin.test.ts"]
        },
        {
          "id": "auth#75",
          "surface": "auth",
          "aliases": [],
          "rowRef": "75",
          "rowNumber": 75,
          "section": "`User` methods",
          "api": "User` methods",
          "behavior": "Custom-claims changes (`sandbox.updateUser` / re-seed) reach an active session on the next FORCED token refresh, not immediately — claims are read live from the user DB at mint time (prod's refresh-propagation story; AUTH-B10)",
          "status": "✓",
          "evidence": "`unit:sandbox-user-admin.test.ts`, `unit:sandbox-cluster-b9-b12.test.ts`",
          "risk": ["timing"],
          "riskScore": 2,
          "riskReasons": ["asserts timing semantics"],
          "automation": "oracle-backed",
          "oracleObservations": ["auth-claims-forced-refresh-propagation"],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-cluster-b9-b12.test.ts", "packages/pyric/test/auth/sandbox-user-admin.test.ts"]
        },
        {
          "id": "auth#61",
          "surface": "auth",
          "aliases": [],
          "rowRef": "61",
          "rowNumber": 61,
          "section": "`User` methods",
          "api": "User` methods",
          "behavior": "`user.reload()` / `user.delete()` / `user.toJSON()` / `user.refreshToken` / `user.tenantId`",
          "status": "—",
          "evidence": "not modeled by the sandbox; documented in the deny-list rather than synthesized (AUTH-GAP)",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unsupported",
          "oracleObservations": [],
          "conformanceTests": [],
          "exceptionReason": "unsupported / intentionally out of scope"
        },
        {
          "id": "auth#62",
          "surface": "auth",
          "aliases": [],
          "rowRef": "62",
          "rowNumber": 62,
          "section": "`User` methods",
          "api": "User` methods",
          "behavior": "`updateProfile(user, {displayName, photoURL})`",
          "status": "—",
          "evidence": "not implemented",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unsupported",
          "oracleObservations": [],
          "conformanceTests": [],
          "exceptionReason": "unsupported / intentionally out of scope"
        },
      ],
    },
    {
      kind: 'table',
      prefix: "## `sandbox.*` (sandbox-only test driver)\n",
      rows: [
        {
          "id": "auth#63",
          "surface": "auth",
          "aliases": [],
          "rowRef": "63",
          "rowNumber": 63,
          "section": "`sandbox.*` (sandbox-only test driver)",
          "api": "sandbox.*` (sandbox-only test driver)",
          "behavior": "`sandbox.seedUsers(auth, [{uid, email, password, displayName?, customClaims?, providerId?}])` seeds the user DB; `providerId` defaults to `'password'`",
          "status": "✓",
          "evidence": "`unit:sandbox-test-driver.test.ts`, `unit:sandbox-user-admin.test.ts`",
          "risk": ["specific-value"],
          "riskScore": 2,
          "riskReasons": ["asserts 1 specific value(s)"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-test-driver.test.ts", "packages/pyric/test/auth/sandbox-user-admin.test.ts"],
          "exceptionReason": "sandbox-only behavior — no prod equivalent to observe"
        },
        {
          "id": "auth#63a",
          "surface": "auth",
          "aliases": [],
          "rowRef": "63a",
          "rowNumber": 63,
          "section": "`sandbox.*` (sandbox-only test driver)",
          "api": "sandbox.*` (sandbox-only test driver)",
          "behavior": "Re-seeding an existing uid OVERWRITES it: a new email drops the stale email→record mapping (the old email no longer signs in), and re-seeded `customClaims` are LIVE — a held `User`'s `getIdToken(true)` reflects the new claims rather than the claims frozen at mint time",
          "status": "✓",
          "evidence": "`unit:sandbox-cluster-b9-b12.test.ts` (locks AUTH-B9 + AUTH-B10)",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-cluster-b9-b12.test.ts"],
          "exceptionReason": "sandbox-only behavior — no prod equivalent to observe"
        },
        {
          "id": "auth#64",
          "surface": "auth",
          "aliases": [],
          "rowRef": "64",
          "rowNumber": 64,
          "section": "`sandbox.*` (sandbox-only test driver)",
          "api": "sandbox.*` (sandbox-only test driver)",
          "behavior": "`sandbox.setUser(auth, user)` / `sandbox.setUser(auth, null)` directly switches identity. Bypasses the `disabled` check and does NOT bump `lastLoginAt` (not a real sign-in)",
          "status": "✓",
          "evidence": "`unit:sandbox-test-driver.test.ts`",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-test-driver.test.ts"],
          "exceptionReason": "sandbox-only behavior — no prod equivalent to observe"
        },
        {
          "id": "auth#65",
          "surface": "auth",
          "aliases": [],
          "rowRef": "65",
          "rowNumber": 65,
          "section": "`sandbox.*` (sandbox-only test driver)",
          "api": "sandbox.*` (sandbox-only test driver)",
          "behavior": "`sandbox.mockSignInResult(auth, {providerId, user, …})` pre-stages a popup/credential result",
          "status": "✓",
          "evidence": "`unit:sandbox-providers.test.ts`",
          "risk": [],
          "riskScore": 0,
          "riskReasons": [],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-providers.test.ts"],
          "exceptionReason": "sandbox-only behavior — no prod equivalent to observe"
        },
        {
          "id": "auth#66",
          "surface": "auth",
          "aliases": [],
          "rowRef": "66",
          "rowNumber": 66,
          "section": "`sandbox.*` (sandbox-only test driver)",
          "api": "sandbox.*` (sandbox-only test driver)",
          "behavior": "All `sandbox.*` methods throw `failed-precondition` on prod-backed handles",
          "status": "✓",
          "evidence": "`unit:sandbox-test-driver.test.ts`, `unit:sandbox-user-admin.test.ts`",
          "risk": ["specific-value", "error-code"],
          "riskScore": 5,
          "riskReasons": ["asserts 1 specific value(s)", "asserts Firebase error code(s): `failed-precondition`"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-test-driver.test.ts", "packages/pyric/test/auth/sandbox-user-admin.test.ts"],
          "exceptionReason": "sandbox-only behavior — no prod equivalent to observe"
        },
        {
          "id": "auth#67",
          "surface": "auth",
          "aliases": [],
          "rowRef": "67",
          "rowNumber": 67,
          "section": "`sandbox.*` (sandbox-only test driver)",
          "api": "sandbox.*` (sandbox-only test driver)",
          "behavior": "`sandbox.reset()` (host-side, via `Sandbox.reset()`) clears auth state and fires sign-out",
          "status": "✓",
          "evidence": "`unit:sandbox-listeners.test.ts`",
          "risk": ["listener"],
          "riskScore": 2,
          "riskReasons": ["asserts listener semantics"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-listeners.test.ts"],
          "exceptionReason": "sandbox-only behavior — no prod equivalent to observe"
        },
        {
          "id": "auth#71",
          "surface": "auth",
          "aliases": [],
          "rowRef": "71",
          "rowNumber": 71,
          "section": "`sandbox.*` (sandbox-only test driver)",
          "api": "sandbox.*` (sandbox-only test driver)",
          "behavior": "`sandbox.listIdentities(auth)` returns the REAL provider per identity — `providerId` primary label (`'anonymous'` for anonymous users) + emulator-shaped `providerUserInfo` array; anonymous users included",
          "status": "✓",
          "evidence": "`unit:sandbox-user-admin.test.ts` (\"provider tracking\") — fixes the pre-epic mislabeling (`'password'`/`'anonymous'` only)",
          "risk": ["specific-value"],
          "riskScore": 2,
          "riskReasons": ["asserts 3 specific value(s)"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-user-admin.test.ts"],
          "exceptionReason": "sandbox-only behavior — no prod equivalent to observe"
        },
        {
          "id": "auth#72",
          "surface": "auth",
          "aliases": [],
          "rowRef": "72",
          "rowNumber": 72,
          "section": "`sandbox.*` (sandbox-only test driver)",
          "api": "sandbox.*` (sandbox-only test driver)",
          "behavior": "`sandbox.createSignInCredential(auth, {providerId, uid | spec})` mints backend-owned credentials for host-driven flows: `{uid}` picks an existing identity (`auth/user-not-found` for unknown uids); `{spec}` upserts (same-email reuse; default uid `'<providerId>:<email>'`; no password). Tokens route through the backend token cache",
          "status": "✓",
          "evidence": "`unit:sandbox-user-admin.test.ts` (\"sandbox.createSignInCredential\")",
          "risk": ["specific-value", "error-code"],
          "riskScore": 5,
          "riskReasons": ["asserts 2 specific value(s)", "asserts Firebase error code(s): `auth/user-not-found`"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-user-admin.test.ts"],
          "exceptionReason": "sandbox-only behavior — no prod equivalent to observe"
        },
        {
          "id": "auth#73",
          "surface": "auth",
          "aliases": [],
          "rowRef": "73",
          "rowNumber": 73,
          "section": "`sandbox.*` (sandbox-only test driver)",
          "api": "sandbox.*` (sandbox-only test driver)",
          "behavior": "User-admin CRUD: `sandbox.listUsers` / `createUser` (no sign-in; `auth/uid-already-exists`, `auth/email-already-in-use`, `auth/invalid-email`, `auth/weak-password`) / `updateUser` (displayName incl. null-clear, email re-key, password + provider link, customClaims wholesale replace, disabled, emailVerified) / `deleteUser` / `clearUsers`. Deletion/clear/disable do NOT terminate active sessions (prod parity). Record shape: `{uid, email, displayName, phoneNumber, photoUrl, customClaims, providerUserInfo, isAnonymous, disabled, emailVerified, createdAt, lastLoginAt}` with ISO timestamps",
          "status": "✓",
          "evidence": "`unit:sandbox-user-admin.test.ts` (CRUD describes)",
          "risk": ["specific-value", "error-code"],
          "riskScore": 5,
          "riskReasons": ["asserts 4 specific value(s)", "asserts Firebase error code(s): `auth/uid-already-exists`, `auth/email-already-in-use`, `auth/invalid-email`, `auth/weak-password`"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-user-admin.test.ts"],
          "exceptionReason": "sandbox-only behavior — no prod equivalent to observe"
        },
        {
          "id": "auth#74",
          "surface": "auth",
          "aliases": [],
          "rowRef": "74",
          "rowNumber": 74,
          "section": "`sandbox.*` (sandbox-only test driver)",
          "api": "sandbox.*` (sandbox-only test driver)",
          "behavior": "`sandbox.subscribeUsers(auth, cb)` fires a coarse no-payload callback on every user-DB mutation (seed/create/update/delete/clear, provider links, lastLoginAt bumps); no initial fire; throwing listeners isolated; unsubscribe stops fires",
          "status": "✓",
          "evidence": "`unit:sandbox-user-admin.test.ts` (\"sandbox.subscribeUsers\")",
          "risk": ["listener"],
          "riskScore": 2,
          "riskReasons": ["asserts listener semantics"],
          "automation": "unit-backed",
          "oracleObservations": [],
          "conformanceTests": ["packages/pyric/test/auth/sandbox-user-admin.test.ts"],
          "exceptionReason": "sandbox-only behavior — no prod equivalent to observe"
        },
      ],
    },
    { kind: 'markdown', markdown: "\n## Deny-list (intentionally NOT shimmed)\n\nThese exist in `firebase/auth` but the sandbox refuses to import/use\nthem. The agent's writeApp prompt and the deploy bundle's metafile\ngate enforce the deny-list at build time.\n\n| Name | Reason |\n|---|---|\n| `linkWithCredential` / `linkWithPopup` / `linkWithRedirect` | v0 scope — account linking is non-trivial state |\n| `unlink` | Same as above |\n| `reauthenticateWithCredential` / `reauthenticateWithPopup` / `reauthenticateWithRedirect` | v0 scope |\n| `updateEmail` / `updatePassword` | Mutates auth state in ways the sandbox doesn't model |\n| `verifyBeforeUpdateEmail` / `sendEmailVerification` / `applyActionCode` / `checkActionCode` / `confirmPasswordReset` / `sendPasswordResetEmail` / `verifyPasswordResetCode` | Email-link flows require an SMTP path; deliberately out of scope |\n| `multiFactor(user)` / MFA APIs | Not modeled |\n| `useDeviceLanguage` / `setLanguageCode` | i18n surface; not in v0 |\n| `beforeAuthStateChanged` | Blocking middleware; sandbox uses synchronous fan-out and has no equivalent yet |\n| `User.reload()` / `User.delete()` / `User.toJSON()` | Account-lifecycle / serialization the sandbox doesn't model — documented (not synthesized) per AUTH-GAP; the cheap profile fields (`photoURL`/`emailVerified`/`phoneNumber`/`providerData`/`providerId`) ARE present |\n| `User.metadata` / `User.refreshToken` / `User.tenantId` | Not tracked by the sandbox; documented per AUTH-GAP |\n| Positional listener `error` / `complete` args on `onAuthStateChanged` / `onIdTokenChanged` | Sandbox observers never error/complete (synchronous in-memory fan-out); pass the `{ next, error, complete }` observer object if you need those handlers. The prod backend forwards all three. |\n\n---\n\n## Visible gaps to address next\n\nRows currently marked **?** (need explicit probes):\n\n- #3 `getAuth(app)` prod-backend dispatch — landing once the\n  empirical oracle harness (`scripts/oracle/run.ts`) captures the\n  observation against a real Firebase project. Harness is in\n  place; needs the `PYRIC_ORACLE_FIREBASE_CONFIG` env var pointed\n  at a dedicated oracle project before observations can be\n  committed. See `scripts/oracle/README.md` for project setup.\n- #69 (ordering only) — disabled-vs-wrong-password precedence on\n  `signInWithEmailAndPassword`. Sandbox checks disabled BEFORE the\n  password compare (anti-probing best-known semantics); needs an\n  oracle capture against a disabled prod account to lock the order.\n- #68 (prod side) — `IdTokenResult.signInProvider` values per flow are\n  documented SDK behavior but not yet oracle-captured.\n\nRows **locked by the empirical oracle harness** (committed observations under `scripts/oracle/observations/`, captured against the `blockingfun` project):\n\n- #10 `onAuthStateChanged` exactly-one-per-transition — oracle confirmed signIn → signOut → signIn each produced exactly 1 fire (in addition to the initial null fire on subscribe); sandbox matches.\n- #14 `signInWithEmailAndPassword` user-not-found — oracle confirmed prod still emits `auth/user-not-found` (not the newer `auth/invalid-credential`); sandbox matches.\n- #17 `signInWithEmailAndPassword` fires once with the new user — oracle confirmed `firesForSignIn: 1` with the signed-in uid against prod; sandbox matches.\n- #18 `auth/invalid-email` format-validation — oracle confirmed `createUserWithEmailAndPassword(auth, 'not-an-email', …)` throws `auth/invalid-email` against prod; sandbox now matches (validation lives in `sandbox-backend.ts` and runs before user-DB lookup on both `signIn` and `createUser` paths).\n- #19 `auth/weak-password` strength-validation — oracle confirmed prod rejects 3-char passwords with `auth/weak-password` and message `Password should be at least 6 characters`; sandbox now matches the same 6-char threshold (validated on `createUser` only — `signIn` lets in previously-seeded weak passwords, mirroring prod).\n- #24 `createUserWithEmailAndPassword` fires once with the new user — oracle confirmed `firesForCreate: 1` with the newly-created uid against prod; sandbox matches.\n- #26 `signOut` fires null exactly once — oracle confirmed the signOut transition produced exactly 1 fire with `uid === null`; sandbox matches.\n- #30 `onAuthStateChanged` on every subsequent identity change — oracle confirmed signIn → signOut → signIn → signOut all 4 fired exactly once; sandbox matches.\n- #32 `Unsubscribe` removes the observer — oracle confirmed post-unsubscribe signOut+signIn+signOut produced zero further fires; sandbox matches.\n- #33 multiple subscribers all fire — oracle confirmed two listeners registered back-to-back both fire on each transition; sandbox matches.\n- #36 observer object form (`{next, error, complete}`) — oracle confirmed prod accepts both forms; both fire on every transition; sandbox matches.\n- #21 `createUserWithEmailAndPassword` `operationType` — oracle confirmed prod returns `'signIn'` (NOT `'register'`); sandbox matches.\n- #22 `createUserWithEmailAndPassword` duplicate email — oracle confirmed prod emits `auth/email-already-in-use`; sandbox matches.\n- #25 `signOut` synchronous-null — oracle confirmed prod sets `auth.currentUser` to `null` in the synchronous continuation immediately after `await signOut(auth)` resolves; sandbox matches.\n- #27 `signOut` idempotent — oracle confirmed prod is a no-op, no listener fire on the redundant call.\n- #29 `onAuthStateChanged` initial-fire timing — oracle confirmed prod fires the initial value on the microtask after subscribe, not synchronously; sandbox matches.\n- #31 `onAuthStateChanged` no-dup on sync transition — oracle baseline: prod has no synchronous state-change API, so the dedup case is sandbox-only. Async subscribe + signIn produces two natural fires (initial null, then user).\n- #35 `onAuthStateChanged` throwing-observer isolation — oracle confirmed a throwing observer does not block subsequent observers; sandbox matches.\n- #37 `onAuthStateChanged` same-user no-double-fire — oracle confirmed calling `signInAnonymously` twice in a row returns the same uid and the second call does NOT produce a fresh listener fire; sandbox matches.\n- #38 `onIdTokenChanged` user-change fires — oracle confirmed every signIn/signOut transition produces exactly one fire; sandbox matches.\n- #39 `onIdTokenChanged` on forced refresh — oracle confirmed prod fires the listener after `getIdToken(true)`; sandbox matches (divergence closed on branch `claude/close-auth-token-refresh`).\n- #40 `onIdTokenChanged` initial-fire parity with `onAuthStateChanged` — oracle confirmed both listeners share the microtask-deferred initial-fire timing; sandbox matches.\n- #55 `getIdToken(forceRefresh)` — oracle confirmed prod returns a different token string after a forced refresh and a subsequent non-forced read returns the cached new token; sandbox matches (divergence closed on branch `claude/close-auth-token-refresh`).\n\nRows currently marked **—** that we might want to fill (rough priority):\n\n1. #20-23 `updateProfile` — common app pattern, agent code often calls it\n2. #57 `user.emailVerified` — used by gating logic in real apps\n3. #58-61 `user.metadata` / `reload` / `delete` — full User shape parity\n\nRows currently marked **⚠** that we might want to upgrade to **✓**\n(by aligning the sandbox to prod or by formally documenting the\ndivergence in `feature-matrix.md`):\n\n- #7 anonymous uid format\n- #12, #28 persistence story\n- #43 setPersistence respect\n- #48 popup window\n" },
  ],
} satisfies CompatibilitySurfaceRegistry;

export default authRegistry;
