import { chromium, expect } from '@playwright/test';
const browser = await chromium.launch({ headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://localhost:5197/?service=rtdb');
  await expect(page.locator('[data-component=MessageBubble]')).toHaveCount(10);
  // Separate the action from the initial subscription deliveries.
  await page.waitForTimeout(3100);
  await page.getByRole('button', { name: 'Run a burst', exact: true }).click();
  await expect(page.locator('#burst')).toBeEnabled();
  await page.waitForTimeout(3100);
  await page.getByRole('tab', { name: 'Traffic', exact: true }).click();
  await page.getByRole('button', { name: 'Rates', exact: true }).click();
  await expect(page.locator('[data-rate-service=rtdb] [data-last-activity]')).not.toHaveText('None recorded');
  await page.getByRole('button', { name: 'Realtime Database', exact: true }).click();
  await expect(page.locator('[data-history-mode=pause]')).toHaveAttribute('aria-pressed', 'true');
  const summary = page.locator('[data-history-summary]');
  await expect(summary.locator('[data-history-total=writes]')).toHaveText('5');
  await expect(summary.locator('[data-history-total=reads]')).toHaveText('2');
  await expect(page.locator('[data-rate-method=get] [data-period-calls]')).toHaveText('2');
  const chartBefore = await page.locator('[data-history-chart]').innerHTML();
  const before = await summary.innerText();
  await page.getByRole('button', { name: 'New message', exact: true }).click();
  await page.waitForTimeout(1200);
  expect(await summary.innerText()).toBe(before);
  expect(await page.locator('[data-history-chart]').innerHTML()).toBe(chartBefore);
  const chart = page.locator('[data-history-chart]');
  await chart.focus();
  await chart.press('ArrowLeft');
  await chart.press('Shift+ArrowLeft');
  await expect(summary).toContainText('2s');
  await expect(chart).toBeFocused();
  await page.locator('[data-history-mode=live]').click();
  await expect(page.locator('[data-history-mode=live]')).toHaveAttribute('aria-pressed', 'true');
  await expect(summary).toContainText('Live period');
  const box = await chart.boundingBox();
  await page.mouse.move(box.x + box.width * 0.3, box.y + 30);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width * 0.8, box.y + 30, { steps: 5 });
  await page.mouse.up();
  await expect(page.locator('[data-history-mode=pause]')).toHaveAttribute('aria-pressed', 'true');
  await expect(summary).toContainText('Selected period');
  await page.screenshot({ path: '/tmp/history-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.locator('[data-rate-detail]').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
  await page.screenshot({ path: '/tmp/history-mobile.png' });
  expect(errors).toEqual([]);
  console.log('PASS: idle burst recall, exact totals, frozen selection, keyboard, Live, drag selection, and narrow layout.');
} finally { await browser.close(); }
