import { chromium, expect } from '@playwright/test';
const browser = await chromium.launch({ headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://localhost:5197/?service=rtdb');
  const messages = page.locator('[data-component=MessageBubble]');
  await expect(messages).toHaveCount(10);
  await expect(messages.first()).toContainText('Message 21.');
  await page.getByRole('button', { name: 'Load older', exact: true }).click();
  await expect(messages).toHaveCount(20);
  await expect(messages.first()).toContainText('Message 11.');
  await page.getByRole('button', { name: 'Reset data', exact: true }).click();
  await expect(messages).toHaveCount(10);
  await page.evaluate(() => { globalThis.__payloads = []; globalThis[Symbol.for('pyric.sdk-activity')].observe(event => { if (event.phase === 'delivery' && event.usage?.payloadBytes) globalThis.__payloads.push({ method: event.method, bytes: event.usage.payloadBytes }); }); });
  await page.getByRole('button', { name: 'Edit latest message', exact: true }).click();
  await expect(messages.last()).toContainText('Edited.');
  const valueBytes = await page.evaluate(() => globalThis.__payloads.filter(event => event.method === 'onValue').reduce((sum, event) => sum + event.bytes, 0));
  await page.getByLabel('Listener', { exact: true }).selectOption('children');
  await expect(messages).toHaveCount(10);
  await page.evaluate(() => { globalThis.__payloads = []; });
  await page.getByRole('button', { name: 'Edit latest message', exact: true }).click();
  await expect(messages.last()).toContainText('Edited. Edited.');
  const childBytes = await page.evaluate(() => globalThis.__payloads.filter(event => event.method === 'onChildChanged').reduce((sum, event) => sum + event.bytes, 0));
  expect(childBytes).toBeGreaterThan(0);
  expect(valueBytes).toBeGreaterThan(childBytes * 5);
  await page.getByRole('button', { name: 'New message', exact: true }).click();
  await expect(messages).toHaveCount(10);
  const active = () => page.evaluate(() => globalThis[Symbol.for('pyric.sdk-activity')].records().filter(record => record.kind === 'subscription' && !record.endedAt));
  expect((await active()).filter(record => record.method === 'onChildAdded')).toHaveLength(1);
  expect((await active()).filter(record => record.method === 'onChildChanged')).toHaveLength(1);
  await page.getByRole('button', { name: 'Stop listeners', exact: true }).click();
  expect(await active()).toHaveLength(0);
  await page.getByRole('button', { name: 'New message', exact: true }).click();
  await page.getByRole('button', { name: 'Start listeners', exact: true }).click();
  await expect(messages).toHaveCount(10);
  await page.getByLabel('Listener', { exact: true }).selectOption('value');
  await page.getByLabel('Scope', { exact: true }).selectOption('conversation');
  await expect(messages).toHaveCount(32);
  expect((await active()).filter(record => record.target.replace(/^\//, '') === 'conversations/design')).toHaveLength(1);
  await page.getByRole('button', { name: 'Reset demo index', exact: true }).click();
  await expect(page.locator('#delivery-status')).toContainText('Demo index reset.');
  await page.getByRole('button', { name: 'Find Alice messages', exact: true }).click();
  await expect(page.locator('#delivery-status')).toContainText('Missing index');
  await page.getByRole('tab', { name: 'Traffic', exact: true }).click();
  await page.locator('[data-inspect-request]').first().click();
  const add = page.locator('[data-index-action=apply]');
  await expect(add).toBeEnabled();
  await add.click();
  await expect(add).toBeDisabled();
  await page.getByRole('button', { name: 'Find Alice messages', exact: true }).click();
  await expect(page.locator('#delivery-status')).toContainText('Found');
  await page.screenshot({ path: '/tmp/chat-rtdb.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '/tmp/chat-rtdb-mobile.png' });
  expect(errors).toEqual([]);
  console.log('PASS: RTDB pagination, edit, child events, scope, stop/restart, reset, index add, and narrow layout.');
} finally { await browser.close(); }
