#!/usr/bin/env bun
import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const recordsDirectory = resolve(packageRoot, 'src/cli/service-command-records');
const outputPath = resolve(packageRoot, 'src/cli/service-commands.generated.ts');
const recordPattern = /^([a-z0-9]+)-([a-z0-9]+)-([a-z0-9]+)\.ts$/;

export interface ServiceCommandRecordSource {
  file: string;
  identifier: string;
  path: readonly [string, string, string];
}

function camelCase(parts: readonly string[]): string {
  return parts[0] + parts.slice(1).map((part) => part[0]!.toUpperCase() + part.slice(1)).join('');
}

export function parseServiceCommandRecord(file: string): ServiceCommandRecordSource {
  const match = recordPattern.exec(file);
  if (!match) {
    throw new Error(
      `invalid service-command record filename '${file}'; expected <service>-<artifact>-<operation>.ts`,
    );
  }
  const path = [match[1]!, match[2]!, match[3]!] as const;
  return { file, identifier: camelCase(path), path };
}

export function renderServiceCommandRegistry(files: readonly string[]): string {
  const records = files.slice().sort().map(parseServiceCommandRecord);
  const identifiers = new Set<string>();
  for (const record of records) {
    if (identifiers.has(record.identifier)) {
      throw new Error(`duplicate generated service-command identifier '${record.identifier}'`);
    }
    identifiers.add(record.identifier);
  }

  const imports = records.map(({ file, identifier }) =>
    `import ${identifier} from './service-command-records/${file.replace(/\.ts$/, '.js')}';`
  );
  const commands = records.map(({ identifier, path }) =>
    `  { path: ${JSON.stringify(path)}, run: ${identifier} },`
  );
  return [
    '// Generated by scripts/generate-service-command-registry.ts. Do not edit.',
    "import type { ServiceCommand } from './service-commands.js';",
    ...imports,
    '',
    'export const SERVICE_COMMANDS = [',
    ...commands,
    '] as const satisfies readonly ServiceCommand[];',
    '',
  ].join('\n');
}

export function generateServiceCommandRegistry(): void {
  const files = readdirSync(recordsDirectory).filter((file) => file.endsWith('.ts'));
  writeFileSync(outputPath, renderServiceCommandRegistry(files));
}

if (import.meta.main) generateServiceCommandRegistry();
