/** Refresh the bundled Latin variable fonts. Run manually, never during install. */
import { writeFile, mkdir } from 'node:fs/promises';
const output = new URL('../src/serve/runtime/', import.meta.url);
const fonts = [
  { family: 'Pyric Geist', url: 'https://fonts.gstatic.com/s/geist/v5/gyByhwUxId8gMEwcGFWNOITd.woff2' },
  { family: 'Pyric Geist Mono', url: 'https://fonts.gstatic.com/s/geistmono/v6/or3nQ6H-1_WfwkMZI_qYFrcdmhHkjko.woff2' },
];
const licenseResponse = await fetch('https://raw.githubusercontent.com/google/fonts/main/ofl/geist/OFL.txt');
if (!licenseResponse.ok) throw new Error(`License download: ${licenseResponse.status}`);
const license = (await licenseResponse.text()).replace(/[ \t]+$/gm, '');
const records = await Promise.all(fonts.map(async ({ family, url }) => {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Font download: ${response.status}`);
  const bytes = Buffer.from(await response.arrayBuffer());
  if (bytes.toString('ascii', 0, 4) !== 'wOF2') throw new Error('Expected WOFF2');
  return { family, base64: bytes.toString('base64') };
}));
await mkdir(new URL('fonts/', output), { recursive: true });
await writeFile(new URL('fonts/OFL.txt', output), license);
await writeFile(new URL('chip-font-data.ts', output), `// Generated by packages/cli/scripts/generate-chip-fonts.ts. Latin subsets; system fallbacks cover other scripts.\n/*!\n${license}\n*/\nexport const CHIP_FONT_DATA: ReadonlyArray<{ family: string; base64: string }> = ${JSON.stringify(records, null, 2)};\n`);
console.log(`Bundled ${records.length} font families (${records.reduce((total, record) => total + Buffer.from(record.base64, 'base64').length, 0)} WOFF2 bytes).`);
