#!/usr/bin/env bun
import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const recordsDirectory = resolve(packageRoot, 'src/bridge/tool-records');
const outputPath = resolve(packageRoot, 'src/bridge/tool-records.generated.ts');
const recordPattern = /^[a-z0-9]+(-[a-z0-9]+)*\.ts$/;

export interface ToolRecordSource {
  file: string;
  identifier: string;
  key: string;
}

function camelCase(parts: readonly string[]): string {
  return parts[0] + parts.slice(1).map((part) => part[0]!.toUpperCase() + part.slice(1)).join('');
}

export function parseToolRecord(file: string): ToolRecordSource {
  if (!recordPattern.test(file)) {
    throw new Error(
      `invalid tool record filename '${file}'; expected lowercase kebab-case <tool>.ts`,
    );
  }
  const key = file.replace(/\.ts$/, '');
  return { file, identifier: camelCase(key.split('-')), key };
}

export function renderToolRegistry(files: readonly string[]): string {
  const records = files.slice().sort().map(parseToolRecord);
  const identifiers = new Set<string>();
  for (const record of records) {
    if (identifiers.has(record.identifier)) {
      throw new Error(`duplicate generated tool record identifier '${record.identifier}'`);
    }
    identifiers.add(record.identifier);
  }

  const imports = records.map(({ file, identifier }) =>
    `import ${identifier} from './tool-records/${file.replace(/\.ts$/, '.js')}';`
  );
  const entries = records.map(({ identifier, key }) =>
    `  { key: ${JSON.stringify(key)}, ...${identifier} },`
  );
  return [
    '// Generated by scripts/generate-tool-registry.ts. Do not edit.',
    "import type { RegisteredToolRecord } from './tool-records.js';",
    ...imports,
    '',
    'export const TOOL_RECORDS = [',
    ...entries,
    '] as const satisfies readonly RegisteredToolRecord[];',
    '',
  ].join('\n');
}

export function generateToolRegistry(): void {
  const files = readdirSync(recordsDirectory).filter((file) => file.endsWith('.ts'));
  writeFileSync(outputPath, renderToolRegistry(files));
}

if (import.meta.main) generateToolRegistry();
