#!/usr/bin/env bun
import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const recordsDirectory = resolve(packageRoot, 'src/bridge/tool-family-records');
const outputPath = resolve(packageRoot, 'src/bridge/tool-families.generated.ts');
const recordPattern = /^[a-z0-9]+(-[a-z0-9]+)*\.ts$/;

export interface ToolFamilyRecordSource {
  file: string;
  identifier: string;
  key: string;
}

function camelCase(parts: readonly string[]): string {
  return parts[0] + parts.slice(1).map((part) => part[0]!.toUpperCase() + part.slice(1)).join('');
}

export function parseToolFamilyRecord(file: string): ToolFamilyRecordSource {
  if (!recordPattern.test(file)) {
    throw new Error(
      `invalid tool-family record filename '${file}'; expected lowercase kebab-case <family>.ts`,
    );
  }
  const key = file.replace(/\.ts$/, '');
  return { file, identifier: camelCase(key.split('-')), key };
}

export function renderToolFamilyRegistry(files: readonly string[]): string {
  const records = files.slice().sort().map(parseToolFamilyRecord);
  const identifiers = new Set<string>();
  for (const record of records) {
    if (identifiers.has(record.identifier)) {
      throw new Error(`duplicate generated tool-family identifier '${record.identifier}'`);
    }
    identifiers.add(record.identifier);
  }

  const imports = records.map(({ file, identifier }) =>
    `import ${identifier} from './tool-family-records/${file.replace(/\.ts$/, '.js')}';`
  );
  const families = records.map(({ identifier, key }) =>
    `  { key: ${JSON.stringify(key)}, ...${identifier} },`
  );
  return [
    '// Generated by scripts/generate-tool-family-registry.ts. Do not edit.',
    "import type { ToolFamily } from './tool-families.js';",
    ...imports,
    '',
    'export const TOOL_FAMILIES = [',
    ...families,
    '] as const satisfies readonly ToolFamily[];',
    '',
  ].join('\n');
}

export function generateToolFamilyRegistry(): void {
  const files = readdirSync(recordsDirectory).filter((file) => file.endsWith('.ts'));
  writeFileSync(outputPath, renderToolFamilyRegistry(files));
}

if (import.meta.main) generateToolFamilyRegistry();
