#!/usr/bin/env bun
/**
 * Renders the site's MCP tool reference from the tool records, so the page
 * can never drift from the registry.
 *
 * Source of truth is the seam `packages/cli/src/bridge/tool-records.ts`
 * (`toolRecords`) for the `tools/list` order and each tool's opening
 * description, and `packages/cli/src/bridge/server/tool-surface.ts`
 * (`composeMcpTools`) for each operation's resolved description, transport,
 * and input schema. One `##` section per tool, one `###` subsection per
 * `tool.op`.
 */
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { composeMcpTools, type JsonSchema, type McpTool, type McpToolOp } from '../src/bridge/server/tool-surface.js';
import { toolRecords, toolOps } from '../src/bridge/tool-records.js';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = resolve(packageRoot, '../site-docs/src/content/reference/mcp-tools.md');

const GENERATED_HEADER =
  '<!-- Generated by packages/cli/scripts/generate-tool-reference.ts. Do not edit. -->';

const FRONT_MATTER = `---
title: "MCP tool reference"
navLabel: "MCP tools"
group: "API reference"
section: "@pyric/cli"
order: 100010
description: "Every MCP tool the bridge serves, one section per tool and one subsection per operation, generated from the tool records."
---`;

/** The type of one non-union schema: its declared type, or 'enum' when only an enum narrows a string. */
function baseType(schema: JsonSchema): string {
  if (Array.isArray(schema.type)) return schema.type[0] ?? 'unknown';
  if (typeof schema.type === 'string') return schema.type;
  if (Array.isArray(schema.enum)) return 'enum';
  return 'unknown';
}

/** A field's type. A union (`oneOf`/`anyOf`) prints its variant types joined with "or". */
function fieldType(schema: JsonSchema): string {
  const variants = (schema.oneOf ?? schema.anyOf) as JsonSchema[] | undefined;
  if (variants && variants.length > 0) {
    const types = variants.map(baseType);
    return [...new Set(types)].join(' or ');
  }
  return baseType(schema);
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').trim();
}

function transportLine(op: McpToolOp): string {
  return op.transport === 'forwarded'
    ? 'Transport: forwarded to the connected sandbox.'
    : 'Transport: in-process.';
}

function fieldTable(op: McpToolOp): string {
  const properties = op.parameters.properties ?? {};
  const names = Object.keys(properties);
  if (names.length === 0) return '_No fields._';
  const required = new Set(op.parameters.required ?? []);
  const rows = names.map((name) => {
    const schema = properties[name]!;
    const type = fieldType(schema);
    const isRequired = required.has(name) ? 'yes' : 'no';
    const description = escapeCell(schema.description ?? '');
    return `| \`${name}\` | ${type} | ${isRequired} | ${description} |`;
  });
  return ['| Field | Type | Required | Description |', '|---|---|---|---|', ...rows].join('\n');
}

function renderOp(tool: McpTool, op: McpToolOp): string {
  return [
    `### \`${tool.name}.${op.op}\``,
    '',
    op.description,
    '',
    transportLine(op),
    '',
    fieldTable(op),
  ].join('\n');
}

function renderTool(record: { name: string; description: string }, tool: McpTool): string {
  const sections = [
    `## \`${tool.name}\``,
    '',
    record.description,
    '',
    ...tool.ops.map((op) => renderOp(tool, op)),
  ];
  return sections.join('\n\n');
}

/** Renders the full page. Called directly by the test; `main` writes its result to disk. */
export function render(): string {
  const records = toolRecords();
  const recordByName = new Map(records.map((record) => [record.name, record]));
  const tools = composeMcpTools();
  const opCount = toolOps().length;

  const intro = [
    '# MCP tool reference',
    '',
    `The default \`pyric sandbox --bridge\` / \`pyric bridge\` surface: ${tools.length} tools, ${opCount} operations. Each tool takes a required \`op\` field selecting the operation below; the remaining fields are the union of every operation's fields, but a call is validated against only the fields of the \`op\` it names.`,
  ].join('\n');

  const toolSections = tools.map((tool) => renderTool(recordByName.get(tool.name)!, tool));

  return [FRONT_MATTER, '', GENERATED_HEADER, '', intro, '', ...toolSections, ''].join('\n\n').replace(/\n{3,}/g, '\n\n');
}

export function main(): void {
  writeFileSync(outputPath, render());
}

if (import.meta.main) main();
