#!/usr/bin/env bun
/**
 * Render the service-command registry from two directories.
 *
 * A hand-written command is one record under `src/cli/service-command-records/`,
 * keyed by its filename. A derived command is one method record under
 * `src/bridge/surface/methods/<tool>/<method>.ts`: every method of the service
 * surface is a `pyric <tool> <method>` command, routed to the same handler the
 * MCP tool calls. Both kinds land in one generated registry, so the dispatcher
 * does not need to know which is which.
 *
 * The method records are read as a directory listing rather than imported: this
 * generator runs early in the build, before the generated conformance modules a
 * record's import graph reaches exist.
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { surfaceSources } from '../src/bridge/surface/generate-manifest.js';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const recordsDirectory = resolve(packageRoot, 'src/cli/service-command-records');
const surfaceDirectory = resolve(packageRoot, 'src/bridge/surface');
const outputPath = resolve(packageRoot, 'src/cli/service-commands.generated.ts');
const recordPattern = /^[a-z0-9]+(-[a-z0-9]+){1,2}\.ts$/;

export interface ServiceCommandRecordSource {
  file: string;
  identifier: string;
  path: readonly [string, string] | readonly [string, string, string];
}

function camelCase(parts: readonly string[]): string {
  return parts[0] + parts.slice(1).map((part) => part[0]!.toUpperCase() + part.slice(1)).join('');
}

/**
 * The route is the filename: `<service>-<artifact>-<operation>.ts`, or
 * `<service>-<operation>.ts` when the subject is the service itself and there
 * is no artifact word (ADR-0012 Decision 2, restated by ADR-0013).
 */
export function parseServiceCommandRecord(file: string): ServiceCommandRecordSource {
  if (!recordPattern.test(file)) {
    throw new Error(
      `invalid service-command record filename '${file}'; expected <service>-<artifact>-<operation>.ts or <service>-<operation>.ts`,
    );
  }
  const words = file.replace(/\.ts$/, '').split('-');
  const path = (words.length === 2
    ? [words[0]!, words[1]!]
    : [words[0]!, words[1]!, words[2]!]) as ServiceCommandRecordSource['path'];
  return { file, identifier: camelCase(path), path };
}

/** One `pyric <tool> <method>` command derived from a method record. */
export interface SurfaceCommandSource {
  tool: string;
  method: string;
}

/** Every derived command, in tool then method order. */
export function surfaceCommandSources(
  sources: ReadonlyArray<{ tool: string; methods: readonly string[] }>,
): SurfaceCommandSource[] {
  return sources.flatMap(({ tool, methods }) => methods.map((method) => ({ tool, method })));
}

export function renderServiceCommandRegistry(
  files: readonly string[],
  surface: readonly SurfaceCommandSource[] = [],
): string {
  const records = files.slice().sort().map(parseServiceCommandRecord);
  const identifiers = new Set<string>();
  for (const record of records) {
    if (identifiers.has(record.identifier)) {
      throw new Error(`duplicate generated service-command identifier '${record.identifier}'`);
    }
    identifiers.add(record.identifier);
  }

  const imports = records.map(({ file, identifier }) =>
    `import ${identifier} from './service-command-records/${file.replace(/\.ts$/, '.js')}';`
  );
  const commands = records.map(({ identifier, path }) =>
    `  { path: ${JSON.stringify(path)}, run: ${identifier} },`
  );
  const derived = surface.map(({ tool, method }) =>
    `  { path: ['${tool}', '${method}'], run: surfaceMethodCommand('${tool}.${method}') },`
  );
  return [
    '// Generated by scripts/generate-service-command-registry.ts. Do not edit.',
    "import type { ServiceCommand } from './service-commands.js';",
    "import { surfaceMethodCommand } from './surface-method-command.js';",
    ...imports,
    '',
    'export const SERVICE_COMMANDS = [',
    ...commands,
    ...derived,
    '] as const satisfies readonly ServiceCommand[];',
    '',
  ].join('\n');
}

export function generateServiceCommandRegistry(): void {
  const files = readdirSync(recordsDirectory).filter((file) => file.endsWith('.ts'));
  const sources = surfaceSources(readdirSync(resolve(surfaceDirectory, 'tools')), (tool) =>
    readdirSync(resolve(surfaceDirectory, 'methods', tool)),
  );
  writeFileSync(outputPath, renderServiceCommandRegistry(files, surfaceCommandSources(sources)));
}

if (import.meta.main) generateServiceCommandRegistry();
