#!/usr/bin/env bun
/**
 * Render the tool descriptions the service surface serves. A build-time
 * generator, so it lives beside the other generators the prebuild runs rather
 * than inside the sources it writes into.
 *
 * The text is derived from the method records, so a signature or an effect
 * class changes in one place and the description follows. The generated file is
 * what `tools/list` serves; a test regenerates it and diffs, so an edited
 * description fails rather than shipping.
 */
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { TOOLS } from '../src/bridge/surface/methods/registry.js';
import { renderToolDescriptions } from '../src/bridge/surface/tool-description.js';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = resolve(packageRoot, 'src/bridge/surface/descriptions.generated.ts');

/** The generated module source for one description map. */
export function renderDescriptionModule(descriptions: Record<string, string>): string {
  const entries = Object.entries(descriptions).map(
    ([name, description]) => `  ${JSON.stringify(name)}: ${JSON.stringify(description)},`,
  );
  return [
    '// Generated by scripts/generate-surface-descriptions.ts. Do not edit.',
    'export const TOOL_DESCRIPTIONS: Readonly<Record<string, string>> = {',
    ...entries,
    '};',
    '',
  ].join('\n');
}

export function generateToolDescriptions(): void {
  writeFileSync(outputPath, renderDescriptionModule(renderToolDescriptions(TOOLS)));
}

if (import.meta.main) generateToolDescriptions();
