/**
 * Pure inputs to the standalone compile (scripts/compile.ts), extracted so
 * tests can pin the two contracts that broke silently before:
 *
 * 1. The generated entry must explicitly invoke the CLI (`runDirect()`).
 *    Inside a `bun build --compile` binary the CLI module is an import —
 *    `import.meta.main` is false and `process.argv[1]` is the user's first
 *    argument — so `isDirectRun()` never fires and a bare
 *    `await import(...)` produces a binary that exits 0 silently.
 * 2. Every runtime `workspace:*` dependency of @pyric/cli must ship as an
 *    embedded tarball, or a vendored install dies with EUNSUPPORTEDPROTOCOL
 *    (or a registry 404) on the missing package.
 */

/** One workspace package embedded into the standalone binary as a tarball. */
export interface EmbeddedWorkspacePackage {
  /** npm package name (what dep specs reference). */
  name: string;
  /** Path of the package dir relative to the monorepo root. */
  dir: string;
  /** Stable tarball filename inside the binary and `vendor/` (version-free). */
  tarball: string;
}

/**
 * Every workspace package a vendored consumer install needs to resolve
 * offline: @pyric/cli itself plus each of its runtime `workspace:*` deps.
 * Order is dependency-first (matters only for readability; installs read the
 * whole set).
 */
export const EMBEDDED_WORKSPACE_PACKAGES: readonly EmbeddedWorkspacePackage[] = [
  { name: 'pyric', dir: 'packages/pyric', tarball: 'pyric.tgz' },
  { name: 'pyric-admin', dir: 'packages/pyric-admin', tarball: 'pyric-admin.tgz' },
  { name: 'create-pyric', dir: 'packages/create-pyric', tarball: 'create-pyric.tgz' },
  { name: '@pyric/cli', dir: 'packages/cli', tarball: 'pyric-cli.tgz' },
];

/**
 * Source of the generated `build/standalone-entry.js` the binary compiles
 * from. Sets the embedded-assets global, then imports the CLI and calls its
 * exported `runDirect()` — never relying on direct-run detection.
 */
export function generatedEntrySource(opts: {
  version: string;
  assetVersion: string;
  workerVersion: string;
  cliImportSpecifier: string;
}): string {
  return (
    '// GENERATED by scripts/compile.ts — do not edit.\n' +
    `globalThis.__PYRIC_EMBEDDED__ = {\n` +
    `  version: ${JSON.stringify(opts.version)},\n` +
    `  assetVersion: ${JSON.stringify(opts.assetVersion)},\n` +
    `  workerVersion: ${JSON.stringify(opts.workerVersion)},\n` +
    `  sdk: () => import('./embedded-sdk.js').then((m) => m.default),\n` +
    `  studio: () => import('./embedded-studio.js').then((m) => m.default),\n` +
    `  docs: () => import('./embedded-docs.js').then((m) => m.default),\n` +
    `  tarballs: () => import('./embedded-tarballs.js').then((m) => m.default),\n` +
    `};\n` +
    `const cli = await import(${JSON.stringify(opts.cliImportSpecifier)});\n` +
    `cli.runDirect();\n`
  );
}
