import type { AssuranceCapabilityRecord } from './types.ts';

/** The Storage authorization path a coarse read/write probe walks: path match,
 *  the read/write umbrellas, deny-by-default, and the request/resource bindings
 *  a size / content-type / metadata / auth rule reads. */
export const capability: AssuranceCapabilityRecord = {
  service: 'storage',
  description: 'Coarse read/write with auth, size, content type, metadata, and path matching.',
  dependencies: [
    { kind: 'construct', id: 'storage.rule-kind.match' },
    { kind: 'construct', id: 'storage.rule-kind.allow-read' },
    { kind: 'construct', id: 'storage.rule-kind.allow-write' },
    { kind: 'construct', id: 'storage.binding.request' },
    { kind: 'construct', id: 'storage.binding.request.auth' },
    { kind: 'construct', id: 'storage.binding.request.auth.uid' },
    { kind: 'construct', id: 'storage.binding.request.auth.token' },
    { kind: 'construct', id: 'storage.binding.request.resource' },
    { kind: 'construct', id: 'storage.binding.request.resource.size' },
    { kind: 'construct', id: 'storage.binding.request.resource.contentType' },
    { kind: 'construct', id: 'storage.binding.request.resource.metadata' },
    { kind: 'construct', id: 'storage.binding.resource' },
    { kind: 'construct', id: 'storage.binding.resource.size' },
    { kind: 'construct', id: 'storage.binding.resource.contentType' },
    { kind: 'construct', id: 'storage.binding.resource.metadata' },
    { kind: 'construct', id: 'storage.binding.path-variable' },
    { kind: 'construct', id: 'storage.operator.eq' },
    { kind: 'construct', id: 'storage.operator.neq' },
    { kind: 'construct', id: 'storage.operator.lt' },
    { kind: 'construct', id: 'storage.operator.and' },
    { kind: 'construct', id: 'storage.operator.or' },
    { kind: 'construct', id: 'storage.operator.not' },
    { kind: 'construct', id: 'storage.semantic.read-umbrella' },
    { kind: 'construct', id: 'storage.semantic.write-umbrella' },
    { kind: 'construct', id: 'storage.semantic.recursive-wildcard' },
    { kind: 'construct', id: 'storage.semantic.deny-by-default' },
    { kind: 'registry-row', id: 'storage-rules#98' },
    { kind: 'registry-row', id: 'storage-rules#99' },
    { kind: 'registry-row', id: 'storage-rules#100' },
    { kind: 'registry-row', id: 'storage-rules#101' },
    { kind: 'registry-row', id: 'storage-rules#102' },
    { kind: 'registry-row', id: 'storage-rules#103' },
    { kind: 'registry-row', id: 'storage-rules#114' },
  ],
};
