/**
 * The rule cases the rtdb-rules-deploy-refusals probe deploys one at a time,
 * keyed by the observation label. Each value is the rules subtree for that one
 * case, so a `$wildcard` case can declare or omit the variable it reads. The
 * sandbox replay compiles the same subtrees.
 */
export const RULES_DEPLOY_REFUSAL_CASES: Record<string, Record<string, unknown>> = {
  'hasChildren with two string arguments': { '.validate': "newData.hasChildren('a', 'b')" },
  'hasChildren with one string argument': { '.validate': "newData.hasChildren('a')" },
  'hasChildren with an array holding a number': { '.validate': "newData.hasChildren(['a', 1])" },
  'hasChildren with an empty array': { '.validate': 'newData.hasChildren([])' },
  'hasChildren with an array of strings': { '.validate': "newData.hasChildren(['a', 'b'])" },
  'hasChildren with no arguments': { '.validate': 'newData.hasChildren()' },
  'hasChildren with two arrays': { '.validate': "newData.hasChildren(['a'], ['b'])" },
  'hasChildren with a data value': { '.validate': 'newData.hasChildren(data.val())' },
  'beginsWith with a number literal': { '.validate': 'newData.val().beginsWith(12)' },
  'contains with a null literal': { '.validate': 'newData.val().contains(null)' },
  'endsWith with a boolean literal': { '.validate': 'newData.val().endsWith(true)' },
  'contains with a data value': { '.validate': 'newData.val().contains(data.val())' },
  'beginsWith with no arguments': { '.validate': 'newData.val().beginsWith()' },
  'beginsWith with two arguments': { '.validate': "newData.val().beginsWith('a', 'b')" },
  'child with a number literal': { '.validate': 'newData.child(5).exists()' },
  'child with auth.uid': { '.validate': "root.child('users').child(auth.uid).exists()" },
  'hasChild with a null literal': { '.validate': 'newData.hasChild(null)' },
  'replace with a number replacement': { '.validate': "newData.val().replace('a', 5) == 'x'" },
  'replace with a regex literal pattern': { '.validate': "newData.val().replace(/a/, 'z') == 'zbc'" },
  'replace with a slash-delimited string pattern': { '.validate': "newData.val().replace('/a/g', 'z') == 'z'" },
  'matches with a string argument': { '.validate': "newData.val().matches('^a')" },
  'matches with a slash-delimited string argument': { '.validate': "newData.val().matches('/^a/i')" },
  'matches with an unterminated character class': { '.validate': 'newData.val().matches(/[a/)' },
  'matches with the i flag': { '.validate': 'newData.val().matches(/^A/i)' },
  'matches with the g flag': { '.validate': 'newData.val().matches(/^A/g)' },
  'undeclared wildcard variable': { '.read': '$undeclared == auth.uid' },
  'declared wildcard variable': { $declared: { '.read': '$declared == auth.uid' } },
  'ancestor wildcard variable': { $outer: { inner: { '.read': '$outer == auth.uid' } } },
  'sibling wildcard variable': { $one: { '.read': true }, two: { '.read': '$one == auth.uid' } },
  'snapshot on the left of ==': { '.write': "data == 'locked'" },
  'snapshot on the right of ==': { '.write': "'locked' == data" },
  'snapshot on the left of !=': { '.write': "data != 'locked'" },
  'snapshot on the right of !=': { '.write': "'locked' != data" },
  'snapshot on the left of ===': { '.write': "data === 'locked'" },
  'snapshot on the left of !==': { '.write': "data !== 'locked'" },
  'snapshot compared to null': { '.write': 'data == null' },
  'snapshot compared to snapshot': { '.write': 'data == newData' },
  'child snapshot compared to a string': { '.write': "data.child('x') == 'locked'" },
  'parent snapshot compared to parent snapshot': { '.write': 'data.parent() == data.parent()' },
  'snapshot on the left of +': { '.validate': 'newData + 1 > 0' },
  'snapshot on the right of +': { '.validate': '1 + newData > 0' },
  'snapshot on the left of -': { '.validate': 'newData - 1 > 0' },
  'snapshot on the left of *': { '.validate': 'newData * 2 > 0' },
  'snapshot on the left of <': { '.validate': 'newData < 5' },
  'snapshot on the right of <': { '.validate': '5 < newData' },
  'snapshot on the left of >=': { '.validate': 'newData >= 5' },
  'literal tautology': { '.read': '1 == 1' },
  'literal contradiction': { '.read': '1 != 1' },
  'child with a dot segment': { '.validate': "newData.child('.').exists()" },
  'child with a dot-dot segment': { '.validate': "newData.child('..').exists()" },
};
